# Within-Subjects t-test

## Overview

In the previous chapters we have looked at one-sample t-tests and between-samples t-tests. In this chapter we will continue to look at t-tests in general, with the PreClass Activity looking really at the assumption of variance in a between-subjects t-test, and the InClass Activity looking at the remaining type of t-test; the **within-subjects t-test** (sometimes called the **dependent sample** or **paired-sample t-test**). The within-subjects t-test is a statistical procedure used to determine whether the mean difference between two sets of observations **from the same or matched participants** is zero. 

As in all tests, the within-subjects t-test has two competing hypotheses: the null hypothesis and the alternative hypothesis. 

* The null hypothesis assumes that the true mean difference between the paired samples is zero: $$H_0: \mu1 = \mu_2$$. 
* The alternative hypothesis assumes that the true mean difference between the paired samples is not equal to zero: $$H_1: \mu1 \ne \mu_2$$.

In this chapter we are going to look at running the within-subjects t-test but to begin with we will do a little work on the checks of your data that you need to perform prior to analysis.

**Assumptions of tests**

So far we have focussed your skills on data-wrangling, visualisations and probability, and now we are moving more towards the actual analysis stage of research. However, as you will know from your lectures, all tests, and particularly parametric tests, make a number of assumptions about the data that is being tested, and that you, as a responsible researcher, need to check these assumptions are "held" as any violation of the assumptions may make your results invalid. 

For t-tests the assumptions change for between-subjects and within-subjects designs (the one-sample and matched-pairs designs can be thought of as within-subjects designs).

The assumptions of the **between-subjects t-test** are:

* All data points are independent.
* The variance across both groups/conditions should be equal.
* The dependent variable must be continuous (interval/ratio).  
* The dependent variable should be normally distributed.  

And the assumptions of the **within-subjects t-test** are:

* All participants appear in both conditions/groups. 
* The dependent variable must be continuous (interval/ratio).  
* The dependent variable should be normally distributed.  

Before beginning any analysis, using your data-wrangling skills, you **must** check to see if the data deviates from these assumptions, and whether it contains any outliers, in order to assess the quality of the results. 

So in this lab we will:

* Understand about assumptions of t-tests in general
* Learn about the assumption of equal variance in between-subjects t-tests
* Run all assumption checks and analysis in an experiment with a within-subjects design.


