## PreClass Activity

The PreClass Activity for this chapter is reading. It is quite a bit of reading but don't worry if you don't understand it all the first time round. The best way to deal with this is to read through the information as prep, get the gist, then use it to support the activities, and then re-read to consolidate knowledge for the assessment. And ask questions. This will seem difficult at first but by working with the ideas and examples, you can understand the concepts introduced here.

### Read

**Chapters**

* As preparation for the inclass activities, please read Chapters 1 to 3 of <a href="https://drive.google.com/file/d/0B1fyuTuvj3YoaFdUR3FZaXNuNXc/view" target = "_blank">Miller and Haden (2013)</a>. The inclass activities will be working up to and including the concept of Sums of Squares which is around Section 3.4 of Miller and Haden (2013), so at least read up to and including that section.

When reading Miller and Haden it will help to remember that:

* **Factor** is another name for **Variable**
* **Level** is another name for **Condition**
* E.g. a between-subjects experiment with one independent variable (sleep quality) and two conditions (Good vs Poor) can be said to have one factor with two levels. 

The key terms we want you to be becoming familiar with from these chapters, though perhaps you don't quite fully understand them, are:

* **ANOVA** - short for Analysis of Variance. A statistical test used to compare the spread of the variance across two or more conditions and/or two or more factors. 
* **estimation equations** - formulas (or equations) that we use to determine our best guess (estimates) at parameters (values) of a population of interest from our sample parameters (values)
* **decomposition matrices** - a table (matrix) that breaks down information into individual components. In this instance, the decomposition matrix breaks down how each individual observation/participant is fitted into the GLM based on the estimation equations.
* **sums of squares** - an estimate of the total spread of the data around a parameter (such as the mean). We have seen sums of squares before in lectures, as the top part of the variance equation for example: 

$$\sum(x - \bar{x})^2$$

The activities we will look at next will help you understand these terms better. In short, over the next two chapters, we will show you how to take data from a simulated experiment and apply the estimation equations to create a decomposition matrix summarising this data. This decomposition matrix will show how each participant and condition is fitted to the General Linear Model. Then, from that matrix, we will calculate the relevant sums of squares for each condition, which will in turn be used in our ANOVA calculation to determine if there is a significant difference between conditions. It is going to be a lot more fun than it sounds!

If you want to get ahead, you should try the next activities. The first part reiterates and expands on the Miller and Haden information.

<span style="font-size: 22px; font-weight: bold; color: var(--blue);">Job Done - Activity Complete!</span>