# Data-Wrangling: A Key Skill

## Overview

One of the key skills in any researcher's toolbox is the ability to work with data. When you run an experiment you get lots of data in various files. For instance, it is not uncommon for an experimental software to create a new file for every participant you run and for each participant's file to contain numerous columns and rows of data, only some of which are important. Being able to wrangle that data, manipulate it into different layouts, extract the parts you need, and summarise it, is one of the most important skills we will help you learn in the coming weeks.

The next few labs are aimed at refreshing and consolidating your skills in working with data. This lab focuses on organizing data using the `tidyverse` package. Over the course of the activities, you will recap the main functions and how to use them, and we will use a number of real datasets to give you a wide range of exposure to what Psychology is about, and to reiterate that the same skills apply across different datasets. **The skills don't change, just the data!**

There are some questions to answer as you go along to help build your skills: use the example code as a guide and check your answer against the solutions at the end of the chapter. Finally, remember to be pro-active in your learning, work together as a community, and if you get stuck, ask on the forums, google what you are trying to do (e.g. "mutate table tidyverse"), and use the **<a href = "https://www.rstudio.com/resources/cheatsheets/" target = "_blank">cheatsheets</a>** or the **<a href = "https://psyteachr.github.io/" target = "_blank">Grassroots PsyTeacher book</a>**. The key cheatsheet for this activity is the Data Transformation Cheatsheet with `dplyr`.

In this lab you will recap on:

* Data-Wrangling with the Wickham Six one-table verbs.
* Additional useful functions such as count, pivot_longer (to gether data) and joins
* Piping and making efficient codes.

**Note:** This preclass is a bit of a read but it is important that you have all this information in the one place so you can quickly refer back to it. Also, you did a very similar task in the Grassroots book so it is about recapping more than learning afresh. But take your time to try to understand the information and be sure to ask any questions you have. **"Try first, then ask"** is our only rule!

`r hide("Portfolio Point - Getting Help")`
```{block, type ="info"}
Remember to open up your Portfolio that you created in Lab 1 so you can add useful information to it as you work through the tasks! Also summarising the information we give in this preclass, in your own words, is a great way to learn! You don't have to read all of these but they might help from time to time to explain parts further.
    
For instance, do you remember how to get help on an R function in RStudio? In your Console window, you can call the help function (e.g. `?mutate`) to view the reference page for each function. This example shows how to get help on the `mutate()` function within `dplyr`, which we will use in later labs.
```
`r unhide()`
