# Visualisation Through **`ggplot2`**

## Overview

In the last lab we encouraged you to always be looking at your data, making sure you are understanding your data, paying attention to how it is made up in regards to data types, and what the different functions do to your data. Remember that it is one thing to get a function to run, but you need to check it is doing what you think it is doing. It is just a function. You are the human! 

A second way of looking at your data, and what we are going to focus on in this chapter, is through visualisation - figures and plots - to help understand patterns and effects in your data. For example, when we asked you about the relationship between age and the Ponzo illusion in Chapter 1. 

Visualisation is very important for understanding your data, for example in regards to seeing differences between groups, but also for seeing where things don't quite match up with what you think is happening. A great example of this is Anscombe's Quartet, which you can read up about at a later date if you like - <a href = "https://en.wikipedia.org/wiki/Anscombe%27s_quartet" target = "_blank">see here</a> - four datasets given exact same means but with very different underlying structures when visualised. The key point is that it is always good to visualise your data and visualisation should be a common step in your practical skill set.

In the PsyTeachR <a href="https://psyteachr.github.io/" target = "_blank">Grassroots book</a> we introduced data visualisation using `ggplot2`, the main visualisation package of `tidyverse`. You should look back at that when working through this chapter, and you can find additional info here at the main page for the package: <a href = "https://ggplot2.tidyverse.org/" target = "_blank">ggplot2</a>. 

Today we will revisit plotting data and expand your skills in order to make effective and informative figures. This will become really beneficial to you as your progress as visualisation of any data is a skill that applies to multiple careers, not just Psychology.

In this lab you will:

1. Recap on visualisation
2. Expand your skills to produce new figures
3. Learn about Mental Rotation