## PreClass Activity 2

### Continuous Data - Brief Recap on The Normal Distribution

This a very short recap on the normal distribution which will help you work through the rest of this chapter if you read it before attempting the rest. In the first PreClass activity, we have seen how we can use a distribution to estimate probabilities and determine cut-off values (these will play an important part in hypothesis testing in later chapters!), but we have looked only at the **discrete binomial distribution**. Many of the variables we will encounter will be **continuous** and tend to show a **normal distribution** (e.g. height, weight, IQ). 

Let's say we're interested in the height of the `r glossary("population")` of Level 2 psychology students, which we estimate to be between 146cm and 194cm. If we plotted this as a continuous, normal distribution, it will look like:

``` {r normplot1, eval = TRUE, echo = FALSE, fig.cap = 'The Normal Distribution of height in Level 2 Psychology students (black line). Green line represents the mean. Blue line represent 1 Standard Deviation from the mean. Yellow line represents 2 Standard Deviation from the mean. Red line represents 3 Standard Deviation from the mean.'}

x <- seq(146,194,0.01) # here we use the sequence function to generate our quantiles ranging from -4 to 4 in steps of 0.01
mean = 170
sd = 7
y = dnorm(x, mean, sd)
ymin<- min(y)
ymax<- max(y)

plot(x,y, type = "l", col = "black", xlab = "Height (cm)", ylab = "Density (probability)", yaxt='n' )
polygon(c(mean,mean), c( ymin, ymax), border ="green")
polygon(c(mean-sd, mean-sd), c(y[x==mean-sd], ymin), border ="blue")
polygon(c(mean-(2*sd),mean-(2*sd)), c( y[x==mean-(2*sd)], ymin), border ="orange")
polygon(c(mean-(3*sd),mean-(3*sd)), c( y[x==mean-(3*sd)], ymin), border ="red")
polygon(c(mean+sd,mean+sd), c( y[x==mean+sd], ymin), border ="blue")
polygon(c(mean+(2*sd),mean+(2*sd)), c( y[x==mean+(2*sd)], ymin), border ="orange")
polygon(c(mean+(3*sd),mean+(3*sd)), c( y[x==mean+(3*sd)], ymin), border ="red")
text(170+1, 0.01, expression(mu), col = "green")
text(mean-sd-2, 0.01, expression(-sigma), col = "blue")
text(mean+sd+2, 0.01, expression(+sigma), col = "blue")
text(mean-(2*sd)-2, 0.01, expression(-2*sigma), col = "orange")
text(mean+(2*sd)+2, 0.01, expression(+2*sigma), col = "orange")
text(mean-(3*sd)-2, 0.01, expression(-3*sigma), col = "red")
text(mean+(3*sd)+2, 0.01, expression(+3*sigma), col = "red")

```

The figure shows the hypothetical probability density of heights ranging from 146cm to 194cm in the population of level 2 psychology students (black curve). This data is **normally distributed** and has the following properties:

### Properties of the Normal distribution:

**1. The distribution is defined by its mean and standard deviation:** The mean   ($\mu$) describes the center, and therefore peak density, of the distribution. This is where the largest number of the people in the population will be in terms of height. The standard deviation ($\sigma$) describes how much variation there is from the mean of the distribution - on the figure, the standard deviation is the distance from the mean to the inflection point of the curve (the part where the curve changes from a upside-down bowl shape to a right-side-up bowl shape).  

**2. Distribution is symmetrical around the mean:** The mean lies in the middle of the distribution and divides the area under the curve into two equal sections - so we get the typical bell-shaped curve.  

**3. Total area under the curve is equal to 1:** If we were to add up the probabilities (densities) for every possible height, we would end up with a value of 1.  

**4. The mean, median and mode are all equal:** A good way to check if a given dataset is normally distributed is to calculate each measure of central tendency and see if they are approximately the same (normal distribution) or not (skewed distribution).  

**5. The curve approaches, but never touches, the x axis:** You will never have a probability of 0 for a given x axis value. 

**6. The normal distribution follows the Empirical Rule:** The Empirical Rule states that 99.7% of the data within the normal distribution falls within three standard deviations ($\pm3\sigma$) from the mean, 95% falls within two standard deviations ($\pm2\sigma$), and 68% falls within one standard deviation ($\pm\sigma$).

<span style="font-size: 22px; font-weight: bold; color: var(--blue);">Job Done - Activity Complete!</span>

We will look at the normal distribution more in the InClass activity but if you have any questions please post them on forums or ask a member of staff. Finally, don't forget to add any useful information to your Portfolio before you leave it too long and forget. 
