# NHST and One-sample t-tests

## Overview

In the previous chapters we have talked a lot about probability, comparing values across groups, and the inference from a `r glossary("sample")` to a `r glossary("population")`. In effect this is the essence of a lot of quantitative research that uses Null Hypothesis Significance Testing (NHST). You  collect a sample, calculate a summary statistic about that sample, and use probability to establish the likelihood of that statistic occurring given certain situations. 

However these concepts and ideas are hard to grasp at first and take playing around with data a few times to help get a better understanding of them. As such, to demonstrate these ideas further, and to start introducing commonly used tests and approaches to reproducible science, we will look at data related to sleep - a very important practice for the consolidation of learning that most of us do not get enough of! The study we will look at, to explore NHST more, is by one of our team and makes use of a well known task in Psychology, the Posner Paradigm: <a href = "https://www.sciencedirect.com/science/article/pii/S0005796708002738" target = "_blank">Woods et al (2009) The clock as a focus of selective attention in those with primary insomnia: An experimental study using a modified Posner paradigm </a>. 

In Chapter 6, through the activities, we will:

1. Recap on testing a hypothesis through null hypothesis significance testing (NHST).
2. Learn about approaches to reproducible experiments.
3. Learn about binomial tests, as well as one-sample and independent t-tests.
4. Learn about Posner paradigms and attention (PreClass), and the recency effect (InClass).

`r hide("Portfolio Point - Additional background on The Posner Paradigm")`
```{block, type ="info"}
You don't need to read this to complete the activities it might help it make more sense. 

The Posner paradigm (Posner, 1980), or the Posner Cueing task, is an attentional shift task, often used in a variety of fields to test spatial attention and how this is impacted by disorders or injury. It works by having participants look at a fixation cross in the center of a screen. To either side is an empty box. After a short delay, a cue (e.g. an arrow, an asterisk, or some other attention grabbing image) appears in one of the boxes (e.g. the box to the left of the fixation). This stays on screen for a few hundred milliseconds and is then replaced by a second image called the target (e.g. a different shape or image). Participants then have to respond left or right depending on which side of the fixation the target appeared. The dependent variable (DV) is the time taken to respond to the target appearing. 

Key to the task is that in most trials the target will appear on the same side as the cue - the cue facilitates the target - and so participants will be quicker to respond. These are called valid trials. However, on some occasions the target will appear on the other side from the cue - e.g. the cue is on the left but the target appears on the right - and these are called invalid trials; participants will be slower to respond here as the cue misleads the participant. 

From that, you should be starting to get an idea of how a Posner paradigm can help to measure attention and how it can help determine if people have issues in shifting attention (particularly from the invalid trials).

Reference:

<a href="https://www.tandfonline.com/doi/abs/10.1080/00335558008248231" target = "_blank">Posner, M. (1980) Orienting of attention. Quarterly Journal of Experimental Psychology, 32(1), 3-25</a>
```
`r unhide()`
