## InClass Activity

1. Like the PreClass, we want to spend some time reflecting on what we have learnt and as such this InClass is about looking at ideas, concepts, and codes, that you have had issue with and seeing if we can resolve those issues. In class, we will spend some time looking at any issues you have had along the way.

2. We will also look at some other interesting things you can do in R should you wish to expand your own knowledge and skills, such as:

     - Popping out the Source Window to make working easier - <a href="https://support.rstudio.com/hc/en-us/articles/207126217-Using-Source-Windows" target = "_blank">Using Source Windows</a>
     - Analysing Twitter data with the **`rtweet`** package [@R-rtweet]
     - Animating plots with the **`ggganimate`** package [@R-gganimate]
     - Creating quickfire quizzes with the **`webexercises`** [@R-webexercises]
     - Make your own memes using the **`meme`** package [@R-meme]
     - <a href="https://dreamrs.shinyapps.io/memory-hex/" target = "_blank">The Hex Sticker Memory game</a> and <a href="https://community.rstudio.com/t/shiny-contest-submission-hex-memory-game/25336" target = "_blank">the background behind it</a>
     - <a href = "https://datatitian.com/how-to-turn-your-ggplot2-visualization-into-an-interactive-tweet/" target = "_blank">Creating interactive plots using ggplot and plotly</a>
     - Even funkier visualtions using the **`ggforce`** package - check out `facet_zoom()` [@R-ggforce]
     - Many diverse fields are now using R and this is a good example: <a href = "https://learn.r-journalism.com/en/" target = "_blank">R for Journalists</a>
     - Using the `knitr::read_chunk()` function to call R script code through R Markdown [@R-knitr]
     - The **`statcheck`** package for checking that you and others are presenting their inferential analyses accurately (in terms of df and p-value) and in APA format [@R-statcheck]
     - A great repository of R resources for teaching, learning, writing webpages, CVs, and doing very cool things with webpages
