## InClass Activity

1. Like in the PreClass we want to spend sometime reflecting on what we have learnt and as such this InClass is about looking at ideas, concepts, and codes, that you have had issues with and seeing if we can resolve those issues. It would be particularly worthwhile spending sometime looking at aspects of working with the GLM and decomposition matrices as this will make up much of the course next year.

2. We will also look at some other interesting things you can do in R, should you wish to expand your own knowledge and skills. Below is the list we looked at in Semester 1 but, I am sure we have found loads more as the year has gone on, such as:

* New

     - **`redoc`** package, by Ross Noam, for collaborative editing of Word documents (https://noamross.github.io/redoc/)
     - **`faux`** for the creation of simulated data (https://debruine.github.io/faux/) [@R-faux]
     - **`checkpoint`** for timestamping the version of the packages you are using in your code
     - `mydata <- read.delim("clipboard")` for creating a dataframe from your copy and paste function on your keyboard.
     - **R.Online** to compare codes across different versions of R (https://srv.colinfay.me:1001/)
     - **Hack Your Data Beautiful** (https://psyteachr.github.io/hack-your-data/index.html) - a workshop run by a team of postgraduates in Psychology @ Glasgow that shows a range of excellent and interesting skills and applications.

* Previous

    - Popping out the Source Window to make working easier - <a href="https://support.rstudio.com/hc/en-us/articles/207126217-Using-Source-Windows" target = "_blank">Using Source Windows</a>
    - Analysing Twitter data with the **`rtweet`** package [@R-rtweet]
    - Animating plots with the **`ggganimate`** package [@R-gganimate]
    - Creating quickfire quizzes with the **`webexercises`** [@R-webexercises]
    - Make your own memes using the **`meme`** package [@R-meme]
    - <a href="https://dreamrs.shinyapps.io/memory-hex/" target = "_blank">The Hex Sticker Memory game</a> and <a href="https://community.rstudio.com/t/shiny-contest-submission-hex-memory-game/25336" target = "_blank">the background behind it</a>
    - <a href = "https://datatitian.com/how-to-turn-your-ggplot2-visualization-into-an-interactive-tweet/" target = "_blank">Creating interactive plots using ggplot and plotly</a>
    - Even funkier visualtions using the **`ggforce`** package - check out `facet_zoom()` [@R-ggforce]
    - Many diverse fields are now using R and this is a good example: <a href = "https://learn.r-journalism.com/en/" target = "_blank">R for Journalists</a>
    - Using the `knitr::read_chunk()` function to call R script code through R Markdown [@R-knitr]
