<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Lab 12 Continuing the GLM: One-factor ANOVA | Level 2 Research Methods and Statistics Practical Skills</title>
  <meta name="description" content="ug2-practical-materials" />
  <meta name="generator" content="bookdown 0.22 and GitBook 2.6.7" />

  <meta property="og:title" content="Lab 12 Continuing the GLM: One-factor ANOVA | Level 2 Research Methods and Statistics Practical Skills" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="ug2-practical-materials" />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Lab 12 Continuing the GLM: One-factor ANOVA | Level 2 Research Methods and Statistics Practical Skills" />
  
  <meta name="twitter:description" content="ug2-practical-materials" />
  




  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="introduction-to-glm-one-factor-anova.html"/>
<link rel="next" href="continuing-the-glm-two-factor-designs.html"/>
<script src="libs/header-attrs-2.9/header-attrs.js"></script>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />
<meta property="og:title" content="psyTeachR Level 2 Research Methods and Statistics Practical Skills">
<meta property="og:description" content="This course covers data skills such as R Markdown, data wrangling with tidyverse, and data visualisation with ggplot2. It also introduces statistical concepts such as permutation tests, Null Hypothesis Significance Testing (NHST), alpha, power, effect size, and sample size. Semester 2 focusses on correlations and the general linear model.">
<meta property="og:image" content="https://psyteachr.github.io/images/twitter/L2.png">
<meta property="og:url" content="https://psyteachr.github.io/ug2-practical/">
<meta property="twitter:card" content="summary_large_image">


<link rel="shortcut icon" href="https://psyteachr.github.io/images/logo.png">


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="include/psyteachr.css" type="text/css" />
<link rel="stylesheet" href="include/webex.css" type="text/css" />
<link rel="stylesheet" href="include/style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Level 2 Practical</a></li>
<li><a href="https://zenodo.org/badge/latestdoi/166541567"><img src="https://zenodo.org/badge/166541567.svg" alt="DOI"></a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Overview</a></li>
<li class="chapter" data-level="" data-path="foreword.html"><a href="foreword.html"><i class="fa fa-check"></i>Foreword</a></li>
<li class="chapter" data-level="1" data-path="starting-with-r-markdown.html"><a href="starting-with-r-markdown.html"><i class="fa fa-check"></i><b>1</b> Starting with R Markdown</a>
<ul>
<li class="chapter" data-level="1.1" data-path="starting-with-r-markdown.html"><a href="starting-with-r-markdown.html#overview-1"><i class="fa fa-check"></i><b>1.1</b> Overview</a>
<ul>
<li class="chapter" data-level="1.1.1" data-path="starting-with-r-markdown.html"><a href="starting-with-r-markdown.html#what-is-r-markdown"><i class="fa fa-check"></i><b>1.1.1</b> What is R Markdown?</a></li>
<li class="chapter" data-level="1.1.2" data-path="starting-with-r-markdown.html"><a href="starting-with-r-markdown.html#advantages-of-using-r-markdown"><i class="fa fa-check"></i><b>1.1.2</b> Advantages of using R Markdown</a></li>
<li class="chapter" data-level="1.1.3" data-path="starting-with-r-markdown.html"><a href="starting-with-r-markdown.html#creating-an-r-markdown-.rmd-file"><i class="fa fa-check"></i><b>1.1.3</b> Creating an R Markdown (.Rmd) File</a></li>
<li class="chapter" data-level="1.1.4" data-path="starting-with-r-markdown.html"><a href="starting-with-r-markdown.html#one-last-thing-before-beginning"><i class="fa fa-check"></i><b>1.1.4</b> One last thing before beginning!</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="starting-with-r-markdown.html"><a href="starting-with-r-markdown.html#preclass-activiy"><i class="fa fa-check"></i><b>1.2</b> PreClass Activiy</a>
<ul>
<li class="chapter" data-level="1.2.1" data-path="starting-with-r-markdown.html"><a href="starting-with-r-markdown.html#lets-begin"><i class="fa fa-check"></i><b>1.2.1</b> Let’s Begin</a></li>
<li class="chapter" data-level="1.2.2" data-path="starting-with-r-markdown.html"><a href="starting-with-r-markdown.html#code-chunks"><i class="fa fa-check"></i><b>1.2.2</b> Code Chunks</a></li>
<li class="chapter" data-level="1.2.3" data-path="starting-with-r-markdown.html"><a href="starting-with-r-markdown.html#knitting-code"><i class="fa fa-check"></i><b>1.2.3</b> Knitting Code</a></li>
<li class="chapter" data-level="1.2.4" data-path="starting-with-r-markdown.html"><a href="starting-with-r-markdown.html#adding-code-chunk-rules-and-options"><i class="fa fa-check"></i><b>1.2.4</b> Adding Code Chunk Rules and Options</a></li>
<li class="chapter" data-level="1.2.5" data-path="starting-with-r-markdown.html"><a href="starting-with-r-markdown.html#adding-inline-code"><i class="fa fa-check"></i><b>1.2.5</b> Adding Inline Code</a></li>
<li class="chapter" data-level="1.2.6" data-path="starting-with-r-markdown.html"><a href="starting-with-r-markdown.html#formatting-the-r-markdown-file"><i class="fa fa-check"></i><b>1.2.6</b> Formatting the R Markdown File</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="starting-with-r-markdown.html"><a href="starting-with-r-markdown.html#inclass-activiy"><i class="fa fa-check"></i><b>1.3</b> InClass Activiy</a>
<ul>
<li class="chapter" data-level="1.3.1" data-path="starting-with-r-markdown.html"><a href="starting-with-r-markdown.html#r-markdown-and-the-experimental-design-portfolio"><i class="fa fa-check"></i><b>1.3.1</b> R Markdown and The Experimental Design Portfolio</a></li>
<li class="chapter" data-level="1.3.2" data-path="starting-with-r-markdown.html"><a href="starting-with-r-markdown.html#the-ponzo-illusion-and-age"><i class="fa fa-check"></i><b>1.3.2</b> The Ponzo Illusion and Age</a></li>
<li class="chapter" data-level="1.3.3" data-path="starting-with-r-markdown.html"><a href="starting-with-r-markdown.html#Ch1InClassQueT1"><i class="fa fa-check"></i><b>1.3.3</b> Task 1: Setting up Your R Markdown Portfolio</a></li>
<li class="chapter" data-level="1.3.4" data-path="starting-with-r-markdown.html"><a href="starting-with-r-markdown.html#Ch1InClassQueT2"><i class="fa fa-check"></i><b>1.3.4</b> Task 2: Give your Report a Heading</a></li>
<li class="chapter" data-level="1.3.5" data-path="starting-with-r-markdown.html"><a href="starting-with-r-markdown.html#Ch1InClassQueT3"><i class="fa fa-check"></i><b>1.3.5</b> Task 3: Creating a Code Chunk</a></li>
<li class="chapter" data-level="1.3.6" data-path="starting-with-r-markdown.html"><a href="starting-with-r-markdown.html#Ch1InClassQueT4"><i class="fa fa-check"></i><b>1.3.6</b> Task 4: Writing your Report</a></li>
<li class="chapter" data-level="1.3.7" data-path="starting-with-r-markdown.html"><a href="starting-with-r-markdown.html#Ch1InClassQueT5"><i class="fa fa-check"></i><b>1.3.7</b> Task 5: Making Text Bold or Italicized</a></li>
<li class="chapter" data-level="1.3.8" data-path="starting-with-r-markdown.html"><a href="starting-with-r-markdown.html#Ch1InClassQueT6"><i class="fa fa-check"></i><b>1.3.8</b> Task 6: Adding Links to the Data in your Methods</a></li>
<li class="chapter" data-level="1.3.9" data-path="starting-with-r-markdown.html"><a href="starting-with-r-markdown.html#Ch1InClassQueT7"><i class="fa fa-check"></i><b>1.3.9</b> Task 7: Adding an Image to your Methods</a></li>
<li class="chapter" data-level="1.3.10" data-path="starting-with-r-markdown.html"><a href="starting-with-r-markdown.html#Ch1InClassQueT8"><i class="fa fa-check"></i><b>1.3.10</b> Task 8: Adding a Table to your Results</a></li>
<li class="chapter" data-level="1.3.11" data-path="starting-with-r-markdown.html"><a href="starting-with-r-markdown.html#Ch1InClassQueT9"><i class="fa fa-check"></i><b>1.3.11</b> Task 9: Adding a Figure to your Results</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="starting-with-r-markdown.html"><a href="starting-with-r-markdown.html#assignment"><i class="fa fa-check"></i><b>1.4</b> Assignment</a></li>
<li class="chapter" data-level="1.5" data-path="starting-with-r-markdown.html"><a href="starting-with-r-markdown.html#solutions-to-questions"><i class="fa fa-check"></i><b>1.5</b> Solutions to Questions</a>
<ul>
<li class="chapter" data-level="1.5.1" data-path="starting-with-r-markdown.html"><a href="starting-with-r-markdown.html#inclass-activities"><i class="fa fa-check"></i><b>1.5.1</b> InClass Activities</a></li>
</ul></li>
<li class="chapter" data-level="1.6" data-path="starting-with-r-markdown.html"><a href="starting-with-r-markdown.html#inclass-comparison"><i class="fa fa-check"></i><b>1.6</b> InClass Comparison</a>
<ul>
<li class="chapter" data-level="" data-path="starting-with-r-markdown.html"><a href="starting-with-r-markdown.html#lab-1---the-magnitude-of-the-ponzo-illusion-varies-as-a-function-of-age"><i class="fa fa-check"></i>Lab 1 - The Magnitude of the Ponzo Illusion varies as a function of Age</a></li>
<li class="chapter" data-level="" data-path="starting-with-r-markdown.html"><a href="starting-with-r-markdown.html#introduction"><i class="fa fa-check"></i>Introduction</a></li>
<li class="chapter" data-level="" data-path="starting-with-r-markdown.html"><a href="starting-with-r-markdown.html#methods"><i class="fa fa-check"></i>Methods</a></li>
<li class="chapter" data-level="" data-path="starting-with-r-markdown.html"><a href="starting-with-r-markdown.html#results"><i class="fa fa-check"></i>Results</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html"><i class="fa fa-check"></i><b>2</b> Data-Wrangling: A Key Skill</a>
<ul>
<li class="chapter" data-level="2.1" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#overview-2"><i class="fa fa-check"></i><b>2.1</b> Overview</a></li>
<li class="chapter" data-level="2.2" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#preclass-activity"><i class="fa fa-check"></i><b>2.2</b> PreClass Activity</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#revisiting-the-wickham-six"><i class="fa fa-check"></i><b>2.2.1</b> Revisiting the Wickham Six</a></li>
<li class="chapter" data-level="2.2.2" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#learning-to-wrangle-is-there-a-chastity-belt-on-perception"><i class="fa fa-check"></i><b>2.2.2</b> Learning to Wrangle: Is there a Chastity Belt on Perception</a></li>
<li class="chapter" data-level="2.2.3" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#Ch2PreClassQueT1"><i class="fa fa-check"></i><b>2.2.3</b> The <strong><code>select()</code></strong> Function - to keep only specific columns</a></li>
<li class="chapter" data-level="2.2.4" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#Ch2PreClassQueT2"><i class="fa fa-check"></i><b>2.2.4</b> The <strong><code>arrange()</code></strong> Function - to sort and arrange columns</a></li>
<li class="chapter" data-level="2.2.5" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#Ch2PreClassQueT3"><i class="fa fa-check"></i><b>2.2.5</b> The <strong><code>filter()</code></strong> Function - to keep only parts of the data</a></li>
<li class="chapter" data-level="2.2.6" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#Ch2PreClassQueT4"><i class="fa fa-check"></i><b>2.2.6</b> The <strong><code>mutate()</code></strong> Function - for adding new columns</a></li>
<li class="chapter" data-level="2.2.7" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#Ch2PreClassQueT5"><i class="fa fa-check"></i><b>2.2.7</b> The <strong><code>group_by()</code></strong> Function - to group parts of data altogether</a></li>
<li class="chapter" data-level="2.2.8" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#Ch2PreClassQueT6"><i class="fa fa-check"></i><b>2.2.8</b> The <strong><code>summarise()</code></strong> Function - to do some calculations on the data</a></li>
<li class="chapter" data-level="2.2.9" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#two-other-useful-functions"><i class="fa fa-check"></i><b>2.2.9</b> Two Other Useful Functions</a></li>
<li class="chapter" data-level="2.2.10" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#last-but-not-least---pipes-to-make-your-code-efficient"><i class="fa fa-check"></i><b>2.2.10</b> Last but not least - Pipes (<strong><code>%&gt;%</code></strong>) to make your code efficient</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#inclass-activity"><i class="fa fa-check"></i><b>2.3</b> InClass Activity</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#task-1-open-a-script"><i class="fa fa-check"></i><b>2.3.1</b> Task 1: Open a Script</a></li>
<li class="chapter" data-level="2.3.2" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#Ch2InClassQueT2"><i class="fa fa-check"></i><b>2.3.2</b> Task 2: Bring in Your Library</a></li>
<li class="chapter" data-level="2.3.3" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#Ch2InClassQueT3"><i class="fa fa-check"></i><b>2.3.3</b> Task 3: Load in the Data</a></li>
<li class="chapter" data-level="2.3.4" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#Ch2InClassQueT4"><i class="fa fa-check"></i><b>2.3.4</b> Task 4: Review Your Data.</a></li>
<li class="chapter" data-level="2.3.5" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#Ch2InClassQueT5"><i class="fa fa-check"></i><b>2.3.5</b> Task 5: Gathering Data with pivot_longer().</a></li>
<li class="chapter" data-level="2.3.6" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#Ch2InClassQueT6"><i class="fa fa-check"></i><b>2.3.6</b> Task 6: Combining Data.</a></li>
<li class="chapter" data-level="2.3.7" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#Ch2InClassQueT7"><i class="fa fa-check"></i><b>2.3.7</b> Task 7: Calculating the AQ Scores.</a></li>
<li class="chapter" data-level="2.3.8" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#Ch2InClassQueT8"><i class="fa fa-check"></i><b>2.3.8</b> Task 8: One Last Thing on Pipes</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#test-yourself"><i class="fa fa-check"></i><b>2.4</b> Test Yourself</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#todays-topic---the-ageing-brain"><i class="fa fa-check"></i><b>2.4.1</b> Today’s Topic - The Ageing Brain</a></li>
<li class="chapter" data-level="2.4.2" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#load-in-the-data"><i class="fa fa-check"></i><b>2.4.2</b> Load in the data</a></li>
<li class="chapter" data-level="2.4.3" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#Ch2AssignQueT1"><i class="fa fa-check"></i><b>2.4.3</b> Task 1 - Oldest Participant</a></li>
<li class="chapter" data-level="2.4.4" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#Ch2AssignQueT2"><i class="fa fa-check"></i><b>2.4.4</b> Task 2 - Arranging D-SPAN</a></li>
<li class="chapter" data-level="2.4.5" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#Ch2AssignQueT3"><i class="fa fa-check"></i><b>2.4.5</b> Task 3 - Foreign Language Speakers</a></li>
<li class="chapter" data-level="2.4.6" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#Ch2AssignQueT4"><i class="fa fa-check"></i><b>2.4.6</b> Task 4 - Creating Percentage MOCA scores</a></li>
<li class="chapter" data-level="2.4.7" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#Ch2AssignQueT5"><i class="fa fa-check"></i><b>2.4.7</b> Task 5 - Remove the MOCA column</a></li>
<li class="chapter" data-level="2.4.8" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#Ch2AssignQueT6"><i class="fa fa-check"></i><b>2.4.8</b> Task 6 - Gather the Responses together</a></li>
<li class="chapter" data-level="2.4.9" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#Ch2AssignQueT7"><i class="fa fa-check"></i><b>2.4.9</b> Task 7 - Joining the data</a></li>
<li class="chapter" data-level="2.4.10" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#Ch2AssignQueT8"><i class="fa fa-check"></i><b>2.4.10</b> Task 8 - Working the Pipes</a></li>
<li class="chapter" data-level="2.4.11" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#Ch2AssignQueT9"><i class="fa fa-check"></i><b>2.4.11</b> Task 9 - Difference in Musical Means</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#solutions-to-questions-1"><i class="fa fa-check"></i><b>2.5</b> Solutions to Questions</a>
<ul>
<li class="chapter" data-level="2.5.1" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#preclass-activities"><i class="fa fa-check"></i><b>2.5.1</b> PreClass Activities</a></li>
<li class="chapter" data-level="2.5.2" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#inclass-actitivies"><i class="fa fa-check"></i><b>2.5.2</b> InClass Actitivies</a></li>
<li class="chapter" data-level="2.5.3" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#test-yourself-activities"><i class="fa fa-check"></i><b>2.5.3</b> Test Yourself Activities</a></li>
</ul></li>
<li class="chapter" data-level="2.6" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#additional-material"><i class="fa fa-check"></i><b>2.6</b> Additional Material</a>
<ul>
<li class="chapter" data-level="" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#more-on-read_csv"><i class="fa fa-check"></i>More on read_csv()</a></li>
<li class="chapter" data-level="" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#more-on-code-layout"><i class="fa fa-check"></i>More on Code Layout</a></li>
<li><a href="data-wrangling-a-key-skill.html#more-on-gathering-data---pivot_longer-and-gather">More on gathering data - <code>pivot_longer()</code> and <code>gather()</code></a></li>
<li class="chapter" data-level="" data-path="data-wrangling-a-key-skill.html"><a href="data-wrangling-a-key-skill.html#more-on-binding-and-joining"><i class="fa fa-check"></i>More on binding and joining</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="visualisation-through-ggplot2.html"><a href="visualisation-through-ggplot2.html"><i class="fa fa-check"></i><b>3</b> Visualisation Through <strong><code>ggplot2</code></strong></a>
<ul>
<li class="chapter" data-level="3.1" data-path="visualisation-through-ggplot2.html"><a href="visualisation-through-ggplot2.html#overview-3"><i class="fa fa-check"></i><b>3.1</b> Overview</a></li>
<li class="chapter" data-level="3.2" data-path="visualisation-through-ggplot2.html"><a href="visualisation-through-ggplot2.html#preclass-activity-1"><i class="fa fa-check"></i><b>3.2</b> PreClass Activity</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="visualisation-through-ggplot2.html"><a href="visualisation-through-ggplot2.html#scatterplots---geom_point"><i class="fa fa-check"></i><b>3.2.1</b> Scatterplots - <code>geom_point()</code></a></li>
<li class="chapter" data-level="3.2.2" data-path="visualisation-through-ggplot2.html"><a href="visualisation-through-ggplot2.html#histograms---geom_histogram"><i class="fa fa-check"></i><b>3.2.2</b> Histograms - geom_histogram()</a></li>
<li class="chapter" data-level="3.2.3" data-path="visualisation-through-ggplot2.html"><a href="visualisation-through-ggplot2.html#boxplots---geom_boxplot"><i class="fa fa-check"></i><b>3.2.3</b> Boxplots - geom_boxplot()</a></li>
<li class="chapter" data-level="3.2.4" data-path="visualisation-through-ggplot2.html"><a href="visualisation-through-ggplot2.html#barplots---geom_bar-or-geom_col"><i class="fa fa-check"></i><b>3.2.4</b> Barplots - geom_bar() or geom_col()</a></li>
<li class="chapter" data-level="3.2.5" data-path="visualisation-through-ggplot2.html"><a href="visualisation-through-ggplot2.html#themes-labels-guides-and-facet_wraps"><i class="fa fa-check"></i><b>3.2.5</b> Themes, Labels, Guides, and <strong><code>facet_wraps()</code></strong></a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="visualisation-through-ggplot2.html"><a href="visualisation-through-ggplot2.html#inclass-activity-1"><i class="fa fa-check"></i><b>3.3</b> InClass Activity</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="visualisation-through-ggplot2.html"><a href="visualisation-through-ggplot2.html#mental-rotation-angle-and-reaction-time"><i class="fa fa-check"></i><b>3.3.1</b> Mental Rotation: Angle and Reaction Time</a></li>
<li class="chapter" data-level="3.3.2" data-path="visualisation-through-ggplot2.html"><a href="visualisation-through-ggplot2.html#Ch3InClassQueT1"><i class="fa fa-check"></i><b>3.3.2</b> Task 1: Loading and Viewing the Data</a></li>
<li class="chapter" data-level="3.3.3" data-path="visualisation-through-ggplot2.html"><a href="visualisation-through-ggplot2.html#Ch3InClassQueT2"><i class="fa fa-check"></i><b>3.3.3</b> Task 2: Recreating the Figure</a></li>
<li class="chapter" data-level="3.3.4" data-path="visualisation-through-ggplot2.html"><a href="visualisation-through-ggplot2.html#Ch3InClassQueT3"><i class="fa fa-check"></i><b>3.3.4</b> Task 3: Examining Additional Variable Effects</a></li>
<li class="chapter" data-level="3.3.5" data-path="visualisation-through-ggplot2.html"><a href="visualisation-through-ggplot2.html#Ch3InClassQueT4"><i class="fa fa-check"></i><b>3.3.5</b> Task 4: Grouping the Figure Data</a></li>
<li class="chapter" data-level="3.3.6" data-path="visualisation-through-ggplot2.html"><a href="visualisation-through-ggplot2.html#Ch3InClassQueT5"><i class="fa fa-check"></i><b>3.3.6</b> Task 5: Identifying Groups Using <strong><code>aes()</code></strong></a></li>
<li class="chapter" data-level="3.3.7" data-path="visualisation-through-ggplot2.html"><a href="visualisation-through-ggplot2.html#Ch3InClassQueT6"><i class="fa fa-check"></i><b>3.3.7</b> Task 6: Changing the Shape and Size of Data Points</a></li>
<li class="chapter" data-level="3.3.8" data-path="visualisation-through-ggplot2.html"><a href="visualisation-through-ggplot2.html#Ch3InClassQueT7"><i class="fa fa-check"></i><b>3.3.8</b> Task 7: Adding Labels and Changing the Background</a></li>
<li class="chapter" data-level="3.3.9" data-path="visualisation-through-ggplot2.html"><a href="visualisation-through-ggplot2.html#Ch3InClassQueT8"><i class="fa fa-check"></i><b>3.3.9</b> Task 8: Separating a Variable and Removing Legends</a></li>
<li class="chapter" data-level="3.3.10" data-path="visualisation-through-ggplot2.html"><a href="visualisation-through-ggplot2.html#additional-considerations-briefly"><i class="fa fa-check"></i><b>3.3.10</b> Additional Considerations (briefly!)</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="visualisation-through-ggplot2.html"><a href="visualisation-through-ggplot2.html#assignment-1"><i class="fa fa-check"></i><b>3.4</b> Assignment</a></li>
<li class="chapter" data-level="3.5" data-path="visualisation-through-ggplot2.html"><a href="visualisation-through-ggplot2.html#solutions-to-questions-2"><i class="fa fa-check"></i><b>3.5</b> Solutions to Questions</a>
<ul>
<li class="chapter" data-level="3.5.1" data-path="visualisation-through-ggplot2.html"><a href="visualisation-through-ggplot2.html#inclass-activities-1"><i class="fa fa-check"></i><b>3.5.1</b> InClass Activities</a></li>
</ul></li>
<li class="chapter" data-level="3.6" data-path="visualisation-through-ggplot2.html"><a href="visualisation-through-ggplot2.html#additional-material-1"><i class="fa fa-check"></i><b>3.6</b> Additional Material</a>
<ul>
<li><a href="visualisation-through-ggplot2.html#more-on-aes---when-to-and-when-not-to">More on <code>aes()</code> - when to and when not to!</a></li>
<li class="chapter" data-level="" data-path="visualisation-through-ggplot2.html"><a href="visualisation-through-ggplot2.html#combining-plots-into-one-figure"><i class="fa fa-check"></i>Combining Plots into one Figure</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html"><i class="fa fa-check"></i><b>4</b> Revisiting Probability Distributions</a>
<ul>
<li class="chapter" data-level="4.1" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#overview-4"><i class="fa fa-check"></i><b>4.1</b> Overview</a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#discrete-or-continuous-datasets"><i class="fa fa-check"></i><b>4.1.1</b> Discrete or Continuous Datasets</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#preclass-activity-1-1"><i class="fa fa-check"></i><b>4.2</b> PreClass Activity 1</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#general-probability-calculations"><i class="fa fa-check"></i><b>4.2.1</b> General Probability Calculations</a></li>
<li class="chapter" data-level="4.2.2" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#creating-a-simple-probability-distribution"><i class="fa fa-check"></i><b>4.2.2</b> Creating a Simple Probability Distribution</a></li>
<li class="chapter" data-level="4.2.3" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#the-binomial-distribution---creating-a-discrete-distribution"><i class="fa fa-check"></i><b>4.2.3</b> The Binomial Distribution - Creating a Discrete Distribution</a></li>
<li class="chapter" data-level="4.2.4" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#dbinom---the-density-function"><i class="fa fa-check"></i><b>4.2.4</b> <strong><code>dbinom()</code></strong> - The Density Function</a></li>
<li class="chapter" data-level="4.2.5" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#pbinom---the-cumulative-probability-function"><i class="fa fa-check"></i><b>4.2.5</b> <strong><code>pbinom()</code></strong> - The Cumulative Probability Function</a></li>
<li class="chapter" data-level="4.2.6" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#qbinom---the-quantile-function"><i class="fa fa-check"></i><b>4.2.6</b> <strong><code>qbinom()</code></strong> - The Quantile Function</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#preclass-activity-2"><i class="fa fa-check"></i><b>4.3</b> PreClass Activity 2</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#continuous-data---brief-recap-on-the-normal-distribution"><i class="fa fa-check"></i><b>4.3.1</b> Continuous Data - Brief Recap on The Normal Distribution</a></li>
<li class="chapter" data-level="4.3.2" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#properties-of-the-normal-distribution"><i class="fa fa-check"></i><b>4.3.2</b> Properties of the Normal distribution:</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#inclass-activity-1-1"><i class="fa fa-check"></i><b>4.4</b> InClass Activity 1</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#continuous-data-and-the-normal-distribution"><i class="fa fa-check"></i><b>4.4.1</b> Continuous Data and the Normal Distribution</a></li>
<li class="chapter" data-level="4.4.2" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#estimating-from-the-normal-distribution"><i class="fa fa-check"></i><b>4.4.2</b> Estimating from the Normal Distribution</a></li>
<li class="chapter" data-level="4.4.3" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#dnorm---the-density-function-for-the-normal-distribution"><i class="fa fa-check"></i><b>4.4.3</b> <strong><code>dnorm()</code></strong> - The Density Function for the Normal Distribution</a></li>
<li class="chapter" data-level="4.4.4" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#pnorm---the-cumulative-probability-function"><i class="fa fa-check"></i><b>4.4.4</b> <strong><code>pnorm()</code></strong> - The Cumulative Probability function</a></li>
<li class="chapter" data-level="4.4.5" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#qnorm---the-quantile-function"><i class="fa fa-check"></i><b>4.4.5</b> <strong><code>qnorm()</code></strong> - The Quantile Function</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#inclass-activity-2-additional"><i class="fa fa-check"></i><b>4.5</b> InClass Activity 2 (Additional)</a>
<ul>
<li class="chapter" data-level="4.5.1" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#return-of-the-binomial-ch4inclassquebinomial"><i class="fa fa-check"></i><b>4.5.1</b> Return of the Binomial {Ch4InClassQueBinomial}</a></li>
</ul></li>
<li class="chapter" data-level="4.6" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#inclass-activity-3-additional"><i class="fa fa-check"></i><b>4.6</b> InClass Activity 3 (Additional)</a>
<ul>
<li class="chapter" data-level="4.6.1" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#back-to-basics"><i class="fa fa-check"></i><b>4.6.1</b> Back to Basics</a></li>
</ul></li>
<li class="chapter" data-level="4.7" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#test-yourself-1"><i class="fa fa-check"></i><b>4.7</b> Test Yourself</a>
<ul>
<li class="chapter" data-level="4.7.1" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#todays-topic---probability"><i class="fa fa-check"></i><b>4.7.1</b> Today’s Topic - Probability</a></li>
<li class="chapter" data-level="4.7.2" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#Ch4AssignQueLib"><i class="fa fa-check"></i><b>4.7.2</b> Load in the Library</a></li>
<li class="chapter" data-level="4.7.3" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#Ch4AssignQueT1"><i class="fa fa-check"></i><b>4.7.3</b> Assignment Task 1</a></li>
<li class="chapter" data-level="4.7.4" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#Ch4AssignQueT2"><i class="fa fa-check"></i><b>4.7.4</b> Assignment Task 2</a></li>
<li class="chapter" data-level="4.7.5" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#Ch4AssignQueT3"><i class="fa fa-check"></i><b>4.7.5</b> Assignment Task 3</a></li>
<li class="chapter" data-level="4.7.6" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#Ch4AssignQueT4"><i class="fa fa-check"></i><b>4.7.6</b> Assignment Task 4</a></li>
<li class="chapter" data-level="4.7.7" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#Ch4AssignQueT5"><i class="fa fa-check"></i><b>4.7.7</b> Assignment Task 5</a></li>
<li class="chapter" data-level="4.7.8" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#Ch4AssignQueT6"><i class="fa fa-check"></i><b>4.7.8</b> Assignment Task 6</a></li>
<li class="chapter" data-level="4.7.9" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#Ch4AssignQueT7"><i class="fa fa-check"></i><b>4.7.9</b> Assignment Task 7</a></li>
<li class="chapter" data-level="4.7.10" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#Ch4AssignQueT8"><i class="fa fa-check"></i><b>4.7.10</b> Assignment Task 8</a></li>
<li class="chapter" data-level="4.7.11" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#Ch4AssignQueT9"><i class="fa fa-check"></i><b>4.7.11</b> Assignment Task 9</a></li>
<li class="chapter" data-level="4.7.12" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#Ch4AssignQueT10"><i class="fa fa-check"></i><b>4.7.12</b> Assignment Task 10</a></li>
</ul></li>
<li class="chapter" data-level="4.8" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#solutions-to-questions-3"><i class="fa fa-check"></i><b>4.8</b> Solutions to Questions</a>
<ul>
<li class="chapter" data-level="4.8.1" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#inclass-activities-2"><i class="fa fa-check"></i><b>4.8.1</b> InClass Activities</a></li>
<li class="chapter" data-level="4.8.2" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#return-of-the-binomial"><i class="fa fa-check"></i><b>4.8.2</b> Return of the Binomial</a></li>
<li class="chapter" data-level="4.8.3" data-path="revisiting-probability-distributions.html"><a href="revisiting-probability-distributions.html#test-yourself-activities-1"><i class="fa fa-check"></i><b>4.8.3</b> Test Yourself Activities</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="permutation-tests-a-skill-set.html"><a href="permutation-tests-a-skill-set.html"><i class="fa fa-check"></i><b>5</b> Permutation Tests - A Skill Set</a>
<ul>
<li class="chapter" data-level="5.1" data-path="permutation-tests-a-skill-set.html"><a href="permutation-tests-a-skill-set.html#overview-5"><i class="fa fa-check"></i><b>5.1</b> Overview</a></li>
<li class="chapter" data-level="5.2" data-path="permutation-tests-a-skill-set.html"><a href="permutation-tests-a-skill-set.html#preclass-activity-3"><i class="fa fa-check"></i><b>5.2</b> PreClass Activity</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="permutation-tests-a-skill-set.html"><a href="permutation-tests-a-skill-set.html#skill-1-generating-random-numbers"><i class="fa fa-check"></i><b>5.2.1</b> Skill 1: Generating Random Numbers</a></li>
<li class="chapter" data-level="5.2.2" data-path="permutation-tests-a-skill-set.html"><a href="permutation-tests-a-skill-set.html#skill-2-permuting-values"><i class="fa fa-check"></i><b>5.2.2</b> Skill 2: Permuting Values</a></li>
<li class="chapter" data-level="5.2.3" data-path="permutation-tests-a-skill-set.html"><a href="permutation-tests-a-skill-set.html#skill-3-creating-tibbles"><i class="fa fa-check"></i><b>5.2.3</b> Skill 3: Creating Tibbles</a></li>
<li class="chapter" data-level="5.2.4" data-path="permutation-tests-a-skill-set.html"><a href="permutation-tests-a-skill-set.html#skill-4-computing-differences-in-group-means"><i class="fa fa-check"></i><b>5.2.4</b> Skill 4: Computing Differences in Group Means</a></li>
<li class="chapter" data-level="5.2.5" data-path="permutation-tests-a-skill-set.html"><a href="permutation-tests-a-skill-set.html#skill-5-creating-your-own-functions"><i class="fa fa-check"></i><b>5.2.5</b> Skill 5: Creating Your Own Functions</a></li>
<li class="chapter" data-level="5.2.6" data-path="permutation-tests-a-skill-set.html"><a href="permutation-tests-a-skill-set.html#skill-6-replicating-operations"><i class="fa fa-check"></i><b>5.2.6</b> Skill 6: Replicating Operations</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="permutation-tests-a-skill-set.html"><a href="permutation-tests-a-skill-set.html#inclass-activity-2"><i class="fa fa-check"></i><b>5.3</b> InClass Activity</a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="permutation-tests-a-skill-set.html"><a href="permutation-tests-a-skill-set.html#permutation-tests-of-hypotheses"><i class="fa fa-check"></i><b>5.3.1</b> Permutation Tests of Hypotheses</a></li>
<li class="chapter" data-level="5.3.2" data-path="permutation-tests-a-skill-set.html"><a href="permutation-tests-a-skill-set.html#Ch5InClassQueT1"><i class="fa fa-check"></i><b>5.3.2</b> Step 1: Load in Add-on Packages and Data</a></li>
<li class="chapter" data-level="5.3.3" data-path="permutation-tests-a-skill-set.html"><a href="permutation-tests-a-skill-set.html#Ch5InClassQueT2"><i class="fa fa-check"></i><b>5.3.3</b> Step 2: Calculate the Original Mean Difference - <span class="math inline">\(D_{orig}\)</span></a></li>
<li class="chapter" data-level="5.3.4" data-path="permutation-tests-a-skill-set.html"><a href="permutation-tests-a-skill-set.html#Ch5InClassQueT3"><i class="fa fa-check"></i><b>5.3.4</b> Step 3: Permute the Group Labels</a></li>
<li class="chapter" data-level="5.3.5" data-path="permutation-tests-a-skill-set.html"><a href="permutation-tests-a-skill-set.html#Ch5InClassQueT4"><i class="fa fa-check"></i><b>5.3.5</b> Step 4: Create the Null-Hypothesis Distribution (NHD) for the Difference</a></li>
<li class="chapter" data-level="5.3.6" data-path="permutation-tests-a-skill-set.html"><a href="permutation-tests-a-skill-set.html#Ch5InClassQueT5"><i class="fa fa-check"></i><b>5.3.6</b> Step 5: Compare the Observed Mean Difference to the NHD</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="permutation-tests-a-skill-set.html"><a href="permutation-tests-a-skill-set.html#assignment-2"><i class="fa fa-check"></i><b>5.4</b> Assignment</a></li>
<li class="chapter" data-level="5.5" data-path="permutation-tests-a-skill-set.html"><a href="permutation-tests-a-skill-set.html#solutions-to-questions-4"><i class="fa fa-check"></i><b>5.5</b> Solutions to Questions</a>
<ul>
<li class="chapter" data-level="5.5.1" data-path="permutation-tests-a-skill-set.html"><a href="permutation-tests-a-skill-set.html#inclass-activities-3"><i class="fa fa-check"></i><b>5.5.1</b> InClass Activities</a></li>
</ul></li>
<li class="chapter" data-level="5.6" data-path="permutation-tests-a-skill-set.html"><a href="permutation-tests-a-skill-set.html#additional-material-2"><i class="fa fa-check"></i><b>5.6</b> Additional Material</a>
<ul>
<li><a href="permutation-tests-a-skill-set.html#more-on-pivot_wider">More on <code>pivot_wider()</code></a></li>
<li class="chapter" data-level="" data-path="permutation-tests-a-skill-set.html"><a href="permutation-tests-a-skill-set.html#more-on-simulating-your-own-data"><i class="fa fa-check"></i>More on simulating your own data</a></li>
<li class="chapter" data-level="" data-path="permutation-tests-a-skill-set.html"><a href="permutation-tests-a-skill-set.html#more-on-permutations---a-blog"><i class="fa fa-check"></i>More on Permutations - a blog</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="nhst-and-one-sample-t-tests.html"><a href="nhst-and-one-sample-t-tests.html"><i class="fa fa-check"></i><b>6</b> NHST and One-sample t-tests</a>
<ul>
<li class="chapter" data-level="6.1" data-path="nhst-and-one-sample-t-tests.html"><a href="nhst-and-one-sample-t-tests.html#overview-6"><i class="fa fa-check"></i><b>6.1</b> Overview</a></li>
<li class="chapter" data-level="6.2" data-path="nhst-and-one-sample-t-tests.html"><a href="nhst-and-one-sample-t-tests.html#preclass-activity-4"><i class="fa fa-check"></i><b>6.2</b> PreClass Activity</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="nhst-and-one-sample-t-tests.html"><a href="nhst-and-one-sample-t-tests.html#the-binomial-test"><i class="fa fa-check"></i><b>6.2.1</b> The Binomial Test</a></li>
<li class="chapter" data-level="6.2.2" data-path="nhst-and-one-sample-t-tests.html"><a href="nhst-and-one-sample-t-tests.html#Ch6PreClassQueT1"><i class="fa fa-check"></i><b>6.2.2</b> Task 1: Creating a Dataframe</a></li>
<li class="chapter" data-level="6.2.3" data-path="nhst-and-one-sample-t-tests.html"><a href="nhst-and-one-sample-t-tests.html#Ch6PreClassQueT2"><i class="fa fa-check"></i><b>6.2.3</b> Task 2: Comparing Original and New Sample Reaction Times</a></li>
<li class="chapter" data-level="6.2.4" data-path="nhst-and-one-sample-t-tests.html"><a href="nhst-and-one-sample-t-tests.html#Ch6PreClassQueT3"><i class="fa fa-check"></i><b>6.2.4</b> Task 3: Calculating Probability</a></li>
<li class="chapter" data-level="6.2.5" data-path="nhst-and-one-sample-t-tests.html"><a href="nhst-and-one-sample-t-tests.html#the-one-sample-t-test"><i class="fa fa-check"></i><b>6.2.5</b> The One-Sample t-test</a></li>
<li class="chapter" data-level="6.2.6" data-path="nhst-and-one-sample-t-tests.html"><a href="nhst-and-one-sample-t-tests.html#Ch6PreClassQueT4"><i class="fa fa-check"></i><b>6.2.6</b> Task 4: Calculating the Mean and Standard Deviation</a></li>
<li class="chapter" data-level="6.2.7" data-path="nhst-and-one-sample-t-tests.html"><a href="nhst-and-one-sample-t-tests.html#Ch6PreClassQueT5"><i class="fa fa-check"></i><b>6.2.7</b> Task 5: Calculating the Observed Test Statistic</a></li>
<li class="chapter" data-level="6.2.8" data-path="nhst-and-one-sample-t-tests.html"><a href="nhst-and-one-sample-t-tests.html#Ch6PreClassQueT6"><i class="fa fa-check"></i><b>6.2.8</b> Task 6: Comparing the Observed Test Statistic to the t-distribution using <strong><code>pt()</code></strong></a></li>
<li class="chapter" data-level="6.2.9" data-path="nhst-and-one-sample-t-tests.html"><a href="nhst-and-one-sample-t-tests.html#Ch6PreClassQueT7"><i class="fa fa-check"></i><b>6.2.9</b> Task 7: Comparing the Observed Test Statistic to the t-distribution using <strong><code>t.test()</code></strong></a></li>
<li class="chapter" data-level="6.2.10" data-path="nhst-and-one-sample-t-tests.html"><a href="nhst-and-one-sample-t-tests.html#Ch6PreClassQueT8"><i class="fa fa-check"></i><b>6.2.10</b> Task 8: Drawing Conclusions about the new data</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="nhst-and-one-sample-t-tests.html"><a href="nhst-and-one-sample-t-tests.html#inclass-activity-3"><i class="fa fa-check"></i><b>6.3</b> InClass Activity</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="nhst-and-one-sample-t-tests.html"><a href="nhst-and-one-sample-t-tests.html#Ch6InClassQueT1"><i class="fa fa-check"></i><b>6.3.1</b> Task 1: Evaluators</a></li>
<li class="chapter" data-level="6.3.2" data-path="nhst-and-one-sample-t-tests.html"><a href="nhst-and-one-sample-t-tests.html#Ch6InClassQueT2"><i class="fa fa-check"></i><b>6.3.2</b> Task 2: Ratings</a></li>
<li class="chapter" data-level="6.3.3" data-path="nhst-and-one-sample-t-tests.html"><a href="nhst-and-one-sample-t-tests.html#Ch6InClassQueT3"><i class="fa fa-check"></i><b>6.3.3</b> Task 3: Creating a Figure</a></li>
<li class="chapter" data-level="6.3.4" data-path="nhst-and-one-sample-t-tests.html"><a href="nhst-and-one-sample-t-tests.html#Ch6InClassQueT4"><i class="fa fa-check"></i><b>6.3.4</b> Task 4: t-tests</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="nhst-and-one-sample-t-tests.html"><a href="nhst-and-one-sample-t-tests.html#test-yourself-2"><i class="fa fa-check"></i><b>6.4</b> Test Yourself</a>
<ul>
<li class="chapter" data-level="6.4.1" data-path="nhst-and-one-sample-t-tests.html"><a href="nhst-and-one-sample-t-tests.html#Ch6AssignQueT1A"><i class="fa fa-check"></i><b>6.4.1</b> Task 1A: Libraries</a></li>
<li class="chapter" data-level="6.4.2" data-path="nhst-and-one-sample-t-tests.html"><a href="nhst-and-one-sample-t-tests.html#Ch6AssignQueT1B"><i class="fa fa-check"></i><b>6.4.2</b> Task 1B: Loading in the data</a></li>
<li class="chapter" data-level="6.4.3" data-path="nhst-and-one-sample-t-tests.html"><a href="nhst-and-one-sample-t-tests.html#Ch6AssignQueT2"><i class="fa fa-check"></i><b>6.4.3</b> Task 2: Selecting only relevant columns</a></li>
<li class="chapter" data-level="6.4.4" data-path="nhst-and-one-sample-t-tests.html"><a href="nhst-and-one-sample-t-tests.html#Ch6AssignQueT3"><i class="fa fa-check"></i><b>6.4.4</b> Task 3: Verify the number of subjects in each group</a></li>
<li class="chapter" data-level="6.4.5" data-path="nhst-and-one-sample-t-tests.html"><a href="nhst-and-one-sample-t-tests.html#Ch6AssignQueT4"><i class="fa fa-check"></i><b>6.4.5</b> Task 4: Reproduce Figure 2a</a></li>
<li class="chapter" data-level="6.4.6" data-path="nhst-and-one-sample-t-tests.html"><a href="nhst-and-one-sample-t-tests.html#Ch6AssignQueT5"><i class="fa fa-check"></i><b>6.4.6</b> Task 5: Interpreting your Figure</a></li>
<li class="chapter" data-level="6.4.7" data-path="nhst-and-one-sample-t-tests.html"><a href="nhst-and-one-sample-t-tests.html#Ch6AssignQueT6"><i class="fa fa-check"></i><b>6.4.7</b> Task 6: t-test</a></li>
<li class="chapter" data-level="6.4.8" data-path="nhst-and-one-sample-t-tests.html"><a href="nhst-and-one-sample-t-tests.html#Ch6AssignQueT7"><i class="fa fa-check"></i><b>6.4.8</b> Task 7: Reporting results</a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="nhst-and-one-sample-t-tests.html"><a href="nhst-and-one-sample-t-tests.html#solutions-to-questions-5"><i class="fa fa-check"></i><b>6.5</b> Solutions to Questions</a>
<ul>
<li class="chapter" data-level="6.5.1" data-path="nhst-and-one-sample-t-tests.html"><a href="nhst-and-one-sample-t-tests.html#preclass-activities-1"><i class="fa fa-check"></i><b>6.5.1</b> PreClass Activities</a></li>
<li class="chapter" data-level="6.5.2" data-path="nhst-and-one-sample-t-tests.html"><a href="nhst-and-one-sample-t-tests.html#inclass-activities-4"><i class="fa fa-check"></i><b>6.5.2</b> InClass Activities</a></li>
<li class="chapter" data-level="6.5.3" data-path="nhst-and-one-sample-t-tests.html"><a href="nhst-and-one-sample-t-tests.html#test-yourself-activities-2"><i class="fa fa-check"></i><b>6.5.3</b> Test Yourself Activities</a></li>
</ul></li>
<li class="chapter" data-level="6.6" data-path="nhst-and-one-sample-t-tests.html"><a href="nhst-and-one-sample-t-tests.html#additional-material-3"><i class="fa fa-check"></i><b>6.6</b> Additional Material</a>
<ul>
<li><a href="nhst-and-one-sample-t-tests.html#more-on-t.test---vectors-vs.-formula">More on <code>t.test()</code> - vectors vs. formula</a></li>
<li class="chapter" data-level="" data-path="nhst-and-one-sample-t-tests.html"><a href="nhst-and-one-sample-t-tests.html#misleading-and-appropriate-barplots"><i class="fa fa-check"></i>Misleading and Appropriate Barplots</a></li>
<li class="chapter" data-level="" data-path="nhst-and-one-sample-t-tests.html"><a href="nhst-and-one-sample-t-tests.html#analysing-chi-squares"><i class="fa fa-check"></i>Analysing chi-squares</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="within-subjects-t-test.html"><a href="within-subjects-t-test.html"><i class="fa fa-check"></i><b>7</b> Within-Subjects t-test</a>
<ul>
<li class="chapter" data-level="7.1" data-path="within-subjects-t-test.html"><a href="within-subjects-t-test.html#overview-7"><i class="fa fa-check"></i><b>7.1</b> Overview</a></li>
<li class="chapter" data-level="7.2" data-path="within-subjects-t-test.html"><a href="within-subjects-t-test.html#preclass-activity-5"><i class="fa fa-check"></i><b>7.2</b> PreClass Activity</a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="within-subjects-t-test.html"><a href="within-subjects-t-test.html#reading"><i class="fa fa-check"></i><b>7.2.1</b> Reading</a></li>
<li class="chapter" data-level="7.2.2" data-path="within-subjects-t-test.html"><a href="within-subjects-t-test.html#task"><i class="fa fa-check"></i><b>7.2.2</b> Task</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="within-subjects-t-test.html"><a href="within-subjects-t-test.html#inclass-activity-4"><i class="fa fa-check"></i><b>7.3</b> InClass Activity</a>
<ul>
<li class="chapter" data-level="7.3.1" data-path="within-subjects-t-test.html"><a href="within-subjects-t-test.html#Ch7InClassQueT1"><i class="fa fa-check"></i><b>7.3.1</b> Task 1: Load the Data</a></li>
<li class="chapter" data-level="7.3.2" data-path="within-subjects-t-test.html"><a href="within-subjects-t-test.html#Ch7InClassQueT2"><i class="fa fa-check"></i><b>7.3.2</b> Task 2: Wrangle the Data</a></li>
<li class="chapter" data-level="7.3.3" data-path="within-subjects-t-test.html"><a href="within-subjects-t-test.html#Ch7InClassQueT3"><i class="fa fa-check"></i><b>7.3.3</b> Task 3: Look at the Histogram for Normality</a></li>
<li class="chapter" data-level="7.3.4" data-path="within-subjects-t-test.html"><a href="within-subjects-t-test.html#Ch7InClassQueT4"><i class="fa fa-check"></i><b>7.3.4</b> Task 4: A Boxplot of Outliers</a></li>
<li class="chapter" data-level="7.3.5" data-path="within-subjects-t-test.html"><a href="within-subjects-t-test.html#Ch7InClassQueT5"><i class="fa fa-check"></i><b>7.3.5</b> Task 5: The Violin Plot</a></li>
<li class="chapter" data-level="7.3.6" data-path="within-subjects-t-test.html"><a href="within-subjects-t-test.html#Ch7InClassQueT6"><i class="fa fa-check"></i><b>7.3.6</b> Task 6: Calculating Descriptives</a></li>
<li class="chapter" data-level="7.3.7" data-path="within-subjects-t-test.html"><a href="within-subjects-t-test.html#Ch7InClassQueT7"><i class="fa fa-check"></i><b>7.3.7</b> Task 7: Visualising Means and Descriptives</a></li>
<li class="chapter" data-level="7.3.8" data-path="within-subjects-t-test.html"><a href="within-subjects-t-test.html#Ch7InClassQueT8"><i class="fa fa-check"></i><b>7.3.8</b> Task 8: The t-test</a></li>
<li class="chapter" data-level="7.3.9" data-path="within-subjects-t-test.html"><a href="within-subjects-t-test.html#Ch7InClassQueT9"><i class="fa fa-check"></i><b>7.3.9</b> Task 9: The Write-up</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="within-subjects-t-test.html"><a href="within-subjects-t-test.html#assignment-3"><i class="fa fa-check"></i><b>7.4</b> Assignment</a></li>
<li class="chapter" data-level="7.5" data-path="within-subjects-t-test.html"><a href="within-subjects-t-test.html#solutions-to-questions-6"><i class="fa fa-check"></i><b>7.5</b> Solutions to Questions</a>
<ul>
<li class="chapter" data-level="7.5.1" data-path="within-subjects-t-test.html"><a href="within-subjects-t-test.html#inclass-activities-5"><i class="fa fa-check"></i><b>7.5.1</b> InClass Activities</a></li>
</ul></li>
<li class="chapter" data-level="7.6" data-path="within-subjects-t-test.html"><a href="within-subjects-t-test.html#additional-material-4"><i class="fa fa-check"></i><b>7.6</b> Additional Material</a>
<ul>
<li class="chapter" data-level="" data-path="within-subjects-t-test.html"><a href="within-subjects-t-test.html#non-parametric-tests"><i class="fa fa-check"></i>Non-Parametric tests</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="apes-alpha-power-effect-sizes-sample-size.html"><a href="apes-alpha-power-effect-sizes-sample-size.html"><i class="fa fa-check"></i><b>8</b> APES - Alpha, Power, Effect Sizes, Sample Size</a>
<ul>
<li class="chapter" data-level="8.1" data-path="apes-alpha-power-effect-sizes-sample-size.html"><a href="apes-alpha-power-effect-sizes-sample-size.html#overview-8"><i class="fa fa-check"></i><b>8.1</b> Overview</a></li>
<li class="chapter" data-level="8.2" data-path="apes-alpha-power-effect-sizes-sample-size.html"><a href="apes-alpha-power-effect-sizes-sample-size.html#preclass-activity-6"><i class="fa fa-check"></i><b>8.2</b> PreClass Activity</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="apes-alpha-power-effect-sizes-sample-size.html"><a href="apes-alpha-power-effect-sizes-sample-size.html#reading-1"><i class="fa fa-check"></i><b>8.2.1</b> Reading</a></li>
<li class="chapter" data-level="8.2.2" data-path="apes-alpha-power-effect-sizes-sample-size.html"><a href="apes-alpha-power-effect-sizes-sample-size.html#watch"><i class="fa fa-check"></i><b>8.2.2</b> Watch</a></li>
<li class="chapter" data-level="8.2.3" data-path="apes-alpha-power-effect-sizes-sample-size.html"><a href="apes-alpha-power-effect-sizes-sample-size.html#optional"><i class="fa fa-check"></i><b>8.2.3</b> Optional</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="apes-alpha-power-effect-sizes-sample-size.html"><a href="apes-alpha-power-effect-sizes-sample-size.html#inclass-activity-5"><i class="fa fa-check"></i><b>8.3</b> InClass Activity</a>
<ul>
<li class="chapter" data-level="8.3.1" data-path="apes-alpha-power-effect-sizes-sample-size.html"><a href="apes-alpha-power-effect-sizes-sample-size.html#Ch8InClassQueT1"><i class="fa fa-check"></i><b>8.3.1</b> Task 1: Effect size from a one-sample t-test</a></li>
<li class="chapter" data-level="8.3.2" data-path="apes-alpha-power-effect-sizes-sample-size.html"><a href="apes-alpha-power-effect-sizes-sample-size.html#Ch8InClassQueT2"><i class="fa fa-check"></i><b>8.3.2</b> Task 2: Effect size from between-subjects t-test</a></li>
<li class="chapter" data-level="8.3.3" data-path="apes-alpha-power-effect-sizes-sample-size.html"><a href="apes-alpha-power-effect-sizes-sample-size.html#Ch8InClassQueT3"><i class="fa fa-check"></i><b>8.3.3</b> Task 3: Effect Size from matched-pairs t-test</a></li>
<li class="chapter" data-level="8.3.4" data-path="apes-alpha-power-effect-sizes-sample-size.html"><a href="apes-alpha-power-effect-sizes-sample-size.html#Ch8InClassQueT4"><i class="fa fa-check"></i><b>8.3.4</b> Task 4: t-value and effect size for a between-subjects Experiment</a></li>
<li class="chapter" data-level="8.3.5" data-path="apes-alpha-power-effect-sizes-sample-size.html"><a href="apes-alpha-power-effect-sizes-sample-size.html#Ch8InClassQueT5"><i class="fa fa-check"></i><b>8.3.5</b> Task 5: Sample size for standard power one-sample t-test</a></li>
<li class="chapter" data-level="8.3.6" data-path="apes-alpha-power-effect-sizes-sample-size.html"><a href="apes-alpha-power-effect-sizes-sample-size.html#Ch8InClassQueT6"><i class="fa fa-check"></i><b>8.3.6</b> Task 6: Effect size from a high power between-subjects t-test</a></li>
<li class="chapter" data-level="8.3.7" data-path="apes-alpha-power-effect-sizes-sample-size.html"><a href="apes-alpha-power-effect-sizes-sample-size.html#Ch8InClassQueT7"><i class="fa fa-check"></i><b>8.3.7</b> Task 7: Power of Published Research</a></li>
</ul></li>
<li class="chapter" data-level="8.4" data-path="apes-alpha-power-effect-sizes-sample-size.html"><a href="apes-alpha-power-effect-sizes-sample-size.html#test-yourself-3"><i class="fa fa-check"></i><b>8.4</b> Test Yourself</a>
<ul>
<li class="chapter" data-level="8.4.1" data-path="apes-alpha-power-effect-sizes-sample-size.html"><a href="apes-alpha-power-effect-sizes-sample-size.html#Ch8AssignQueT1"><i class="fa fa-check"></i><b>8.4.1</b> Assignment Task 1</a></li>
<li class="chapter" data-level="8.4.2" data-path="apes-alpha-power-effect-sizes-sample-size.html"><a href="apes-alpha-power-effect-sizes-sample-size.html#Ch8AssignQueT2"><i class="fa fa-check"></i><b>8.4.2</b> Assignment Task 2</a></li>
<li class="chapter" data-level="8.4.3" data-path="apes-alpha-power-effect-sizes-sample-size.html"><a href="apes-alpha-power-effect-sizes-sample-size.html#Ch8AssignQueT3"><i class="fa fa-check"></i><b>8.4.3</b> Assignment Task 3</a></li>
<li class="chapter" data-level="8.4.4" data-path="apes-alpha-power-effect-sizes-sample-size.html"><a href="apes-alpha-power-effect-sizes-sample-size.html#Ch8AssignQueT4"><i class="fa fa-check"></i><b>8.4.4</b> Assignment Task 4</a></li>
<li class="chapter" data-level="8.4.5" data-path="apes-alpha-power-effect-sizes-sample-size.html"><a href="apes-alpha-power-effect-sizes-sample-size.html#Ch8AssignQueT5"><i class="fa fa-check"></i><b>8.4.5</b> Assignment Task 5</a></li>
<li class="chapter" data-level="8.4.6" data-path="apes-alpha-power-effect-sizes-sample-size.html"><a href="apes-alpha-power-effect-sizes-sample-size.html#Ch8AssignQueT6"><i class="fa fa-check"></i><b>8.4.6</b> Assignment Task 6</a></li>
<li class="chapter" data-level="8.4.7" data-path="apes-alpha-power-effect-sizes-sample-size.html"><a href="apes-alpha-power-effect-sizes-sample-size.html#Ch8AssignQueT7"><i class="fa fa-check"></i><b>8.4.7</b> Assignment Task 7</a></li>
<li class="chapter" data-level="8.4.8" data-path="apes-alpha-power-effect-sizes-sample-size.html"><a href="apes-alpha-power-effect-sizes-sample-size.html#Ch8AssignQueT8"><i class="fa fa-check"></i><b>8.4.8</b> Assignment Task 8</a></li>
<li class="chapter" data-level="8.4.9" data-path="apes-alpha-power-effect-sizes-sample-size.html"><a href="apes-alpha-power-effect-sizes-sample-size.html#Ch8AssignQueT9"><i class="fa fa-check"></i><b>8.4.9</b> Assignment Task 9</a></li>
<li class="chapter" data-level="8.4.10" data-path="apes-alpha-power-effect-sizes-sample-size.html"><a href="apes-alpha-power-effect-sizes-sample-size.html#Ch8AssignQueT10"><i class="fa fa-check"></i><b>8.4.10</b> Assignment Task 10</a></li>
<li class="chapter" data-level="8.4.11" data-path="apes-alpha-power-effect-sizes-sample-size.html"><a href="apes-alpha-power-effect-sizes-sample-size.html#Ch8AssignQueT11"><i class="fa fa-check"></i><b>8.4.11</b> Assignment Task 11</a></li>
<li class="chapter" data-level="8.4.12" data-path="apes-alpha-power-effect-sizes-sample-size.html"><a href="apes-alpha-power-effect-sizes-sample-size.html#the-pwr-package"><i class="fa fa-check"></i><b>8.4.12</b> The <strong><code>pwr</code></strong> package</a></li>
</ul></li>
<li class="chapter" data-level="8.5" data-path="apes-alpha-power-effect-sizes-sample-size.html"><a href="apes-alpha-power-effect-sizes-sample-size.html#solutions-to-questions-7"><i class="fa fa-check"></i><b>8.5</b> Solutions to Questions</a>
<ul>
<li class="chapter" data-level="8.5.1" data-path="apes-alpha-power-effect-sizes-sample-size.html"><a href="apes-alpha-power-effect-sizes-sample-size.html#inclass-activities-6"><i class="fa fa-check"></i><b>8.5.1</b> InClass Activities</a></li>
<li class="chapter" data-level="8.5.2" data-path="apes-alpha-power-effect-sizes-sample-size.html"><a href="apes-alpha-power-effect-sizes-sample-size.html#test-yourself-activities-3"><i class="fa fa-check"></i><b>8.5.2</b> Test Yourself Activities</a></li>
</ul></li>
<li class="chapter" data-level="8.6" data-path="apes-alpha-power-effect-sizes-sample-size.html"><a href="apes-alpha-power-effect-sizes-sample-size.html#additional-material-5"><i class="fa fa-check"></i><b>8.6</b> Additional Material</a>
<ul>
<li><a href="apes-alpha-power-effect-sizes-sample-size.html#a-different-power-function---power.t.test">A different power function - <code>power.t.test()</code></a></li>
<li class="chapter" data-level="" data-path="apes-alpha-power-effect-sizes-sample-size.html"><a href="apes-alpha-power-effect-sizes-sample-size.html#cohens-d-to-r"><i class="fa fa-check"></i>Cohen’s d to r</a></li>
<li class="chapter" data-level="" data-path="apes-alpha-power-effect-sizes-sample-size.html"><a href="apes-alpha-power-effect-sizes-sample-size.html#how-to-choose-an-effect-size"><i class="fa fa-check"></i>How to choose an effect size</a></li>
<li class="chapter" data-level="" data-path="apes-alpha-power-effect-sizes-sample-size.html"><a href="apes-alpha-power-effect-sizes-sample-size.html#interpreting-and-writing-up-power"><i class="fa fa-check"></i>Interpreting and writing up power</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="reflection-chpts-1-9.html"><a href="reflection-chpts-1-9.html"><i class="fa fa-check"></i><b>9</b> Reflection - Chpts 1-9</a>
<ul>
<li class="chapter" data-level="9.1" data-path="reflection-chpts-1-9.html"><a href="reflection-chpts-1-9.html#overview-9"><i class="fa fa-check"></i><b>9.1</b> Overview</a></li>
<li class="chapter" data-level="9.2" data-path="reflection-chpts-1-9.html"><a href="reflection-chpts-1-9.html#preclass-activity-7"><i class="fa fa-check"></i><b>9.2</b> PreClass Activity</a></li>
<li class="chapter" data-level="9.3" data-path="reflection-chpts-1-9.html"><a href="reflection-chpts-1-9.html#inclass-activity-6"><i class="fa fa-check"></i><b>9.3</b> InClass Activity</a></li>
<li class="chapter" data-level="9.4" data-path="reflection-chpts-1-9.html"><a href="reflection-chpts-1-9.html#assignment-4"><i class="fa fa-check"></i><b>9.4</b> Assignment</a></li>
<li class="chapter" data-level="9.5" data-path="reflection-chpts-1-9.html"><a href="reflection-chpts-1-9.html#solutions-to-questions-8"><i class="fa fa-check"></i><b>9.5</b> Solutions to Questions</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="correlations.html"><a href="correlations.html"><i class="fa fa-check"></i><b>10</b> Correlations</a>
<ul>
<li class="chapter" data-level="10.1" data-path="correlations.html"><a href="correlations.html#overview-10"><i class="fa fa-check"></i><b>10.1</b> Overview</a></li>
<li class="chapter" data-level="10.2" data-path="correlations.html"><a href="correlations.html#preclass-activity-8"><i class="fa fa-check"></i><b>10.2</b> PreClass Activity</a>
<ul>
<li class="chapter" data-level="10.2.1" data-path="correlations.html"><a href="correlations.html#read"><i class="fa fa-check"></i><b>10.2.1</b> Read</a></li>
<li class="chapter" data-level="10.2.2" data-path="correlations.html"><a href="correlations.html#watch-1"><i class="fa fa-check"></i><b>10.2.2</b> Watch</a></li>
<li class="chapter" data-level="10.2.3" data-path="correlations.html"><a href="correlations.html#play"><i class="fa fa-check"></i><b>10.2.3</b> Play</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="correlations.html"><a href="correlations.html#inclass-activity-7"><i class="fa fa-check"></i><b>10.3</b> InClass Activity</a>
<ul>
<li class="chapter" data-level="10.3.1" data-path="correlations.html"><a href="correlations.html#Ch10InClassQueT1"><i class="fa fa-check"></i><b>10.3.1</b> Task 1 - The Data</a></li>
<li class="chapter" data-level="10.3.2" data-path="correlations.html"><a href="correlations.html#Ch10InClassQueT2"><i class="fa fa-check"></i><b>10.3.2</b> Task 2 - Interval or Ordinal</a></li>
<li class="chapter" data-level="10.3.3" data-path="correlations.html"><a href="correlations.html#Ch10InClassQueT3"><i class="fa fa-check"></i><b>10.3.3</b> Task 3 - Missing Data</a></li>
<li class="chapter" data-level="10.3.4" data-path="correlations.html"><a href="correlations.html#Ch10InClassQueT4"><i class="fa fa-check"></i><b>10.3.4</b> Task 4 - Normality</a></li>
<li class="chapter" data-level="10.3.5" data-path="correlations.html"><a href="correlations.html#Ch10InClassQueT5"><i class="fa fa-check"></i><b>10.3.5</b> Task 5 - Descriptives</a></li>
<li class="chapter" data-level="10.3.6" data-path="correlations.html"><a href="correlations.html#Ch10InClassQueT6"><i class="fa fa-check"></i><b>10.3.6</b> Task 6 - Pearson or Spearman?</a></li>
<li class="chapter" data-level="10.3.7" data-path="correlations.html"><a href="correlations.html#Ch10InClassQueT7"><i class="fa fa-check"></i><b>10.3.7</b> Task 7 - Interpretation</a></li>
<li class="chapter" data-level="10.3.8" data-path="correlations.html"><a href="correlations.html#advanced-1-matrix-of-scatterplots"><i class="fa fa-check"></i><b>10.3.8</b> Advanced 1: Matrix of Scatterplots</a></li>
<li class="chapter" data-level="10.3.9" data-path="correlations.html"><a href="correlations.html#Ch10InClassQueT8"><i class="fa fa-check"></i><b>10.3.9</b> Task 8 - The Matrix</a></li>
<li class="chapter" data-level="10.3.10" data-path="correlations.html"><a href="correlations.html#advanced-2-attitudes-towards-vaping"><i class="fa fa-check"></i><b>10.3.10</b> Advanced 2: Attitudes towards Vaping</a></li>
<li class="chapter" data-level="10.3.11" data-path="correlations.html"><a href="correlations.html#Ch10InClassQueT9"><i class="fa fa-check"></i><b>10.3.11</b> Task 9 - Attitudes to Vaping</a></li>
</ul></li>
<li class="chapter" data-level="10.4" data-path="correlations.html"><a href="correlations.html#assignment-5"><i class="fa fa-check"></i><b>10.4</b> Assignment</a></li>
<li class="chapter" data-level="10.5" data-path="correlations.html"><a href="correlations.html#solutions-to-questions-9"><i class="fa fa-check"></i><b>10.5</b> Solutions to Questions</a>
<ul>
<li class="chapter" data-level="10.5.1" data-path="correlations.html"><a href="correlations.html#inclass-activities-7"><i class="fa fa-check"></i><b>10.5.1</b> InClass Activities</a></li>
</ul></li>
<li class="chapter" data-level="10.6" data-path="correlations.html"><a href="correlations.html#additional-material-6"><i class="fa fa-check"></i><b>10.6</b> Additional Material</a>
<ul>
<li class="chapter" data-level="" data-path="correlations.html"><a href="correlations.html#checking-for-outliers-with-z-scores"><i class="fa fa-check"></i>Checking for outliers with z-scores</a></li>
<li class="chapter" data-level="" data-path="correlations.html"><a href="correlations.html#a-different-approach-to-making-a-correlation-table"><i class="fa fa-check"></i>A different approach to making a correlation table</a></li>
<li class="chapter" data-level="" data-path="correlations.html"><a href="correlations.html#comparing-correlations"><i class="fa fa-check"></i>Comparing Correlations</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="11" data-path="introduction-to-glm-one-factor-anova.html"><a href="introduction-to-glm-one-factor-anova.html"><i class="fa fa-check"></i><b>11</b> Introduction to GLM: One-factor ANOVA</a>
<ul>
<li class="chapter" data-level="11.1" data-path="introduction-to-glm-one-factor-anova.html"><a href="introduction-to-glm-one-factor-anova.html#overview-11"><i class="fa fa-check"></i><b>11.1</b> Overview</a></li>
<li class="chapter" data-level="11.2" data-path="introduction-to-glm-one-factor-anova.html"><a href="introduction-to-glm-one-factor-anova.html#preclass-activity-9"><i class="fa fa-check"></i><b>11.2</b> PreClass Activity</a>
<ul>
<li class="chapter" data-level="11.2.1" data-path="introduction-to-glm-one-factor-anova.html"><a href="introduction-to-glm-one-factor-anova.html#read-1"><i class="fa fa-check"></i><b>11.2.1</b> Read</a></li>
</ul></li>
<li class="chapter" data-level="11.3" data-path="introduction-to-glm-one-factor-anova.html"><a href="introduction-to-glm-one-factor-anova.html#inclass-activity-8"><i class="fa fa-check"></i><b>11.3</b> InClass Activity</a>
<ul>
<li class="chapter" data-level="11.3.1" data-path="introduction-to-glm-one-factor-anova.html"><a href="introduction-to-glm-one-factor-anova.html#recreate-decomposition-matrix-from-the-raw-data"><i class="fa fa-check"></i><b>11.3.1</b> Recreate decomposition matrix from the raw data</a></li>
<li class="chapter" data-level="11.3.2" data-path="introduction-to-glm-one-factor-anova.html"><a href="introduction-to-glm-one-factor-anova.html#Ch11InClassQueT1"><i class="fa fa-check"></i><b>11.3.2</b> Step 1: Create the basic tibble</a></li>
<li class="chapter" data-level="11.3.3" data-path="introduction-to-glm-one-factor-anova.html"><a href="introduction-to-glm-one-factor-anova.html#Ch11InClassQueT2"><i class="fa fa-check"></i><b>11.3.3</b> Step 2: Estimate the Grand Mean <span class="math inline">\(\hat{\mu}\)</span></a></li>
<li class="chapter" data-level="11.3.4" data-path="introduction-to-glm-one-factor-anova.html"><a href="introduction-to-glm-one-factor-anova.html#Ch11InClassQueT3"><i class="fa fa-check"></i><b>11.3.4</b> Step 3: Entering the estimates <span class="math inline">\(\hat{A}_1\)</span>, <span class="math inline">\(\hat{A}_2\)</span>, <span class="math inline">\(\hat{A}_3\)</span></a></li>
<li class="chapter" data-level="11.3.5" data-path="introduction-to-glm-one-factor-anova.html"><a href="introduction-to-glm-one-factor-anova.html#Ch11InClassQueT4"><i class="fa fa-check"></i><b>11.3.5</b> Step 4: Calculate Residuals <span class="math inline">\(\widehat{S(A)}_{ij}\)</span></a></li>
<li class="chapter" data-level="11.3.6" data-path="introduction-to-glm-one-factor-anova.html"><a href="introduction-to-glm-one-factor-anova.html#Ch11InClassQueT5"><i class="fa fa-check"></i><b>11.3.6</b> Step 5: Sums of squares</a></li>
</ul></li>
<li class="chapter" data-level="11.4" data-path="introduction-to-glm-one-factor-anova.html"><a href="introduction-to-glm-one-factor-anova.html#test-yourself-4"><i class="fa fa-check"></i><b>11.4</b> Test Yourself</a>
<ul>
<li class="chapter" data-level="11.4.1" data-path="introduction-to-glm-one-factor-anova.html"><a href="introduction-to-glm-one-factor-anova.html#Ch11AssignQueT1"><i class="fa fa-check"></i><b>11.4.1</b> Question 1</a></li>
<li class="chapter" data-level="11.4.2" data-path="introduction-to-glm-one-factor-anova.html"><a href="introduction-to-glm-one-factor-anova.html#Ch11AssignQueT2"><i class="fa fa-check"></i><b>11.4.2</b> Question 2</a></li>
<li class="chapter" data-level="11.4.3" data-path="introduction-to-glm-one-factor-anova.html"><a href="introduction-to-glm-one-factor-anova.html#Ch11AssignQueT3"><i class="fa fa-check"></i><b>11.4.3</b> Question 3</a></li>
<li class="chapter" data-level="11.4.4" data-path="introduction-to-glm-one-factor-anova.html"><a href="introduction-to-glm-one-factor-anova.html#Ch11AssignQueT4"><i class="fa fa-check"></i><b>11.4.4</b> Question 4</a></li>
<li class="chapter" data-level="11.4.5" data-path="introduction-to-glm-one-factor-anova.html"><a href="introduction-to-glm-one-factor-anova.html#Ch11AssignQueT5"><i class="fa fa-check"></i><b>11.4.5</b> Question 5</a></li>
<li class="chapter" data-level="11.4.6" data-path="introduction-to-glm-one-factor-anova.html"><a href="introduction-to-glm-one-factor-anova.html#Ch11AssignQueT6"><i class="fa fa-check"></i><b>11.4.6</b> Question 6</a></li>
<li class="chapter" data-level="11.4.7" data-path="introduction-to-glm-one-factor-anova.html"><a href="introduction-to-glm-one-factor-anova.html#Ch11AssignQueT7"><i class="fa fa-check"></i><b>11.4.7</b> Question 7</a></li>
<li class="chapter" data-level="11.4.8" data-path="introduction-to-glm-one-factor-anova.html"><a href="introduction-to-glm-one-factor-anova.html#Ch11AssignQueT8"><i class="fa fa-check"></i><b>11.4.8</b> Question 8</a></li>
<li class="chapter" data-level="11.4.9" data-path="introduction-to-glm-one-factor-anova.html"><a href="introduction-to-glm-one-factor-anova.html#Ch11AssignQueT9"><i class="fa fa-check"></i><b>11.4.9</b> Question 9: Create your own decomposition matrix</a></li>
</ul></li>
<li class="chapter" data-level="11.5" data-path="introduction-to-glm-one-factor-anova.html"><a href="introduction-to-glm-one-factor-anova.html#solutions-to-questions-10"><i class="fa fa-check"></i><b>11.5</b> Solutions to Questions</a>
<ul>
<li class="chapter" data-level="11.5.1" data-path="introduction-to-glm-one-factor-anova.html"><a href="introduction-to-glm-one-factor-anova.html#inclass-activities-8"><i class="fa fa-check"></i><b>11.5.1</b> InClass Activities</a></li>
<li class="chapter" data-level="11.5.2" data-path="introduction-to-glm-one-factor-anova.html"><a href="introduction-to-glm-one-factor-anova.html#test-yourself-activities-4"><i class="fa fa-check"></i><b>11.5.2</b> Test Yourself Activities</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="12" data-path="continuing-the-glm-one-factor-anova.html"><a href="continuing-the-glm-one-factor-anova.html"><i class="fa fa-check"></i><b>12</b> Continuing the GLM: One-factor ANOVA</a>
<ul>
<li class="chapter" data-level="12.1" data-path="continuing-the-glm-one-factor-anova.html"><a href="continuing-the-glm-one-factor-anova.html#overview-12"><i class="fa fa-check"></i><b>12.1</b> Overview</a></li>
<li class="chapter" data-level="12.2" data-path="continuing-the-glm-one-factor-anova.html"><a href="continuing-the-glm-one-factor-anova.html#preclass-activity-10"><i class="fa fa-check"></i><b>12.2</b> PreClass Activity</a>
<ul>
<li class="chapter" data-level="12.2.1" data-path="continuing-the-glm-one-factor-anova.html"><a href="continuing-the-glm-one-factor-anova.html#read-2"><i class="fa fa-check"></i><b>12.2.1</b> Read</a></li>
<li class="chapter" data-level="12.2.2" data-path="continuing-the-glm-one-factor-anova.html"><a href="continuing-the-glm-one-factor-anova.html#try"><i class="fa fa-check"></i><b>12.2.2</b> Try</a></li>
</ul></li>
<li class="chapter" data-level="12.3" data-path="continuing-the-glm-one-factor-anova.html"><a href="continuing-the-glm-one-factor-anova.html#inclass-activity-9"><i class="fa fa-check"></i><b>12.3</b> InClass Activity</a>
<ul>
<li class="chapter" data-level="12.3.1" data-path="continuing-the-glm-one-factor-anova.html"><a href="continuing-the-glm-one-factor-anova.html#Ch12InClassQueT1"><i class="fa fa-check"></i><b>12.3.1</b> Task 1 - Quick Checks</a></li>
<li class="chapter" data-level="12.3.2" data-path="continuing-the-glm-one-factor-anova.html"><a href="continuing-the-glm-one-factor-anova.html#Ch12InClassQueT2"><i class="fa fa-check"></i><b>12.3.2</b> Task 2 - Mean squares and degrees of freedom</a></li>
<li class="chapter" data-level="12.3.3" data-path="continuing-the-glm-one-factor-anova.html"><a href="continuing-the-glm-one-factor-anova.html#Ch12InClassQueT3"><i class="fa fa-check"></i><b>12.3.3</b> Task 3 - F-ratios</a></li>
<li class="chapter" data-level="12.3.4" data-path="continuing-the-glm-one-factor-anova.html"><a href="continuing-the-glm-one-factor-anova.html#Ch12InClassQueT4"><i class="fa fa-check"></i><b>12.3.4</b> Task 4 - Using afex::aov_ez()</a></li>
</ul></li>
<li class="chapter" data-level="12.4" data-path="continuing-the-glm-one-factor-anova.html"><a href="continuing-the-glm-one-factor-anova.html#assignment-6"><i class="fa fa-check"></i><b>12.4</b> Assignment</a></li>
<li class="chapter" data-level="12.5" data-path="continuing-the-glm-one-factor-anova.html"><a href="continuing-the-glm-one-factor-anova.html#solutions-to-questions-11"><i class="fa fa-check"></i><b>12.5</b> Solutions to Questions</a>
<ul>
<li class="chapter" data-level="12.5.1" data-path="continuing-the-glm-one-factor-anova.html"><a href="continuing-the-glm-one-factor-anova.html#inclass-activities-9"><i class="fa fa-check"></i><b>12.5.1</b> InClass Activities</a></li>
</ul></li>
<li class="chapter" data-level="12.6" data-path="continuing-the-glm-one-factor-anova.html"><a href="continuing-the-glm-one-factor-anova.html#additional-material-7"><i class="fa fa-check"></i><b>12.6</b> Additional Material</a>
<ul>
<li class="chapter" data-level="12.6.1" data-path="continuing-the-glm-one-factor-anova.html"><a href="continuing-the-glm-one-factor-anova.html#levenes-test-of-homogeneity"><i class="fa fa-check"></i><b>12.6.1</b> Levene’s Test of Homogeneity</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="13" data-path="continuing-the-glm-two-factor-designs.html"><a href="continuing-the-glm-two-factor-designs.html"><i class="fa fa-check"></i><b>13</b> Continuing the GLM: Two-factor designs</a>
<ul>
<li class="chapter" data-level="13.1" data-path="continuing-the-glm-two-factor-designs.html"><a href="continuing-the-glm-two-factor-designs.html#overview-13"><i class="fa fa-check"></i><b>13.1</b> Overview</a></li>
<li class="chapter" data-level="13.2" data-path="continuing-the-glm-two-factor-designs.html"><a href="continuing-the-glm-two-factor-designs.html#preclass-activity-11"><i class="fa fa-check"></i><b>13.2</b> PreClass Activity</a>
<ul>
<li class="chapter" data-level="13.2.1" data-path="continuing-the-glm-two-factor-designs.html"><a href="continuing-the-glm-two-factor-designs.html#read-3"><i class="fa fa-check"></i><b>13.2.1</b> Read</a></li>
<li class="chapter" data-level="13.2.2" data-path="continuing-the-glm-two-factor-designs.html"><a href="continuing-the-glm-two-factor-designs.html#try-1"><i class="fa fa-check"></i><b>13.2.2</b> TRY</a></li>
</ul></li>
<li class="chapter" data-level="13.3" data-path="continuing-the-glm-two-factor-designs.html"><a href="continuing-the-glm-two-factor-designs.html#inclass-activity-10"><i class="fa fa-check"></i><b>13.3</b> InClass Activity</a>
<ul>
<li class="chapter" data-level="13.3.1" data-path="continuing-the-glm-two-factor-designs.html"><a href="continuing-the-glm-two-factor-designs.html#Ch13InClassQueT1"><i class="fa fa-check"></i><b>13.3.1</b> Estimation equations and decomposition matrix</a></li>
<li class="chapter" data-level="13.3.2" data-path="continuing-the-glm-two-factor-designs.html"><a href="continuing-the-glm-two-factor-designs.html#Ch13InClassQueT2"><i class="fa fa-check"></i><b>13.3.2</b> Adding the missing columns</a></li>
<li class="chapter" data-level="13.3.3" data-path="continuing-the-glm-two-factor-designs.html"><a href="continuing-the-glm-two-factor-designs.html#Ch13InClassQueT3"><i class="fa fa-check"></i><b>13.3.3</b> Understanding the two-factor decomposition matrix</a></li>
<li class="chapter" data-level="13.3.4" data-path="continuing-the-glm-two-factor-designs.html"><a href="continuing-the-glm-two-factor-designs.html#Ch13InClassQueT4"><i class="fa fa-check"></i><b>13.3.4</b> Get your data ready for analysis</a></li>
<li class="chapter" data-level="13.3.5" data-path="continuing-the-glm-two-factor-designs.html"><a href="continuing-the-glm-two-factor-designs.html#Ch13InClassQueT5"><i class="fa fa-check"></i><b>13.3.5</b> Visualizing 2x2 designs: The interaction plot</a></li>
<li class="chapter" data-level="13.3.6" data-path="continuing-the-glm-two-factor-designs.html"><a href="continuing-the-glm-two-factor-designs.html#Ch13InClassQueT6"><i class="fa fa-check"></i><b>13.3.6</b> Running a 2x2 between-subjects ANOVA with aov_ez</a></li>
<li class="chapter" data-level="13.3.7" data-path="continuing-the-glm-two-factor-designs.html"><a href="continuing-the-glm-two-factor-designs.html#app-understanding-main-effects-and-interactions"><i class="fa fa-check"></i><b>13.3.7</b> App: Understanding main effects and interactions</a></li>
</ul></li>
<li class="chapter" data-level="13.4" data-path="continuing-the-glm-two-factor-designs.html"><a href="continuing-the-glm-two-factor-designs.html#test-yourself-5"><i class="fa fa-check"></i><b>13.4</b> Test Yourself</a>
<ul>
<li class="chapter" data-level="13.4.1" data-path="continuing-the-glm-two-factor-designs.html"><a href="continuing-the-glm-two-factor-designs.html#Ch13AssignQueT1A"><i class="fa fa-check"></i><b>13.4.1</b> Task 1A: Libraries</a></li>
<li class="chapter" data-level="13.4.2" data-path="continuing-the-glm-two-factor-designs.html"><a href="continuing-the-glm-two-factor-designs.html#Ch13AssignQueT1B"><i class="fa fa-check"></i><b>13.4.2</b> Task 1B: Loading in the data</a></li>
<li class="chapter" data-level="13.4.3" data-path="continuing-the-glm-two-factor-designs.html"><a href="continuing-the-glm-two-factor-designs.html#Ch13AssignQueT2"><i class="fa fa-check"></i><b>13.4.3</b> Task 2: Calculate cell means</a></li>
<li class="chapter" data-level="13.4.4" data-path="continuing-the-glm-two-factor-designs.html"><a href="continuing-the-glm-two-factor-designs.html#Ch13AssignQueT3"><i class="fa fa-check"></i><b>13.4.4</b> Task 3: Marginal means for sex</a></li>
<li class="chapter" data-level="13.4.5" data-path="continuing-the-glm-two-factor-designs.html"><a href="continuing-the-glm-two-factor-designs.html#Ch13AssignQueT4"><i class="fa fa-check"></i><b>13.4.5</b> Task 4: Marginal means for condition</a></li>
<li class="chapter" data-level="13.4.6" data-path="continuing-the-glm-two-factor-designs.html"><a href="continuing-the-glm-two-factor-designs.html#Ch13AssignQueT5"><i class="fa fa-check"></i><b>13.4.6</b> Task 5: Interaction plot</a></li>
<li class="chapter" data-level="13.4.7" data-path="continuing-the-glm-two-factor-designs.html"><a href="continuing-the-glm-two-factor-designs.html#Ch13AssignQueT6"><i class="fa fa-check"></i><b>13.4.7</b> Task 6: Recap Question 1</a></li>
<li class="chapter" data-level="13.4.8" data-path="continuing-the-glm-two-factor-designs.html"><a href="continuing-the-glm-two-factor-designs.html#Ch13AssignQueT7"><i class="fa fa-check"></i><b>13.4.8</b> Task 7: Recap Question 2</a></li>
<li class="chapter" data-level="13.4.9" data-path="continuing-the-glm-two-factor-designs.html"><a href="continuing-the-glm-two-factor-designs.html#Ch13AssignQueT8"><i class="fa fa-check"></i><b>13.4.9</b> Task 8: Recap Question 3</a></li>
<li class="chapter" data-level="13.4.10" data-path="continuing-the-glm-two-factor-designs.html"><a href="continuing-the-glm-two-factor-designs.html#Ch13AssignQueT9"><i class="fa fa-check"></i><b>13.4.10</b> Task 9: Running the factorial ANOVA</a></li>
<li class="chapter" data-level="13.4.11" data-path="continuing-the-glm-two-factor-designs.html"><a href="continuing-the-glm-two-factor-designs.html#Ch13AssignQueT10"><i class="fa fa-check"></i><b>13.4.11</b> Task 10: Interpreting the ANOVA output Question</a></li>
<li class="chapter" data-level="13.4.12" data-path="continuing-the-glm-two-factor-designs.html"><a href="continuing-the-glm-two-factor-designs.html#Ch13AssignQueT11"><i class="fa fa-check"></i><b>13.4.12</b> Task 11: Report your results</a></li>
</ul></li>
<li class="chapter" data-level="13.5" data-path="continuing-the-glm-two-factor-designs.html"><a href="continuing-the-glm-two-factor-designs.html#solutions-to-questions-12"><i class="fa fa-check"></i><b>13.5</b> Solutions to Questions</a>
<ul>
<li class="chapter" data-level="13.5.1" data-path="continuing-the-glm-two-factor-designs.html"><a href="continuing-the-glm-two-factor-designs.html#inclass-activities-10"><i class="fa fa-check"></i><b>13.5.1</b> InClass Activities</a></li>
<li class="chapter" data-level="13.5.2" data-path="continuing-the-glm-two-factor-designs.html"><a href="continuing-the-glm-two-factor-designs.html#test-yourself-activities-5"><i class="fa fa-check"></i><b>13.5.2</b> Test Yourself Activities</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="14" data-path="regression.html"><a href="regression.html"><i class="fa fa-check"></i><b>14</b> Regression</a>
<ul>
<li class="chapter" data-level="14.1" data-path="regression.html"><a href="regression.html#overview-14"><i class="fa fa-check"></i><b>14.1</b> Overview</a></li>
<li class="chapter" data-level="14.2" data-path="regression.html"><a href="regression.html#preclass-activity-12"><i class="fa fa-check"></i><b>14.2</b> PreClass Activity</a>
<ul>
<li class="chapter" data-level="14.2.1" data-path="regression.html"><a href="regression.html#read-4"><i class="fa fa-check"></i><b>14.2.1</b> Read</a></li>
</ul></li>
<li class="chapter" data-level="14.3" data-path="regression.html"><a href="regression.html#inclass-activity-11"><i class="fa fa-check"></i><b>14.3</b> InClass Activity</a>
<ul>
<li class="chapter" data-level="14.3.1" data-path="regression.html"><a href="regression.html#Ch14InClassQueT1"><i class="fa fa-check"></i><b>14.3.1</b> Task 1: Setup</a></li>
<li class="chapter" data-level="14.3.2" data-path="regression.html"><a href="regression.html#Ch14InClassQueT2"><i class="fa fa-check"></i><b>14.3.2</b> Task 2: Restructuring the ratings</a></li>
<li class="chapter" data-level="14.3.3" data-path="regression.html"><a href="regression.html#Ch14InClassQueT3"><i class="fa fa-check"></i><b>14.3.3</b> Task 3: Calculate mean trustworthiness rating for each voice</a></li>
<li class="chapter" data-level="14.3.4" data-path="regression.html"><a href="regression.html#Ch14InClassQueT4"><i class="fa fa-check"></i><b>14.3.4</b> Task 4: Joining the Data together</a></li>
<li class="chapter" data-level="14.3.5" data-path="regression.html"><a href="regression.html#Ch14InClassQueT5"><i class="fa fa-check"></i><b>14.3.5</b> Task 5: Scatterplot</a></li>
<li class="chapter" data-level="14.3.6" data-path="regression.html"><a href="regression.html#Ch14InClassQueT6"><i class="fa fa-check"></i><b>14.3.6</b> Task 6: Spreading the data with <code>pivot_wider()</code></a></li>
<li class="chapter" data-level="14.3.7" data-path="regression.html"><a href="regression.html#Ch14InClassQueT7"><i class="fa fa-check"></i><b>14.3.7</b> Task 7: The Regressions</a></li>
<li class="chapter" data-level="14.3.8" data-path="regression.html"><a href="regression.html#Ch14InClassQueT8"><i class="fa fa-check"></i><b>14.3.8</b> Task 8: Model interpretations</a></li>
<li class="chapter" data-level="14.3.9" data-path="regression.html"><a href="regression.html#Ch14InClassQueT9"><i class="fa fa-check"></i><b>14.3.9</b> Task 9: Making predictions</a></li>
</ul></li>
<li class="chapter" data-level="14.4" data-path="regression.html"><a href="regression.html#assignment-7"><i class="fa fa-check"></i><b>14.4</b> Assignment</a></li>
<li class="chapter" data-level="14.5" data-path="regression.html"><a href="regression.html#solutions-to-questions-13"><i class="fa fa-check"></i><b>14.5</b> Solutions to Questions</a>
<ul>
<li class="chapter" data-level="14.5.1" data-path="regression.html"><a href="regression.html#inclass-activities-11"><i class="fa fa-check"></i><b>14.5.1</b> InClass Activities</a></li>
<li class="chapter" data-level="14.5.2" data-path="regression.html"><a href="regression.html#task-1-1"><i class="fa fa-check"></i><b>14.5.2</b> Task 1</a></li>
<li class="chapter" data-level="14.5.3" data-path="regression.html"><a href="regression.html#task-2"><i class="fa fa-check"></i><b>14.5.3</b> Task 2</a></li>
<li class="chapter" data-level="14.5.4" data-path="regression.html"><a href="regression.html#task-3"><i class="fa fa-check"></i><b>14.5.4</b> Task 3</a></li>
<li class="chapter" data-level="14.5.5" data-path="regression.html"><a href="regression.html#task-4"><i class="fa fa-check"></i><b>14.5.5</b> Task 4</a></li>
<li class="chapter" data-level="14.5.6" data-path="regression.html"><a href="regression.html#task-5"><i class="fa fa-check"></i><b>14.5.6</b> Task 5</a></li>
<li class="chapter" data-level="14.5.7" data-path="regression.html"><a href="regression.html#task-6"><i class="fa fa-check"></i><b>14.5.7</b> Task 6</a></li>
<li class="chapter" data-level="14.5.8" data-path="regression.html"><a href="regression.html#task-7"><i class="fa fa-check"></i><b>14.5.8</b> Task 7</a></li>
<li class="chapter" data-level="14.5.9" data-path="regression.html"><a href="regression.html#task-8"><i class="fa fa-check"></i><b>14.5.9</b> Task 8</a></li>
<li class="chapter" data-level="14.5.10" data-path="regression.html"><a href="regression.html#task-9"><i class="fa fa-check"></i><b>14.5.10</b> Task 9</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="15" data-path="combining-anova-and-regression-e-g-ancovas.html"><a href="combining-anova-and-regression-e-g-ancovas.html"><i class="fa fa-check"></i><b>15</b> Combining ANOVA and Regression (e.g. ANCOVAs)</a>
<ul>
<li class="chapter" data-level="15.1" data-path="combining-anova-and-regression-e-g-ancovas.html"><a href="combining-anova-and-regression-e-g-ancovas.html#overview-15"><i class="fa fa-check"></i><b>15.1</b> Overview</a></li>
<li class="chapter" data-level="15.2" data-path="combining-anova-and-regression-e-g-ancovas.html"><a href="combining-anova-and-regression-e-g-ancovas.html#preclass-activity-13"><i class="fa fa-check"></i><b>15.2</b> PreClass Activity</a>
<ul>
<li class="chapter" data-level="15.2.1" data-path="combining-anova-and-regression-e-g-ancovas.html"><a href="combining-anova-and-regression-e-g-ancovas.html#read-5"><i class="fa fa-check"></i><b>15.2.1</b> Read</a></li>
<li class="chapter" data-level="15.2.2" data-path="combining-anova-and-regression-e-g-ancovas.html"><a href="combining-anova-and-regression-e-g-ancovas.html#activity"><i class="fa fa-check"></i><b>15.2.2</b> Activity</a></li>
<li class="chapter" data-level="15.2.3" data-path="combining-anova-and-regression-e-g-ancovas.html"><a href="combining-anova-and-regression-e-g-ancovas.html#Ch15PreClassQueT1"><i class="fa fa-check"></i><b>15.2.3</b> Loading in the data</a></li>
<li class="chapter" data-level="15.2.4" data-path="combining-anova-and-regression-e-g-ancovas.html"><a href="combining-anova-and-regression-e-g-ancovas.html#Ch15PreClassQueT2"><i class="fa fa-check"></i><b>15.2.4</b> Compute the well-being score for each participant</a></li>
<li class="chapter" data-level="15.2.5" data-path="combining-anova-and-regression-e-g-ancovas.html"><a href="combining-anova-and-regression-e-g-ancovas.html#Ch15PreClassQueT3"><i class="fa fa-check"></i><b>15.2.5</b> Visualising Screen time on all technologies</a></li>
<li class="chapter" data-level="15.2.6" data-path="combining-anova-and-regression-e-g-ancovas.html"><a href="combining-anova-and-regression-e-g-ancovas.html#Ch15PreClassQueT4"><i class="fa fa-check"></i><b>15.2.6</b> Visualising the Screen time and Well-being relationship</a></li>
</ul></li>
<li class="chapter" data-level="15.3" data-path="combining-anova-and-regression-e-g-ancovas.html"><a href="combining-anova-and-regression-e-g-ancovas.html#inclass-activity-12"><i class="fa fa-check"></i><b>15.3</b> InClass Activity</a>
<ul>
<li class="chapter" data-level="15.3.1" data-path="combining-anova-and-regression-e-g-ancovas.html"><a href="combining-anova-and-regression-e-g-ancovas.html#Ch15InClassQueT1"><i class="fa fa-check"></i><b>15.3.1</b> Smartphone and well-being for boys and girls</a></li>
<li class="chapter" data-level="15.3.2" data-path="combining-anova-and-regression-e-g-ancovas.html"><a href="combining-anova-and-regression-e-g-ancovas.html#Ch15InClassQueT2"><i class="fa fa-check"></i><b>15.3.2</b> Visualising and Interpreting the relationship between smartphone use and wellbeing by sex</a></li>
<li class="chapter" data-level="15.3.3" data-path="combining-anova-and-regression-e-g-ancovas.html"><a href="combining-anova-and-regression-e-g-ancovas.html#a-side-point-on-mean-centering-and-deviation-coding"><i class="fa fa-check"></i><b>15.3.3</b> A side point on mean centering and deviation coding</a></li>
<li class="chapter" data-level="15.3.4" data-path="combining-anova-and-regression-e-g-ancovas.html"><a href="combining-anova-and-regression-e-g-ancovas.html#Ch15InClassQueT3"><i class="fa fa-check"></i><b>15.3.4</b> Estimating model parameters</a></li>
<li class="chapter" data-level="15.3.5" data-path="combining-anova-and-regression-e-g-ancovas.html"><a href="combining-anova-and-regression-e-g-ancovas.html#Ch15InClassQueT4"><i class="fa fa-check"></i><b>15.3.5</b> Final Interpretations</a></li>
</ul></li>
<li class="chapter" data-level="15.4" data-path="combining-anova-and-regression-e-g-ancovas.html"><a href="combining-anova-and-regression-e-g-ancovas.html#test-yourself-6"><i class="fa fa-check"></i><b>15.4</b> Test Yourself</a>
<ul>
<li class="chapter" data-level="15.4.1" data-path="combining-anova-and-regression-e-g-ancovas.html"><a href="combining-anova-and-regression-e-g-ancovas.html#Ch15AssignQueT1A"><i class="fa fa-check"></i><b>15.4.1</b> Task 1A: Load add-on packages</a></li>
<li class="chapter" data-level="15.4.2" data-path="combining-anova-and-regression-e-g-ancovas.html"><a href="combining-anova-and-regression-e-g-ancovas.html#Ch15AssignQueT1B"><i class="fa fa-check"></i><b>15.4.2</b> Task 1B: Load the data</a></li>
<li class="chapter" data-level="15.4.3" data-path="combining-anova-and-regression-e-g-ancovas.html"><a href="combining-anova-and-regression-e-g-ancovas.html#Ch15AssignQueT2"><i class="fa fa-check"></i><b>15.4.3</b> Task 2: Demographics</a></li>
<li class="chapter" data-level="15.4.4" data-path="combining-anova-and-regression-e-g-ancovas.html"><a href="combining-anova-and-regression-e-g-ancovas.html#Ch15AssignQueT3"><i class="fa fa-check"></i><b>15.4.4</b> Task 3: Plotting the general relationship of F0 and HGS</a></li>
<li class="chapter" data-level="15.4.5" data-path="combining-anova-and-regression-e-g-ancovas.html"><a href="combining-anova-and-regression-e-g-ancovas.html#Ch15AssignQueT4"><i class="fa fa-check"></i><b>15.4.5</b> Task 4: Analysing the general relationship of F0 and HGS</a></li>
<li class="chapter" data-level="15.4.6" data-path="combining-anova-and-regression-e-g-ancovas.html"><a href="combining-anova-and-regression-e-g-ancovas.html#Ch15AssignQueT5"><i class="fa fa-check"></i><b>15.4.6</b> Task 5: Interpreting the general relationship of F0 and HGS</a></li>
<li class="chapter" data-level="15.4.7" data-path="combining-anova-and-regression-e-g-ancovas.html"><a href="combining-anova-and-regression-e-g-ancovas.html#Ch15AssignQueT6"><i class="fa fa-check"></i><b>15.4.7</b> Task 6: Plotting the modulation of voice/strength relationship by sex</a></li>
<li class="chapter" data-level="15.4.8" data-path="combining-anova-and-regression-e-g-ancovas.html"><a href="combining-anova-and-regression-e-g-ancovas.html#Ch15AssignQueT7"><i class="fa fa-check"></i><b>15.4.8</b> Task 7: Mean centering and Deviation coding the variables.</a></li>
<li class="chapter" data-level="15.4.9" data-path="combining-anova-and-regression-e-g-ancovas.html"><a href="combining-anova-and-regression-e-g-ancovas.html#Ch15AssignQueT8"><i class="fa fa-check"></i><b>15.4.9</b> Task 8: Estimate the modulation of voice/strength relationship by sex</a></li>
<li class="chapter" data-level="15.4.10" data-path="combining-anova-and-regression-e-g-ancovas.html"><a href="combining-anova-and-regression-e-g-ancovas.html#Ch15AssignQueT9"><i class="fa fa-check"></i><b>15.4.10</b> Task 9: Interpreting the output 1</a></li>
<li class="chapter" data-level="15.4.11" data-path="combining-anova-and-regression-e-g-ancovas.html"><a href="combining-anova-and-regression-e-g-ancovas.html#Ch15AssignQueT10"><i class="fa fa-check"></i><b>15.4.11</b> Task 10: Interpreting the output 2</a></li>
<li class="chapter" data-level="15.4.12" data-path="combining-anova-and-regression-e-g-ancovas.html"><a href="combining-anova-and-regression-e-g-ancovas.html#Ch15AssignQueT11"><i class="fa fa-check"></i><b>15.4.12</b> Task 11: Interpreting the output 3</a></li>
</ul></li>
<li class="chapter" data-level="15.5" data-path="combining-anova-and-regression-e-g-ancovas.html"><a href="combining-anova-and-regression-e-g-ancovas.html#solutions-to-questions-14"><i class="fa fa-check"></i><b>15.5</b> Solutions to Questions</a>
<ul>
<li class="chapter" data-level="15.5.1" data-path="combining-anova-and-regression-e-g-ancovas.html"><a href="combining-anova-and-regression-e-g-ancovas.html#preclass-activities-2"><i class="fa fa-check"></i><b>15.5.1</b> PreClass Activities</a></li>
<li class="chapter" data-level="15.5.2" data-path="combining-anova-and-regression-e-g-ancovas.html"><a href="combining-anova-and-regression-e-g-ancovas.html#inclass-activities-12"><i class="fa fa-check"></i><b>15.5.2</b> InClass Activities</a></li>
<li class="chapter" data-level="15.5.3" data-path="combining-anova-and-regression-e-g-ancovas.html"><a href="combining-anova-and-regression-e-g-ancovas.html#test-yourself-activities-6"><i class="fa fa-check"></i><b>15.5.3</b> Test Yourself Activities</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="16" data-path="reflection-chpts-10-15.html"><a href="reflection-chpts-10-15.html"><i class="fa fa-check"></i><b>16</b> Reflection - Chpts 10-15</a>
<ul>
<li class="chapter" data-level="16.1" data-path="reflection-chpts-10-15.html"><a href="reflection-chpts-10-15.html#overview-16"><i class="fa fa-check"></i><b>16.1</b> Overview</a></li>
<li class="chapter" data-level="16.2" data-path="reflection-chpts-10-15.html"><a href="reflection-chpts-10-15.html#preclass-activity-14"><i class="fa fa-check"></i><b>16.2</b> PreClass Activity</a></li>
<li class="chapter" data-level="16.3" data-path="reflection-chpts-10-15.html"><a href="reflection-chpts-10-15.html#inclass-activity-13"><i class="fa fa-check"></i><b>16.3</b> InClass Activity</a></li>
<li class="chapter" data-level="16.4" data-path="reflection-chpts-10-15.html"><a href="reflection-chpts-10-15.html#update-your-notes"><i class="fa fa-check"></i><b>16.4</b> Update Your Notes</a></li>
<li class="chapter" data-level="16.5" data-path="reflection-chpts-10-15.html"><a href="reflection-chpts-10-15.html#in-the-end"><i class="fa fa-check"></i><b>16.5</b> In The End!</a></li>
</ul></li>
<li class="appendix"><span><b>Appendices</b></span></li>
<li class="chapter" data-level="" data-path="acknolwedgements.html"><a href="acknolwedgements.html"><i class="fa fa-check"></i>Acknolwedgements</a></li>
<li class="chapter" data-level="" data-path="stats-by-hand.html"><a href="stats-by-hand.html"><i class="fa fa-check"></i>Stats by Hand</a></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a rel="license" href="https://creativecommons.org/licenses/by-sa/4.0/" 
    target="blank"><img alt="Creative Commons License" 
    style="border-width:0" 
    src="https://i.creativecommons.org/l/by-sa/4.0/88x31.png" /></a><li>
<li><a href="https://psyteachr.github.io/" target="blank">PsyTeachR</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Level 2 Research Methods and Statistics Practical Skills</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="continuing-the-glm-one-factor-anova" class="section level1" number="12">
<h1><span class="header-section-number">Lab 12</span> Continuing the GLM: One-factor ANOVA</h1>
<div id="overview-12" class="section level2" number="12.1">
<h2><span class="header-section-number">12.1</span> Overview</h2>
<p>In the previous chapter you learned how to decompose a dependent variable into components of the general linear model, expressing the values in terms of a decomposition matrix, before finishing up with calculating the sums of squares. In this chapter, we will take it a step further and look at running the ANOVA from those values. Through this we will start exploring the relationships between sums of squares (SS), mean squares (MS), degrees of freedom (df), and F-ratios. In this chapter we will show you how you go from the decomposition matrix we created in the previous chapter to actually determining if there is a significant difference or not.</p>
<p>In the last chapter we had you work through the calculations step-by-step “by hand” to gain a conceptual understanding, and we will continue that in the first half of the inclass activities. However, when you run an ANOVA, typically the software does all of these calculations for you. As such, in the second part of the activities, we’ll show you how to run a one-factor ANOVA using the <code>aov_ez()</code> function in the <strong><code>afex</code></strong> add-on package. From there you will see how the output of this function maps onto the concepts you’ve been learning about.</p>
<p>Some key terms from this chapter are:</p>
<ul>
<li><strong>Sums of Squares (SS)</strong> - an estimate of the total spread of the data (variance) around a parameter (such as the mean). We saw these in Chapter 11</li>
<li><strong>degrees of freedom (df)</strong> - the number of observations that are free to vary to produce a known output. Again we have seen these before in all previous tests. The df impacts on the distribution that is used to compare against for probability</li>
<li><strong>Mean Square (MS)</strong> - an average estimate of the spread of the data (variance) calculated by <span class="math inline">\(MS = \frac{SS}{df}\)</span></li>
<li><strong>F-ratio </strong>- the test statistic of the ANOVA from the F-distribution. Calculated as <span class="math inline">\(F = \frac{MS_{between}}{MS_{within}}\)</span> or <span class="math inline">\(F = \frac{MS_{A}}{MS_{err}}\)</span>.</li>
</ul>
<p>Again, these terms will become more familiar as we work through this Chapter so don’t worry if you don’t understand them yet. The main thing to understand is that we go from the indivual data to the decomposition matrix to the Sums of Squares to the Mean Squares to the F-ratio. But in summary this is what we are doing:</p>
<p><strong>ANOVA PATH:</strong> <span class="math inline">\(Data \to Decomp. Matrix \to SS \to MS \to F\)</span></p>
<p>As such, the goals of this chapter are to:</p>
<ul>
<li>to demonstrate how Sums of Squares leads to an F-value, finishing off the decomposition matrix</li>
<li>to determine the probability of a F-value for given degrees of freedom (df)</li>
<li>to explore using the <code>aov_ez()</code> function and how the outcome compares to your decomposition matrix calculations.</li>
</ul>
<p><strong>Note:</strong> The <strong><code>afex</code></strong> package is already installed on the Boyd Orr machines and only needs read into the library in the normal fashion. Do not install it on the Boyd Orr Lab machines. If you are using your own laptop you will need to make sure you have installed the <strong><code>afex</code></strong> package.</p>

</div>
<div id="preclass-activity-10" class="section level2" number="12.2">
<h2><span class="header-section-number">12.2</span> PreClass Activity</h2>
<p>As per the previous Chapter, the PreClass activity for this lab is reading (re-reading in fact) and trying out some of the Miller and Haden activities. We will go over similar activities in the remainder of this chapter so it will really help you to spend a few minutes trying out the Miller and Haden activities and thinking about them.</p>
<div id="read-2" class="section level3" number="12.2.1">
<h3><span class="header-section-number">12.2.1</span> Read</h3>
<p><strong>Chapters</strong></p>
<ul>
<li>Re-read Chapter 3 of <a href="https://drive.google.com/file/d/0B1fyuTuvj3YoaFdUR3FZaXNuNXc/view" target = "_blank">Miller and Haden (2013)</a> and make sure you are understanding it. Particularly focus on how the decomposition matrix leads to the ANOVA output through sums of squares, dfs, and mean squares.</li>
</ul>
</div>
<div id="try" class="section level3" number="12.2.2">
<h3><span class="header-section-number">12.2.2</span> Try</h3>
<p><strong>Activities</strong></p>
<ul>
<li>Test your understanding by working through Computational Exercise #1 in section 3.12 of Miller and Haden (page 31) all the way to the summary table. The answer is in Miller and Haden section 3.13 but be sure to work through the example first. Don’t worry about sketching the data. What you want to do is work the values through the decomposition matrix all the way to the F-value.
<ul>
<li>The decomposition matrix is very similar to the one we looked at in Chapter 11, but with less conditions.</li>
<li>The sums of squares would be calculated the same way as we did in Chapter 11.</li>
<li>Use the formulas shown to calculate F.</li>
</ul></li>
</ul>
<p><span class="math display">\[MS = \frac{SS}{df} \space\space\space\space\space F = \frac{MS_{between}}{MS_{within}}\]</span></p>
<ul>
<li>It may also help to review Chapter 4 on probability as we move onto understanding F distributions and p-values.</li>
</ul>
<p><span style="font-size: 22px; font-weight: bold; color: var(--blue);">Job Done - Activity Complete!</span></p>

</div>
</div>
<div id="inclass-activity-9" class="section level2" number="12.3">
<h2><span class="header-section-number">12.3</span> InClass Activity</h2>
<p><strong>One-factor ANOVA: Worked example</strong></p>
<p>Just like we did in Chapter 11, let’s start with some simulated data corresponding to a between-subjects design with three groups (conditions/levels) on one factor (variable). In this hypothetical study, you’re investigating the effects of ambient noise on concentration. You have participants transcribe a handwritten document onto a laptop and count the number of typing errors (DV = typos) each participant makes under their respective different conditions:</p>
<ul>
<li>while hearing ambient conversation such as you would find in a busy cafe (<strong>cafe</strong> condition);</li>
<li>while listening to mellow jazz music (<strong>jazz</strong> condition);</li>
<li>or in silence (<strong>silence</strong> condition).</li>
</ul>
<p>Again for practice we will only use small, highly under-powered groups. You have three different participants in each condition. As such, your data are as follows:</p>
<ul>
<li><strong>cafe</strong>: 111, 102, 111</li>
<li><strong>jazz</strong>: 89, 127, 90</li>
<li><strong>silence</strong>: 97, 85, 88</li>
</ul>
<p>Below is the decomposition matrix for this data set, based on the GLM: <span class="math display">\[Y_{ij} = \mu + A_i + S(A)_{ij}\]</span></p>
<p>Here we are copying what we did in the last chapter in both the inclass and assignment and what you did for the homework activity - with just less participants. You can have a go at creating the decomposition matrix yourself from scratch if you like, as good practice, or, in the interests of time, feel free to reveal the code and run that code to create the dmx.</p>
<p><strong>Note</strong> that we have also included a column called <code>sub_id</code> with a unique identifier for each participant. This is not that important for the decomposition matrix but we will definitely need it later for running the ANOVA using the <code>afex::aov_ez()</code> function, so let’s just include it now so we don’t forget.</p>
<div class="webex-solution">
<button>
Reveal DMX code
</button>
<div class="sourceCode" id="cb543"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb543-1"><a href="continuing-the-glm-one-factor-anova.html#cb543-1" aria-hidden="true" tabindex="-1"></a>dmx <span class="ot">&lt;-</span> <span class="fu">tibble</span>(<span class="at">sub_id =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">9</span>,</span>
<span id="cb543-2"><a href="continuing-the-glm-one-factor-anova.html#cb543-2" aria-hidden="true" tabindex="-1"></a>              <span class="at">i =</span> <span class="fu">rep</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>, <span class="at">each =</span> <span class="dv">3</span>),</span>
<span id="cb543-3"><a href="continuing-the-glm-one-factor-anova.html#cb543-3" aria-hidden="true" tabindex="-1"></a>              <span class="at">j =</span> <span class="fu">rep</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>, <span class="at">times =</span> <span class="dv">3</span>),</span>
<span id="cb543-4"><a href="continuing-the-glm-one-factor-anova.html#cb543-4" aria-hidden="true" tabindex="-1"></a>              <span class="at">typos =</span> <span class="fu">c</span>(<span class="dv">111</span>, <span class="dv">102</span>, <span class="dv">111</span>, </span>
<span id="cb543-5"><a href="continuing-the-glm-one-factor-anova.html#cb543-5" aria-hidden="true" tabindex="-1"></a>                    <span class="dv">89</span>, <span class="dv">127</span>, <span class="dv">90</span>,</span>
<span id="cb543-6"><a href="continuing-the-glm-one-factor-anova.html#cb543-6" aria-hidden="true" tabindex="-1"></a>                    <span class="dv">97</span>, <span class="dv">85</span>, <span class="dv">88</span>),</span>
<span id="cb543-7"><a href="continuing-the-glm-one-factor-anova.html#cb543-7" aria-hidden="true" tabindex="-1"></a>              <span class="at">sound =</span> <span class="fu">rep</span>(<span class="fu">c</span>(<span class="st">&quot;cafe&quot;</span>, <span class="st">&quot;jazz&quot;</span>, <span class="st">&quot;silence&quot;</span>), <span class="at">each =</span> <span class="dv">3</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb543-8"><a href="continuing-the-glm-one-factor-anova.html#cb543-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">mu =</span> <span class="fu">mean</span>(typos)) <span class="sc">%&gt;%</span></span>
<span id="cb543-9"><a href="continuing-the-glm-one-factor-anova.html#cb543-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(i) <span class="sc">%&gt;%</span></span>
<span id="cb543-10"><a href="continuing-the-glm-one-factor-anova.html#cb543-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Ai =</span> <span class="fu">mean</span>(typos) <span class="sc">-</span> mu) <span class="sc">%&gt;%</span></span>
<span id="cb543-11"><a href="continuing-the-glm-one-factor-anova.html#cb543-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>() <span class="sc">%&gt;%</span></span>
<span id="cb543-12"><a href="continuing-the-glm-one-factor-anova.html#cb543-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">err =</span> typos <span class="sc">-</span> (mu <span class="sc">+</span> Ai))</span></code></pre></div>
</div>
<div style="border: 0px;overflow-x: scroll; width:100%; ">
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:dmx-show">Table 12.1: </span>Decomposition Matrix for Typos Example
</caption>
<thead>
<tr>
<th style="text-align:center;">
sub_id
</th>
<th style="text-align:center;">
i
</th>
<th style="text-align:center;">
j
</th>
<th style="text-align:center;">
typos
</th>
<th style="text-align:center;">
sound
</th>
<th style="text-align:center;">
mu
</th>
<th style="text-align:center;">
Ai
</th>
<th style="text-align:center;">
err
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
111
</td>
<td style="text-align:center;">
cafe
</td>
<td style="text-align:center;">
100
</td>
<td style="text-align:center;">
8
</td>
<td style="text-align:center;">
3
</td>
</tr>
<tr>
<td style="text-align:center;">
2
</td>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
2
</td>
<td style="text-align:center;">
102
</td>
<td style="text-align:center;">
cafe
</td>
<td style="text-align:center;">
100
</td>
<td style="text-align:center;">
8
</td>
<td style="text-align:center;">
-6
</td>
</tr>
<tr>
<td style="text-align:center;">
3
</td>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
3
</td>
<td style="text-align:center;">
111
</td>
<td style="text-align:center;">
cafe
</td>
<td style="text-align:center;">
100
</td>
<td style="text-align:center;">
8
</td>
<td style="text-align:center;">
3
</td>
</tr>
<tr>
<td style="text-align:center;">
4
</td>
<td style="text-align:center;">
2
</td>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
89
</td>
<td style="text-align:center;">
jazz
</td>
<td style="text-align:center;">
100
</td>
<td style="text-align:center;">
2
</td>
<td style="text-align:center;">
-13
</td>
</tr>
<tr>
<td style="text-align:center;">
5
</td>
<td style="text-align:center;">
2
</td>
<td style="text-align:center;">
2
</td>
<td style="text-align:center;">
127
</td>
<td style="text-align:center;">
jazz
</td>
<td style="text-align:center;">
100
</td>
<td style="text-align:center;">
2
</td>
<td style="text-align:center;">
25
</td>
</tr>
<tr>
<td style="text-align:center;">
6
</td>
<td style="text-align:center;">
2
</td>
<td style="text-align:center;">
3
</td>
<td style="text-align:center;">
90
</td>
<td style="text-align:center;">
jazz
</td>
<td style="text-align:center;">
100
</td>
<td style="text-align:center;">
2
</td>
<td style="text-align:center;">
-12
</td>
</tr>
<tr>
<td style="text-align:center;">
7
</td>
<td style="text-align:center;">
3
</td>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
97
</td>
<td style="text-align:center;">
silence
</td>
<td style="text-align:center;">
100
</td>
<td style="text-align:center;">
-10
</td>
<td style="text-align:center;">
7
</td>
</tr>
<tr>
<td style="text-align:center;">
8
</td>
<td style="text-align:center;">
3
</td>
<td style="text-align:center;">
2
</td>
<td style="text-align:center;">
85
</td>
<td style="text-align:center;">
silence
</td>
<td style="text-align:center;">
100
</td>
<td style="text-align:center;">
-10
</td>
<td style="text-align:center;">
-5
</td>
</tr>
<tr>
<td style="text-align:center;">
9
</td>
<td style="text-align:center;">
3
</td>
<td style="text-align:center;">
3
</td>
<td style="text-align:center;">
88
</td>
<td style="text-align:center;">
silence
</td>
<td style="text-align:center;">
100
</td>
<td style="text-align:center;">
-10
</td>
<td style="text-align:center;">
-2
</td>
</tr>
</tbody>
</table>
</div>
<p>We finished off last week by calculating the Sums of Squares for the different columns - a measure of the variance attributable to that part of the model (or that column). Remember that to calculate the Sums of Squares (or often shortend to <span class="math inline">\(SS\)</span>) we square all the values in a column and sum them up. So for example:</p>
<p><span class="math display">\[SS_{\mu} = \sum\mu^2 = (\mu_{11} \times \mu_{11}) + (\mu_{12} \times \mu_{12}) + \space ... \space (\mu_{33} \times \mu_{33})\]</span></p>
<p>We also said at the end of the last Chapter that the Sums of Squares of the different columns were all linked through the following relationship:</p>
<p><span class="math display">\[SS_{total} = SS_{\mu} + SS_{A} + SS_{error}\]</span></p>
<ul>
<li>Have a go at calculating the SS of the above decomposition matrix (<code>dmx</code>) using the code we showed you towards the end of the inclass activity in the last chapter. If unsure, then the code can be revealed below:</li>
</ul>
<div class="webex-solution">
<button>
Show how to calculate Sums of Squares
</button>
<div class="sourceCode" id="cb544"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb544-1"><a href="continuing-the-glm-one-factor-anova.html#cb544-1" aria-hidden="true" tabindex="-1"></a>dat_ss <span class="ot">&lt;-</span> dmx <span class="sc">%&gt;%</span> </span>
<span id="cb544-2"><a href="continuing-the-glm-one-factor-anova.html#cb544-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">total =</span> <span class="fu">sum</span>(typos<span class="sc">^</span><span class="dv">2</span>),</span>
<span id="cb544-3"><a href="continuing-the-glm-one-factor-anova.html#cb544-3" aria-hidden="true" tabindex="-1"></a>            <span class="at">ss_mu =</span> <span class="fu">sum</span>(mu<span class="sc">^</span><span class="dv">2</span>),</span>
<span id="cb544-4"><a href="continuing-the-glm-one-factor-anova.html#cb544-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">ss_sound =</span> <span class="fu">sum</span>(Ai<span class="sc">^</span><span class="dv">2</span>),</span>
<span id="cb544-5"><a href="continuing-the-glm-one-factor-anova.html#cb544-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">ss_err =</span> <span class="fu">sum</span>(err<span class="sc">^</span><span class="dv">2</span>))</span></code></pre></div>
<ul>
<li><strong>Which would give:</strong></li>
</ul>
<div style="border: 0px;overflow-x: scroll; width:100%; ">
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:dat-ss-show">Table 12.2: </span>Sums of Squares for Typos Example
</caption>
<thead>
<tr>
<th style="text-align:center;">
total
</th>
<th style="text-align:center;">
ss_mu
</th>
<th style="text-align:center;">
ss_sound
</th>
<th style="text-align:center;">
ss_err
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;">
91574
</td>
<td style="text-align:center;">
90000
</td>
<td style="text-align:center;">
504
</td>
<td style="text-align:center;">
1070
</td>
</tr>
</tbody>
</table>
</div>
<p>We can then check that we have calculated everything correctly by using the following relationship:</p>
<p><span class="math display">\[SS_{total} = SS_{\mu} + SS_{A} + SS_{error}\]</span></p>
<p>then:</p>
<p><span class="math display">\[91574 = 90000 + 504 + 1070\]</span></p>
</div>
<div id="Ch12InClassQueT1" class="section level3" number="12.3.1">
<h3><span class="header-section-number">12.3.1</span> Task 1 - Quick Checks</h3>
<p><span style="font-size: 22px; font-weight: bold; color: var(--green);">QuickFire Questions</span></p>
<p>Answer the following questions. The solutions are at the end of the chapter.</p>
<ol style="list-style-type: decimal">
<li><p>If the <strong>corrected total Sum of Squares</strong> is the <span class="math inline">\(SS_{total}\)</span> minus the part of the total attributable to the intercept (i.e., the grand mean, <span class="math inline">\(SS_{\mu}\)</span>), calculate the corrected total Sum of Squares for the above example.</p>
<ul>
<li><strong>hint</strong>: <span class="math inline">\(SS_{corrected} = SS_{total} - SS_{\mu}\)</span></li>
</ul></li>
<li><p>What proportion of the <strong>corrected total sum of squares</strong> is attributable to the main effect of <code>sound</code>?</p>
<ul>
<li><strong>hint</strong>: <span class="math inline">\(SS_{sound} = SS_{A}\)</span></li>
<li><strong>hint</strong>: <span class="math inline">\(\frac{SS_{sound}}{SS_{corrected}}\)</span></li>
</ul></li>
<li><p>What proportion of the <strong>corrected total sum of squares</strong> is attributable to residual error?</p>
<ul>
<li><strong>hint</strong>: <span class="math inline">\(SS_{error}\)</span></li>
</ul></li>
</ol>
</div>
<div id="Ch12InClassQueT2" class="section level3" number="12.3.2">
<h3><span class="header-section-number">12.3.2</span> Task 2 - Mean squares and degrees of freedom</h3>
<p>Great, so now we know how to create our decomposition matrix and how to calculate our sums of squares. The only thing left to do is to calculate the <strong>F-ratio</strong> (the test statistic for the ANOVA, otherwise called the <strong>F-value</strong>) to determine if there is a significant effect between our groups. But, as it is always good to have a view of the whole picture, let’s not forget that the whole purpose here is to show you where the numbers come from in our quest to determine if there is a significant difference between our groups, or in other words, is there an effect of listening condition on concentration!</p>
<p>You will remember from your lectures and from your reading of Miller &amp; Haden (2013) that the F-value is a ratio of two estimates of population variance:</p>
<p><span class="math display">\[F = \frac{MS_{between}}{MS_{within}}  = \frac{MS_{treatment}}{MS_{error}} = \frac{MS_{A}}{MS_{S(A)}}= \frac{MS_{A}}{MS_{error}}\]</span></p>
<p>And you will also remember that the Mean Square (MS) is the Sums of Squares (SS) divided by its degrees of freedom (df). If you don’t remember what degrees of freedom are, go back to pages 21-23 of <a href="https://drive.google.com/file/d/0B1fyuTuvj3YoaFdUR3FZaXNuNXc/view" target = "_blank">Miller and Haden (2013)</a>. They have a good explanation for it, however, these things are easy to forget, so make sure to qucikly skim back through the book. So the general formula for the Mean Square is:</p>
<p><span class="math display">\[MS = \frac{SS}{df}\]</span></p>
<p>Let’s start trying to put all this information together! If we know the SS of our group/treatment (<span class="math inline">\(SS_{A} = 504\)</span> - also called the <strong>between variance</strong>) and we know the SS of our error/residuals (<span class="math inline">\(SS_{error} = 1070\)</span> - also called the <strong>within variance</strong>), then we can convert both of the <span class="math inline">\(SS\)</span>s to Mean Squares (MS) (i.e. the average variance for that condition) by dividing them by their respective degrees of freedom (df).</p>
<p>We can then calculate F-value (also called F-observed) by: <span class="math display">\[F = \frac{MS_{A}}{MS_{error}}\]</span></p>
<p>If the <span class="math inline">\(MS_{error}\)</span> is larger than <span class="math inline">\(MS_{A}\)</span> (the group effect) then F-value will be small and there will be no significant effect of group - any difference in groups is purely due to individual differences (another way of thinking about error). On the other hand, if <span class="math inline">\(MS_{A}\)</span> (the group effect) is larger than <span class="math inline">\(MS_{error}\)</span> then F-value will be large, and depending on how large the F-value is, there may be a significant difference caused by your group variable.</p>
<p>With all that in mind, and it may take a couple of readings, try to answer the following questions (consulting Miller &amp; Haden Ch. 3 and your lecture slides where needed). The solutions are at the end of the chapter.</p>
<p><span style="font-size: 22px; font-weight: bold; color: var(--green);">QuickFire Questions</span></p>
<ol style="list-style-type: decimal">
<li>Stated in terms of <span class="math inline">\(\mu_{jazz}\)</span>, <span class="math inline">\(\mu_{cafe}\)</span>, and <span class="math inline">\(\mu_{silence}\)</span>, what is the null hypothesis for this specific study of the effects of sound on typographic errors? You may need to look back to Chapters 6 and 7 to think about this.</li>
</ol>
<p><strong>Hint:</strong> the alternative hypothesis for a two condition experiment would be <span class="math inline">\(\mu_{1} \ne \mu_{2}\)</span></p>
<ol start="2" style="list-style-type: decimal">
<li><p>How many degrees of freedom are there for <span class="math inline">\(A_{i}\)</span>, the main effect of <strong>sound</strong>, if <span class="math inline">\(dfA_{i}\)</span> = k - 1?</p></li>
<li><p>How many degrees of freedom are there for <span class="math inline">\(S(A)_{ij}\)</span>, the error term, if <span class="math inline">\(dfS(A)_{ij}\)</span> = N - <span class="math inline">\(dfA_{i}\)</span> - 1?</p></li>
</ol>
<p><strong>Hint:</strong> You can also refer to <span class="math inline">\(dfS(A)_{ij}\)</span> as <span class="math inline">\(df_{error}\)</span></p>
<ol start="4" style="list-style-type: decimal">
<li>Calculate <span class="math inline">\(MS_{A}\)</span>, where <span class="math inline">\(A\)</span> is the factor <strong>sound</strong>.</li>
</ol>
<p><strong>Note:</strong> You can access individual columns in a table using double square brackets <code>[[]]</code>; for instance dat_ss[[“ss_mu”]] gives you the column <code>ss_mu</code> from <code>dat_ss</code>. This is an alternative to <code>$</code> that some may know; e.g. <code>dat_ss$mu</code>.</p>
<ol start="5" style="list-style-type: decimal">
<li>Calculate <span class="math inline">\(MS_{S(A)}\)</span>.</li>
</ol>
<p><strong>Hint:</strong> You can also refer to <span class="math inline">\(MS_{S(A)}\)</span> as <span class="math inline">\(MS_{error}\)</span></p>
<div class="webex-solution">
<button>
Hints for Task 2
</button>
<div class="info">
<ol style="list-style-type: decimal">
<li>
Remember that the null says that there are no differences between conditions.
</li>
<li>
Sound, our factor, has three levels.
</li>
<li>
N is the total number of participants
</li>
<li>
<span class="math inline"><span class="math inline">\(MS_{A} = \frac{SS_{A}}{dfA_{i}}\)</span></span>
</li>
<li>
<span class="math inline"><span class="math inline">\(MS_{S(A)} = \frac{SS_{error}}{dfS(A)_{ij}}\)</span></span>
</li>
</ol>
</div>
</div>
</div>
<div id="Ch12InClassQueT3" class="section level3" number="12.3.3">
<h3><span class="header-section-number">12.3.3</span> Task 3 - F-ratios</h3>
<p>Last step, calculating the F-value. As above, if the null hypothesis is true (<span class="math inline">\(\mu_{1} = \mu_{2} = \mu_{3}\)</span>), then both estimates of the population variance (<span class="math inline">\(MS_{between}\)</span> and <span class="math inline">\(MS_{within}\)</span>) should be equal, and the <span class="math inline">\(F\)</span>-ratio should approach 1 (because <span class="math inline">\(\frac{x}{x} = 1\)</span>). Now, we can’t expect these two estimates to be <strong>exactly</strong> equal because of sampling bias, so to see how <strong>un</strong>likely our observed F-ratio is under the null hypothesis, we have to compare it to the F-distribution.</p>
<p>To learn a bit about the F-distribution we have created a shiny app to play with, which you can see below. Shiny Apps are interactive webpages and applications made through R.</p>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-2"></span>
<iframe src="https://shiny.psy.gla.ac.uk/Dale/fdist/" width="100%" height="1050px">
</iframe>
<p class="caption">
Figure 4.12: F-distribution app
</p>
</div>
<ul>
<li><p>The F distribution is a representation of the probability of various values of F under the null hypothesis. It depends upon two parameters: <span class="math inline">\(df_{numerator}\)</span> and <span class="math inline">\(df_{denominator}\)</span>. Play around with the sliders corresponding to these two parameters and observe how the shape of the distribution changes.</p></li>
<li><p>There is also a slider that lets you specify an observed <span class="math inline">\(F\)</span> ratio (to one digit of precision). It is represented on the <span style="color:blue">blue line</span> of the graph. Move this slider around and watch how the p-values change. The p-value is the total area under the curve to the right of the blue line.</p></li>
<li><p>The <span style="color:red">red line</span> on the plot denotes the critical value of F required for a significant difference, given the <span class="math inline">\(\alpha\)</span> (type 1 error rate) and the <span class="math inline">\(df_{numerator}\)</span> and <span class="math inline">\(df_{denominator}\)</span> .</p></li>
</ul>
<p><span style="font-size: 22px; font-weight: bold; color: var(--green);">QuickFire Questions</span></p>
<p>Try using your data and the app to answer the following questions. The solutions are at the end of the chapter.</p>
<ol style="list-style-type: decimal">
<li><p>From your data, calculate the observed F-value (called <code>f_obs</code>) for the effect of <code>sound</code> on <code>typos</code> (concentration).</p>
<ul>
<li><strong>hint</strong>: <span class="math inline">\(MS_{between} / MS_{within}\)</span></li>
</ul></li>
</ol>
<p>Using the app shown above, set <span class="math inline">\(\alpha = .05\)</span>, set the degrees of freedom to correspond to those in your study, and set the observed F ratio as close as you can to the value you got in the above question.</p>
<ol start="2" style="list-style-type: decimal">
<li><p>Now, according to the app, what is the critical value for <span class="math inline">\(F\)</span> (<strong>hint</strong>: red line)?</p></li>
<li><p>According to the app, what is the approximate <span class="math inline">\(p\)</span> value associated with your observed <span class="math inline">\(F\)</span> ratio?</p></li>
<li><p>Based on these values, do you reject or retain the null hypothesis?</p></li>
</ol>
<p><strong>Tricky question:</strong> Note that you can use the distribution functions for <span class="math inline">\(F\)</span> in the same way you did in Chapter 4 for the normal distribution (<code>pnorm()</code>, <code>dnorm()</code>, <code>qnorm()</code>) or for the binomial distribution (<code>pbinom()</code>, <code>dbinom()</code>, <code>qbinom()</code>), keeping in mind however that the F distribution, being continuous, is more analogous to the normal distribution. See <code>?df</code> for the distribution functions associated with <span class="math inline">\(F\)</span>.</p>
<ol start="5" style="list-style-type: decimal">
<li>Using the appropriate distribution function, calculate the <span class="math inline">\(p\)</span> value associated with <span class="math inline">\(F_{obs}\)</span>. This will be more precise than the app.</li>
</ol>
<div class="webex-solution">
<button>
Hints for Question 5
</button>
<div class="info">
<ul>
<li>
look at inputs for the function - ?pf
</li>
<li>
ignore ncp
</li>
<li>
f_obs = q
</li>
<li>
lower.tail? What is the probability of obtaining an F_obs higher than your value.
</li>
</ul>
</div>
</div>
</div>
<div id="Ch12InClassQueT4" class="section level3" number="12.3.4">
<h3><span class="header-section-number">12.3.4</span> Task 4 - Using afex::aov_ez()</h3>
<p>Great, so we have calculated the F-value for this test and made a judgement about whether it is significant or not. But that was quite a long way of doing it, and whilst it is always great to understand where the data comes from, you don’t want to have to do that each time you run a test. So now we are going to re-analyse the same dataset but this time we are going to have the computer do all the computational work for us.</p>
<p>There are various options for running ANOVAs in R, but the function we will be using for this course is <code>aov_ez()</code> function in the <strong><code>afex</code></strong> add-on package. Note that to use <code>aov_ez()</code> you either have to load in the package using <code>library(afex)</code>, or you can call it directly without loading using <code>afex::aov_ez()</code> (the <code>package_name::function</code> syntax). If you’re just using the function once, the latter often makes more sense. The <strong><code>afex</code></strong> package is already installed in the Boyd Orr machines so it only needs called to the library. On your own machines you will need to install the package if you haven’t already done so.</p>
<ul>
<li>Have a quick read through the documentation for <code>aov_ez</code> (type <code>?aov_ez</code> in the console) and then look at the code below which shows how to run the ANOVA and try to understand it. Pay specific attention to how you stipulate the datafile, the dv, the factor, the participants, etc.</li>
</ul>
<div class="sourceCode" id="cb545"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb545-1"><a href="continuing-the-glm-one-factor-anova.html#cb545-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(afex)</span>
<span id="cb545-2"><a href="continuing-the-glm-one-factor-anova.html#cb545-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb545-3"><a href="continuing-the-glm-one-factor-anova.html#cb545-3" aria-hidden="true" tabindex="-1"></a>dat <span class="ot">&lt;-</span> <span class="fu">select</span>(dmx, sub_id, typos, sound)</span>
<span id="cb545-4"><a href="continuing-the-glm-one-factor-anova.html#cb545-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb545-5"><a href="continuing-the-glm-one-factor-anova.html#cb545-5" aria-hidden="true" tabindex="-1"></a>results <span class="ot">&lt;-</span> afex<span class="sc">::</span><span class="fu">aov_ez</span>(<span class="at">data =</span> dat,</span>
<span id="cb545-6"><a href="continuing-the-glm-one-factor-anova.html#cb545-6" aria-hidden="true" tabindex="-1"></a>                         <span class="at">dv =</span> <span class="st">&quot;typos&quot;</span>,</span>
<span id="cb545-7"><a href="continuing-the-glm-one-factor-anova.html#cb545-7" aria-hidden="true" tabindex="-1"></a>                         <span class="at">id =</span> <span class="st">&quot;sub_id&quot;</span>,</span>
<span id="cb545-8"><a href="continuing-the-glm-one-factor-anova.html#cb545-8" aria-hidden="true" tabindex="-1"></a>                         <span class="at">type =</span> <span class="dv">3</span>,</span>
<span id="cb545-9"><a href="continuing-the-glm-one-factor-anova.html#cb545-9" aria-hidden="true" tabindex="-1"></a>                         <span class="at">between =</span> <span class="st">&quot;sound&quot;</span>)</span></code></pre></div>
<p>You will have seen a couple of messages pop up about converting <code>sound</code> to factor. That is fine. You can see these in the solutions if you want to confirm yours are the same. If we then look at the output of the analysis through the following code:</p>
<div class="sourceCode" id="cb546"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb546-1"><a href="continuing-the-glm-one-factor-anova.html#cb546-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(results<span class="sc">$</span>Anova)</span></code></pre></div>
<p>We see:</p>
<pre><code>## Anova Table (Type III tests)
## 
## Response: dv
##             Sum Sq Df  F value    Pr(&gt;F)    
## (Intercept)  90000  1 504.6729 5.091e-07 ***
## sound          504  2   1.4131    0.3142    
## Residuals     1070  6                       
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>And if you ran the following code:</p>
<div class="sourceCode" id="cb548"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb548-1"><a href="continuing-the-glm-one-factor-anova.html#cb548-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(results<span class="sc">$</span>anova_table)</span></code></pre></div>
<p>Then you would be able to see the effect size for this ANOVA in the form of generalised eta-squared (ges) - <span class="math inline">\(\eta_G^2 = .32\)</span>:</p>
<pre><code>## Anova Table (Type 3 tests)
## 
## Response: typos
##       num Df den Df    MSE      F    ges Pr(&gt;F)
## sound      2      6 178.33 1.4131 0.3202 0.3142</code></pre>
<ul>
<li>Looking at the ANOVA ouput, do you see how the numbers match up with what we calculated above? You can ignore the intercept for now (though the Sums of Squares will be familiar). This table doesn’t show the Mean Squares but it does show the Sums of Squares and the F-value.</li>
<li>What do you conclude about the effects of ambient noise on concentration?</li>
</ul>
<p><strong>Conclusion</strong></p>
<p>Not much to be honest with you! The study returns a non-significant finding suggesting that there is no significant effect of ambient noise on concentration, F(2, 6) = 1.413, p = .31, ges = 0.32. However, before you go off and publish this highly underpowered study we should probably look to replicate it with a larger sample (which you could calculate using your skills from Chapter 8).</p>
<p><span style="font-size: 22px; font-weight: bold; color: var(--blue);">Job Done - Activity Complete!</span></p>
<p>Excellent work today! And super interesting as well, huh? Quick, everyone to the cafe and don’t worry about the typos!!!! Only joking, we are all going to the cafe to replicate!</p>
<p><strong>One last thing:</strong></p>
<p>Before ending this section, if you have any questions, please post them on the available forums or speak to a member of the team. Finally, don’t forget to add any useful information to your Portfolio before you leave it too long and forget. Remember the more you work with knowledge and skills the easier they become.</p>

</div>
</div>
<div id="assignment-6" class="section level2" number="12.4">
<h2><span class="header-section-number">12.4</span> Assignment</h2>
<p>This is a <strong>summative</strong> assignment and as such, as well as testing your knowledge, skills, and learning, this assignment contributes to your overall grade for this semester. You will be instructed by the Course Lead on Moodle as to when you will receive this assignment, as well as given full instructions as to how to access and submit the assignment. Please check the information and schedule on the Level 2 Moodle page.</p>

</div>
<div id="solutions-to-questions-11" class="section level2" number="12.5">
<h2><span class="header-section-number">12.5</span> Solutions to Questions</h2>
<p>Below you will find the solutions to the questions for the Activities for this chapter. Only look at them after giving the questions a good try and speaking to the tutor about any issues.</p>
<div id="inclass-activities-9" class="section level3" number="12.5.1">
<h3><span class="header-section-number">12.5.1</span> InClass Activities</h3>
<div id="inclass-task-1-6" class="section level4" number="12.5.1.1">
<h4><span class="header-section-number">12.5.1.1</span> InClass Task 1</h4>
<p><strong>Question 1</strong></p>
<ul>
<li><span class="math inline">\(SS_{corrected\ total} = SS_{total} - SS_{\mu}\)</span></li>
<li><span class="math inline">\(SS_{total}\)</span> = 91574</li>
<li><span class="math inline">\(SS_{\mu}\)</span> = 90000</li>
<li><span class="math inline">\(SS_{corrected\ total}\)</span> = 91574 - 90000 = 1574</li>
</ul>
<p><strong>Question 2</strong></p>
<ul>
<li><span class="math inline">\(SS_{sound}\)</span> = 504</li>
<li><span class="math inline">\(SS_{corrected\ total}\)</span> = 1574</li>
<li><span class="math inline">\(SS_{sound} / SS_{corrected\ total}\)</span> = 504 / 1574 = 0.32</li>
</ul>
<p><strong>Question 3</strong></p>
<ul>
<li><span class="math inline">\(SS_{err}\)</span> = 1070</li>
<li><span class="math inline">\(SS_{corrected\ total}\)</span> = 1574</li>
<li><span class="math inline">\(SS_{err} / SS_{corrected\ total}\)</span> = 1070 / 1574 = 0.68</li>
</ul>
<p><a href="continuing-the-glm-one-factor-anova.html#Ch12InClassQueT1">Return to Task</a></p>
</div>
<div id="inclass-task-2-7" class="section level4" number="12.5.1.2">
<h4><span class="header-section-number">12.5.1.2</span> InClass Task 2</h4>
<p><strong>Question 1</strong></p>
<p><span class="math inline">\(\mu_{cafe} = \mu_{jazz} = \mu_{silence}\)</span></p>
<p><strong>Question 2</strong></p>
<ul>
<li>k = number of conditions, so:</li>
</ul>
<p>df = k - 1 = 3 - 1 = 2</p>
<p><strong>Question 3</strong></p>
<ul>
<li>N = 9, and <span class="math inline">\(dfA_{i}\)</span> = 2, so</li>
</ul>
<p>df = 9 - 2 - 1 = 6</p>
<p><strong>Question 4</strong></p>
<ul>
<li>The factor df = 2</li>
</ul>
<div class="sourceCode" id="cb550"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb550-1"><a href="continuing-the-glm-one-factor-anova.html#cb550-1" aria-hidden="true" tabindex="-1"></a>ms_a <span class="ot">&lt;-</span> dat_ss[[<span class="st">&quot;ss_sound&quot;</span>]] <span class="sc">/</span> 2L</span></code></pre></div>
<ul>
<li>Giving <span class="math inline">\(MS_{A}\)</span> = 252</li>
</ul>
<p><strong>Question 5</strong></p>
<ul>
<li>The residual df = 6</li>
</ul>
<div class="sourceCode" id="cb551"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb551-1"><a href="continuing-the-glm-one-factor-anova.html#cb551-1" aria-hidden="true" tabindex="-1"></a>ms_err <span class="ot">&lt;-</span> dat_ss[[<span class="st">&quot;ss_err&quot;</span>]] <span class="sc">/</span> 6L</span></code></pre></div>
<ul>
<li>Giving <span class="math inline">\(MS_{S(A)}\)</span> = 178.3333333</li>
</ul>
<p><a href="continuing-the-glm-one-factor-anova.html#Ch12InClassQueT2">Return to Task</a></p>
</div>
<div id="inclass-task-3-6" class="section level4" number="12.5.1.3">
<h4><span class="header-section-number">12.5.1.3</span> InClass Task 3</h4>
<p><strong>Question 1</strong></p>
<div class="sourceCode" id="cb552"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb552-1"><a href="continuing-the-glm-one-factor-anova.html#cb552-1" aria-hidden="true" tabindex="-1"></a>f_obs <span class="ot">&lt;-</span> ms_a <span class="sc">/</span> ms_err</span></code></pre></div>
<ul>
<li>Giving a F-value of F = 1.413 when rounded to three decimal places.</li>
</ul>
<p><strong>Question 2</strong></p>
<p>The red line should be about F = 5.143, meaning that that is the minimum value of F, for those dfs, considered to be statistically significant at <span class="math inline">\(\alpha = .05\)</span></p>
<p><strong>Question 3</strong></p>
<p>Reading off the app, the approximate p-value for f_obs is p = .317.</p>
<p><strong>Question 4</strong></p>
<p>As <span class="math inline">\(p\)</span> &gt; <span class="math inline">\(\alpha\)</span> we would retain the null hypothesis that there is no significant effect of group in this study</p>
<p><strong>Question 5</strong></p>
<p>This could alternatively calculated using coding as such:</p>
<div class="sourceCode" id="cb553"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb553-1"><a href="continuing-the-glm-one-factor-anova.html#cb553-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pf</span>(f_obs, <span class="dv">2</span>, <span class="dv">6</span>, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<p>Which would give a p-value of p = 0.314 and again could be written up as F(2, 6) = 1.413, p = 0.314, suggesting no significant effect of ambiance or location on concentration as measured through the number of typos.</p>
<p><a href="continuing-the-glm-one-factor-anova.html#Ch12InClassQueT3">Return to Task</a></p>
</div>
<div id="inclass-task-4-6" class="section level4" number="12.5.1.4">
<h4><span class="header-section-number">12.5.1.4</span> InClass Task 4</h4>
<div class="sourceCode" id="cb554"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb554-1"><a href="continuing-the-glm-one-factor-anova.html#cb554-1" aria-hidden="true" tabindex="-1"></a>dat <span class="ot">&lt;-</span> <span class="fu">select</span>(dmx, sub_id, typos, sound)</span>
<span id="cb554-2"><a href="continuing-the-glm-one-factor-anova.html#cb554-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb554-3"><a href="continuing-the-glm-one-factor-anova.html#cb554-3" aria-hidden="true" tabindex="-1"></a>results <span class="ot">&lt;-</span> afex<span class="sc">::</span><span class="fu">aov_ez</span>(<span class="at">data =</span> dat,</span>
<span id="cb554-4"><a href="continuing-the-glm-one-factor-anova.html#cb554-4" aria-hidden="true" tabindex="-1"></a>                         <span class="at">dv =</span> <span class="st">&quot;typos&quot;</span>,</span>
<span id="cb554-5"><a href="continuing-the-glm-one-factor-anova.html#cb554-5" aria-hidden="true" tabindex="-1"></a>                         <span class="at">id =</span> <span class="st">&quot;sub_id&quot;</span>,</span>
<span id="cb554-6"><a href="continuing-the-glm-one-factor-anova.html#cb554-6" aria-hidden="true" tabindex="-1"></a>                         <span class="at">type =</span> <span class="dv">3</span>,</span>
<span id="cb554-7"><a href="continuing-the-glm-one-factor-anova.html#cb554-7" aria-hidden="true" tabindex="-1"></a>                         <span class="at">between =</span> <span class="st">&quot;sound&quot;</span>)</span></code></pre></div>
<pre><code>## Converting to factor: sound</code></pre>
<pre><code>## Contrasts set to contr.sum for the following variables: sound</code></pre>
<p><br>
And when we look at the output table see:</p>
<table>
<caption>
<span id="tab:afex-output2">Table 12.3: </span>ANOVA output
</caption>
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:right;">
Sum Sq
</th>
<th style="text-align:right;">
Df
</th>
<th style="text-align:right;">
F value
</th>
<th style="text-align:right;">
Pr(&gt;F)
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
(Intercept)
</td>
<td style="text-align:right;">
90000
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
504.673
</td>
<td style="text-align:right;">
0.000
</td>
</tr>
<tr>
<td style="text-align:left;">
sound
</td>
<td style="text-align:right;">
504
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
1.413
</td>
<td style="text-align:right;">
0.314
</td>
</tr>
<tr>
<td style="text-align:left;">
Residuals
</td>
<td style="text-align:right;">
1070
</td>
<td style="text-align:right;">
6
</td>
<td style="text-align:right;">
</td>
<td style="text-align:right;">
</td>
</tr>
</tbody>
</table>
<p><br></p>
<p>From this we can see that the numbers we calculated match up exactly with the values that the function produced - F(2, 6) = 1.41, p = .31. You can also see that there is no significant effect and as such we cannot reject the null hypothesis.</p>
<p><a href="continuing-the-glm-one-factor-anova.html#Ch12InClassQueT4">Return to Task</a></p>
<p><span style="font-size: 22px; font-weight: bold; color: var(--purple);">Chapter Complete!</span></p>

</div>
</div>
</div>
<div id="additional-material-7" class="section level2" number="12.6">
<h2><span class="header-section-number">12.6</span> Additional Material</h2>
<p>Below is some additional material that might help you understand ANOVAs a bit more and some additional ideas.</p>
<div id="levenes-test-of-homogeneity" class="section level3" number="12.6.1">
<h3><span class="header-section-number">12.6.1</span> Levene’s Test of Homogeneity</h3>
<p>From previous chapters and from your lectures you will know that every test has a series of assumptions that are required to be held in order for your conclusions to be valid, and the ANOVA is no exception. As always the specific assumptions change depending on the design of the study, but in the instance of the experiment in this chapter - a between-subjects design - the assumptions are as follows:</p>
<ul>
<li>Data should be interval/ratio</li>
<li>Data in each condition should be normally distributed</li>
<li>Data is independent from each other</li>
<li>There is homogeneity of variance across different conditions (i.e. different conditions have equal variances).</li>
</ul>
<p>You will spot that these are actually very similar to a between-subjects t-test and that again just shows that the two tests are highly related.</p>
<p>Now we know various ways to check things like normality and variance, with visual inspection being one of them, but a common test that people tend to use is what is called <strong>Levene’s Test of Homogeneity</strong>. In fact, if you think back to Chapter 7, when you run a t-test and set the variance as <code>var.equal = FALSE</code>, if you really wanted to run the test as <code>var.equal = TRUE</code> then it would be Levene’s test you should run first to confirm that variance is actually equal. However, the issue with the ANOVA is that it actually assumes variance is equal, so it is best to run a Levene’s test whenever you run an ANOVA that has at least one between-subjects condition. That is what we are going to show you here as well as how to interpret it and a little bit of discussion after. The main thing to note about Levene’s Test of Homogeniety is that the null hypothesis for this test states that there is no significant difference in variance between conditions:</p>
<p><span class="math display">\[H_{0}: \sigma_{1}^2 = \sigma_{2}^2 \]</span>
Conversely, the alternative hypothesis states that there is a difference in variance between conditions:</p>
<p><span class="math display">\[H_{1}: \sigma_{1}^2 \ne \sigma_{2}^2 \]</span></p>
<p>So a non-significant finding in Levene’s test would suggests equal variance across conditions as required by the assumptions of the ANOVA, whereas a significant finding for Levene’s Test would suggest unequal variance and you may need to think about the assumptions of your data.</p>
<p><strong>Running the test</strong></p>
So here is our data again from the main activities, which we have stored in a tibble called <code>dmx</code>:
<br>
<br>
<div style="border: 0px;overflow-x: scroll; width:100%; ">
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:dmx-show">Table 12.1: </span>Decomposition Matrix for Typos Example
</caption>
<thead>
<tr>
<th style="text-align:center;">
sub_id
</th>
<th style="text-align:center;">
i
</th>
<th style="text-align:center;">
j
</th>
<th style="text-align:center;">
typos
</th>
<th style="text-align:center;">
sound
</th>
<th style="text-align:center;">
mu
</th>
<th style="text-align:center;">
Ai
</th>
<th style="text-align:center;">
err
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
111
</td>
<td style="text-align:center;">
cafe
</td>
<td style="text-align:center;">
100
</td>
<td style="text-align:center;">
8
</td>
<td style="text-align:center;">
3
</td>
</tr>
<tr>
<td style="text-align:center;">
2
</td>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
2
</td>
<td style="text-align:center;">
102
</td>
<td style="text-align:center;">
cafe
</td>
<td style="text-align:center;">
100
</td>
<td style="text-align:center;">
8
</td>
<td style="text-align:center;">
-6
</td>
</tr>
<tr>
<td style="text-align:center;">
3
</td>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
3
</td>
<td style="text-align:center;">
111
</td>
<td style="text-align:center;">
cafe
</td>
<td style="text-align:center;">
100
</td>
<td style="text-align:center;">
8
</td>
<td style="text-align:center;">
3
</td>
</tr>
<tr>
<td style="text-align:center;">
4
</td>
<td style="text-align:center;">
2
</td>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
89
</td>
<td style="text-align:center;">
jazz
</td>
<td style="text-align:center;">
100
</td>
<td style="text-align:center;">
2
</td>
<td style="text-align:center;">
-13
</td>
</tr>
<tr>
<td style="text-align:center;">
5
</td>
<td style="text-align:center;">
2
</td>
<td style="text-align:center;">
2
</td>
<td style="text-align:center;">
127
</td>
<td style="text-align:center;">
jazz
</td>
<td style="text-align:center;">
100
</td>
<td style="text-align:center;">
2
</td>
<td style="text-align:center;">
25
</td>
</tr>
<tr>
<td style="text-align:center;">
6
</td>
<td style="text-align:center;">
2
</td>
<td style="text-align:center;">
3
</td>
<td style="text-align:center;">
90
</td>
<td style="text-align:center;">
jazz
</td>
<td style="text-align:center;">
100
</td>
<td style="text-align:center;">
2
</td>
<td style="text-align:center;">
-12
</td>
</tr>
<tr>
<td style="text-align:center;">
7
</td>
<td style="text-align:center;">
3
</td>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
97
</td>
<td style="text-align:center;">
silence
</td>
<td style="text-align:center;">
100
</td>
<td style="text-align:center;">
-10
</td>
<td style="text-align:center;">
7
</td>
</tr>
<tr>
<td style="text-align:center;">
8
</td>
<td style="text-align:center;">
3
</td>
<td style="text-align:center;">
2
</td>
<td style="text-align:center;">
85
</td>
<td style="text-align:center;">
silence
</td>
<td style="text-align:center;">
100
</td>
<td style="text-align:center;">
-10
</td>
<td style="text-align:center;">
-5
</td>
</tr>
<tr>
<td style="text-align:center;">
9
</td>
<td style="text-align:center;">
3
</td>
<td style="text-align:center;">
3
</td>
<td style="text-align:center;">
88
</td>
<td style="text-align:center;">
silence
</td>
<td style="text-align:center;">
100
</td>
<td style="text-align:center;">
-10
</td>
<td style="text-align:center;">
-2
</td>
</tr>
</tbody>
</table>
</div>
<p><br></p>
Let’s run a quick visual inspection of the variance in each condition using a boxplot as such:
<br>
<div class="figure" style="text-align: center"><span id="fig:boxplot-hide"></span>
<img src="12-s02-lab12f_files/figure-html/boxplot-hide-1.png" alt="A boxplot of our data to check for homogeneity of variance" width="100%" />
<p class="caption">
Figure 12.1: A boxplot of our data to check for homogeneity of variance
</p>
</div>
<p><br>
And as you can see it does not look like there is equal variance. However, maybe we don’t really trust our eyes and as such we want to run the Levene’s Test. To do that we use the below code:</p>
<div class="sourceCode" id="cb557"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb557-1"><a href="continuing-the-glm-one-factor-anova.html#cb557-1" aria-hidden="true" tabindex="-1"></a>car<span class="sc">::</span><span class="fu">leveneTest</span>(typos <span class="sc">~</span> sound, <span class="at">data =</span> dmx, <span class="at">center =</span> median)</span></code></pre></div>
<pre><code>## Warning in leveneTest.default(y = y, group = group, ...): group coerced to
## factor.</code></pre>
<p>Where we are:</p>
<ul>
<li>using the <code>leveneTest()</code> function from the <strong><code>car</code></strong> package.</li>
<li>using the <strong>formula</strong> approach that we saw in t-test where we are saying effectively DV “by” IV - typos ~ sound, where <code>~</code> stands for “by.”<br />
</li>
<li>saying the data is in the tibble <code>dmx</code></li>
<li>and we are telling the code to run based on the medians of the distribution. This is a bit of a judgement call and you could use the mean instead of the median, but this paper would seem to suggest the median is optimal: <a href="https://www.sciencedirect.com/science/article/abs/pii/0167715285900161" target="_blank">Carroll &amp; Schnieder (1985) A note on levene’s tests for equality of variances</a></li>
</ul>
<p>If we run the <code>leveneTest()</code> code we get the following output:</p>
<pre><code>## Warning in leveneTest.default(y = y, group = group, ...): group coerced to
## factor.</code></pre>
<div class="kable-table">
<table>
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:right;">
Df
</th>
<th style="text-align:right;">
F value
</th>
<th style="text-align:right;">
Pr(&gt;F)
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
group
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
0.5165877
</td>
<td style="text-align:right;">
0.6208682
</td>
</tr>
<tr>
<td style="text-align:left;">
</td>
<td style="text-align:right;">
6
</td>
<td style="text-align:right;">
NA
</td>
<td style="text-align:right;">
NA
</td>
</tr>
</tbody>
</table>
</div>
<p>And now with your knowledge of understanding F-values and ANOVA tables (see Levene’s is really just a sort of ANOVA) you can determine that, F(2, 6) = 0.517, p = .621. This tells us that there is no significant difference between the variance across the different conditions. Which, if you look at the boxplot, is completely the opposite of what we expected! Why is that? Most likely, that is because we have such small numbers of participants in our samples and you will remember from Chapter 8, small samples mean low power and unreliable findings. This is actually a good example why people often use visual inspection as well as some analytical tests to make checks on assumptions and they pull information together to make a judgement. The boxplot would say that variance is unequal. Levene’s test would say variance is equal. Here, I would probably suggest taking a cautious approach and run a lot more participants before I consider running my analysis.</p>
<p><strong>Using <code>afex</code> to run Levene’s</strong></p>
<p>One issue with the above example is that it requires another package - <strong><code>car</code></strong>. This isn’t a major problem but say you only had the <strong><code>afex</code></strong> package to use. Well fortunately that package also has a function that can check Levene’s Test - <code>afex::test_levene()</code>. And it works as follows:</p>
<ol style="list-style-type: decimal">
<li>First run the ANOVA as shown in the chapter and store the output</li>
</ol>
<div class="sourceCode" id="cb560"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb560-1"><a href="continuing-the-glm-one-factor-anova.html#cb560-1" aria-hidden="true" tabindex="-1"></a>results <span class="ot">&lt;-</span> afex<span class="sc">::</span><span class="fu">aov_ez</span>(<span class="at">data =</span> dmx,</span>
<span id="cb560-2"><a href="continuing-the-glm-one-factor-anova.html#cb560-2" aria-hidden="true" tabindex="-1"></a>                         <span class="at">dv =</span> <span class="st">&quot;typos&quot;</span>,</span>
<span id="cb560-3"><a href="continuing-the-glm-one-factor-anova.html#cb560-3" aria-hidden="true" tabindex="-1"></a>                         <span class="at">id =</span> <span class="st">&quot;sub_id&quot;</span>,</span>
<span id="cb560-4"><a href="continuing-the-glm-one-factor-anova.html#cb560-4" aria-hidden="true" tabindex="-1"></a>                         <span class="at">type =</span> <span class="dv">3</span>,</span>
<span id="cb560-5"><a href="continuing-the-glm-one-factor-anova.html#cb560-5" aria-hidden="true" tabindex="-1"></a>                         <span class="at">between =</span> <span class="st">&quot;sound&quot;</span>)</span></code></pre></div>
<pre><code>## Converting to factor: sound</code></pre>
<pre><code>## Contrasts set to contr.sum for the following variables: sound</code></pre>
<ol start="2" style="list-style-type: decimal">
<li>Now use the output of the ANOVA, in this instance <code>results</code>, as the input for the Levene’s Test, and again center on the median</li>
</ol>
<div class="sourceCode" id="cb563"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb563-1"><a href="continuing-the-glm-one-factor-anova.html#cb563-1" aria-hidden="true" tabindex="-1"></a>afex<span class="sc">::</span><span class="fu">test_levene</span>(results, <span class="at">center =</span> median)</span></code></pre></div>
<div class="kable-table">
<table>
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:right;">
Df
</th>
<th style="text-align:right;">
F value
</th>
<th style="text-align:right;">
Pr(&gt;F)
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
group
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
0.5165877
</td>
<td style="text-align:right;">
0.6208682
</td>
</tr>
<tr>
<td style="text-align:left;">
</td>
<td style="text-align:right;">
6
</td>
<td style="text-align:right;">
NA
</td>
<td style="text-align:right;">
NA
</td>
</tr>
</tbody>
</table>
</div>
<p>And if we look at that output we see the exact same finding as we did using <code>car::leveneTest()</code>- F(2, 6) = 0.517, p = .621. So the positives of this approach is that you only use one package and it gives the same results as using two packages. The downside is that you have to run the ANOVA first - see how we use the ANOVA output as an input for <code>test_levene()</code> - which is a bit of an odd way of treating this assumption. Normally you would run the assumption check first and then the test.</p>
<p><strong>Help I have unequal variance!</strong></p>
<p>Right, so you have found that your variance is not equal and you are now worried about what to do in regards your assumptions. Well, there is much debate on how robust the ANOVA is, where robust would mean that your False Positive rate does not necessarily inflate if the assumptions are not held. Some say that the ANOVA is not robust and you should use a non-parametric style of analysis instead in this instance, or break the ANOVA down into a series of Welch’s t-tests (assuming unequal variance) and control the False Positive rate through Bonferroni corrections. Some however say that the ANOVA is actually pretty robust. We would recommend reading this paper <a href="https://link.springer.com/article/10.3758/s13428-017-0918-2" target="_blank">Blanca et al. (2018) Effect of variance ratio on ANOVA robustness: Might 1.5 be the limit?</a> which suggests that some degree of unequal variance is acceptable. Alternatively, just as there is a Welch’s t-test that does not assume equal variance there is also a Welch’s ANOVA that does not assume equal variance. This paper <a href="https://psyarxiv.com/wnezg/" target="_blank">Delacre et al., (preprint) Taking Parametric Assumptions Seriously Arguments for the Use of Welch’s F-test instead of the Classical F-test in One-way ANOVA</a> goes into great detail about why using Welch’s ANOVA is always advisable. You may be wondering how do you run a Welch’s ANOVA in R, yeah? That is a very good question that you should ask Phil to write about one day after he figures it out himself.</p>
<p><span style="font-size: 22px; font-weight: bold; color: var(--purple);">End of Additional Material!</span></p>

</div>
</div>
</div>
<div class="psyteachr_footer">
  
</div>
<script>

/* update total correct if #webex-total_correct exists */
update_total_correct = function() {
  if (t = document.getElementById("webex-total_correct")) {
    t.innerHTML =
      document.getElementsByClassName("webex-correct").length + " of " +
      document.getElementsByClassName("webex-solveme").length + " correct";
  }
}

/* webex-solution button toggling function */
b_func = function() {
  var cl = this.parentElement.classList;
  if (cl.contains('open')) {
    cl.remove("open");
  } else {
    cl.add("open");
  }
}

/* function for checking solveme answers */
solveme_func = function(e) {
  var real_answers = JSON.parse(this.dataset.answer);
  var my_answer = this.value;
  var cl = this.classList;
  if (cl.contains("ignorecase")) {
    my_answer = my_answer.toLowerCase();
  }
  if (cl.contains("nospaces")) {
    my_answer = my_answer.replace(/ /g, "")
  }
  
  if (my_answer !== "" & real_answers.includes(my_answer)) {
    cl.add("webex-correct");
  } else {
    cl.remove("webex-correct");
  }

  // match numeric answers within a specified tolerance
  if(this.dataset.tol > 0){
    var tol = JSON.parse(this.dataset.tol);  
    var matches = real_answers.map(x => Math.abs(x - my_answer) < tol)
    if (matches.reduce((a, b) => a + b, 0) > 0) {
      cl.add("webex-correct");
    } else {
      cl.remove("webex-correct");
    }  
  }

  // added regex bit
  if (cl.contains("regex")){
    answer_regex = RegExp(real_answers.join("|"))
    if (answer_regex.test(my_answer)) {
      cl.add("webex-correct");
    }  
  }
  
  update_total_correct();
}

window.onload = function() {
  /* set up solution buttons */
  var buttons = document.getElementsByTagName("button");

  for (var i = 0; i < buttons.length; i++) {
    if (buttons[i].parentElement.classList.contains('webex-solution')) {
      buttons[i].onclick = b_func;
    }
  }
  
  /* set up webex-solveme inputs */
  var solveme = document.getElementsByClassName("webex-solveme");

  for (var i = 0; i < solveme.length; i++) {
    /* make sure input boxes don't auto-anything */
    solveme[i].setAttribute("autocomplete","off");
    solveme[i].setAttribute("autocorrect", "off");
    solveme[i].setAttribute("autocapitalize", "off"); 
    solveme[i].setAttribute("spellcheck", "false");
    solveme[i].value = "";
    
    /* adjust answer for ignorecase or nospaces */
    var cl = solveme[i].classList;
    var real_answer = solveme[i].dataset.answer;
    if (cl.contains("ignorecase")) {
      real_answer = real_answer.toLowerCase();
    }
    if (cl.contains("nospaces")) {
      real_answer = real_answer.replace(/ /g, "");
    }
    solveme[i].dataset.answer = real_answer;
    
    /* attach checking function */
    solveme[i].onkeyup = solveme_func;
    solveme[i].onchange = solveme_func;
  }
  
  update_total_correct();
}

</script>
            </section>

          </div>
        </div>
      </div>
<a href="introduction-to-glm-one-factor-anova.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="continuing-the-glm-two-factor-designs.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"],
"google": false
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": {},
"toc": {
"collapse": "section",
"scroll_highlight": true
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
