<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>Chapter 13 Factorial ANOVA | Analysis</title>
<meta name="author" content="Phil McAleer, Carolina E. Kuepper-Tetzel, Helena Paterson">
<meta name="description" content="In this chapter, we are continuing from the previous chapter on ANOVA and we're going to look at an example of a Factorial ANOVA. You'll learn more about interpreting these in the lectures, but...">
<meta name="generator" content="bookdown 0.39 with bs4_book()">
<meta property="og:title" content="Chapter 13 Factorial ANOVA | Analysis">
<meta property="og:type" content="book">
<meta property="og:url" content="https://psyteachr.github.io/analysis-v2/factorial-anova.html">
<meta property="og:image" content="https://psyteachr.github.io/analysis-v2/images/logos/logo.png">
<meta property="og:description" content="In this chapter, we are continuing from the previous chapter on ANOVA and we're going to look at an example of a Factorial ANOVA. You'll learn more about interpreting these in the lectures, but...">
<meta name="twitter:card" content="summary">
<meta name="twitter:title" content="Chapter 13 Factorial ANOVA | Analysis">
<meta name="twitter:description" content="In this chapter, we are continuing from the previous chapter on ANOVA and we're going to look at an example of a Factorial ANOVA. You'll learn more about interpreting these in the lectures, but...">
<meta name="twitter:image" content="https://psyteachr.github.io/analysis-v2/images/logos/logo.png">
<!-- JS --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/fuse.js/6.4.6/fuse.js" integrity="sha512-zv6Ywkjyktsohkbp9bb45V6tEMoWhzFzXis+LrMehmJZZSys19Yxf1dopHx7WzIKxr5tK2dVcYmaCk2uqdjF4A==" crossorigin="anonymous"></script><script src="https://kit.fontawesome.com/6ecbd6c532.js" crossorigin="anonymous"></script><script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link href="libs/bootstrap-4.6.0/bootstrap.min.css" rel="stylesheet">
<script src="libs/bootstrap-4.6.0/bootstrap.bundle.min.js"></script><script src="libs/bs3compat-0.6.1/transition.js"></script><script src="libs/bs3compat-0.6.1/tabs.js"></script><script src="libs/bs3compat-0.6.1/bs3compat.js"></script><link href="libs/bs4_book-1.0.0/bs4_book.css" rel="stylesheet">
<script src="libs/bs4_book-1.0.0/bs4_book.js"></script><script src="libs/kePrint-0.0.1/kePrint.js"></script><link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet">
<!-- Global site tag (gtag.js) - Google Analytics --><script async src="https://www.googletagmanager.com/gtag/js?id=G-6NP3MF25W3"></script><script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'G-6NP3MF25W3');
    </script><script src="https://cdnjs.cloudflare.com/ajax/libs/autocomplete.js/0.38.0/autocomplete.jquery.min.js" integrity="sha512-GU9ayf+66Xx2TmpxqJpliWbT5PiGYxpaG8rfnBEk1LL8l1KGkRShhngwdXK1UgqhAzWpZHSiYPc09/NwDQIGyg==" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/mark.min.js" integrity="sha512-5CYOlHXGh6QpOFA/TeTylKLWfB3ftPsde7AnmhuitiTX4K5SqCLBeKro6sPS8ilsz1Q4NRx3v8Ko2IBiszzdww==" crossorigin="anonymous"></script><!-- CSS --><style type="text/css">
    
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  </style>
<style type="text/css">
    /* Used with Pandoc 2.11+ new --citeproc when CSL is used */
    div.csl-bib-body { }
    div.csl-entry {
      clear: both;
          margin-bottom: 0em;
        }
    .hanging div.csl-entry {
      margin-left:2em;
      text-indent:-2em;
    }
    div.csl-left-margin {
      min-width:2em;
      float:left;
    }
    div.csl-right-inline {
      margin-left:2em;
      padding-left:1em;
    }
    div.csl-indent {
      margin-left: 2em;
    }
  </style>
<link rel="stylesheet" href="include/psyteachr.css">
<link rel="stylesheet" href="include/webex.css">
<link rel="stylesheet" href="include/style.css">
</head>
<body data-spy="scroll" data-target="#toc">

<div class="container-fluid">
<div class="row">
  <header class="col-sm-12 col-lg-3 sidebar sidebar-book"><a class="sr-only sr-only-focusable" href="#content">Skip to main content</a>

    <div class="d-flex align-items-start justify-content-between">
      <h1>
        <a href="index.html" title="">Analysis</a>
      </h1>
      <button class="btn btn-outline-primary d-lg-none ml-2 mt-1" type="button" data-toggle="collapse" data-target="#main-nav" aria-expanded="true" aria-controls="main-nav"><i class="fas fa-bars"></i><span class="sr-only">Show table of contents</span></button>
    </div>

    <div id="main-nav" class="collapse-lg">
      <form role="search">
        <input id="search" class="form-control" type="search" placeholder="Search" aria-label="Search">
</form>

      <nav aria-label="Table of contents"><h2>Table of contents</h2>
        <ul class="book-toc list-unstyled">
<li><a class="" href="index.html">Overview</a></li>
<li><a class="" href="starting-with-r-markdown.html"><span class="header-section-number">1</span> Starting with R Markdown</a></li>
<li><a class="" href="data-wrangling-a-key-skill.html"><span class="header-section-number">2</span> Data-Wrangling: A Key Skill</a></li>
<li><a class="" href="data-visualisation-through-ggplot2.html"><span class="header-section-number">3</span> Data Visualisation Through ggplot2</a></li>
<li><a class="" href="revisiting-probability-distributions.html"><span class="header-section-number">4</span> Revisiting Probability Distributions</a></li>
<li><a class="" href="nhst-binomial-test-and-one-sample-t-test.html"><span class="header-section-number">5</span> NHST: Binomial test and One-Sample t-test</a></li>
<li><a class="" href="nhst-two-sample-t-test.html"><span class="header-section-number">6</span> NHST: Two-Sample t-test</a></li>
<li><a class="" href="nhst-paired-sample-t-test-and-nonparametric-tests.html"><span class="header-section-number">7</span> NHST: Paired-Sample t-test and Nonparametric tests</a></li>
<li><a class="" href="apes---alpha-power-effect-sizes-sample-size.html"><span class="header-section-number">8</span> APES - Alpha, Power, Effect Sizes, Sample Size</a></li>
<li><a class="" href="correlations.html"><span class="header-section-number">9</span> Correlations</a></li>
<li><a class="" href="simple-regression.html"><span class="header-section-number">10</span> Simple Regression</a></li>
<li><a class="" href="multiple-regression.html"><span class="header-section-number">11</span> Multiple Regression</a></li>
<li><a class="" href="one-way-anova.html"><span class="header-section-number">12</span> One-way ANOVA</a></li>
<li><a class="active" href="factorial-anova.html"><span class="header-section-number">13</span> Factorial ANOVA</a></li>
<li class="book-part">Appendices</li>
<li><a class="" href="acknowledgements.html">Acknowledgements</a></li>
<li><a class="" href="installing-r.html"><span class="header-section-number">A</span> Installing R</a></li>
<li><a class="" href="updating-r-rstudio-and-packages.html"><span class="header-section-number">B</span> Updating R, RStudio, and packages</a></li>
<li><a class="" href="exporting-files-from-the-server.html"><span class="header-section-number">C</span> Exporting files from the server</a></li>
<li><a class="" href="symbols.html"><span class="header-section-number">D</span> Symbols</a></li>
<li><a class="" href="license.html">License</a></li>
<li><a class="" href="references.html">References</a></li>
</ul>

        <div class="book-extra">
          <p><a id="book-repo" href="https://github.com/psyteachr/analysis-v2">View book source <i class="fab fa-github"></i></a></p>
        </div>
      </nav>
</div>
  </header><main class="col-sm-12 col-md-9 col-lg-7" id="content"><div id="factorial-anova" class="section level1" number="13">
<h1>
<span class="header-section-number">13</span> Factorial ANOVA<a class="anchor" aria-label="anchor" href="#factorial-anova"><i class="fas fa-link"></i></a>
</h1>
<p>In this chapter, we are continuing from the previous chapter on ANOVA and we're going to look at an example of a Factorial ANOVA. You'll learn more about interpreting these in the lectures, but for now, we'll just focus on the code.</p>
<p>We're going to reproduce the analysis from Experiment 3 of <a href="https://journals.sagepub.com/doi/abs/10.1177/0956797614542274">Zhang, T., Kim, T., Brooks, A. W., Gino, F., &amp; Norton, M. I. (2014). A "present" for the future: The unexpected value of rediscovery. Psychological Science, 25, 1851-1860.</a>.</p>
<p>To help you understand the data we are working with, here is the abstract:</p>
<blockquote>
<p>Although documenting everyday activities may seem trivial, four studies reveal that creating records of the present generates unexpected benefits by allowing future rediscoveries. In Study 1, we used a time-capsule paradigm to show that individuals underestimate the extent to which rediscovering experiences from the past will be curiosity provoking and interesting in the future. In Studies 2 and 3, we found that people are particularly likely to underestimate the pleasure of rediscovering ordinary, mundane experiences, as opposed to extraordinary experiences. Finally, Study 4 demonstrates that underestimating the pleasure of rediscovery leads to time-inconsistent choices: Individuals forgo opportunities to document the present but then prefer rediscovering those moments in the future to engaging in an alternative fun activity. Underestimating the value of rediscovery is linked to people’s erroneous faith in their memory of everyday events. By documenting the present, people provide themselves with the opportunity to rediscover mundane moments that may otherwise have been forgotten.</p>
</blockquote>
<p>This experiment has a 2 x 2 mixed design:</p>
<ul>
<li>The first IV is time (time1, time2) and is within-subjects</li>
<li>The second IV is type of event (ordinary vs. extraordinary) and is a between-subjects factor * The DV we will use is <code>interest</code>
</li>
</ul>
<div id="factorial-a1" class="section level2" number="13.1">
<h2>
<span class="header-section-number">13.1</span> Activity 1: Set-up<a class="anchor" aria-label="anchor" href="#factorial-a1"><i class="fas fa-link"></i></a>
</h2>
<ul>
<li>Open R Studio and set the working directory to your chapter folder. Ensure the environment is clear.</li>
<li>Open a new R Markdown document and save it in your working directory. Call the file "Factorial ANOVA".</li>
<li>Download <a href="data/13-s02/Zhang%20et%20al.%202014%20Exp%203.csv" download>Zhang et al. 2014 Exp 3.csv</a> and extract the files in to your folder.</li>
<li>If you're on the server, avoid a number of issues by restarting the session - click <code>Session</code> - <code>Restart R</code>
</li>
<li>If you are working on your own computer, install the package <code>rcompanion</code>. Remember <strong>do not install packages on university computers, they are already installed</strong>.</li>
<li>Type and run the code that loads <code>pwr</code>, <code>rcompanion</code>, <code>lsr</code>, <code>car</code>, <code>broom</code>, <code>afex</code>, <code>emmeans</code> and <code>tidyverse</code> using the <code><a href="https://rdrr.io/r/base/library.html">library()</a></code> function.</li>
</ul>
<p>Run the below code to load the data and wrangle it into the format we need. You don't need to write this code yourself, but do make sure you can understand what each line is doing - a good way to do this when the code uses pipes (<code>%&gt;%</code>) is to highlight and run each line progressively so you can see how it builds up. Line-by-line the code:</p>
<ul>
<li>Reads in the data file</li>
<li>Select the three columns we need<br>
</li>
<li>Adds on a column of subject IDs<br>
</li>
<li>Tidies the data</li>
<li>Recodes the values of <code>Condition</code> from numeric to text labels</li>
<li>Recodes the values of <code>time</code> to be easier to read/write</li>
</ul>
<div class="sourceCode" id="cb477"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">factorial</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://readr.tidyverse.org/reference/read_delim.html">read_csv</a></span><span class="op">(</span><span class="st">"Zhang et al. 2014 Exp 3.csv"</span><span class="op">)</span><span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="va">Condition</span>, <span class="va">T1_Predicted_Interest_Composite</span>, <span class="va">T2_Actual_Interest_Composite</span><span class="op">)</span><span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>subject <span class="op">=</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/row_number.html">row_number</a></span><span class="op">(</span><span class="op">)</span><span class="op">)</span><span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://tidyr.tidyverse.org/reference/pivot_longer.html">pivot_longer</a></span><span class="op">(</span>names_to <span class="op">=</span> <span class="st">"time"</span>,values_to <span class="op">=</span> <span class="st">"interest"</span>, cols <span class="op">=</span>       <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"T1_Predicted_Interest_Composite"</span>,<span class="st">"T2_Actual_Interest_Composite"</span><span class="op">)</span><span class="op">)</span><span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>Condition <span class="op">=</span> <span class="fu">dplyr</span><span class="fu">::</span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/recode.html">recode</a></span><span class="op">(</span><span class="va">Condition</span>, <span class="st">"1"</span> <span class="op">=</span> <span class="st">"Ordinary"</span>, <span class="st">"2"</span> <span class="op">=</span> <span class="st">"Extraordinary"</span><span class="op">)</span><span class="op">)</span><span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>time <span class="op">=</span> <span class="fu">dplyr</span><span class="fu">::</span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/recode.html">recode</a></span><span class="op">(</span><span class="va">time</span>, <span class="st">"T1_Predicted_Interest_Composite"</span> <span class="op">=</span> <span class="st">"time1_interest"</span>,</span>
<span>                       <span class="st">"T2_Actual_Interest_Composite"</span> <span class="op">=</span> <span class="st">"time2_interest"</span><span class="op">)</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>Condition <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">as.factor</a></span><span class="op">(</span><span class="va">Condition</span><span class="op">)</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span> <span class="op">(</span>time<span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">as.factor</a></span><span class="op">(</span><span class="va">time</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
</div>
<div id="factorial-a2" class="section level2" number="13.2">
<h2>
<span class="header-section-number">13.2</span> Activity 2: Descriptive statistics<a class="anchor" aria-label="anchor" href="#factorial-a2"><i class="fas fa-link"></i></a>
</h2>
<ul>
<li>Calculate descriptive statistics (mean and SD) for <code>interest</code> for each <code>Condition</code> for each <code>time</code> (hint: you will need to <code><a href="https://dplyr.tidyverse.org/reference/group_by.html">group_by()</a></code> two variables) and store it in an object named <code>sum_dat_factorial</code>. These are known as the cells means.</li>
</ul>
</div>
<div id="factorial-a3" class="section level2" number="13.3">
<h2>
<span class="header-section-number">13.3</span> Activity 3: Violin-boxplots<a class="anchor" aria-label="anchor" href="#factorial-a3"><i class="fas fa-link"></i></a>
</h2>
<p>We're going to produce two kinds of plots to visualise our data. First, we'll produce violin-boxplots so that we can see the distribution of our data.</p>
<ul>
<li>Write the code that produces the below violin-boxplots for the scores in each group.
<ul>
<li>Hint 1: you will need to add in the second IV in the first call to ggplot as a fill argument (aes(x,y,fill)).</li>
<li>Hint 2: you will need to add <code>position = position_dodge(.9)</code> to geom_boxplot to get the plots to align.</li>
</ul>
</li>
</ul>
<p>You don't need to replicate the exact colour scheme used below, see if you can play around with the settings to whatever colour scheme you think works best.</p>
<div class="figure" style="text-align: center">
<span style="display:block;" id="fig:plt1"></span>
<img src="13-s02-lab13a_files/figure-html/plt1-1.png" alt="Violin-boxplot by condition and time" width="100%"><p class="caption">
Figure 13.1: Violin-boxplot by condition and time
</p>
</div>
</div>
<div id="factorial-a4" class="section level2" number="13.4">
<h2>
<span class="header-section-number">13.4</span> Activity 4: Interaction plots<a class="anchor" aria-label="anchor" href="#factorial-a4"><i class="fas fa-link"></i></a>
</h2>
<p>Now we're going to produce an interaction plot that makes it easier to see how the IVs are interacting, which requires some ggplot2 functions we haven't come across yet. Rather than using the raw data in <code>dat_factorial</code>, we use the means that we produced in <code>sum_dat_factorial</code>. This type of plot requires two geoms, one to draw the points, and one to draw the lines that connect them.</p>
<p>This plot reproduces the plot used in the paper.</p>
<ul>
<li>Run the code and then play around with how it looks by changing the arguments for e.g., colour, line-type, and the theme.</li>
</ul>
<div class="sourceCode" id="cb478"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">sum_dat_factorial</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">time</span>, y <span class="op">=</span> <span class="va">mean</span>, group <span class="op">=</span> <span class="va">Condition</span>, shape <span class="op">=</span> <span class="va">Condition</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span>size <span class="op">=</span> <span class="fl">3</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_path.html">geom_line</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>linetype <span class="op">=</span> <span class="va">Condition</span><span class="op">)</span><span class="op">)</span><span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_discrete.html">scale_x_discrete</a></span><span class="op">(</span>labels <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Time 1"</span>, <span class="st">"Time 2"</span><span class="op">)</span><span class="op">)</span><span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_classic</a></span><span class="op">(</span><span class="op">)</span></span></code></pre></div>
<div class="figure" style="text-align: center">
<span style="display:block;" id="fig:plot2"></span>
<img src="13-s02-lab13a_files/figure-html/plot2-1.png" alt="Interaction plot" width="100%"><p class="caption">
Figure 13.2: Interaction plot
</p>
</div>
</div>
<div id="factorial-a5" class="section level2" number="13.5">
<h2>
<span class="header-section-number">13.5</span> Activity 5: ANOVA<a class="anchor" aria-label="anchor" href="#factorial-a5"><i class="fas fa-link"></i></a>
</h2>
<ul>
<li><p>Complete the below code to run the factorial ANOVA. Remember that you will need to specify both IVs and that one of them is between-subjects and one of them is within-subjects. Look up the help documentation for <code>aov_ez</code> to find out how to do this.</p></li>
<li><p>Save the ANOVA model to an object called <code>mod_factorial</code></p></li>
<li><p>Pull out the anova table, you can either do this with <code>mod_factorial$anova_table</code> or <code>anova(mod_factorial)</code> both have the same result. Save this to an object named <code>factorial_output</code> and make sure you have used <code><a href="https://generics.r-lib.org/reference/tidy.html">tidy()</a></code>.</p></li>
</ul>
<div class="sourceCode" id="cb479"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">mod_factorial</span> <span class="op">&lt;-</span> <span class="fu">aov_ez</span><span class="op">(</span>id <span class="op">=</span> <span class="st">"NULL"</span>,</span>
<span>               data <span class="op">=</span> <span class="cn">NULL</span>, </span>
<span>               between <span class="op">=</span> <span class="st">"NULL"</span>, </span>
<span>               within <span class="op">=</span> <span class="st">"NULL"</span>,</span>
<span>               dv <span class="op">=</span> <span class="st">"NULL"</span>, </span>
<span>               type <span class="op">=</span> <span class="fl">3</span>,</span>
<span>               es <span class="op">=</span> <span class="st">"NULL"</span><span class="op">)</span> </span>
<span><span class="va">factorial_output</span> <span class="op">&lt;-</span> <span class="cn">NULL</span></span></code></pre></div>
<p>Look at the results. Remember the information about how to read p-values in scientific notation.</p>
<ul>
<li>Is the main effect of condition significant? <select class="webex-select"><option value="blank"></option>
<option value="">Yes</option>
<option value="answer">No</option></select>
</li>
<li>Is the main effect of time significant? <select class="webex-select"><option value="blank"></option>
<option value="answer">Yes</option>
<option value="">No</option></select>
</li>
<li>Is the two-way interaction significant? <select class="webex-select"><option value="blank"></option>
<option value="answer">Yes</option>
<option value="">No</option></select>
</li>
</ul>
</div>
<div id="factorial-a6" class="section level2" number="13.6">
<h2>
<span class="header-section-number">13.6</span> Activity 6: Assumption checking<a class="anchor" aria-label="anchor" href="#factorial-a6"><i class="fas fa-link"></i></a>
</h2>
<p>The assumptions for a factorial ANOVA are the same as the one-way ANOVA.</p>
<ol style="list-style-type: decimal">
<li>The DV is interval or ratio data</li>
<li>The observations should be independent</li>
<li>The residuals should be normally distributed</li>
<li>There should be homogeneity of variance between the groups</li>
</ol>
<p>As before, we know assumption 2 is met from the design of the study. Assumption 1 throws up an interesting issue which is the problem of ordinal data. Ordinal data is the kind of data that comes from Likert scales and is very, very common in psychology. The problem is that ordinal data isn't interval or ratio data, there's a fixed number of values it can take (the values of the Likert scale) and you can't claim that the distance between the values is equal (is the difference between strongly agree and agree the same as the difference between agree and neutral?).</p>
<p>Technically, we shouldn't use an ANOVA to analyse ordinal data - <em>but almost everyone does</em>. Most people would argue that if there are multiple Likert scale items that are averaged (which is the case in our study) and this averaged data is normally distributed, then it is not a problem. There is a minority (who are actually correct) that argue you should use non-parametric methods or more complicated tests such as ordinal regression for this type of data. Whichever route you choose, you should understand the data you have and you should be able to justify your decision.</p>
<ul>
<li><p>To test assumption 3, extract the residuals from the model (<code>mod_factorial$lm$residuals</code>), create a qq-plot and conduct a Shapiro-Wilk test.</p></li>
<li><p>Are the residuals normally distributed? <select class="webex-select"><option value="blank"></option>
<option value="">Yes</option>
<option value="">No</option>
<option value="answer">No, but given the sample it is probably acceptable to proceed</option></select></p></li>
</ul>
<p>For the final assumption, we can again use <code><a href="https://rdrr.io/pkg/afex/man/deprecated.html">test_levene()</a></code> to test homogeneity of variance.</p>
<ul>
<li>Conduct Levene's test. Is assumption 4 met? <select class="webex-select"><option value="blank"></option>
<option value="answer">Yes</option>
<option value="">No</option></select>
</li>
</ul>
</div>
<div id="factorial-a7" class="section level2" number="13.7">
<h2>
<span class="header-section-number">13.7</span> Activity 7: Post-hoc tests<a class="anchor" aria-label="anchor" href="#factorial-a7"><i class="fas fa-link"></i></a>
</h2>
<p>Because the interaction is significant, we should follow this up with post-hoc tests using <code><a href="https://rdrr.io/pkg/emmeans/man/emmeans.html">emmeans()</a></code> to determine which comparisons are significant. If the overall interaction is not significant, you should not conduct additional tests.</p>
<p><code><a href="https://rdrr.io/pkg/emmeans/man/emmeans.html">emmeans()</a></code> requires you to specify the <code>aov</code> object, and then the factors you want to contrast. For an interaction, we use the notation <code>pairwise ~ IV1 | IV2</code> and you specify which multiple comparison correction you want to apply. Finally, you can use <code><a href="https://generics.r-lib.org/reference/tidy.html">tidy()</a></code> to tidy up the output of the contrasts and save it into a tibble.</p>
<ul>
<li>Run the below code and view the results.</li>
</ul>
<div class="sourceCode" id="cb480"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># run the tests</span></span>
<span><span class="va">posthoc_factorial</span> <span class="op">&lt;-</span> <span class="fu">emmeans</span><span class="op">(</span><span class="va">mod_factorial</span>, </span>
<span>                             <span class="va">pairwise</span> <span class="op">~</span> <span class="va">time</span><span class="op">|</span> <span class="va">Condition</span>, </span>
<span>                             adjust <span class="op">=</span> <span class="st">"bonferroni"</span><span class="op">)</span></span>
<span><span class="co"># tidy up the output of the tests</span></span>
<span><span class="va">contrasts_factorial</span> <span class="op">&lt;-</span> <span class="va">posthoc_factorial</span><span class="op">$</span><span class="va">contrasts</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://generics.r-lib.org/reference/tidy.html">tidy</a></span><span class="op">(</span><span class="op">)</span></span></code></pre></div>
<p>Note that because there are two factors, we could also reverse the order of the IVs. Above, we get the results contrasting time 1 and time 2 for each condition. Instead, we could look at the difference between ordinary and extraordinary events at each time point.</p>
<ul>
<li>Run the below code and look at the output of <code>contrast_factorial</code> and <code>contrasts_factorial2</code> carefully making sure you understand how to interpret the results. You will find it useful to refer to the interaction plot we made earlier.</li>
</ul>
<div class="sourceCode" id="cb481"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">posthoc_factorial2</span> <span class="op">&lt;-</span> <span class="fu">emmeans</span><span class="op">(</span><span class="va">mod_factorial</span>, </span>
<span>                             <span class="va">pairwise</span> <span class="op">~</span> <span class="va">Condition</span><span class="op">|</span> <span class="va">time</span>, </span>
<span>                             adjust <span class="op">=</span> <span class="st">"bonferroni"</span><span class="op">)</span> </span>
<span><span class="va">contrasts_factorial2</span> <span class="op">&lt;-</span> <span class="va">posthoc_factorial2</span><span class="op">$</span><span class="va">contrasts</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://generics.r-lib.org/reference/tidy.html">tidy</a></span><span class="op">(</span><span class="op">)</span></span></code></pre></div>
<p>Because our main effects (condition and time) only have two levels, we don't need to do any post-hoc tests to determine which conditions differ from each other, however, if one of our factors had three levels then we could use <code><a href="https://rdrr.io/pkg/emmeans/man/emmeans.html">emmeans()</a></code> to calculate the contrast for the main effects, like we did for the one-way ANOVA.</p>
<p>Finally, to calculate effect size for the pairwise comparisons we again need to do this individually using 'cohensD()<code>from</code>lsr<code>.  * Run the below code to add on effect sizes to</code>contrasts_factorial<code>and</code>contrasts_factorial2`.</p>
<div class="sourceCode" id="cb482"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">d_extra_t1_t2</span> <span class="op">&lt;-</span> <span class="fu">cohensD</span><span class="op">(</span><span class="va">interest</span> <span class="op">~</span> <span class="va">time</span>, </span>
<span>                         data <span class="op">=</span> <span class="op">(</span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">factorial</span>, <span class="va">Condition</span> <span class="op">==</span> <span class="st">"Extraordinary"</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="fu"><a href="https://rdrr.io/r/base/droplevels.html">droplevels</a></span><span class="op">(</span><span class="op">)</span><span class="op">)</span><span class="op">)</span> </span>
<span><span class="va">d_ord_t1_t2</span> <span class="op">&lt;-</span> <span class="fu">cohensD</span><span class="op">(</span><span class="va">interest</span> <span class="op">~</span> <span class="va">time</span>, </span>
<span>                         data <span class="op">=</span> <span class="op">(</span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">factorial</span>, <span class="va">Condition</span> <span class="op">==</span> <span class="st">"Ordinary"</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="fu"><a href="https://rdrr.io/r/base/droplevels.html">droplevels</a></span><span class="op">(</span><span class="op">)</span><span class="op">)</span><span class="op">)</span> </span>
<span><span class="va">Condition_ds</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="va">d_extra_t1_t2</span>, <span class="va">d_ord_t1_t2</span><span class="op">)</span></span>
<span><span class="va">contrasts_factorial</span> <span class="op">&lt;-</span> <span class="va">contrasts_factorial</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>eff_size <span class="op">=</span> <span class="va">Condition_ds</span><span class="op">)</span></span>
<span><span class="va">d_time1_extra_ord</span> <span class="op">&lt;-</span> <span class="fu">cohensD</span><span class="op">(</span><span class="va">interest</span> <span class="op">~</span> <span class="va">Condition</span>, </span>
<span>                         data <span class="op">=</span> <span class="op">(</span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">factorial</span>, <span class="va">time</span> <span class="op">==</span> <span class="st">"time1_interest"</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="fu"><a href="https://rdrr.io/r/base/droplevels.html">droplevels</a></span><span class="op">(</span><span class="op">)</span><span class="op">)</span><span class="op">)</span> </span>
<span><span class="va">d_time2_extra_ord</span> <span class="op">&lt;-</span> <span class="fu">cohensD</span><span class="op">(</span><span class="va">interest</span> <span class="op">~</span> <span class="va">Condition</span>, </span>
<span>                         data <span class="op">=</span> <span class="op">(</span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">factorial</span>, <span class="va">time</span> <span class="op">==</span> <span class="st">"time2_interest"</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="fu"><a href="https://rdrr.io/r/base/droplevels.html">droplevels</a></span><span class="op">(</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="va">time_ds</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="va">d_time1_extra_ord</span>, <span class="va">d_time2_extra_ord</span><span class="op">)</span></span>
<span><span class="va">contrasts_factorial2</span> <span class="op">&lt;-</span> <span class="va">contrasts_factorial2</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>eff_size <span class="op">=</span> <span class="va">time_ds</span><span class="op">)</span></span></code></pre></div>
</div>
<div id="factorial-a8" class="section level2" number="13.8">
<h2>
<span class="header-section-number">13.8</span> Activity 8: Write-up<a class="anchor" aria-label="anchor" href="#factorial-a8"><i class="fas fa-link"></i></a>
</h2>
<ul>
<li>p-values of &lt; .001 have been entered manually. There is a way to get R to produce this formatting but it's overly complicated for our purposes. If you want to push yourself, look up the <a href="https://github.com/crsh/papaja">papaja</a> package.</li>
<li>The values of partial eta-squared do not match between our analysis and those reported in the paper. We haven't figured out why this is yet - if you know, please get in touch!</li>
<li>We have replaced the simple effects in the main paper with our pairwise comparisons.</li>
</ul>
<p>First we need to calculate descriptives for the main effect of time as we didn't do this earlier.</p>
<div class="sourceCode" id="cb483"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">time_descrip</span> <span class="op">&lt;-</span> <span class="va">factorial</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/group_by.html">group_by</a></span><span class="op">(</span><span class="va">time</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarise</a></span><span class="op">(</span>mean_interest <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">interest</span>, na.rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>,</span>
<span>            sd_interest <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/sd.html">sd</a></span><span class="op">(</span><span class="va">interest</span>, na.rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>,</span>
<span>            min <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">interest</span><span class="op">)</span> <span class="op">-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">qnorm</a></span><span class="op">(</span><span class="fl">0.975</span><span class="op">)</span><span class="op">*</span><span class="fu"><a href="https://rdrr.io/r/stats/sd.html">sd</a></span><span class="op">(</span><span class="va">interest</span><span class="op">)</span><span class="op">/</span><span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">sqrt</a></span><span class="op">(</span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/context.html">n</a></span><span class="op">(</span><span class="op">)</span><span class="op">)</span>,</span>
<span>            max <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">interest</span><span class="op">)</span> <span class="op">+</span> <span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">qnorm</a></span><span class="op">(</span><span class="fl">0.975</span><span class="op">)</span><span class="op">*</span><span class="fu"><a href="https://rdrr.io/r/stats/sd.html">sd</a></span><span class="op">(</span><span class="va">interest</span><span class="op">)</span><span class="op">/</span><span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">sqrt</a></span><span class="op">(</span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/context.html">n</a></span><span class="op">(</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<p>Copy and paste the below into <strong>white-space</strong>.</p>
<div class="sourceCode" id="cb484"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb484-1"><a href="factorial-anova.html#cb484-1" tabindex="-1"></a>We conducted the same repeated measures ANOVA with interest as the dependent measure and again found a main effect of time, <span class="fu">F</span>(<span class="st">`</span><span class="at">r factorial_output$num.Df[2]</span><span class="st">`</span>, <span class="st">`</span><span class="at">r factorial_output$den.Df[2]</span><span class="st">`</span>) <span class="ot">=</span> <span class="st">`</span><span class="at">r factorial_output$statistic[2] %&gt;% round(2)</span><span class="st">`</span>, p <span class="sc">&lt;</span> .<span class="dv">001</span>, ηp2 <span class="ot">=</span> <span class="st">`</span><span class="at">r factorial_output$ges[2] %&gt;% round(3)</span><span class="st">`</span>; anticipated interest at Time <span class="dv">1</span> (<span class="at">M =</span> <span class="st">`</span><span class="at">r time_descrip$mean_interest[1] %&gt;% round(2)</span><span class="st">`</span>), SD <span class="ot">=</span> <span class="st">`</span><span class="at">r time_descrip$sd_interest[1]%&gt;% round(2)</span><span class="st">`</span><span class="er">))</span> was lower than actual interest at Time <span class="dv">2</span> (<span class="at">M =</span> <span class="st">`</span><span class="at">r time_descrip$mean_interest[2]%&gt;% round(2)</span><span class="st">`</span>, <span class="at">SD =</span> <span class="st">`</span><span class="at">r time_descrip$sd_interest[2]%&gt;% round(2)</span><span class="st">`</span>).We also observed an interaction between time and type of experience, <span class="fu">F</span>(<span class="st">`</span><span class="at">r factorial_output$num.Df[3]</span><span class="st">`</span>, <span class="st">`</span><span class="at">r factorial_output$den.Df[3]</span><span class="st">`</span>) <span class="ot">=</span> <span class="st">`</span><span class="at">r factorial_output$statistic[3] %&gt;% round(3)</span><span class="st">`</span>, p <span class="ot">=</span> <span class="st">`</span><span class="at">r factorial_output$p.value[3] %&gt;% round(2)</span><span class="st">`</span>, ηp2 <span class="ot">=</span> <span class="st">`</span><span class="at">r factorial_output$ges[3] %&gt;% round(3)</span><span class="st">`</span>. Pairwise comparisons revealed that <span class="cf">for</span> ordinary events, predicted interest at Time <span class="dv">1</span> (<span class="at">M =</span> <span class="st">`</span><span class="at">r sum_dat_factorial$mean[3]%&gt;% round(2)</span><span class="st">`</span>, <span class="at">SD =</span> <span class="st">`</span><span class="at">r sum_dat_factorial$sd[3]%&gt;% round(2)</span><span class="st">`</span>) was lower than experienced interest at Time <span class="dv">2</span> (<span class="at">M =</span> <span class="st">`</span><span class="at">r sum_dat_factorial$mean[4]%&gt;% round(2)</span><span class="st">`</span>, <span class="at">SD =</span> <span class="st">`</span><span class="at">r sum_dat_factorial$sd[4]%&gt;% round(2)</span><span class="st">`</span>), <span class="fu">t</span>(<span class="st">`</span><span class="at">r contrasts_factorial$df[2]%&gt;% round(2)</span><span class="st">`</span>) <span class="ot">=</span> <span class="st">`</span><span class="at">r contrasts_factorial$statistic[2]%&gt;% round(2)</span><span class="st">`</span>, p <span class="sc">&lt;</span> .<span class="dv">001</span>, d <span class="ot">=</span> <span class="st">`</span><span class="at">r contrasts_factorial$eff_size[2]%&gt;% round(2)</span><span class="st">`</span>. Although predicted interest <span class="cf">for</span> extraordinary events at Time <span class="dv">1</span> (<span class="at">M =</span> <span class="st">`</span><span class="at">r sum_dat_factorial$mean[1]%&gt;% round(2)</span><span class="st">`</span>, <span class="at">SD =</span> <span class="st">`</span><span class="at">r sum_dat_factorial$sd[1]%&gt;% round(2)</span><span class="st">`</span>) was lower than experienced interest at Time <span class="dv">2</span> (<span class="at">M =</span> <span class="st">`</span><span class="at">r sum_dat_factorial$mean[2]%&gt;% round(2)</span><span class="st">`</span>, <span class="at">SD =</span> <span class="st">`</span><span class="at">r sum_dat_factorial$sd[2]%&gt;% round(2)</span><span class="st">`</span>), <span class="fu">t</span>(<span class="st">`</span><span class="at">r contrasts_factorial$df[1]%&gt;% round(2)</span><span class="st">`</span>) <span class="ot">=</span> <span class="st">`</span><span class="at">r contrasts_factorial$statistic[1]%&gt;% round(2)</span><span class="st">`</span>, p <span class="sc">&lt;</span> .<span class="dv">001</span>, d <span class="ot">=</span> <span class="st">`</span><span class="at">r contrasts_factorial$eff_size[1]%&gt;% round(2)</span><span class="st">`</span> , the magnitude of underestimation was smaller than <span class="cf">for</span> ordinary events.</span></code></pre></div>
<blockquote>
<p>We conducted the same repeated measures ANOVA with interest as the dependent measure and again found a main effect of time, F(1, 128) = 25.88, p &lt; .001, ηp2 = 0.044; anticipated interest at Time 1 (M = 4.2), SD = 1.12)) was lower than actual interest at Time 2 (M = 4.69, SD = 1.19).We also observed an interaction between time and type of experience, F(1, 128) = 4.445, p = 0.04, ηp2 = 0.008. Pairwise comparisons revealed that for ordinary events, predicted interest at Time 1 (M = 4.04, SD = 1.09) was lower than experienced interest at Time 2 (M = 4.73, SD = 1.24), t(128) = -5.05, p &lt; .001, d = 0.59. Although predicted interest for extraordinary events at Time 1 (M = 4.36, SD = 1.13) was lower than experienced interest at Time 2 (M = 4.65, SD = 1.14), t(128) = -2.12, p &lt; .001, d = 0.25 , the magnitude of underestimation was smaller than for ordinary events.</p>
</blockquote>
</div>
<div id="factorial-a9" class="section level2" number="13.9">
<h2>
<span class="header-section-number">13.9</span> Activity 9: Transforming data<a class="anchor" aria-label="anchor" href="#factorial-a9"><i class="fas fa-link"></i></a>
</h2>
<p>In this chapter we decided that the violation of the assumption of normality was ok so that we could replicate the results in the paper. But what if we weren't happy with this or if the violation had been more extreme? One option to deal with normality is to <strong>transform your data</strong>.</p>
<p>There are various options for how you can transform data but we're going to use Tukeys Ladder of Powers transformation. This finds the power transformation that makes the data fit the normal distribution as closely as possible with this type of transformation.</p>
<ul>
<li>Run the below code. This will use <code><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate()</a></code> to add a new variable to the data-set, <code>interest_tukey</code> which is going to be our transformed DV. The function <code><a href="https://rdrr.io/pkg/rcompanion/man/transformTukey.html">transformTukey()</a></code> is from the <code>rcompanion</code> package. Setting <code>plotit = TRUE</code> will automatically create qqPlots and histograms so that we can immediately visualise the new variable.</li>
</ul>
<div class="sourceCode" id="cb485"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">factorial</span> <span class="op">&lt;-</span> <span class="va">factorial</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>interest_tukey <span class="op">=</span> <span class="fu">transformTukey</span><span class="op">(</span><span class="va">interest</span>, plotit<span class="op">=</span><span class="cn">TRUE</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<p>Now that you've transformed the DV we can re-run the ANOVA with this new variable.</p>
<div class="sourceCode" id="cb486"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">tukey_factorial</span> <span class="op">&lt;-</span> <span class="fu">aov_ez</span><span class="op">(</span>id <span class="op">=</span> <span class="st">"subject"</span>,</span>
<span>               data <span class="op">=</span> <span class="va">factorial</span>, </span>
<span>               between <span class="op">=</span> <span class="st">"Condition"</span>, </span>
<span>               within <span class="op">=</span> <span class="st">"time"</span>,</span>
<span>               dv <span class="op">=</span> <span class="st">"interest_tukey"</span>, </span>
<span>               type <span class="op">=</span> <span class="fl">3</span><span class="op">)</span></span>
<span><span class="va">tukey_factorial</span></span></code></pre></div>
<p>Notice that doing this hasn't changed the pattern of the ANOVA results, the p-values for the main effects and interactions are very slightly different but the overall conclusions remain the same. This is likely because the violations of normality was quite mild and there is a large sample size, however, with the transformation we can be more confident in our results and it may not always be the case that the transformed ANOVA is the same if the violations were more extreme.</p>
</div>
<div id="practice-your-skills-14" class="section level2" number="13.10">
<h2>
<span class="header-section-number">13.10</span> Practice Your Skills<a class="anchor" aria-label="anchor" href="#practice-your-skills-14"><i class="fas fa-link"></i></a>
</h2>
<p><strong>Two-Factor ANOVA: Perspective-Taking in Language Comprehension</strong></p>
<p>In order to complete this exercise, download the .Rmd file which you need to edit titled <code>GUID_Level2B_PracticeSkills.Rmd</code>. This can be downloaded within a zip file from the below link. Once downloaded and unzipped you should create a new folder that you will use as your working directory; put the .Rmd file in that folder and set your working directory to that folder through the drop-down menus at the top. <a href="./data/13-s02/homework/ch13-practiceskills.zip" target="_blank">Download the Practice Your Skills Exercise .zip file from here</a>.</p>
<p><strong>Background: Perspective-Taking in Language Comprehension</strong></p>
<p>For this exercise, you will be looking at real data from <strong>Experiment 2</strong> of <a href="https://www.sciencedirect.com/science/article/pii/S0010027703000647?via%3Dihub" target="_blank">Keysar, Lin, and Barr (2003)</a>, "Limits on Theory of Mind Use in Adults", <strong>Cognition</strong>, <strong>89</strong>, 29--41. This study used eye-tracking to investigate people's ability to take another's perspective during a communication game. (The data that you will be analysing, while real, did not appear in the original report.)</p>
<p>The communication game that participants played was as follows: Each participant sat at a table opposite a confederate participant (a person from the lab who pretended to be a naive participant). Between the two participants was an upright set of shelves (see figure below). The participants played a game in which the real participant was assigned the role of the "matcher" and the confederate the role of the "director". The director was given a picture with a goal state for the grid, showing how the objects needed to be arranged. However, the director was not allowed to touch the objects. To get the objects in their proper places, the director needed to give instructions to the matcher to move the objects. For example, the director might say, "take the red box in the top corner and move it down to the very bottom row," and the matcher would then perform the action. The matcher's eye movements were tracked as they listened to and interpreted the director's instructions.</p>
<div class="figure" style="text-align: center">
<span style="display:block;" id="fig:img-lab13-grids"></span>
<img src="images/s02-lab13/homework/grids.png" alt="Director-Matcher Viewpoints from Keysar, Lin, and Barr (2003)" width="50%"><p class="caption">
Figure 13.3: Director-Matcher Viewpoints from Keysar, Lin, and Barr (2003)
</p>
</div>
<p>To investigate perspective taking, the instructions given by the director were actually scripted beforehand in order to create certain ambiguities. Most of the objects in the grid, such as the red box, were mutually visible to both participants (i.e., visible from both sides of the grid). However, some of objects, like the brush and the green candle, were occluded from the director's view; the matcher could see them, but had no reason to believe that the director knew the contents of these occluded squares, and thus had no reason to expect them to ever refer to them. However, sometimes the director would refer to a mutually visible object using a description that also happened to match one of the hidden objects. For instance, the director might instruct the matcher to "pick up the small candle." Note that for the director, the small candle is the purple candle. A given matcher would see this grid in one of two conditions: In the <strong>Experimental</strong> condition, the matcher saw an additional green candle in a hidden box that was even smaller than the purple candle (see middle panel of the above figure). This object was called a "competitor" because it matched the description of the intended referent (the purple candle). In the <strong>Baseline</strong> condition, the green candle was replaced with an object that did not match the director's description, such as an apple. These ambiguous situations provided the main data for the experiment, and in total there were eight different grids in the experiment that presented analogous situations to the example above.</p>
<p><a href="https://journals.sagepub.com/doi/abs/10.1111/1467-9280.00211" target="_blank">A previous eye-tracking study by the same authors</a> had found the presence of the competitors severely confused the matchers, suggesting that people were surprisingly egocentric---they found it hard to ignore "privileged" information when interpreting another person's speech. For example, when the director said to "pick up the small candle," they spent far more time looking at a hidden green candle than a hidden apple, even though neither one of these objects, being hidden, was a viable referent. We refer to the difference in looking time as the 'egocentric interference effect'.</p>
<p>Experiment 2 by Keysar, Lin, and Barr aimed to follow up on this finding. In the previous article, the matcher had reason to believe that the director was merely ignorant of the identity of the hidden objects. But what would happen if the matcher was given reason to believe that the director actually had a <strong>false belief</strong> about the hidden object? For example, would the matcher experience less egocentric interference if they had reason to think that the director thought that the hidden candle was a toy truck?</p>
<p>To test this, half of the participants were randomly assigned to a <strong>false belief</strong> condition, where the matcher was led to believe that the director had a false belief about the identity of the hidden object; the other half participated in the <strong>ignorance</strong> condition, where as in previous experiments, they were led to believe that the director simply did not know what was in the hidden squares.</p>
<p>There were 40 participants in this experiment, 20 in the false belief condition, and 20 in the ignorance condition. There were also an equal number of male and female participants in the study. To spoil the plot a bit, Keysar, Lin and Barr did not find any effect of condition on looking time. However, they did not consider sex as a potential moderating variable. Thus, we will explore the effects of ignorance vs. false belief on egocentric interference, broken down by the sex of the matcher.</p>
<p><strong>Before starting lets check:</strong></p>
<ol style="list-style-type: decimal">
<li><p>The <code>.csv</code> file is saved into a folder on your computer and you have manually set this folder as your working directory.</p></li>
<li><p>The <code>.Rmd</code> file is saved in the same folder as the <code>.csv</code> files. Save it with the format <code>GUID_Level2B_PracticeSkills.Rmd</code> where <code>GUID</code> is replaced with your <code>GUID</code>.</p></li>
</ol>
<div id="Ch13AssignQueT1A" class="section level3" number="13.10.1">
<h3>
<span class="header-section-number">13.10.1</span> Task 1A: Libraries<a class="anchor" aria-label="anchor" href="#Ch13AssignQueT1A"><i class="fas fa-link"></i></a>
</h3>
<ul>
<li>In today's exercise you will need both the <code>tidyverse</code> and <code>afex</code> packages. Enter code into the t1A code chunk below to load in both of these libraries.</li>
</ul>
<div class="sourceCode" id="cb487"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># load in the packages</span></span></code></pre></div>
</div>
<div id="Ch13AssignQueT1B" class="section level3" number="13.10.2">
<h3>
<span class="header-section-number">13.10.2</span> Task 1B: Loading in the data<a class="anchor" aria-label="anchor" href="#Ch13AssignQueT1B"><i class="fas fa-link"></i></a>
</h3>
<ul>
<li>Use <code><a href="https://readr.tidyverse.org/reference/read_delim.html">read_csv()</a></code> to replace the <code>NULL</code> in the t1B code chunk below to load in the data stored in the datafile <code>keysar_lin_barr_2003.csv</code>. Store the data in the variable <code>dat</code>.</li>
</ul>
<div class="sourceCode" id="cb488"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">dat</span> <span class="op">&lt;-</span> <span class="cn">NULL</span></span></code></pre></div>
<p>Take a look at your data (<code>dat</code>) in the console using <code><a href="https://pillar.r-lib.org/reference/glimpse.html">glimpse()</a></code> or <code><a href="https://rdrr.io/r/utils/View.html">View()</a></code>, or just display it by typing in the name. You will see the following columns:</p>
<div class="inline-table"><table class="table table-sm">
<thead><tr class="header">
<th>variable</th>
<th>description</th>
</tr></thead>
<tbody>
<tr class="odd">
<td><code>subject</code></td>
<td>unique identifier for each subject</td>
</tr>
<tr class="even">
<td><code>sex</code></td>
<td>whether the participant was male or female</td>
</tr>
<tr class="odd">
<td><code>condition</code></td>
<td>what condition the subject was in</td>
</tr>
<tr class="even">
<td><code>looktime</code></td>
<td>egocentric interference</td>
</tr>
</tbody>
</table></div>
<p>We have simplified things from the original experiment by collapsing the baseline vs. experimental conditions into a single DV. Our DV, egocentric interference, is the average difference in looking time for each participant (in milliseconds per trial) for hidden competitors (e.g., small candle) versus hidden non-competitors (e.g., apple). The larger this number, the more egocentric interference the participant experienced.</p>
</div>
<div id="Ch13AssignQueT2" class="section level3" number="13.10.3">
<h3>
<span class="header-section-number">13.10.3</span> Task 2: Calculate cell means<a class="anchor" aria-label="anchor" href="#Ch13AssignQueT2"><i class="fas fa-link"></i></a>
</h3>
<p>Today we are going to focus on just the main analysis and write-up, and not the assumptions, but as always you should check that your <strong>assumptions</strong> hold and justify your decisions.</p>
<p>One of the elements we will need for our write-up is some descriptives. We want to start by creating some summary statistics for the four conditions. Remember, two factors (sex and condition) with 2 levels each (sex: female vs. male; condition: false belief vs. ignorance) will give you four conditions, and as such in our summary table, four cells created by factorially combining sex and condition.</p>
<ul>
<li>Replace the NULL in the <code>t2</code> code chunk below to create the four cells created by factorially combining sex and condition, calculating the mean and standard deviation for each cell.
<ul>
<li>Store the descriptives in the tibble called <code>cell_means</code>
</li>
<li>Call the column for the mean <code>m</code> and the column for the standard deviation <code>sd</code>.</li>
<li>Your table should have four rows and four columns as shown below but with your values replacing the XXs</li>
<li>Follow the case and spelling <em>exactly</em>.</li>
</ul>
</li>
</ul>
<div class="sourceCode" id="cb489"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">cell_means</span> <span class="op">&lt;-</span> <span class="cn">NULL</span></span></code></pre></div>
<div class="inline-table"><table class="table table-sm">
<thead><tr class="header">
<th align="left">sex</th>
<th align="left">condition</th>
<th align="left">m</th>
<th align="left">sd</th>
</tr></thead>
<tbody>
<tr class="odd">
<td align="left">female</td>
<td align="left">false belief</td>
<td align="left">XX</td>
<td align="left">XX</td>
</tr>
<tr class="even">
<td align="left">female</td>
<td align="left">ignorance</td>
<td align="left">XX</td>
<td align="left">XX</td>
</tr>
<tr class="odd">
<td align="left">male</td>
<td align="left">false belief</td>
<td align="left">XX</td>
<td align="left">XX</td>
</tr>
<tr class="even">
<td align="left">male</td>
<td align="left">ignorance</td>
<td align="left">XX</td>
<td align="left">XX</td>
</tr>
</tbody>
</table></div>
</div>
<div id="Ch13AssignQueT3" class="section level3" number="13.10.4">
<h3>
<span class="header-section-number">13.10.4</span> Task 3: Marginal means for sex<a class="anchor" aria-label="anchor" href="#Ch13AssignQueT3"><i class="fas fa-link"></i></a>
</h3>
<p>We will also need to have some descriptives where we just look at the means of a given factor; the marginal means - the means of the levels of one factor regardless of the other factor.</p>
<ul>
<li>Replace the NULL in the <code>t3</code> code chunk below to calculate the marginal means and standard deviations for the factor sex.
<ul>
<li>Store these descriptives in the tibble <code>marg_sex</code>
</li>
<li>Call the column for the mean <code>m</code> and the column for the standard deviation <code>sd</code>.</li>
<li>Your table should have two rows and three columns as shown below but with your values replacing the XXs</li>
<li>Follow the case and spelling <em>exactly</em>.</li>
</ul>
</li>
</ul>
<div class="sourceCode" id="cb490"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">marg_sex</span> <span class="op">&lt;-</span> <span class="cn">NULL</span></span></code></pre></div>
<div class="inline-table"><table class="table table-sm">
<thead><tr class="header">
<th align="left">sex</th>
<th align="left">m</th>
<th align="left">sd</th>
</tr></thead>
<tbody>
<tr class="odd">
<td align="left">female</td>
<td align="left">XX</td>
<td align="left">XX</td>
</tr>
<tr class="even">
<td align="left">male</td>
<td align="left">XX</td>
<td align="left">XX</td>
</tr>
</tbody>
</table></div>
</div>
<div id="Ch13AssignQueT4" class="section level3" number="13.10.5">
<h3>
<span class="header-section-number">13.10.5</span> Task 4: Marginal means for condition<a class="anchor" aria-label="anchor" href="#Ch13AssignQueT4"><i class="fas fa-link"></i></a>
</h3>
<p>And now do the same for condition.</p>
<ul>
<li>Replace the NULL in the <code>t4</code> code chunk below to calculate the marginal means and standard deviations for the factor, condition
<ul>
<li>Store these descriptives in the tibble <code>marg_cond</code>
</li>
<li>Call the column for the mean <code>m</code> and the column for the standard deviation <code>sd</code>.</li>
<li>Your table should have two rows and three columns as shown below but with your values replacing the XXs</li>
<li>Follow the case and spelling <em>exactly</em>.</li>
</ul>
</li>
</ul>
<div class="sourceCode" id="cb491"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">marg_cond</span> <span class="op">&lt;-</span> <span class="cn">NULL</span></span></code></pre></div>
<div class="inline-table"><table class="table table-sm">
<thead><tr class="header">
<th align="left">condition</th>
<th align="left">m</th>
<th align="left">sd</th>
</tr></thead>
<tbody>
<tr class="odd">
<td align="left">false belief</td>
<td align="left">XX</td>
<td align="left">XX</td>
</tr>
<tr class="even">
<td align="left">ignorance</td>
<td align="left">XX</td>
<td align="left">XX</td>
</tr>
</tbody>
</table></div>
</div>
<div id="Ch13AssignQueT5" class="section level3" number="13.10.6">
<h3>
<span class="header-section-number">13.10.6</span> Task 5: Interaction plot<a class="anchor" aria-label="anchor" href="#Ch13AssignQueT5"><i class="fas fa-link"></i></a>
</h3>
<p>And finally we are going to need a plot. When you have two factors, you want to show both factors on the plot to give the reader as much information as possible and save on figure space. The best way to do this is through some sort of interaction plot. It is really a lot easier than it looks and it only requires you to think about setting the aes by the different conditions.</p>
<ul>
<li>Insert code into the <code>t5</code> code chunk below to replicate the figure shown to you.
<ul>
<li>Pay particular attention to labels, axes dimensions, color and background.</li>
<li>Note that the figure must appear when your code is knitted.</li>
</ul>
</li>
<li>
<strong>Note:</strong> The figure below is a nice figure but should really have error bars on it if I was including it in an actual paper. Including the error bars may help in clarifying the descriptive statistics and you will see that here, although the means are different, there is huge overlap in terms of error bars which may indicate no overall effect.</li>
</ul>
<div class="sourceCode" id="cb492"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># to do: something with ggplot to replicate the figure</span></span></code></pre></div>
<pre><code>## `summarise()` has grouped output by 'sex'. You can override using the `.groups`
## argument.</code></pre>
<div class="figure" style="text-align: center">
<span style="display:block;" id="fig:t5-hide"></span>
<img src="13-s02-lab13a_files/figure-html/t5-hide-1.png" alt="Replicate this Figure" width="100%"><p class="caption">
Figure 13.4: Replicate this Figure
</p>
</div>
</div>
<div id="Ch13AssignQueT6" class="section level3" number="13.10.7">
<h3>
<span class="header-section-number">13.10.7</span> Task 6: Recap Question 1<a class="anchor" aria-label="anchor" href="#Ch13AssignQueT6"><i class="fas fa-link"></i></a>
</h3>
<p>Thinking about the above information, one of the below statements would be an acceptable hypothesis for the interaction effect of sex and condition, but which one:</p>
<ul>
<li>In the <code>t6</code> code chunk below, replace the <code>NULL</code> with the number of the statement below that best summarises this analysis. Store this single value in <code>answer_t6</code>
</li>
</ul>
<ol style="list-style-type: decimal">
<li>We hypothesised that there will be a significant difference between males and females in egocentric interference (mean looking time (msecs)) regardless of condition.</li>
<li>We hypothesised that there will be a significant difference between participants in the false belief condition and those in the ignorance condition in terms of egocentric interference (mean looking time (msecs)) regardless of sex of participant.</li>
<li>We hypothesised that there would be a significant interaction between condition and sex of participant on egocentric interference (mean looking time (msecs))</li>
<li>We hypothesised that there will be no significant difference between males and females in egocentric interference (mean looking time (msecs)) regardless of condition but that there would be a significant difference between participants in the false belief condition and those in the ignorance condition in terms of egocentric interference (mean looking time (msecs)) regardless of sex of participant.</li>
</ol>
<div class="sourceCode" id="cb494"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">answer_t6</span> <span class="op">&lt;-</span> <span class="cn">NULL</span></span></code></pre></div>
</div>
<div id="Ch13AssignQueT7" class="section level3" number="13.10.8">
<h3>
<span class="header-section-number">13.10.8</span> Task 7: Recap Question 2<a class="anchor" aria-label="anchor" href="#Ch13AssignQueT7"><i class="fas fa-link"></i></a>
</h3>
<p>Thinking about the above information, one of the below statements is a good description of the marginal means for sex, but which one:</p>
<ul>
<li>In the <code>t7</code> code chunk below, replace the <code>NULL</code> with the number of the statement below that best summarises this analysis. Store this single value in <code>answer_t7</code>
</li>
</ul>
<ol style="list-style-type: decimal">
<li>The female participants have an average longer looking time (M = 777.98, SD = 911.53) than the male participants (M = 555.04, SD = 707.81) which may suggest a significant main effect of sex.</li>
<li>The female participants have an average shorter looking time (M = 777.98, SD = 911.53) than the male participants (M = 555.04, SD = 707.81) which may suggest a significant main effect of condition.</li>
<li>The female participants have an average shorter looking time (M = 777.98, SD = 911.53) than the male participants (M = 555.04, SD = 707.81) which may suggest a significant main effect of sex.</li>
<li>The female participants have an average longer looking time (M = 777.98, SD = 911.53) than the male participants (M = 555.04, SD = 707.81) which may suggest a significant main effect of condition.</li>
</ol>
<div class="sourceCode" id="cb495"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">answer_t7</span> <span class="op">&lt;-</span> <span class="cn">NULL</span></span></code></pre></div>
</div>
<div id="Ch13AssignQueT8" class="section level3" number="13.10.9">
<h3>
<span class="header-section-number">13.10.9</span> Task 8: Recap Question 3<a class="anchor" aria-label="anchor" href="#Ch13AssignQueT8"><i class="fas fa-link"></i></a>
</h3>
<p>Thinking about the above information, one of the below statements is a good description of the marginal means for condition, but which one:</p>
<ul>
<li>In the <code>t8</code> code chunk below, replace the <code>NULL</code> with the number of the statement below that best summarises this analysis. Store this single value in <code>answer_t8</code>
</li>
</ul>
<ol style="list-style-type: decimal">
<li>The participants in the false belief group had an average longer looking time (M = 549.58, SD = 775.91) than the participants in the ignorance group (M = 749.58, SD = 861.23), which may suggest a significant main effect of condition.</li>
<li>The participants in the false belief group had an average shorter looking time (M = 549.58, SD = 775.91) than the participants in the ignorance group (M = 749.58, SD = 861.23), which may suggest a significant main effect of condition.</li>
<li>The participants in the false belief group had an average longer looking time (M = 549.58, SD = 775.91) than the participants in the ignorance group (M = 749.58, SD = 861.23), which may suggest a significant main effect of sex.</li>
<li>The participants in the false belief group had an average shorter looking time (M = 549.58, SD = 775.91) than the participants in the ignorance group (M = 749.58, SD = 861.23), which may suggest a significant main effect of sex.</li>
</ol>
<div class="sourceCode" id="cb496"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">answer_t8</span> <span class="op">&lt;-</span> <span class="cn">NULL</span></span></code></pre></div>
</div>
<div id="Ch13AssignQueT9" class="section level3" number="13.10.10">
<h3>
<span class="header-section-number">13.10.10</span> Task 9: Running the Factorial ANOVA<a class="anchor" aria-label="anchor" href="#Ch13AssignQueT9"><i class="fas fa-link"></i></a>
</h3>
<p>Great, so we have looked at our descriptives and thought about what effects there might be. What we need to do now is run the ANOVA using the <code><a href="https://rdrr.io/pkg/afex/man/aov_car.html">aov_ez()</a></code> function. The ANOVA we are going to run is a two-way between-subjects ANOVA because both conditions are between-subjects variables. You may need to refer back to the chapter or to have a look at the help on <code><a href="https://rdrr.io/pkg/afex/man/aov_car.html">aov_ez()</a></code> to see how to add a second variable/factor.</p>
<ul>
<li>Replace the NULL in the <code>t9</code> code chunk below to run this two-way between-subjects ANOVA.
<ul>
<li>Look at the chapter or help for guidance. You need the data, the DV, the two between-subjects conditions, and the participant id.</li>
<li>Set the type to <code>type = 3</code>
</li>
<li>Do not <code><a href="https://generics.r-lib.org/reference/tidy.html">tidy()</a></code> the output. Do nothing to the output other than store it in the variable named <code>mod</code> (note: technically it will store as a list).</li>
<li>You will see in red in the output that the code will convert the conditions to factors automatically, and set the contrasts. This is fine.</li>
</ul>
</li>
</ul>
<div class="sourceCode" id="cb497"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">mod</span> <span class="op">&lt;-</span> <span class="cn">NULL</span></span></code></pre></div>
</div>
<div id="Ch13AssignQueT10" class="section level3" number="13.10.11">
<h3>
<span class="header-section-number">13.10.11</span> Task 10: Interpreting the ANOVA output Question<a class="anchor" aria-label="anchor" href="#Ch13AssignQueT10"><i class="fas fa-link"></i></a>
</h3>
<p>Thinking about the above information, one of the below statements is a good summary of the outcome ANOVA, but which one:</p>
<ul>
<li>In the <code>t10</code> code chunk below, replace the <code>NULL</code> with the number of the statement below that best summarises this analysis. Store this single value in <code>answer_t10</code>
</li>
</ul>
<ol style="list-style-type: decimal">
<li>There is a significant main effect of sex, but no main effect of condition and no interaction between condition and sex.</li>
<li>There is a significant main effect of condition, but no main effect of sex and no interaction between condition and sex.</li>
<li>There is no significant main effect of sex or condition and there is no significant interaction between condition and sex.</li>
<li>There is a significant main effect of sex, a significant main effect of condition, and a significant interaction between condition and sex.</li>
</ol>
<div class="sourceCode" id="cb498"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">answer_t10</span> <span class="op">&lt;-</span> <span class="cn">NULL</span></span></code></pre></div>
</div>
<div id="Ch13AssignQueT11" class="section level3" number="13.10.12">
<h3>
<span class="header-section-number">13.10.12</span> Task 11: Report your results<a class="anchor" aria-label="anchor" href="#Ch13AssignQueT11"><i class="fas fa-link"></i></a>
</h3>
<p>Write a paragraph reporting your findings.</p>
<p><span style="font-size: 22px; font-weight: bold; color: var(--blue);">Finished!</span></p>
<p>Well done! Check your answers against the solutions below.</p>
</div>
</div>
<div id="factorial-sols" class="section level2" number="13.11">
<h2>
<span class="header-section-number">13.11</span> Solutions to Activities<a class="anchor" aria-label="anchor" href="#factorial-sols"><i class="fas fa-link"></i></a>
</h2>
<div id="chapter-activities-1-9" class="section level3" number="13.11.1">
<h3>
<span class="header-section-number">13.11.1</span> Chapter Activities 1-9<a class="anchor" aria-label="anchor" href="#chapter-activities-1-9"><i class="fas fa-link"></i></a>
</h3>
<div id="factorial-a1sol" class="section level4" number="13.11.1.1">
<h4>
<span class="header-section-number">13.11.1.1</span> Activity 1<a class="anchor" aria-label="anchor" href="#factorial-a1sol"><i class="fas fa-link"></i></a>
</h4>
<div class="webex-solution">
<button>
Activity 1
</button>
<div class="sourceCode" id="cb499"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="st"><a href="https://github.com/heliosdrm/pwr">"pwr"</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="st"><a href="https://CRAN.R-project.org/package=rcompanion">"rcompanion"</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="st"><a href="https://r-forge.r-project.org/projects/car/">"car"</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="st"><a href="https://github.com/djnavarro/lsr">"lsr"</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="st"><a href="https://broom.tidymodels.org/">"broom"</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="st"><a href="https://afex.singmann.science/">"afex"</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="st"><a href="https://github.com/rvlenth/emmeans">"emmeans"</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="st"><a href="https://tidyverse.tidyverse.org">"tidyverse"</a></span><span class="op">)</span></span></code></pre></div>
</div>
<p>** Click tab to see solution **</p>
</div>
<div id="factorial-a2sol" class="section level4" number="13.11.1.2">
<h4>
<span class="header-section-number">13.11.1.2</span> Activity 2<a class="anchor" aria-label="anchor" href="#factorial-a2sol"><i class="fas fa-link"></i></a>
</h4>
<div class="webex-solution">
<button>
Solution
</button>
<div class="sourceCode" id="cb500"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">sum_dat_factorial</span><span class="op">&lt;-</span><span class="va">factorial</span><span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/group_by.html">group_by</a></span><span class="op">(</span><span class="va">Condition</span>, <span class="va">time</span><span class="op">)</span><span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarise</a></span><span class="op">(</span>mean <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">interest</span>, na.rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>,</span>
<span>            sd <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/sd.html">sd</a></span><span class="op">(</span><span class="va">interest</span>, na.rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span>
<span>            <span class="op">)</span></span></code></pre></div>
</div>
<p>** Click tab to see solution **</p>
</div>
<div id="factorial-a3sol" class="section level4" number="13.11.1.3">
<h4>
<span class="header-section-number">13.11.1.3</span> Activity 3<a class="anchor" aria-label="anchor" href="#factorial-a3sol"><i class="fas fa-link"></i></a>
</h4>
<div class="webex-solution">
<button>
Solution
</button>
<div class="sourceCode" id="cb501"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">factorial</span>, </span>
<span>       <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">time</span> , y <span class="op">=</span> <span class="va">interest</span>, fill <span class="op">=</span> <span class="va">Condition</span><span class="op">)</span><span class="op">)</span><span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_violin.html">geom_violin</a></span><span class="op">(</span>trim <span class="op">=</span> <span class="cn">FALSE</span>, </span>
<span>              alpha <span class="op">=</span> <span class="fl">.4</span><span class="op">)</span><span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_boxplot.html">geom_boxplot</a></span><span class="op">(</span>position <span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/position_dodge.html">position_dodge</a></span><span class="op">(</span><span class="fl">.9</span><span class="op">)</span>, </span>
<span>               width <span class="op">=</span> <span class="fl">.2</span>, </span>
<span>               alpha <span class="op">=</span> <span class="fl">.6</span><span class="op">)</span><span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_discrete.html">scale_x_discrete</a></span><span class="op">(</span>labels <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Time 1"</span>, <span class="st">"Time 2"</span><span class="op">)</span><span class="op">)</span><span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_viridis.html">scale_fill_viridis_d</a></span><span class="op">(</span>option <span class="op">=</span> <span class="st">"E"</span><span class="op">)</span><span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/stat_summary.html">stat_summary</a></span><span class="op">(</span>fun <span class="op">=</span> <span class="st">"mean"</span>, geom <span class="op">=</span> <span class="st">"point"</span>,</span>
<span>               position <span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/position_dodge.html">position_dodge</a></span><span class="op">(</span>width <span class="op">=</span> <span class="fl">0.9</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/stat_summary.html">stat_summary</a></span><span class="op">(</span>fun.data <span class="op">=</span> <span class="st">"mean_se"</span>, geom <span class="op">=</span> <span class="st">"errorbar"</span>, width <span class="op">=</span> <span class="fl">.1</span>,</span>
<span>               position <span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/position_dodge.html">position_dodge</a></span><span class="op">(</span>width <span class="op">=</span> <span class="fl">0.9</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_minimal</a></span><span class="op">(</span><span class="op">)</span></span></code></pre></div>
</div>
<p>** Click tab to see solution **</p>
</div>
<div id="factorial-a5sol" class="section level4" number="13.11.1.4">
<h4>
<span class="header-section-number">13.11.1.4</span> Activity 5<a class="anchor" aria-label="anchor" href="#factorial-a5sol"><i class="fas fa-link"></i></a>
</h4>
<div class="webex-solution">
<button>
Solution
</button>
<div class="sourceCode" id="cb502"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">mod_factorial</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/afex/man/aov_car.html">aov_ez</a></span><span class="op">(</span>id <span class="op">=</span> <span class="st">"subject"</span>,</span>
<span>               data <span class="op">=</span> <span class="va">factorial</span>, </span>
<span>               between <span class="op">=</span> <span class="st">"Condition"</span>, </span>
<span>               within <span class="op">=</span> <span class="st">"time"</span>,</span>
<span>               dv <span class="op">=</span> <span class="st">"interest"</span>, </span>
<span>               type <span class="op">=</span> <span class="fl">3</span><span class="op">)</span> </span>
<span><span class="va">factorial_output</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/anova.html">anova</a></span><span class="op">(</span><span class="va">mod_factorial</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="fu"><a href="https://generics.r-lib.org/reference/tidy.html">tidy</a></span><span class="op">(</span><span class="op">)</span></span>
<span><span class="co"># OR</span></span>
<span><span class="va">factorial_output</span> <span class="op">&lt;-</span> <span class="va">mod_factorial</span><span class="op">$</span><span class="va">anova_table</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="fu"><a href="https://generics.r-lib.org/reference/tidy.html">tidy</a></span><span class="op">(</span><span class="op">)</span></span></code></pre></div>
</div>
<p>** Click tab to see solution **</p>
</div>
<div id="factorial-a6sol" class="section level4" number="13.11.1.5">
<h4>
<span class="header-section-number">13.11.1.5</span> Activity 6<a class="anchor" aria-label="anchor" href="#factorial-a6sol"><i class="fas fa-link"></i></a>
</h4>
<div class="webex-solution">
<button>
Solution
</button>
<div class="sourceCode" id="cb503"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># normality testing</span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/car/man/qqPlot.html">qqPlot</a></span><span class="op">(</span><span class="va">mod_factorial</span><span class="op">$</span><span class="va">lm</span><span class="op">$</span><span class="va">residuals</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/stats/shapiro.test.html">shapiro.test</a></span><span class="op">(</span><span class="va">mod_factorial</span><span class="op">$</span><span class="va">lm</span><span class="op">$</span><span class="va">residuals</span><span class="op">)</span></span>
<span><span class="co"># levene's test</span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/afex/man/deprecated.html">test_levene</a></span><span class="op">(</span><span class="va">mod_factorial</span><span class="op">)</span></span></code></pre></div>
</div>
<p>** Click tab to see solution **</p>
</div>
</div>
<div id="practice-your-skills-activities" class="section level3" number="13.11.2">
<h3>
<span class="header-section-number">13.11.2</span> Practice Your Skills Activities<a class="anchor" aria-label="anchor" href="#practice-your-skills-activities"><i class="fas fa-link"></i></a>
</h3>
<div id="task-1a-libraries-1" class="section level4" number="13.11.2.1">
<h4>
<span class="header-section-number">13.11.2.1</span> Task 1A: Libraries<a class="anchor" aria-label="anchor" href="#task-1a-libraries-1"><i class="fas fa-link"></i></a>
</h4>
<div class="webex-solution">
<button>
Solution
</button>
<div class="sourceCode" id="cb504"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://afex.singmann.science/">afex</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://tidyverse.tidyverse.org">tidyverse</a></span><span class="op">)</span></span></code></pre></div>
</div>
<p>** Click tab to see solution **</p>
<p><a href="factorial-anova.html#Ch13AssignQueT1A">Return to Task</a></p>
</div>
<div id="task-1b-loading-in-the-data-1" class="section level4" number="13.11.2.2">
<h4>
<span class="header-section-number">13.11.2.2</span> Task 1B: Loading in the data<a class="anchor" aria-label="anchor" href="#task-1b-loading-in-the-data-1"><i class="fas fa-link"></i></a>
</h4>
<div class="webex-solution">
<button>
Solution
</button>
<div class="sourceCode" id="cb505"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">dat</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://readr.tidyverse.org/reference/read_delim.html">read_csv</a></span><span class="op">(</span><span class="st">"keysar_lin_barr_2003.csv"</span><span class="op">)</span></span></code></pre></div>
</div>
<p>** Click tab to see solution **</p>
<p><a href="factorial-anova.html#Ch13AssignQueT1B">Return to Task</a></p>
</div>
<div id="task-2-calculate-cell-means-for-the-cell-means." class="section level4" number="13.11.2.3">
<h4>
<span class="header-section-number">13.11.2.3</span> Task 2: Calculate cell means for the cell means.<a class="anchor" aria-label="anchor" href="#task-2-calculate-cell-means-for-the-cell-means."><i class="fas fa-link"></i></a>
</h4>
<div class="webex-solution">
<button>
Solution
</button>
<div class="sourceCode" id="cb506"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">cell_means</span> <span class="op">&lt;-</span> <span class="va">dat</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/group_by.html">group_by</a></span><span class="op">(</span><span class="va">sex</span>, <span class="va">condition</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarise</a></span><span class="op">(</span>m <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">looktime</span><span class="op">)</span>, sd <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/sd.html">sd</a></span><span class="op">(</span><span class="va">looktime</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<pre><code>## `summarise()` has grouped output by 'sex'. You can override using the `.groups`
## argument.</code></pre>
</div>
<p>** Click tab to see solution **</p>
<div class="inline-table"><table class="table table-sm">
<thead><tr class="header">
<th align="left">sex</th>
<th align="left">condition</th>
<th align="right">m</th>
<th align="right">sd</th>
</tr></thead>
<tbody>
<tr class="odd">
<td align="left">female</td>
<td align="left">false belief</td>
<td align="right">594.5833</td>
<td align="right">899.1660</td>
</tr>
<tr class="even">
<td align="left">female</td>
<td align="left">ignorance</td>
<td align="right">944.6970</td>
<td align="right">932.6990</td>
</tr>
<tr class="odd">
<td align="left">male</td>
<td align="left">false belief</td>
<td align="right">504.5833</td>
<td align="right">676.7338</td>
</tr>
<tr class="even">
<td align="left">male</td>
<td align="left">ignorance</td>
<td align="right">611.1111</td>
<td align="right">778.0212</td>
</tr>
</tbody>
</table></div>
<p><a href="factorial-anova.html#Ch13AssignQueT2">Return to Task</a></p>
</div>
<div id="task-3-marginal-means-for-sex" class="section level4" number="13.11.2.4">
<h4>
<span class="header-section-number">13.11.2.4</span> Task 3: Marginal means for sex<a class="anchor" aria-label="anchor" href="#task-3-marginal-means-for-sex"><i class="fas fa-link"></i></a>
</h4>
<div class="webex-solution">
<button>
Solution
</button>
<div class="sourceCode" id="cb508"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">marg_sex</span> <span class="op">&lt;-</span> <span class="va">dat</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/group_by.html">group_by</a></span><span class="op">(</span><span class="va">sex</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarise</a></span><span class="op">(</span>m <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">looktime</span><span class="op">)</span>, sd <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/sd.html">sd</a></span><span class="op">(</span><span class="va">looktime</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
</div>
<p>** Click tab to see solution **</p>
<div class="inline-table"><table class="table table-sm">
<thead><tr class="header">
<th align="left">sex</th>
<th align="right">m</th>
<th align="right">sd</th>
</tr></thead>
<tbody>
<tr class="odd">
<td align="left">female</td>
<td align="right">777.9762</td>
<td align="right">911.5331</td>
</tr>
<tr class="even">
<td align="left">male</td>
<td align="right">555.0439</td>
<td align="right">707.8138</td>
</tr>
</tbody>
</table></div>
<p><a href="factorial-anova.html#Ch13AssignQueT3">Return to Task</a></p>
</div>
<div id="task-4-marginal-means-for-condition" class="section level4" number="13.11.2.5">
<h4>
<span class="header-section-number">13.11.2.5</span> Task 4: Marginal means for condition<a class="anchor" aria-label="anchor" href="#task-4-marginal-means-for-condition"><i class="fas fa-link"></i></a>
</h4>
<div class="webex-solution">
<button>
Solution
</button>
<div class="sourceCode" id="cb509"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">marg_cond</span> <span class="op">&lt;-</span> <span class="va">dat</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/group_by.html">group_by</a></span><span class="op">(</span><span class="va">condition</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarise</a></span><span class="op">(</span>m <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">looktime</span><span class="op">)</span>, sd <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/sd.html">sd</a></span><span class="op">(</span><span class="va">looktime</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
</div>
<p>** Click tab to see solution **</p>
<div class="inline-table"><table class="table table-sm">
<thead><tr class="header">
<th align="left">condition</th>
<th align="right">m</th>
<th align="right">sd</th>
</tr></thead>
<tbody>
<tr class="odd">
<td align="left">false belief</td>
<td align="right">549.5833</td>
<td align="right">775.9108</td>
</tr>
<tr class="even">
<td align="left">ignorance</td>
<td align="right">794.5833</td>
<td align="right">861.2306</td>
</tr>
</tbody>
</table></div>
<p><a href="factorial-anova.html#Ch13AssignQueT4">Return to Task</a></p>
</div>
<div id="task-5-interaction-plot" class="section level4" number="13.11.2.6">
<h4>
<span class="header-section-number">13.11.2.6</span> Task 5: Interaction plot<a class="anchor" aria-label="anchor" href="#task-5-interaction-plot"><i class="fas fa-link"></i></a>
</h4>
<div class="webex-solution">
<button>
Solution
</button>
<div class="sourceCode" id="cb510"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">cell_means</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span><span class="va">condition</span>, <span class="va">m</span>, shape <span class="op">=</span> <span class="va">sex</span>, group <span class="op">=</span> <span class="va">sex</span>, color <span class="op">=</span> <span class="va">sex</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_path.html">geom_line</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span>size <span class="op">=</span> <span class="fl">3</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>y <span class="op">=</span> <span class="st">"mean looking time (msecs)"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_continuous.html">scale_y_continuous</a></span><span class="op">(</span>limits <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0</span>, <span class="fl">1000</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_bw</a></span><span class="op">(</span><span class="op">)</span></span></code></pre></div>
<div class="figure" style="text-align: center">
<img src="13-s02-lab13a_files/figure-html/t5_sol-1.png" alt="You should have produced a similar figure" width="100%"><p class="caption">
(#fig:t5_sol)You should have produced a similar figure
</p>
</div>
</div>
<p>** Click tab to see solution **</p>
<p><a href="factorial-anova.html#Ch13AssignQueT5">Return to Task</a></p>
</div>
<div id="task-6-recap-question-1" class="section level4" number="13.11.2.7">
<h4>
<span class="header-section-number">13.11.2.7</span> Task 6: Recap Question 1<a class="anchor" aria-label="anchor" href="#task-6-recap-question-1"><i class="fas fa-link"></i></a>
</h4>
<p>We want the alternative, not the null hypothesis here. So, an acceptable hypothesis for the interaction effect of sex and condition would be:</p>
<p><strong>We hypothesised that there would be a significant interaction between condition and sex of participant on egocentric interference (mean looking time (msecs)).</strong></p>
<p>As such the correct answer is:</p>
<div class="sourceCode" id="cb511"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">answer_t6</span> <span class="op">&lt;-</span> <span class="fl">3</span></span></code></pre></div>
<p><a href="factorial-anova.html#Ch13AssignQueT6">Return to Task</a></p>
</div>
<div id="task-7-recap-question-2" class="section level4" number="13.11.2.8">
<h4>
<span class="header-section-number">13.11.2.8</span> Task 7: Recap Question 2<a class="anchor" aria-label="anchor" href="#task-7-recap-question-2"><i class="fas fa-link"></i></a>
</h4>
<p>A good description of the marginal means for sex would be:</p>
<p><strong>The female participants have an average longer looking time (M = 777.98, SD = 911.53) than the male participants (M = 555.04, SD = 707.81) which may suggest a significant main effect of sex.</strong></p>
<p>As such the correct answer is:</p>
<div class="sourceCode" id="cb512"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">answer_t7</span> <span class="op">&lt;-</span> <span class="fl">1</span></span></code></pre></div>
<p><a href="factorial-anova.html#Ch13AssignQueT7">Return to Task</a></p>
</div>
<div id="task-8-recap-question-3" class="section level4" number="13.11.2.9">
<h4>
<span class="header-section-number">13.11.2.9</span> Task 8: Recap Question 3<a class="anchor" aria-label="anchor" href="#task-8-recap-question-3"><i class="fas fa-link"></i></a>
</h4>
<p>A good description of the marginal means for condition would be:</p>
<p><strong>The participants in the false belief group had an average shorter looking time (M = 549.58, SD = 775.91) than the participants in the ignorance group (M = 749.58, SD = 861.23), which may suggest a significant main effect of condition.</strong></p>
<p>As such the correct answer is:</p>
<div class="sourceCode" id="cb513"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">answer_t8</span> <span class="op">&lt;-</span> <span class="fl">2</span></span></code></pre></div>
<p><a href="factorial-anova.html#Ch13AssignQueT8">Return to Task</a></p>
</div>
<div id="task-9-running-the-factorial-anova" class="section level4" number="13.11.2.10">
<h4>
<span class="header-section-number">13.11.2.10</span> Task 9: Running the factorial ANOVA<a class="anchor" aria-label="anchor" href="#task-9-running-the-factorial-anova"><i class="fas fa-link"></i></a>
</h4>
<div class="webex-solution">
<button>
Solution
</button>
<div class="sourceCode" id="cb514"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">mod</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/afex/man/aov_car.html">aov_ez</a></span><span class="op">(</span>data <span class="op">=</span> <span class="va">dat</span>,</span>
<span>                   dv <span class="op">=</span> <span class="st">"looktime"</span>, </span>
<span>                   id <span class="op">=</span> <span class="st">"subject"</span>,</span>
<span>                   type <span class="op">=</span> <span class="fl">3</span>,</span>
<span>                   between <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"condition"</span>, <span class="st">"sex"</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
</div>
<p>** Click tab to see solution **</p>
<div class="sourceCode" id="cb515"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu">knitr</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/knitr/man/kable.html">kable</a></span><span class="op">(</span><span class="va">mod</span><span class="op">$</span><span class="va">anova_table</span><span class="op">)</span></span></code></pre></div>
<div class="inline-table"><table class="table table-sm">
<colgroup>
<col width="20%">
<col width="10%">
<col width="10%">
<col width="13%">
<col width="14%">
<col width="14%">
<col width="14%">
</colgroup>
<thead><tr class="header">
<th align="left"></th>
<th align="right">num Df</th>
<th align="right">den Df</th>
<th align="right">MSE</th>
<th align="right">F</th>
<th align="right">ges</th>
<th align="right">Pr(&gt;F)</th>
</tr></thead>
<tbody>
<tr class="odd">
<td align="left">condition</td>
<td align="right">1</td>
<td align="right">36</td>
<td align="right">692778.4</td>
<td align="right">0.7487009</td>
<td align="right">0.0203735</td>
<td align="right">0.3926176</td>
</tr>
<tr class="even">
<td align="left">sex</td>
<td align="right">1</td>
<td align="right">36</td>
<td align="right">692778.4</td>
<td align="right">0.6442294</td>
<td align="right">0.0175807</td>
<td align="right">0.4274507</td>
</tr>
<tr class="odd">
<td align="left">condition:sex</td>
<td align="right">1</td>
<td align="right">36</td>
<td align="right">692778.4</td>
<td align="right">0.2130405</td>
<td align="right">0.0058830</td>
<td align="right">0.6471716</td>
</tr>
</tbody>
</table></div>
<p><a href="factorial-anova.html#Ch13AssignQueT9">Return to Task</a></p>
</div>
<div id="task-10-interpreting-the-anova-output-question" class="section level4" number="13.11.2.11">
<h4>
<span class="header-section-number">13.11.2.11</span> Task 10: Interpreting the ANOVA output Question<a class="anchor" aria-label="anchor" href="#task-10-interpreting-the-anova-output-question"><i class="fas fa-link"></i></a>
</h4>
<p>A good summary of the outcome ANOVA would be:</p>
<p><strong>There is no significant main effect of sex or condition and there is no significant interaction between condition and sex.</strong></p>
<p>As such the correct answer is:</p>
<div class="sourceCode" id="cb516"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">answer_t10</span> <span class="op">&lt;-</span> <span class="fl">3</span></span></code></pre></div>
<p><a href="factorial-anova.html#Ch13AssignQueT10">Return to Task</a></p>
</div>
<div id="task-11-report-your-results" class="section level4" number="13.11.2.12">
<h4>
<span class="header-section-number">13.11.2.12</span> Task 11: Report your results<a class="anchor" aria-label="anchor" href="#task-11-report-your-results"><i class="fas fa-link"></i></a>
</h4>
<p>There is no definitive way to write this paragraph, but essentially your findings should report both main effects and the interaction, giving appropriate F outputs, e.g. F(1, 36) = .79, p = .38, and give some interpretation/qualification of the results using the means and standard deviations above, e.g. looking time was not significantly different between the false belief task (M = X, SD = XX) or the Ignorance task (M = XX, SD = XX). Something along the following would be appropriate:</p>
<p><strong>A two-way between-subjects factorial ANOVA was conducted testing the main effects and interaction between sex (male vs. female) and condition (false belief vs. ignorance) on the average looking time (msecs) on a matching task. Results revealed no significant interaction (F(1, 36) = .21, p = .647) suggesting that there is no modulation of condition by sex of participant in this looking task. Furthermore, there was no significant main effect of sex (F(1, 36) = .64, p = .429) suggesting that male (M = 555.04, SD = 707.81) and female participants (M = 777.98, SD = 911.53) perform similarly in this task. Finally, there was no significant main effect of condition (F(1, 36) = .79, p = .38) suggesting that whether participants were given a false belief scenario (M = 594.58, SD = 775.91) or an ignorance scenario (M = 794.58, SD = 861.23) had no overall impact on their performance.</strong></p>
<p><a href="factorial-anova.html#Ch13AssignQueT11">Return to Task</a></p>

</div>
</div>
</div>
</div>



<script>

/* update total correct if #webex-total_correct exists */
update_total_correct = function() {
  console.log("webex: update total_correct");

  if (t = document.getElementById("webex-total_correct")) {
    var correct = document.getElementsByClassName("webex-correct").length;
    var solvemes = document.getElementsByClassName("webex-solveme").length;
    var radiogroups = document.getElementsByClassName("webex-radiogroup").length;
    var selects = document.getElementsByClassName("webex-select").length;
    
    t.innerHTML = correct + " of " + (solvemes + radiogroups + selects) + " correct";
  }
}

/* webex-solution button toggling function */
b_func = function() {
  console.log("webex: toggle hide");
  
  var cl = this.parentElement.classList;
  if (cl.contains('open')) {
    cl.remove("open");
  } else {
    cl.add("open");
  }
}

/* function for checking solveme answers */
solveme_func = function(e) {
  console.log("webex: check solveme");

  var real_answers = JSON.parse(this.dataset.answer);
  var my_answer = this.value;
  var cl = this.classList;
  if (cl.contains("ignorecase")) {
    my_answer = my_answer.toLowerCase();
  }
  if (cl.contains("nospaces")) {
    my_answer = my_answer.replace(/ /g, "")
  }

  if (my_answer == "") {
    cl.remove("webex-correct");
    cl.remove("webex-incorrect");
  } else if (real_answers.includes(my_answer)) {
    cl.add("webex-correct");
    cl.remove("webex-incorrect");
  } else {
    cl.add("webex-incorrect");
    cl.remove("webex-correct");
  }

  // match numeric answers within a specified tolerance
  if(this.dataset.tol > 0){
    var tol = JSON.parse(this.dataset.tol);
    var matches = real_answers.map(x => Math.abs(x - my_answer) < tol)
    if (matches.reduce((a, b) => a + b, 0) > 0) {
      cl.add("webex-correct");
    } else {
      cl.remove("webex-correct");
    }
  }

  // added regex bit
  if (cl.contains("regex")){
    answer_regex = RegExp(real_answers.join("|"))
    if (answer_regex.test(my_answer)) {
      cl.add("webex-correct");
    }
  }

  update_total_correct();
}

/* function for checking select answers */
select_func = function(e) {
  console.log("webex: check select");
  
  var cl = this.classList
  
  /* add style */
  cl.remove("webex-incorrect");
  cl.remove("webex-correct");
  if (this.value == "answer") {
    cl.add("webex-correct");
  } else if (this.value != "blank") {
    cl.add("webex-incorrect");
  }
  
  update_total_correct();
}

/* function for checking radiogroups answers */
radiogroups_func = function(e) {
  console.log("webex: check radiogroups");

  var checked_button = document.querySelector('input[name=' + this.id + ']:checked');
  var cl = checked_button.parentElement.classList;
  var labels = checked_button.parentElement.parentElement.children;
  
  /* get rid of styles */
  for (i = 0; i < labels.length; i++) {
    labels[i].classList.remove("webex-incorrect");
    labels[i].classList.remove("webex-correct");
  }
  
  /* add style */
  if (checked_button.value == "answer") {
    cl.add("webex-correct");
  } else {
    cl.add("webex-incorrect");
  }
  
  update_total_correct();
}

window.onload = function() {
  console.log("onload");
  /* set up solution buttons */
  var buttons = document.getElementsByTagName("button");

  for (var i = 0; i < buttons.length; i++) {
    if (buttons[i].parentElement.classList.contains('webex-solution')) {
      buttons[i].onclick = b_func;
    }
  }

  /* set up webex-solveme inputs */
  var solveme = document.getElementsByClassName("webex-solveme");

  for (var i = 0; i < solveme.length; i++) {
    /* make sure input boxes don't auto-anything */
    solveme[i].setAttribute("autocomplete","off");
    solveme[i].setAttribute("autocorrect", "off");
    solveme[i].setAttribute("autocapitalize", "off");
    solveme[i].setAttribute("spellcheck", "false");
    solveme[i].value = "";

    /* adjust answer for ignorecase or nospaces */
    var cl = solveme[i].classList;
    var real_answer = solveme[i].dataset.answer;
    if (cl.contains("ignorecase")) {
      real_answer = real_answer.toLowerCase();
    }
    if (cl.contains("nospaces")) {
      real_answer = real_answer.replace(/ /g, "");
    }
    solveme[i].dataset.answer = real_answer;

    /* attach checking function */
    solveme[i].onkeyup = solveme_func;
    solveme[i].onchange = solveme_func;
  }
  
  /* set up radiogroups */
  var radiogroups = document.getElementsByClassName("webex-radiogroup");
  for (var i = 0; i < radiogroups.length; i++) {
    radiogroups[i].onchange = radiogroups_func;
  }
  
  /* set up selects */
  var selects = document.getElementsByClassName("webex-select");
  for (var i = 0; i < selects.length; i++) {
    selects[i].onchange = select_func;
  }

  update_total_correct();
}

</script><script>
$( document ).ready(function() {
  var cite = ' ';
  var psyteachr = ' <a href="https://psyteachr.github.io/"><img src="images/logos/psyteachr_logo.png" style="height: 31px; color: white;" alt="psyTeachR: Reproducible Research" /></a>';
  var license = ' <a rel="license" href="https://creativecommons.org/licenses/by-sa/4.0/" target="blank"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-sa/4.0/88x31.png"></a>';

  $("footer div.row div:eq(1) p").html(
    psyteachr + license + cite
  );
  
  // open rdrr links externally
  $("a[href^='https://rdrr.io']").click(function(){
    window.open(this.href);
    return false;
  });
  
  // visible second sidebar in mobile
  function move_sidebar() {
    var w = window.innerWidth;
    if (w < 992) {
      $("#toc").appendTo($("#main-nav"));
    } else {
      $("#toc").appendTo($("div.sidebar-chapter"));
    }
  }
  move_sidebar();
  window.onresize = move_sidebar;
});
</script><div class="chapter-nav">
<div class="prev"><a href="one-way-anova.html"><span class="header-section-number">12</span> One-way ANOVA</a></div>
<div class="next"><a href="acknowledgements.html">Acknowledgements</a></div>
</div></main><div class="col-md-3 col-lg-2 d-none d-md-block sidebar sidebar-chapter">
    <nav id="toc" data-toggle="toc" aria-label="On this page"><h2>On this page</h2>
      <ul class="nav navbar-nav">
<li><a class="nav-link" href="#factorial-anova"><span class="header-section-number">13</span> Factorial ANOVA</a></li>
<li><a class="nav-link" href="#factorial-a1"><span class="header-section-number">13.1</span> Activity 1: Set-up</a></li>
<li><a class="nav-link" href="#factorial-a2"><span class="header-section-number">13.2</span> Activity 2: Descriptive statistics</a></li>
<li><a class="nav-link" href="#factorial-a3"><span class="header-section-number">13.3</span> Activity 3: Violin-boxplots</a></li>
<li><a class="nav-link" href="#factorial-a4"><span class="header-section-number">13.4</span> Activity 4: Interaction plots</a></li>
<li><a class="nav-link" href="#factorial-a5"><span class="header-section-number">13.5</span> Activity 5: ANOVA</a></li>
<li><a class="nav-link" href="#factorial-a6"><span class="header-section-number">13.6</span> Activity 6: Assumption checking</a></li>
<li><a class="nav-link" href="#factorial-a7"><span class="header-section-number">13.7</span> Activity 7: Post-hoc tests</a></li>
<li><a class="nav-link" href="#factorial-a8"><span class="header-section-number">13.8</span> Activity 8: Write-up</a></li>
<li><a class="nav-link" href="#factorial-a9"><span class="header-section-number">13.9</span> Activity 9: Transforming data</a></li>
<li>
<a class="nav-link" href="#practice-your-skills-14"><span class="header-section-number">13.10</span> Practice Your Skills</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#Ch13AssignQueT1A"><span class="header-section-number">13.10.1</span> Task 1A: Libraries</a></li>
<li><a class="nav-link" href="#Ch13AssignQueT1B"><span class="header-section-number">13.10.2</span> Task 1B: Loading in the data</a></li>
<li><a class="nav-link" href="#Ch13AssignQueT2"><span class="header-section-number">13.10.3</span> Task 2: Calculate cell means</a></li>
<li><a class="nav-link" href="#Ch13AssignQueT3"><span class="header-section-number">13.10.4</span> Task 3: Marginal means for sex</a></li>
<li><a class="nav-link" href="#Ch13AssignQueT4"><span class="header-section-number">13.10.5</span> Task 4: Marginal means for condition</a></li>
<li><a class="nav-link" href="#Ch13AssignQueT5"><span class="header-section-number">13.10.6</span> Task 5: Interaction plot</a></li>
<li><a class="nav-link" href="#Ch13AssignQueT6"><span class="header-section-number">13.10.7</span> Task 6: Recap Question 1</a></li>
<li><a class="nav-link" href="#Ch13AssignQueT7"><span class="header-section-number">13.10.8</span> Task 7: Recap Question 2</a></li>
<li><a class="nav-link" href="#Ch13AssignQueT8"><span class="header-section-number">13.10.9</span> Task 8: Recap Question 3</a></li>
<li><a class="nav-link" href="#Ch13AssignQueT9"><span class="header-section-number">13.10.10</span> Task 9: Running the Factorial ANOVA</a></li>
<li><a class="nav-link" href="#Ch13AssignQueT10"><span class="header-section-number">13.10.11</span> Task 10: Interpreting the ANOVA output Question</a></li>
<li><a class="nav-link" href="#Ch13AssignQueT11"><span class="header-section-number">13.10.12</span> Task 11: Report your results</a></li>
</ul>
</li>
<li>
<a class="nav-link" href="#factorial-sols"><span class="header-section-number">13.11</span> Solutions to Activities</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#chapter-activities-1-9"><span class="header-section-number">13.11.1</span> Chapter Activities 1-9</a></li>
<li><a class="nav-link" href="#practice-your-skills-activities"><span class="header-section-number">13.11.2</span> Practice Your Skills Activities</a></li>
</ul>
</li>
</ul>

      <div class="book-extra">
        <ul class="list-unstyled">
<li><a id="book-source" href="https://github.com/psyteachr/analysis-v2/blob/master/book/13-s02-lab13a.Rmd">View source <i class="fab fa-github"></i></a></li>
          <li><a id="book-edit" href="https://github.com/psyteachr/analysis-v2/edit/master/book/13-s02-lab13a.Rmd">Edit this page <i class="fab fa-github"></i></a></li>
        </ul>
</div>
    </nav>
</div>

</div>
</div> <!-- .container -->

<footer class="bg-primary text-light mt-5"><div class="container"><div class="row">

  <div class="col-12 col-md-6 mt-3">
    <p>"<strong>Analysis</strong>" was written by Phil McAleer, Carolina E. Kuepper-Tetzel, Helena Paterson. It was last built on 2024-06-11.</p>
  </div>

  <div class="col-12 col-md-6 mt-3">
    <p>This book was built by the <a class="text-light" href="https://bookdown.org">bookdown</a> R package.</p>
  </div>

</div></div>
</footer><!-- dynamically load mathjax for compatibility with self-contained --><script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script><script type="text/x-mathjax-config">const popovers = document.querySelectorAll('a.footnote-ref[data-toggle="popover"]');
for (let popover of popovers) {
  const div = document.createElement('div');
  div.setAttribute('style', 'position: absolute; top: 0, left:0; width:0, height:0, overflow: hidden; visibility: hidden;');
  div.innerHTML = popover.getAttribute('data-content');

  var has_math = div.querySelector("span.math");
  if (has_math) {
    document.body.appendChild(div);
    MathJax.Hub.Queue(["Typeset", MathJax.Hub, div]);
    MathJax.Hub.Queue(function() {
      popover.setAttribute('data-content', div.innerHTML);
      document.body.removeChild(div);
    })
  }
}
</script>
</body>
</html>
