<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>Chapter 6 NHST: Two-Sample t-test | Analysis</title>
<meta name="author" content="Phil McAleer, Carolina E. Kuepper-Tetzel, Helena Paterson">
<meta name="description" content="6.1 Overview In the previous chapter we looked at the situation where you had gathered one sample of data (from one group of participants) and you compared that one group to a known value, e.g. a...">
<meta name="generator" content="bookdown 0.35 with bs4_book()">
<meta property="og:title" content="Chapter 6 NHST: Two-Sample t-test | Analysis">
<meta property="og:type" content="book">
<meta property="og:url" content="https://psyteachr.github.io/analysis-v2/nhst-two-sample-t-test.html">
<meta property="og:image" content="https://psyteachr.github.io/analysis-v2/images/logos/logo.png">
<meta property="og:description" content="6.1 Overview In the previous chapter we looked at the situation where you had gathered one sample of data (from one group of participants) and you compared that one group to a known value, e.g. a...">
<meta name="twitter:card" content="summary">
<meta name="twitter:title" content="Chapter 6 NHST: Two-Sample t-test | Analysis">
<meta name="twitter:description" content="6.1 Overview In the previous chapter we looked at the situation where you had gathered one sample of data (from one group of participants) and you compared that one group to a known value, e.g. a...">
<meta name="twitter:image" content="https://psyteachr.github.io/analysis-v2/images/logos/logo.png">
<!-- JS --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/fuse.js/6.4.6/fuse.js" integrity="sha512-zv6Ywkjyktsohkbp9bb45V6tEMoWhzFzXis+LrMehmJZZSys19Yxf1dopHx7WzIKxr5tK2dVcYmaCk2uqdjF4A==" crossorigin="anonymous"></script><script src="https://kit.fontawesome.com/6ecbd6c532.js" crossorigin="anonymous"></script><script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link href="libs/bootstrap-4.6.0/bootstrap.min.css" rel="stylesheet">
<script src="libs/bootstrap-4.6.0/bootstrap.bundle.min.js"></script><script src="libs/bs3compat-0.5.0/transition.js"></script><script src="libs/bs3compat-0.5.0/tabs.js"></script><script src="libs/bs3compat-0.5.0/bs3compat.js"></script><link href="libs/bs4_book-1.0.0/bs4_book.css" rel="stylesheet">
<script src="libs/bs4_book-1.0.0/bs4_book.js"></script><script src="libs/kePrint-0.0.1/kePrint.js"></script><link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet">
<!-- Global site tag (gtag.js) - Google Analytics --><script async src="https://www.googletagmanager.com/gtag/js?id=G-6NP3MF25W3"></script><script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'G-6NP3MF25W3');
    </script><script src="https://cdnjs.cloudflare.com/ajax/libs/autocomplete.js/0.38.0/autocomplete.jquery.min.js" integrity="sha512-GU9ayf+66Xx2TmpxqJpliWbT5PiGYxpaG8rfnBEk1LL8l1KGkRShhngwdXK1UgqhAzWpZHSiYPc09/NwDQIGyg==" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/mark.min.js" integrity="sha512-5CYOlHXGh6QpOFA/TeTylKLWfB3ftPsde7AnmhuitiTX4K5SqCLBeKro6sPS8ilsz1Q4NRx3v8Ko2IBiszzdww==" crossorigin="anonymous"></script><!-- CSS --><style type="text/css">
    
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  </style>
<style type="text/css">
    /* Used with Pandoc 2.11+ new --citeproc when CSL is used */
    div.csl-bib-body { }
    div.csl-entry {
      clear: both;
        }
    .hanging div.csl-entry {
      margin-left:2em;
      text-indent:-2em;
    }
    div.csl-left-margin {
      min-width:2em;
      float:left;
    }
    div.csl-right-inline {
      margin-left:2em;
      padding-left:1em;
    }
    div.csl-indent {
      margin-left: 2em;
    }
  </style>
<link rel="stylesheet" href="include/psyteachr.css">
<link rel="stylesheet" href="include/webex.css">
<link rel="stylesheet" href="include/style.css">
</head>
<body data-spy="scroll" data-target="#toc">

<div class="container-fluid">
<div class="row">
  <header class="col-sm-12 col-lg-3 sidebar sidebar-book"><a class="sr-only sr-only-focusable" href="#content">Skip to main content</a>

    <div class="d-flex align-items-start justify-content-between">
      <h1>
        <a href="index.html" title="">Analysis</a>
      </h1>
      <button class="btn btn-outline-primary d-lg-none ml-2 mt-1" type="button" data-toggle="collapse" data-target="#main-nav" aria-expanded="true" aria-controls="main-nav"><i class="fas fa-bars"></i><span class="sr-only">Show table of contents</span></button>
    </div>

    <div id="main-nav" class="collapse-lg">
      <form role="search">
        <input id="search" class="form-control" type="search" placeholder="Search" aria-label="Search">
</form>

      <nav aria-label="Table of contents"><h2>Table of contents</h2>
        <ul class="book-toc list-unstyled">
<li><a class="" href="index.html">Overview</a></li>
<li><a class="" href="starting-with-r-markdown.html"><span class="header-section-number">1</span> Starting with R Markdown</a></li>
<li><a class="" href="data-wrangling-a-key-skill.html"><span class="header-section-number">2</span> Data-Wrangling: A Key Skill</a></li>
<li><a class="" href="data-visualisation-through-ggplot2.html"><span class="header-section-number">3</span> Data Visualisation Through ggplot2</a></li>
<li><a class="" href="revisiting-probability-distributions.html"><span class="header-section-number">4</span> Revisiting Probability Distributions</a></li>
<li><a class="" href="nhst-binomial-test-and-one-sample-t-test.html"><span class="header-section-number">5</span> NHST: Binomial test and One-Sample t-test</a></li>
<li><a class="active" href="nhst-two-sample-t-test.html"><span class="header-section-number">6</span> NHST: Two-Sample t-test</a></li>
<li><a class="" href="nhst-paired-sample-t-test-and-nonparametric-tests.html"><span class="header-section-number">7</span> NHST: Paired-Sample t-test and Nonparametric tests</a></li>
<li><a class="" href="apes---alpha-power-effect-sizes-sample-size.html"><span class="header-section-number">8</span> APES - Alpha, Power, Effect Sizes, Sample Size</a></li>
<li><a class="" href="correlations.html"><span class="header-section-number">9</span> Correlations</a></li>
<li><a class="" href="simple-regression.html"><span class="header-section-number">10</span> Simple Regression</a></li>
<li><a class="" href="multiple-regression.html"><span class="header-section-number">11</span> Multiple Regression</a></li>
<li><a class="" href="one-way-anova.html"><span class="header-section-number">12</span> One-way ANOVA</a></li>
<li><a class="" href="factorial-anova.html"><span class="header-section-number">13</span> Factorial ANOVA</a></li>
<li class="book-part">Appendices</li>
<li><a class="" href="acknowledgements.html">Acknowledgements</a></li>
<li><a class="" href="installing-r.html"><span class="header-section-number">A</span> Installing R</a></li>
<li><a class="" href="updating-r-rstudio-and-packages.html"><span class="header-section-number">B</span> Updating R, RStudio, and packages</a></li>
<li><a class="" href="exporting-files-from-the-server.html"><span class="header-section-number">C</span> Exporting files from the server</a></li>
<li><a class="" href="symbols.html"><span class="header-section-number">D</span> Symbols</a></li>
<li><a class="" href="license.html">License</a></li>
<li><a class="" href="references.html">References</a></li>
</ul>

        <div class="book-extra">
          <p><a id="book-repo" href="https://github.com/psyteachr/analysis-v2">View book source <i class="fab fa-github"></i></a></p>
        </div>
      </nav>
</div>
  </header><main class="col-sm-12 col-md-9 col-lg-7" id="content"><div id="nhst-two-sample-t-test" class="section level1" number="6">
<h1>
<span class="header-section-number">6</span> NHST: Two-Sample t-test<a class="anchor" aria-label="anchor" href="#nhst-two-sample-t-test"><i class="fas fa-link"></i></a>
</h1>
<div id="overview-6" class="section level2" number="6.1">
<h2>
<span class="header-section-number">6.1</span> Overview<a class="anchor" aria-label="anchor" href="#overview-6"><i class="fas fa-link"></i></a>
</h2>
<p>In the previous chapter we looked at the situation where you had gathered one sample of data (from one group of participants) and you compared that one group to a known value, e.g. a standard value. An extension of this design is where you gather data from two samples. <strong>Two-sample</strong> designs are very common in Psychology as often we want to know whether there is a difference between groups on a particular variable. Today we will look at this scenario more closely through the <span class="math inline">\(t\)</span>-test analysis.</p>
<p><strong>Comparing the Means of Two Samples</strong></p>
<p>First thing to note is that there are different types of two-sample designs depending on whether or not the two groups are independent (e.g., different participants in different conditions) or not (e.g., same participants in different conditions). In today's chapter we will focus on <strong>independent samples</strong>, which typically means that the observations in the two groups are unrelated - usually meaning different people. In the next chapter, you will examine cases where the observations in the two groups are from pairs (<strong>paired samples</strong>) - most often the same people, but could also be a matched-pairs design.</p>
<!-- 
<div class='webex-solution'><button>Thinking Cap Point - All the different names for one thing!</button>
 -->
<!-- ```{block, type ="info"} -->
<!-- Here is a very brief summary: -->
<!-- * independent and between-subjects design typically mean the same thing - different participants in different conditions. -->
<!-- * within-subjects, dependent samples, paired samples, and repeated measures tend to mean the same participants in all conditions -->
<!-- * matched-pairs design means different people in different conditions but you have matched participants across the conditions so that they are effectively the same person (e.g. age, IQ, Social Economic Status, etc). These designs are analysed as though they were a within-subjects design. -->
<!-- * mixed design is when there is a combination of within-subjects and between-subjects designs in the one experiment. For example, say you are looking at attractiveness and dominance of male and female faces. Everyone might see both male and female faces (within) but half of the participants do ratings of attractiveness and half do ratings of trustworthiness (between).  -->
<!-- * The paper we are looking at in this InClass activity technically uses a mixed design at times but we will use the between-subjects element to show you how to run independent t-tests. -->
<!-- Spend some time when reading articles to really figure out the design they are using. -->
<!-- ``` -->
<!-- 
</div>
   -->
<!-- <br> -->
</div>
<div id="background-of-data-speech-as-indicator-of-intellect" class="section level2" number="6.2">
<h2>
<span class="header-section-number">6.2</span> Background of data: Speech as indicator of intellect<a class="anchor" aria-label="anchor" href="#background-of-data-speech-as-indicator-of-intellect"><i class="fas fa-link"></i></a>
</h2>
<p>For this lab we will be revisiting the data from Schroeder and Epley (2015), which you first encountered as part of the homework for Chapter 5. You can take a look at the Psychological Science article here:</p>
<p>Schroeder, J. and Epley, N. (2015). <a href="https://doi.org/10.1177/0956797615572906" target="_blank">The sound of intellect: Speech reveals a thoughtful mind, increasing a job candidate's appeal.</a> <em>Psychological Science, 26, 277--891</em>.</p>
<p>The abstract from this article explains more about the different experiments conducted (we will be specifically looking at the dataset from Experiment 4, courtesy of the <a href="https://sites.trinity.edu/osl/data-sets-and-activities/t-test-activities" target="_blank">Open Stats Lab</a>):</p>
<p>"<em>A person's mental capacities, such as intellect, cannot be observed directly and so are instead inferred from indirect cues. We predicted that a person's intellect would be conveyed most strongly through a cue closely tied to actual thinking: his or her voice. Hypothetical employers (Experiments 1-3b) and professional recruiters (Experiment 4) watched, listened to, or read job candidates' pitches about why they should be hired. These evaluators (the employers) rated a candidate as more competent, thoughtful, and intelligent when they heard a pitch rather than read it and, as a result, had a more favorable impression of the candidate and were more interested in hiring the candidate. Adding voice to written pitches, by having trained actors (Experiment 3a) or untrained adults (Experiment 3b) read them, produced the same results. Adding visual cues to audio pitches did not alter evaluations of the candidates. For conveying one's intellect, it is important that one's voice, quite literally, be heard.</em>"</p>
<p>To recap on Experiment 4, 39 professional recruiters from Fortune 500 companies evaluated job pitches of M.B.A. candidates (Masters in Business Administration) from the University of Chicago Booth School of Business. The methods and results appear on pages 887--889 of the article if you want to look at them specifically for more details. The original data, in <strong>wide</strong> format, can be found at the <a href="https://drive.google.com/open?id=0Bz-rhZ21ShvOei1MM24xNndnQ00" target="_blank">Open Stats Lab</a> website for later self-directed learning. Today however, we will be working with a modified version in "tidy" format which can be <a href="data/06-s01/inclass/ch6-inclass-data.zip">downloaded from here</a>. If you are unsure about tidy format, refer back to the activities of Chapter 2.</p>
</div>
<div id="the-two-sample-t-test" class="section level2" number="6.3">
<h2>
<span class="header-section-number">6.3</span> The Two-Sample t-test<a class="anchor" aria-label="anchor" href="#the-two-sample-t-test"><i class="fas fa-link"></i></a>
</h2>
<p>The overall goal today is to learn about running a <span class="math inline">\(t\)</span>-test on between-subjects data, as well as learning about analysing actual data along the way. As such, our task today is to reproduce a figure and the results from the article (p. 887-888). The two packages you will need are <code>tidyverse</code>, which we have used a lot, and <code>broom</code>, which is new to you, but will become your friend. One of the main functions we use in broom is <code><a href="https://generics.r-lib.org/reference/tidy.html">broom::tidy()</a></code> - this is an incredibly useful function that converts the output of an inferential test in R from a combination of text and lists, that are really hard to work with - technically called <code>objects</code> - into a tibble that you are very familiar with and that you can then use much more easily. We will show you how to use this function today and then ask you to use it over the coming chapters.</p>
<div id="Ch6InClassQueT1" class="section level3" number="6.3.1">
<h3>
<span class="header-section-number">6.3.1</span> Task 1: Evaluators<a class="anchor" aria-label="anchor" href="#Ch6InClassQueT1"><i class="fas fa-link"></i></a>
</h3>
<ol style="list-style-type: decimal">
<li>Open a new R Markdown file and use code to call <code>broom</code> and <code>tidyverse</code> into your library.</li>
</ol>
<p>Note: Order is important when calling multiple libraries - if two libraries have a function named the same thing, R will use the function from the library loaded in last. We recommend calling libraries in an order that <code>tidyverse</code> is called last as the functions in that library are used most often.</p>
<ol start="2" style="list-style-type: decimal">
<li><p>The file called <code>evaluators.csv</code> contains the demographics of the 39 raters. After downloading and unzipping the data, and of course setting the working directory, load in the information from this file and store it in a tibble called <code>evaluators</code>.</p></li>
<li>
<p>Now, use code to:</p>
<ol style="list-style-type: lower-roman">
<li>calculate the overall mean and standard deviation of the age of the evaluators.</li>
<li>count how many male and how many female evaluators were in the study.</li>
</ol>
</li>
</ol>
<p>Note: Probably easier doing this task in separate lines of code. There are NAs in the data so you will need to include a call to <code>na.rm = TRUE</code>.</p>
<div class="webex-solution">
<button>
Helpful Hint
</button>
<div class="info">
<ul>
<li>
Remember to load the libraries you need!
</li>
<li>
Also make sure you’ve downloaded and saved the data in the folder
you’re working from.
</li>
<li>
You can use <code><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarise()</a></code> and <code><a href="https://dplyr.tidyverse.org/reference/count.html">count()</a></code> or a
pipeline with <code><a href="https://dplyr.tidyverse.org/reference/group_by.html">group_by()</a></code> to complete this task.
</li>
<li>
When analysing the number of male and female evaluators, it isn’t
initially clear that ‘1’ represents males and ‘2’ represents
females.
</li>
<li>
We can use <code><a href="https://dplyr.tidyverse.org/reference/recode.html">recode()</a></code> to convert the numeric names to
indicate something more meaningful. Have a look at<code><a href="https://dplyr.tidyverse.org/reference/recode.html">?recode</a></code>
to see if you can work out how to use it. It’ll help to use
<code><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate()</a></code> to create a new variable to <code><a href="https://dplyr.tidyverse.org/reference/recode.html">recode()</a></code>
the numeric names for evaluators.
</li>
<li>
This website is also incredibly useful and one to save for anytime
you need to use recode():
<a href="https://debruine.github.io/posts/recode/" target="_blank">https://debruine.github.io/posts/recode/</a>
</li>
<li>
For your own analysis and future reproducible analyses, it’s a good
idea to make these representations clearer to others.
</li>
</ul>
</div>
</div>
<p><br></p>
<p><span style="font-size: 22px; font-weight: bold; color: var(--green);">Quickfire Questions</span></p>
<p>Fill in the below answers to check that your calculations are correct:</p>
<ul>
<li>What was the mean age of the evaluators in the study? Type in your answer to one decimal place: <input class="webex-solveme nospaces" size="4" data-answer='["30.9"]'>
</li>
<li>What was the standard deviation of the age of the evaluators in the study? Type in your answer to two decimal places: <input class="webex-solveme nospaces" size="4" data-answer='["6.24"]'>
</li>
<li>How many participants were noted as being female: <input class="webex-solveme nospaces" size="2" data-answer='["30"]'>
</li>
<li>How many participants were noted as being male: <input class="webex-solveme nospaces" size="1" data-answer='["4"]'>
</li>
</ul>
<p><span style="font-size: 22px; font-weight: bold; color: var(--pink);">Thinking Cap Point</span></p>
<p>The paper claims that the mean age of the evaluators was 30.85 years (SD = 6.24) and that there were 9 male and 30 female evaluators. Do you agree? Why might there be differences?</p>
<div class="webex-solution">
<button>
Explain This - Why is there a discrepancy?
</button>
<div class="info">
<p>
This paper claimed there were 9 males. However, looking at your
results you can see only 4 males, with 5 NA entries making up the rest
of the participant count. It looks like the NA and male entries have
been combined! That information might not be clear to a person
re-analysing the data.
</p>
<p>
This is why it’s important to have reproducible data analyses for
others to examine. Having another pair of eyes examining your data can
be very beneficial in spotting any discrepancies - this allows for
critical evaluation of analyses and results and improves the quality of
research being published. All the more reason to emphasize the
importance of conducting replication studies!
</p>
</div>
</div>
</div>
<div id="Ch6InClassQueT2" class="section level3" number="6.3.2">
<h3>
<span class="header-section-number">6.3.2</span> Task 2: Ratings<a class="anchor" aria-label="anchor" href="#Ch6InClassQueT2"><i class="fas fa-link"></i></a>
</h3>
<p>We are now going to calculate an overall <strong>intellect</strong> rating given by each evaluator. To break that down a bit, we are going to calculate how intellectual the evaluators (the raters) thought candidates were overall, depending on whether the evaluators <strong>read</strong> or <strong>listened</strong> to the candidates' resume pitches. This is calculated by averaging the ratings of <code>competent</code>, <code>thoughtful</code> and <code>intelligent</code> for each evaluator held within <code>ratings.csv</code>.</p>
<p>Note: We are not looking at ratings to individual candidates; we are looking at overall ratings for each evaluator. This is a bit confusing but makes sense if you stop to think about it a little. You can think about it in terms of "do raters rate differently depending on whether they read or listen to a resume pitch".</p>
<p>We will then combine the overall <strong>intellect</strong> rating with the overall <strong>impression</strong> ratings and overall <strong>hire</strong> ratings for each evaluator, all ready found in <code>ratings.csv</code>. In the end we will have a new tibble - let's call it <code>ratings2</code> - which has the below structure:</p>
<ul>
<li>eval_id shows the evaluator ID. Each evaluator has a different ID. So all the 1's are the same evaluator.</li>
<li>Category shows the scale that they were rating on - intellect, hire, impression</li>
<li>Rating shows the overall rating given by that evaluator on a given scale.</li>
<li>condition shows whether that evaluator listened to (e.g., evaluators 1, 2 and 3), or read (e.g., evaluator 4) the resume.</li>
</ul>
<div class="kable-table">
<div class="inline-table"><table class="table table-sm">
<thead><tr>
<th style="text-align:right;">
eval_id
</th>
<th style="text-align:left;">
Category
</th>
<th style="text-align:right;">
Rating
</th>
<th style="text-align:left;">
condition
</th>
</tr></thead>
<tbody>
<tr>
<td style="text-align:right;">
1
</td>
<td style="text-align:left;">
hire
</td>
<td style="text-align:right;">
6.000
</td>
<td style="text-align:left;">
listened
</td>
</tr>
<tr>
<td style="text-align:right;">
1
</td>
<td style="text-align:left;">
impression
</td>
<td style="text-align:right;">
7.000
</td>
<td style="text-align:left;">
listened
</td>
</tr>
<tr>
<td style="text-align:right;">
1
</td>
<td style="text-align:left;">
intellect
</td>
<td style="text-align:right;">
6.000
</td>
<td style="text-align:left;">
listened
</td>
</tr>
<tr>
<td style="text-align:right;">
2
</td>
<td style="text-align:left;">
hire
</td>
<td style="text-align:right;">
4.000
</td>
<td style="text-align:left;">
listened
</td>
</tr>
<tr>
<td style="text-align:right;">
2
</td>
<td style="text-align:left;">
impression
</td>
<td style="text-align:right;">
4.667
</td>
<td style="text-align:left;">
listened
</td>
</tr>
<tr>
<td style="text-align:right;">
2
</td>
<td style="text-align:left;">
intellect
</td>
<td style="text-align:right;">
5.667
</td>
<td style="text-align:left;">
listened
</td>
</tr>
<tr>
<td style="text-align:right;">
3
</td>
<td style="text-align:left;">
hire
</td>
<td style="text-align:right;">
5.000
</td>
<td style="text-align:left;">
listened
</td>
</tr>
<tr>
<td style="text-align:right;">
3
</td>
<td style="text-align:left;">
impression
</td>
<td style="text-align:right;">
8.333
</td>
<td style="text-align:left;">
listened
</td>
</tr>
<tr>
<td style="text-align:right;">
3
</td>
<td style="text-align:left;">
intellect
</td>
<td style="text-align:right;">
6.000
</td>
<td style="text-align:left;">
listened
</td>
</tr>
<tr>
<td style="text-align:right;">
4
</td>
<td style="text-align:left;">
hire
</td>
<td style="text-align:right;">
4.000
</td>
<td style="text-align:left;">
read
</td>
</tr>
<tr>
<td style="text-align:right;">
4
</td>
<td style="text-align:left;">
impression
</td>
<td style="text-align:right;">
4.667
</td>
<td style="text-align:left;">
read
</td>
</tr>
<tr>
<td style="text-align:right;">
4
</td>
<td style="text-align:left;">
intellect
</td>
<td style="text-align:right;">
3.333
</td>
<td style="text-align:left;">
read
</td>
</tr>
</tbody>
</table></div>
</div>
<p>The following steps describe how to create the above tibble, but you might want to have a bash yourself without reading them first. The trick when doing data analysis and data wrangling is to first think about what you want to achieve - the end goal - and then what function do I need to use. You know what you want to end up with - the above table - now how do you get there?</p>
<p>Steps 1-3 calculate the new <code>intellect</code> rating. Steps 4 + 5 combine this rating to all other information.</p>
<ol style="list-style-type: decimal">
<li><p>Load the data found in <code>ratings.csv</code> into a tibble called <code>ratings</code>.</p></li>
<li><p><code><a href="https://dplyr.tidyverse.org/reference/filter.html">filter()</a></code> only the relevant variables (<strong>thoughtful</strong>, <strong>competent</strong>, <strong>intelligent</strong>) into a new tibble (call it what you like - in the solutions we use <code>iratings</code>), and calculate a mean <code>Rating</code> for each evaluator.</p></li>
<li><p>Add on a new column called <code>Category</code> where every entry is the word <code>intellect</code>. This tells us that every number in this tibble is an intellect rating.</p></li>
<li><p>Now create a new tibble called <code>ratings2</code> and filter into it just the <strong>impression</strong> and <strong>hire</strong> ratings from the original <code>ratings</code> tibble. Next, bind this tibble with the tibble you created in step 3 to bring together the intellect, impression, and hire ratings, in <code>ratings2</code>.</p></li>
<li><p>Join <code>ratings2</code> with the <code>evaluator</code> tibble that we created in Task 1. Keep only the necessary columns as shown above and arrange by Evaluator and Category.</p></li>
</ol>
<p>Don't forget to use the hints below or the solution at the end of the Chapter if you are stuck. Take this one step at a time.</p>
<div class="webex-solution">
<button>
Helpful Hint
</button>
<div class="info">
<ol style="list-style-type: decimal">
<li>
<p>
Make sure you’ve downloaded and saved the data into the folder
you’re working from.
</p>
</li>
<li>
<p>
<code>filter(Category %in% c())</code> might work and then use
<code><a href="https://dplyr.tidyverse.org/reference/group_by.html">group_by()</a></code> and <code><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarize()</a></code> to calculate a mean
<code>Rating</code> for each evaluator.
</p>
</li>
<li>
<p>
Use <code><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate()</a></code> to create a new column.
</p>
</li>
<li>
<p>
<code><a href="https://dplyr.tidyverse.org/reference/bind_rows.html">bind_rows()</a></code> from Chapter 2 will help you to combine
these variables from two separate tibbles.
</p>
</li>
<li>
<p>
Use <code><a href="https://dplyr.tidyverse.org/reference/mutate-joins.html">inner_join()</a></code> with the common column in both
tibbles. <code><a href="https://dplyr.tidyverse.org/reference/select.html">select()</a></code> and <code><a href="https://dplyr.tidyverse.org/reference/arrange.html">arrange()</a></code> will help you
here, too.
</p>
</li>
</ol>
</div>
</div>
<p><br></p>
</div>
<div id="Ch6InClassQueT3" class="section level3" number="6.3.3">
<h3>
<span class="header-section-number">6.3.3</span> Task 3: Creating a Figure<a class="anchor" aria-label="anchor" href="#Ch6InClassQueT3"><i class="fas fa-link"></i></a>
</h3>
<p>To recap, we now have <code>ratings2</code> which contains an overall <code>Rating</code> score for each evaluator on the three <code>Category</code> (within: hire, impression, intellect) depending on which <code>condition</code> that evaluator was in (between: listened or read). Great! Now we have all the information we need to replicate Figure 7 in the article (page 888), shown here:</p>
<div class="figure" style="text-align: center">
<span style="display:block;" id="fig:img-lab6-figure7"></span>
<img src="images/s01-lab06/inclass/figure_7.png" alt="Figure 7 from Schroeder and Epley (2015) which you should try to replicate." width="50%"><p class="caption">
Figure 6.1: Figure 7 from Schroeder and Epley (2015) which you should try to replicate.
</p>
</div>
<p>Replace the <code>NULL</code>s below to create a very basic version of this figure.</p>
<div class="sourceCode" id="cb240"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">group_means</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/group_by.html">group_by</a></span><span class="op">(</span><span class="va">ratings2</span>, <span class="cn">NULL</span>, <span class="cn">NULL</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarise</a></span><span class="op">(</span>Rating <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">Rating</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">group_means</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span><span class="cn">NULL</span>, <span class="cn">NULL</span>, fill <span class="op">=</span> <span class="cn">NULL</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_bar.html">geom_col</a></span><span class="op">(</span>position <span class="op">=</span> <span class="st">"dodge"</span><span class="op">)</span></span></code></pre></div>
<p><span style="font-size: 22px; font-weight: bold; color: var(--pink);">Thinking Cap Point</span></p>
<p><strong>Improve Your Figure:</strong> How could you improve this plot. What other <code>geom_()</code> options could you try? Are bar charts that informative or would something else be better? How would you add or change the labels of your plot? Could you change the colours in your figure?</p>
<p>Next, have a look at the possible solution below to see a <strong>modern</strong> way of presenting this information. There are some new functions in this solution that you should play about with to understand what they do. Remember it is a layering system, so remove lines and see what happens. Note how in the solution the Figure shows the raw data points as well as the means in each condition; this gives a better impression of the true data as just showing the means can be misleading. You can continue your further exploration of visualisations by reading this paper later when you have a chance: <a href="https://doi.org/10.1371/journal.pbio.1002128" target="_blank">Weissberger et al., 2015, Beyond Bar and Line Graphs: Time for a New Data Presentation Paradigm</a></p>
<div class="webex-solution">
<button>
Solution and Possible Alternative
</button>
<p>Filling in the code as below will create a basic figure as shown:</p>
<div class="sourceCode" id="cb241"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">group_means</span> <span class="op">&lt;-</span> <span class="va">ratings2</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/group_by.html">group_by</a></span><span class="op">(</span><span class="va">condition</span>, <span class="va">Category</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarise</a></span><span class="op">(</span>Rating <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">Rating</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<pre><code>## `summarise()` has grouped output by 'condition'. You can override using the
## `.groups` argument.</code></pre>
<div class="sourceCode" id="cb243"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">group_means</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span><span class="va">Category</span>, <span class="va">Rating</span>, fill <span class="op">=</span> <span class="va">condition</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_bar.html">geom_col</a></span><span class="op">(</span>position <span class="op">=</span> <span class="st">"dodge"</span><span class="op">)</span></span></code></pre></div>
<div class="figure" style="text-align: center">
<span style="display:block;" id="fig:ch6-fig7-solution"></span>
<img src="06-s01-lab06a_files/figure-html/ch6-fig7-solution-1.png" alt="A basic solution to Figure 7" width="100%"><p class="caption">
Figure 6.2: A basic solution to Figure 7
</p>
</div>
<p>Or alternatively, for a more modern presentation of the data:</p>
<div class="sourceCode" id="cb244"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">group_means</span> <span class="op">&lt;-</span> <span class="va">ratings2</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/group_by.html">group_by</a></span><span class="op">(</span><span class="va">condition</span>, <span class="va">Category</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarise</a></span><span class="op">(</span>Rating <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">Rating</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<pre><code>## `summarise()` has grouped output by 'condition'. You can override using the
## `.groups` argument.</code></pre>
<div class="sourceCode" id="cb246"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">ratings2</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span><span class="va">condition</span>, <span class="va">Rating</span>, color <span class="op">=</span> <span class="va">condition</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_jitter.html">geom_jitter</a></span><span class="op">(</span>alpha <span class="op">=</span> <span class="fl">.4</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_violin.html">geom_violin</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>fill <span class="op">=</span> <span class="va">condition</span><span class="op">)</span>, alpha <span class="op">=</span> <span class="fl">.1</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/facet_wrap.html">facet_wrap</a></span><span class="op">(</span><span class="op">~</span><span class="va">Category</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span>data <span class="op">=</span> <span class="va">group_means</span>, size <span class="op">=</span> <span class="fl">2</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>x <span class="op">=</span> <span class="st">"Category"</span>, y <span class="op">=</span> <span class="st">"Recruiters' Evaluation of Candidates"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/coord_cartesian.html">coord_cartesian</a></span><span class="op">(</span>ylim <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0</span>, <span class="fl">10</span><span class="op">)</span>, expand <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/guides.html">guides</a></span><span class="op">(</span>color <span class="op">=</span> <span class="st">"none"</span>, fill <span class="op">=</span> <span class="st">"none"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_bw</a></span><span class="op">(</span><span class="op">)</span></span></code></pre></div>
<div class="figure" style="text-align: center">
<span style="display:block;" id="fig:ch6-fig7-possible"></span>
<img src="06-s01-lab06a_files/figure-html/ch6-fig7-possible-1.png" alt="A possible alternative to Figure 7" width="100%"><p class="caption">
Figure 6.3: A possible alternative to Figure 7
</p>
</div>
</div>
</div>
<div id="Ch6InClassQueT4" class="section level3" number="6.3.4">
<h3>
<span class="header-section-number">6.3.4</span> Task 4: t-tests<a class="anchor" aria-label="anchor" href="#Ch6InClassQueT4"><i class="fas fa-link"></i></a>
</h3>
<p>Brilliant! So far we have checked the descriptives and the visualisations, and the last thing now is to check the inferential tests; the t-tests. You should still have <code>ratings2</code> stored from Task 2. From this tibble, let's reproduce the <strong>t-test</strong> results from the article and at the same time show you how to run a t-test. You can refer back to the lectures to understand the maths of a <strong>between-subjects t-test</strong>, but essentially it is a measure between the difference in means over the variance about those means.</p>
<p>Here is a paragraph from the paper describing the results (p. 887):</p>
<p>"<em>The pattern of evaluations by professional recruiters replicated the pattern observed in Experiments 1 through 3b (see Fig. 7). In particular, the recruiters believed that the job candidates had greater intellect---were more competent, thoughtful, and intelligent---when they listened to pitches (M = 5.63, SD = 1.61) than when they read pitches (M = 3.65, SD = 1.91), t(37) = 3.53, p &lt; .01, 95% CI of the difference = [0.85, 3.13], d = 1.16. The recruiters also formed more positive impressions of the candidates---rated them as more likeable and had a more positive and less negative impression of them---when they listened to pitches (M = 5.97, SD = 1.92) than when they read pitches (M = 4.07, SD = 2.23), t(37) = 2.85, p &lt; .01, 95% CI of the difference = [0.55, 3.24], d = 0.94. Finally, they also reported being more likely to hire the candidates when they listened to pitches (M = 4.71, SD = 2.26) than when they read the same pitches (M = 2.89, SD = 2.06), t(37) = 2.62, p &lt; .01, 95% CI of the difference = [0.41, 3.24], d = 0.86.</em>"</p>
<p>We are going to run the t-tests for Intellect, Hire and Impression; each time comparing evaluators overall ratings for the listened group versus overall ratings for the read group to see if there was a significant difference between the two conditions: i.e., did the evaluators who <strong>listened</strong> to pitches give a significant higher or lower rating than evaluators that <strong>read</strong> pitches.</p>
<p>In terms of hypotheses, we could phrase the null hypothesis for these tests as there is no significant difference between overall ratings on the {insert trait} scale between evaluators who listened to resume pitches and evaluators who read the resume pitches (<span class="math inline">\(H_0: \mu_1 = \mu2\)</span>). Alternatively, we could state it as there will be a significant difference between overall ratings on the {insert trait} scale between evaluators who listened to resume pitches and evaluators who read the resume pitches (<span class="math inline">\(H_1: \mu_1 \ne \mu2\)</span>).</p>
<p>To clarify, we are going to run three between-subjects t-tests in total; one for intellect ratings; one for hire ratings; one for impression ratings. We will show you how to run the t-test on intellect ratings and then ask you to do the remaining two t-tests yourself.</p>
<p>To run this analysis on the intellect ratings you will need the function <code><a href="https://rdrr.io/r/stats/t.test.html">t.test()</a></code> and you will use <code><a href="https://generics.r-lib.org/reference/tidy.html">broom::tidy()</a></code> to pull out the results from each t-test into a tibble. Below, we show you how to create the group means and then run the t-test for intellect. Run these lines and have a look at what they do.</p>
<ol style="list-style-type: decimal">
<li>First we calculate the group means:</li>
</ol>
<div class="sourceCode" id="cb247"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">group_means</span> <span class="op">&lt;-</span> <span class="va">ratings2</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/group_by.html">group_by</a></span><span class="op">(</span><span class="va">condition</span>, <span class="va">Category</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarise</a></span><span class="op">(</span>m <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">Rating</span><span class="op">)</span>, sd <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/sd.html">sd</a></span><span class="op">(</span><span class="va">Rating</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<pre><code>## `summarise()` has grouped output by 'condition'. You can override using the
## `.groups` argument.</code></pre>
<ol start="2" style="list-style-type: decimal">
<li>And we can call them and look at them by typing:</li>
</ol>
<div class="sourceCode" id="cb249"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">group_means</span></span></code></pre></div>
<div class="kable-table">
<div class="inline-table"><table class="table table-sm">
<thead><tr>
<th style="text-align:left;">
condition
</th>
<th style="text-align:left;">
Category
</th>
<th style="text-align:right;">
m
</th>
<th style="text-align:right;">
sd
</th>
</tr></thead>
<tbody>
<tr>
<td style="text-align:left;">
listened
</td>
<td style="text-align:left;">
hire
</td>
<td style="text-align:right;">
4.714286
</td>
<td style="text-align:right;">
2.261479
</td>
</tr>
<tr>
<td style="text-align:left;">
listened
</td>
<td style="text-align:left;">
impression
</td>
<td style="text-align:right;">
5.968254
</td>
<td style="text-align:right;">
1.917477
</td>
</tr>
<tr>
<td style="text-align:left;">
listened
</td>
<td style="text-align:left;">
intellect
</td>
<td style="text-align:right;">
5.634921
</td>
<td style="text-align:right;">
1.608674
</td>
</tr>
<tr>
<td style="text-align:left;">
read
</td>
<td style="text-align:left;">
hire
</td>
<td style="text-align:right;">
2.888889
</td>
<td style="text-align:right;">
2.054805
</td>
</tr>
<tr>
<td style="text-align:left;">
read
</td>
<td style="text-align:left;">
impression
</td>
<td style="text-align:right;">
4.074074
</td>
<td style="text-align:right;">
2.233306
</td>
</tr>
<tr>
<td style="text-align:left;">
read
</td>
<td style="text-align:left;">
intellect
</td>
<td style="text-align:right;">
3.648148
</td>
<td style="text-align:right;">
1.911343
</td>
</tr>
</tbody>
</table></div>
</div>
<ol start="3" style="list-style-type: decimal">
<li>Now to just look at intellect ratings we need to filter them into a new tibble:</li>
</ol>
<div class="sourceCode" id="cb250"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">intellect</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">ratings2</span>, <span class="va">Category</span> <span class="op">==</span> <span class="st">"intellect"</span><span class="op">)</span></span></code></pre></div>
<ol start="4" style="list-style-type: decimal">
<li>And then we run the actual t-test and tidy it into a table.
<ul>
<li>
<code><a href="https://rdrr.io/r/stats/t.test.html">t.test()</a></code> requires two vectors as input</li>
<li>
<code><a href="https://dplyr.tidyverse.org/reference/pull.html">pull()</a></code> will pull out a single column from a tibble, e.g. Rating from intellect</li>
<li>
<code><a href="https://generics.r-lib.org/reference/tidy.html">tidy()</a></code> takes information from a test and turns it into a tibble. Try running the t.test with and without piping into <code><a href="https://generics.r-lib.org/reference/tidy.html">tidy()</a></code> to see what it does differently.</li>
</ul>
</li>
</ol>
<div class="sourceCode" id="cb251"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">intellect_t</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/t.test.html">t.test</a></span><span class="op">(</span><span class="va">intellect</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>                        <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">condition</span> <span class="op">==</span> <span class="st">"listened"</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>                        <span class="fu"><a href="https://dplyr.tidyverse.org/reference/pull.html">pull</a></span><span class="op">(</span><span class="va">Rating</span><span class="op">)</span>,</span>
<span>                      <span class="va">intellect</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>                        <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">condition</span> <span class="op">==</span> <span class="st">"read"</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>                        <span class="fu"><a href="https://dplyr.tidyverse.org/reference/pull.html">pull</a></span><span class="op">(</span><span class="va">Rating</span><span class="op">)</span>,</span>
<span>                      var.equal <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://generics.r-lib.org/reference/tidy.html">tidy</a></span><span class="op">(</span><span class="op">)</span></span></code></pre></div>
<p>Now lets look at the <code>intellect_t</code>tibble we have created (assuming you piped into <code><a href="https://generics.r-lib.org/reference/tidy.html">tidy()</a></code>):</p>
<div style="border: 0px;overflow-x: scroll; width:100%; ">
<div class="inline-table"><table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:ch6-task4-table">Table 6.1: </span>The t-test output of those in the intellect condition.
</caption>
<thead><tr>
<th style="text-align:right;">
estimate
</th>
<th style="text-align:right;">
estimate1
</th>
<th style="text-align:right;">
estimate2
</th>
<th style="text-align:right;">
statistic
</th>
<th style="text-align:right;">
p.value
</th>
<th style="text-align:right;">
parameter
</th>
<th style="text-align:right;">
conf.low
</th>
<th style="text-align:right;">
conf.high
</th>
<th style="text-align:left;">
method
</th>
<th style="text-align:left;">
alternative
</th>
</tr></thead>
<tbody><tr>
<td style="text-align:right;">
1.987
</td>
<td style="text-align:right;">
5.635
</td>
<td style="text-align:right;">
3.648
</td>
<td style="text-align:right;">
3.526
</td>
<td style="text-align:right;">
0.001
</td>
<td style="text-align:right;">
37
</td>
<td style="text-align:right;">
0.845
</td>
<td style="text-align:right;">
3.128
</td>
<td style="text-align:left;">
Two Sample t-test
</td>
<td style="text-align:left;">
two.sided
</td>
</tr></tbody>
</table></div>
</div>
<p><br></p>
<p>From the tibble, <code>intellect_t</code>, you can see that you ran a Two Sample t-test (meaning between-subjects) with a two-tailed hypothesis test ("two.sided"). The mean for the listened condition, <code>estimate1</code>, was 5.635, whilst the mean for the read condition, <code>estimate2</code> was 3.648 - compare these to the means in <code>group_means</code> as a sanity check. So overall there was a difference between the two means of 1.987. The degrees of freedom for the test, <code>parameter</code>, was 37. The observed t-value, <code>statistic</code>, was 3.526, and it was significant as the p-value, <code>p.value</code>, was p = 0.0011, which is lower than the field standard Type 1 error rate of <span class="math inline">\(\alpha = .05\)</span>.</p>
<p>As you will know from your lectures, a t-test is presented as t(df) = t-value, p = p-value. As such, this t-test would be written up as: t(37) = 3.526, p = 0.001.</p>
<p>Thinking about interpretation of this finding, as the effect was significant, we can reject the null hypothesis that there is no significant difference between mean ratings of those who listened to resumes and those who read the resumes, for intellect ratings. We can go further than that and say that the overall intellect ratings for those that listened to the resume was significantly higher (mean diff = 1.987) than those who read the resumes, t(37) = 3.526, p = 0.001, and as such we accept the alternative hypothesis. This would suggest that hearing people speak leads evaluators to rate the candidates as more intellectual than when you merely read the words they have written.</p>
<p><strong>Now Try:</strong></p>
<ol style="list-style-type: decimal">
<li><p>Running the remaining t-tests for <code>hire</code> and for <code>impression</code>. Store them in tibbles called <code>hire_t</code> and <code>impress_t</code> respectively.</p></li>
<li><p>Bind the rows of <code>intellect_t</code>, <code>hire_t</code> and <code>impress_t</code> to create a table of the three t-tests called <code>results</code>. It should look like this:</p></li>
</ol>
<div style="border: 0px;overflow-x: scroll; width:100%; ">
<div class="inline-table"><table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:lab6-task4-table2">Table 6.2: </span>Output of all three t-tests
</caption>
<thead><tr>
<th style="text-align:left;">
Category
</th>
<th style="text-align:right;">
estimate
</th>
<th style="text-align:right;">
estimate1
</th>
<th style="text-align:right;">
estimate2
</th>
<th style="text-align:right;">
statistic
</th>
<th style="text-align:right;">
p.value
</th>
<th style="text-align:right;">
parameter
</th>
<th style="text-align:right;">
conf.low
</th>
<th style="text-align:right;">
conf.high
</th>
<th style="text-align:left;">
method
</th>
<th style="text-align:left;">
alternative
</th>
</tr></thead>
<tbody>
<tr>
<td style="text-align:left;">
intellect
</td>
<td style="text-align:right;">
1.987
</td>
<td style="text-align:right;">
5.635
</td>
<td style="text-align:right;">
3.648
</td>
<td style="text-align:right;">
3.526
</td>
<td style="text-align:right;">
0.001
</td>
<td style="text-align:right;">
37
</td>
<td style="text-align:right;">
0.845
</td>
<td style="text-align:right;">
3.128
</td>
<td style="text-align:left;">
Two Sample t-test
</td>
<td style="text-align:left;">
two.sided
</td>
</tr>
<tr>
<td style="text-align:left;">
hire
</td>
<td style="text-align:right;">
1.825
</td>
<td style="text-align:right;">
4.714
</td>
<td style="text-align:right;">
2.889
</td>
<td style="text-align:right;">
2.620
</td>
<td style="text-align:right;">
0.013
</td>
<td style="text-align:right;">
37
</td>
<td style="text-align:right;">
0.414
</td>
<td style="text-align:right;">
3.237
</td>
<td style="text-align:left;">
Two Sample t-test
</td>
<td style="text-align:left;">
two.sided
</td>
</tr>
<tr>
<td style="text-align:left;">
impression
</td>
<td style="text-align:right;">
1.894
</td>
<td style="text-align:right;">
5.968
</td>
<td style="text-align:right;">
4.074
</td>
<td style="text-align:right;">
2.851
</td>
<td style="text-align:right;">
0.007
</td>
<td style="text-align:right;">
37
</td>
<td style="text-align:right;">
0.548
</td>
<td style="text-align:right;">
3.240
</td>
<td style="text-align:left;">
Two Sample t-test
</td>
<td style="text-align:left;">
two.sided
</td>
</tr>
</tbody>
</table></div>
</div>
<p><br></p>
<p><span style="font-size: 22px; font-weight: bold; color: var(--green);">Quickfire Questions</span></p>
<ul>
<li>
<p>Check your results for <code>hire</code>. Enter the mean estimates and t-test results (means and t-value to 2 decimal places, p-value to 3 decimal places):</p>
<ul>
<li><p>Mean <code>estimate1</code> (listened condition) = <input class="webex-solveme nospaces" size="4" data-answer='["4.71"]'></p></li>
<li><p>Mean <code>estimate2</code> (read condition) = <input class="webex-solveme nospaces" size="4" data-answer='["2.89"]'></p></li>
<li><p>t(<input class="webex-solveme nospaces" size="2" data-answer='["37"]'>) = <input class="webex-solveme nospaces" size="4" data-answer='["2.62"]'>, p = <input class="webex-solveme nospaces" size="5" data-answer='["0.013",".013"]'></p></li>
<li><p>Looking at this result, True or False, this result is significant at <span class="math inline">\(\alpha = .05\)</span>? <select class="webex-select"><option value="blank"></option>
<option value="answer">TRUE</option>
<option value="">FALSE</option></select></p></li>
</ul>
</li>
<li>
<p>Check your results for <code>impression</code>. Enter the mean estimates and t-test results (means and t-value to 2 decimal places, p-value to 3 decimal places):</p>
<ul>
<li><p>Mean<code>estimate1</code> (listened condition) = <input class="webex-solveme nospaces" size="4" data-answer='["5.97"]'></p></li>
<li><p>Mean <code>estimate2</code> (read condition) = <input class="webex-solveme nospaces" size="4" data-answer='["4.07"]'><br></p></li>
<li><p>t(<input class="webex-solveme nospaces" size="2" data-answer='["37"]'>) = <input class="webex-solveme nospaces" size="4" data-answer='["2.85"]'>, p = <input class="webex-solveme nospaces" size="5" data-answer='["0.007",".007"]'></p></li>
<li><p>Looking at this result, True or False, this result is significant at <span class="math inline">\(\alpha = .05\)</span>? <select class="webex-select"><option value="blank"></option>
<option value="answer">TRUE</option>
<option value="">FALSE</option></select></p></li>
</ul>
</li>
</ul>
<div class="webex-solution">
<button>
Helpful Hint
</button>
<div class="info">
<p>
Your t-test answers should have the following structure:
</p>
<p>
<code>t(degrees of freedom) = t-value, p = p-value</code>,
</p>
<p>
where:
</p>
<ul>
<li>
degrees of freedom = <code>parameter</code>,
</li>
<li>
t-value = <code>statistic</code>,
</li>
<li>
and p-value = <code>p.value</code>.
</li>
</ul>
<p>
Remember that if a result has a p-value lower (i.e. smaller) than or
equal to the alpha level then it is said to be significant.
</p>
</div>
</div>
<p><br></p>
<p>So to recap, we looked at the data from Schroeder and Epley (2015), both the descriptives and inferentials, we plotted a figure, and we confirmed that, as in the paper, there are significant differences in each of the three rating categories (hire, impression and intellect), with the listened condition receiving a higher rating than the read condition on each rating. All in, our interpretation would be that people rate you higher when they hear you speak your resume as opposed to them just reading your resume!</p>
<!-- Also, if you have more time, you might want to visit this website that will give you a better understanding of the relationship between the $t$ distribution and the normal distribution: <a href="https://gallery.shinyapps.io/tdist/" target = "_blank">gallery.shinyapps.io/tdist</a> -->

</div>
</div>
<div id="students-versus-welchs-t-tests" class="section level2" number="6.4">
<h2>
<span class="header-section-number">6.4</span> Student's versus Welch's t-tests<a class="anchor" aria-label="anchor" href="#students-versus-welchs-t-tests"><i class="fas fa-link"></i></a>
</h2>
<p>The between-subjects t-test comes in two versions: one assuming equal variance in the two groups (Student's t-test) and another not making this assumption (Welch's t-test). while the Student's t-test is considered the more common and standard t-test in the field, it is advisable to use the Welch's t-test instead.</p>
<p>The blog post <a href="https://daniellakens.blogspot.co.uk/2015/01/always-use-welchs-t-test-instead-of.html" target="_blank">"Always use Welch's t-test instead of Student's t-test"</a> by Daniel Lakens shows that if the groups have equal variance then both tests return the same finding. However, if the assumption of equal variance is violated, i.e. the groups have unequal variance, then Welch's test produces the more accurate finding, based on the data.</p>
<p>This is important as often the final decision on whether assumptions are "held" or "violated" is subjective; i.e. it is down to the researcher to fully decide. Nearly all data will show some level of unequal variance (with perfectly equal variance across multiple conditions actually once revealing fraudulent data). Researchers using the Student's t-test regularly have to make a judgement about whether the variance across the two groups is "equal enough". As such, this blog shows that it is always better to run a Welch's t-test to analyse a between-subjects design as a) Welch's t-test does not have the assumption of equal variance, b) Welch's t-test gives more accurate results when variance is not equal, and c) Welch's t-test performs exactly the same as the Student t-test when variance is equal across groups.</p>
<p>In short, Welch's t-test takes a level of ambiguity (or what may be called a "researcher degree of freedom") out of the analysis and makes the analysis less open to bias or subjectivity. As such, from now on, unless stated otherwise, you should run a Welch's t-test.</p>
<p>In practice it is very easy to run the Welch's t-test, and you can switch between the tests as shown:
* to run a Student's t-test you set <code>var.equal = TRUE</code>
* to run a Welch's t-test you set <code>var.equal = FALSE</code></p>
<p>This would run a Student's t-test:</p>
<div class="sourceCode" id="cb252"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/t.test.html">t.test</a></span><span class="op">(</span><span class="va">my_dv</span> <span class="op">~</span> <span class="va">my_iv</span>, data <span class="op">=</span> <span class="va">my_data</span>, var.equal <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span></code></pre></div>
<p>This would run the Welch's t-test:</p>
<div class="sourceCode" id="cb253"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/t.test.html">t.test</a></span><span class="op">(</span><span class="va">my_dv</span> <span class="op">~</span> <span class="va">my_iv</span>, data <span class="op">=</span> <span class="va">my_data</span>, var.equal <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></span></code></pre></div>
<p>And two ways to know that you have run the Welch's t-test are:</p>
<ol style="list-style-type: decimal">
<li>The output says you ran the <strong>Welch Two Sample t-test</strong>
</li>
<li>The df is likely to have decimal places in the Welch's t-test whereas it will be a whole number in the Student's t-test.</li>
</ol>
<p>Always run the Welch's t-test in a between-subjects design when using R!</p>

</div>
<div id="practice-your-skills-8" class="section level2" number="6.5">
<h2>
<span class="header-section-number">6.5</span> Practice Your Skills<a class="anchor" aria-label="anchor" href="#practice-your-skills-8"><i class="fas fa-link"></i></a>
</h2>
<div id="single-dose-testosterone-administration-impairs-cognitive-reflection-in-men." class="section level3" number="6.5.1">
<h3>
<span class="header-section-number">6.5.1</span> Single-dose testosterone administration impairs cognitive reflection in men.<a class="anchor" aria-label="anchor" href="#single-dose-testosterone-administration-impairs-cognitive-reflection-in-men."><i class="fas fa-link"></i></a>
</h3>
<p>In order to complete this exercise, you first have to download the assignment .Rmd file which you need to edit for this assignment: titled <code>GUID_Ch6_PracticeYourSkills.Rmd</code>. This can be downloaded within a zip file from the link below. Once downloaded and unzipped you should create a new folder that you will use as your working directory; put the .Rmd file in that folder and set your working directory to that folder through the drop-down menus at the top. <a href="data/06-s01/homework/ch6-practiceskills.zip">Download the Assignment .zip file from here</a>.</p>
<p>For this assignment we will be using real data from the following paper:</p>
<p>Nave, G., Nadler, A., Zava, D., and Camerer, C. (2017). <a href="http://journals.sagepub.com/doi/suppl/10.1177/0956797617709592" target="_blank">Single-dose testosterone administration impairs cognitive reflection in men.</a> <em>Psychological Science</em>, <em>28</em>, 1398--1407.</p>
<p>The full data documentation can be found on the <a href="https://osf.io/kzxsh/" target="_blank">Open Science Framework repository</a>, but for this assignment we will just use the <code>.csv</code> file in the zipped folder: <strong>CRT_Data.csv</strong>. You may also want to read the paper, at least in part, to help fully understand this analysis if at times you are unsure. Here is the article's abstract:</p>
<p><em>In nonhumans, the sex steroid testosterone regulates reproductive behaviors such as fighting between males and mating. In humans, correlational studies have linked testosterone with aggression and disorders associated with poor impulse control, but the neuropsychological processes at work are poorly understood. Building on a dual-process framework, we propose a mechanism underlying testosterone's behavioral effects in humans: reduction in cognitive reflection. In the largest study of behavioral effects of testosterone administration to date, 243 men received either testosterone or placebo and took the Cognitive Reflection Test (CRT), which estimates the capacity to override incorrect intuitive judgments with deliberate correct responses. Testosterone administration reduced CRT scores. The effect remained after we controlled for age, mood, math skills, whether participants believed they had received the placebo or testosterone, and the effects of 14 additional hormones, and it held for each of the CRT questions in isolation. Our findings suggest a mechanism underlying testosterone's diverse effects on humans' judgments and decision making and provide novel, clear, and testable predictions.</em></p>
<p>The critical findings are presented on p. 1403 of the paper under the heading "The influence of testosterone on CRT performance". Your task today is to attempt to try and reproduce some of the main results from the paper.</p>
<p>Note: Being unable to get the exact same results as the authors doesn't necessarily mean you are wrong! The authors might be wrong, or might have left out important details. Present what you find.</p>
<p><strong>Before starting lets check:</strong></p>
<ol style="list-style-type: decimal">
<li><p>The <code>.csv</code> file is saved into a folder on your computer and you have manually set this folder as your working directory.</p></li>
<li><p>The <code>.Rmd</code> file is saved in the same folder as the <code>.csv</code> files. For assessments we ask that you save it with the format <code>GUID_Ch6_PracticeYourSkills.Rmd</code> where <code>GUID</code> is replaced with your <code>GUID</code>. Though this is a formative assessment, it may be good practice to do the same here.</p></li>
</ol>
</div>
<div id="Ch6AssignQueT1A" class="section level3" number="6.5.2">
<h3>
<span class="header-section-number">6.5.2</span> Task 1A: Libraries<a class="anchor" aria-label="anchor" href="#Ch6AssignQueT1A"><i class="fas fa-link"></i></a>
</h3>
<ul>
<li>In today's exercise you will need both the <code>tidyverse</code> and <code>broom</code> packages. Enter code into the t1A code chunk below to load in both of these libraries.</li>
</ul>
<div class="sourceCode" id="cb254"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co">## load in the tidyverse and broom packages</span></span></code></pre></div>
</div>
<div id="Ch6AssignQueT1B" class="section level3" number="6.5.3">
<h3>
<span class="header-section-number">6.5.3</span> Task 1B: Loading in the data<a class="anchor" aria-label="anchor" href="#Ch6AssignQueT1B"><i class="fas fa-link"></i></a>
</h3>
<ul>
<li>Use <code><a href="https://readr.tidyverse.org/reference/read_delim.html">read_csv()</a></code> to replace the <code>NULL</code> in the t1B code chunk below to load in the data stored in the data file <code>CRT_Data.csv</code>. Store the data in the variable <code>crt</code>. Do not change the file name of the data file.</li>
</ul>
<div class="sourceCode" id="cb255"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">crt</span> <span class="op">&lt;-</span> <span class="cn">NULL</span></span></code></pre></div>
</div>
<div id="Ch6AssignQueT2" class="section level3" number="6.5.4">
<h3>
<span class="header-section-number">6.5.4</span> Task 2: Selecting only relevant columns<a class="anchor" aria-label="anchor" href="#Ch6AssignQueT2"><i class="fas fa-link"></i></a>
</h3>
<p>Have a look at <code>crt</code>. There are three variables in <code>crt</code> that you will need to find and extract in order to perform the t-test: the subject ID number (<em>hint</em>: each participant has a unique number); the independent variable (<em>hint</em>: each participant has the possibility of being in one of two treatments coded as 1 or 0); and the dependent variable (<em>hint</em>: the test specifically looks at which <em>answers people get correct</em>). Identify those three variables. It might help to look at the first few sentences under the heading "The influence of testosterone on CRT performance" and Figure 2a in the paper for further guidance on the correct variables.</p>
<ul>
<li>Having identified the important three columns, replace the <code>NULL</code> in the t2 code chunk below to select out only those three columns from <code>crt</code> and store them in the tibble <code>crt2</code>.</li>
</ul>
<p><strong>Check your work:</strong> If correct, <code>crt2</code> should be a tibble with 3 columns and 243 rows.</p>
<div class="sourceCode" id="cb256"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">crt2</span> <span class="op">&lt;-</span> <span class="cn">NULL</span></span></code></pre></div>
<p>Note: For the remainder of this assignment you should use <code>crt2</code> as the main source tibble and not <code>crt</code>.</p>
</div>
<div id="Ch6AssignQueT3" class="section level3" number="6.5.5">
<h3>
<span class="header-section-number">6.5.5</span> Task 3: Verify the number of subjects in each group<a class="anchor" aria-label="anchor" href="#Ch6AssignQueT3"><i class="fas fa-link"></i></a>
</h3>
<p>The Participants section of the article contains the following statement:</p>
<p><em>243 men (mostly college students; for demographic details, see Table S1 in the Supplemental Material available online) were randomly administered a topical gel containing either testosterone (n = 125) or placebo (n = 118).</em></p>
<p>In the t3 code block below, replace the <code>NULLs</code> with lines of code to calculate:</p>
<ol style="list-style-type: decimal">
<li><p>The number of men in each Treatment. This should be a tibble called <code>cond_counts</code> containing a column called <code>Treatment</code> showing the two groups and a column called <code>n</code> which shows the number of men in each group.</p></li>
<li><p>The total number of men in the sample. This should be a single value, not a tibble, and should be stored in <code>n_men</code>.</p></li>
</ol>
<p>You know the answer to both of these tasks already. Make sure that your code gives the correct answer!</p>
<div class="sourceCode" id="cb257"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">cond_counts</span> <span class="op">&lt;-</span> <span class="cn">NULL</span></span>
<span><span class="va">n_men</span> <span class="op">&lt;-</span> <span class="cn">NULL</span></span></code></pre></div>
<ul>
<li>Now replace the strings in the statements below, using inline R code, so that it reproduces the sentence from the paper exactly as it is shown above. In other words, in the statement below, anywhere it says <code>"(your code here)"</code>, replace that string (including the quotes), with inline R code. To clarify, when looking at the .Rmd file you should see R code, but when looking at the knitted file, you should see values. Look back at Chapter 1 if you are unsure of how to use inline code.</li>
</ul>
<p><em>Hint:</em> One solution is to do something with <code>cond_counts</code> similar to what we did with <code><a href="https://dplyr.tidyverse.org/reference/filter.html">filter()</a></code> and <code><a href="https://dplyr.tidyverse.org/reference/pull.html">pull()</a></code> in the exercises of this Chapter.</p>
<p><em><code>"(your code here)"</code> men (mostly college students; for demographic details, see Table S1 in the Supplemental Material available online) were randomly administered a topical gel containing either testosterone (n = <code>"(your code here)"</code>) or placebo (n = <code>"(your code here)"</code>).</em></p>
</div>
<div id="Ch6AssignQueT4" class="section level3" number="6.5.6">
<h3>
<span class="header-section-number">6.5.6</span> Task 4: Reproduce Figure 2a<a class="anchor" aria-label="anchor" href="#Ch6AssignQueT4"><i class="fas fa-link"></i></a>
</h3>
<p>Here is Figure 2A from the original paper:</p>
<div class="figure" style="text-align: center">
<span style="display:block;" id="fig:img-lab6-figure2a"></span>
<img src="images/s01-lab06/homework/figure_2a.png" alt="Figure 2A from Nave, Nadler, Zava, and Camerer (2017) which you should replicate" width="50%"><p class="caption">
Figure 6.4: Figure 2A from Nave, Nadler, Zava, and Camerer (2017) which you should replicate
</p>
</div>
<ul>
<li>Write code in the t4 code chunk to reproduce a version of Figure 2a - shown above. Before you create the plot, replace the <code>NULL</code> to make a tibble called <code>crt_means</code> with the mean and standard deviation of the number of <code>CorrectAnswers</code> for each group.</li>
<li>Use <code>crt_means</code> as the source data for the plot.</li>
</ul>
<p><strong>Hint:</strong> you will need to check out <code><a href="https://dplyr.tidyverse.org/reference/recode.html">recode()</a></code> to get the labels of treatments right. <a href="https://psyteachr.github.io/analysis-v2/data-wrangling-a-key-skill.html?q=recode#Ch2PreClassQueT4" target="_blank">Look back at Chapter 2 for a hint on how to use <code>recode()</code>.</a> Or check this short resource for examples on how to use <code><a href="https://dplyr.tidyverse.org/reference/recode.html">recode()</a></code>: <a href="https://debruine.github.io/post/recode/" target="_blank">Recode short tutorial.</a></p>
<p>Don't worry about including the error bars (unless you want to) or the line indicating significance in the plot. Do however make sure to pay attention to the labels of treatments and of the y-axis scale and label. Reposition the x-axis label to below the Figure. You can use colour, if you like.</p>
<div class="sourceCode" id="cb258"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">crt_means</span> <span class="op">&lt;-</span> <span class="cn">NULL</span></span>
<span></span>
<span><span class="co">## TODO: add lines of code using ggplot</span></span></code></pre></div>
</div>
<div id="Ch6AssignQueT5" class="section level3" number="6.5.7">
<h3>
<span class="header-section-number">6.5.7</span> Task 5: Interpreting your Figure<a class="anchor" aria-label="anchor" href="#Ch6AssignQueT5"><i class="fas fa-link"></i></a>
</h3>
<p>Always good to do a slight recap at this point to make sure you are following the analysis. Replace the <code>NULL</code> in the t5 code chunk below with the number of the statement that best describes the data you have calculated and plotted thus far. Store this single value in <code>answer_t5</code>:</p>
<ol style="list-style-type: decimal">
<li><p>The Testosterone group (M = 2.10, SD = 1.02) would appear to have fewer correct answers on average than the Placebo group (M = 1.66, SD = 1.18) on the Cognitive Reflection Test suggesting that testosterone does in fact inhibit the ability to override incorrect intuitive judgments with the correct response.</p></li>
<li><p>The Testosterone group (M = 1.66, SD = 1.18) would appear to have more correct answers on average than the Placebo group (M = 2.10, SD = 1.02) on the Cognitive Reflection Test suggesting that testosterone does in fact inhibit the ability to override incorrect intuitive judgments with the correct response.</p></li>
<li><p>The Testosterone group (M = 1.66, SD = 1.18) would appear to have fewer correct answers on average than the Placebo group (M = 2.10, SD = 1.02) on the Cognitive Reflection Test suggesting that testosterone does in fact inhibit the ability to override incorrect intuitive judgments with the correct response.</p></li>
<li><p>The Testosterone group (M = 2.10, SD = 1.02) would appear to have more correct answers on average than the Placebo group (M = 1.66, SD = 1.18) on the Cognitive Reflection Test suggesting that testosterone does in fact inhibit the ability to override incorrect intuitive judgments with the correct response.</p></li>
</ol>
<div class="sourceCode" id="cb259"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">answer_t5</span> <span class="op">&lt;-</span> <span class="cn">NULL</span></span></code></pre></div>
</div>
<div id="Ch6AssignQueT6" class="section level3" number="6.5.8">
<h3>
<span class="header-section-number">6.5.8</span> Task 6: t-test<a class="anchor" aria-label="anchor" href="#Ch6AssignQueT6"><i class="fas fa-link"></i></a>
</h3>
<p>Now that we have calculated the descriptives in our study we need to run the inferentials. In the t6 code chunk below, replace the <code>NULL</code> with a line of code to run the t-test taking care to make sure that the output table has the Placebo mean under Estimate1 (group 0) and Testosterone mean under Estimate2 (group 1). Assume variance is equal and use <code><a href="https://generics.r-lib.org/reference/tidy.html">broom::tidy()</a></code> to sweep and store the results into a tibble called <code>t_table</code>.</p>
<div class="sourceCode" id="cb260"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">t_table</span> <span class="op">&lt;-</span> <span class="cn">NULL</span></span></code></pre></div>
</div>
<div id="Ch6AssignQueT7" class="section level3" number="6.5.9">
<h3>
<span class="header-section-number">6.5.9</span> Task 7: Reporting results<a class="anchor" aria-label="anchor" href="#Ch6AssignQueT7"><i class="fas fa-link"></i></a>
</h3>
<p>In the t7A code chunk below, replace the <code>NULL</code> with a line of code to pull out the df from t_table. This must be a single value stored in <code>t_df</code>.</p>
<div class="sourceCode" id="cb261"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">t_df</span> <span class="op">&lt;-</span> <span class="cn">NULL</span></span></code></pre></div>
<p>In the t7B code chunk below, replace the <code>NULL</code> with a line of code to pull out the t-value from t_table. Round it to three decimal places. This must be a single value stored in <code>t_value</code>.</p>
<div class="sourceCode" id="cb262"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">t_value</span> <span class="op">&lt;-</span> <span class="cn">NULL</span></span></code></pre></div>
<p>In the t7C code chunk below, replace the <code>NULL</code> with a line of code to pull out the p-value from t_table. Round it to three decimal places. This must be a single value stored in <code>p_value</code>.</p>
<div class="sourceCode" id="cb263"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">p_value</span> <span class="op">&lt;-</span> <span class="cn">NULL</span></span></code></pre></div>
<p>In the t7D code chunk below, replace the <code>NULL</code> with a line of code to calculate the absolute difference between the mean number of correct answers for the Testosterone group and the Placebo group. Round it to three decimal places. This must be a single value stored in <code>t_diff</code>.</p>
<div class="sourceCode" id="cb264"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">t_diff</span> <span class="op">&lt;-</span> <span class="cn">NULL</span></span></code></pre></div>
<p>If you have completed t7A to t7D accurately, then when knitted, one of these statements below will produce an accurate and coherent summary of the results. In the t7E code chunk below, replace the <code>NULL</code> with the number of the statement below that best summarises the data in this study. Store this single value in <code>answer_t7e</code></p>
<ol style="list-style-type: decimal">
<li>The testosterone group performed significantly better ( fewer correct answers) than the placebo group, t() = , p = .</li>
<li>The testosterone group performed significantly worse ( fewer correct answers) than the placebo group, t() = , p = .</li>
<li>The testosterone group performed significantly better ( more correct answers) than the placebo group, t() = , p = .</li>
<li>The testosterone group performed significantly worse ( fewer correct answers) than the placebo group, t() = , p = .</li>
</ol>
<div class="sourceCode" id="cb265"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">answer_t7e</span> <span class="op">&lt;-</span> <span class="cn">NULL</span></span></code></pre></div>
<p>Well done, you are finished! Now you should go check your answers against the solutions at the end of this chapter. You are looking to check that the resulting output from the answers that you have submitted are exactly the same as the output in the solution - for example, remember that a single value is not the same as a coded answer. Where there are alternative answers, it means that you could have submitted any one of the options as they should all return the same answer.</p>

</div>
</div>
<div id="solutions-to-questions-5" class="section level2" number="6.6">
<h2>
<span class="header-section-number">6.6</span> Solutions to Questions<a class="anchor" aria-label="anchor" href="#solutions-to-questions-5"><i class="fas fa-link"></i></a>
</h2>
<div id="the-two-sample-t-test-1" class="section level3" number="6.6.1">
<h3>
<span class="header-section-number">6.6.1</span> The Two-Sample t-test<a class="anchor" aria-label="anchor" href="#the-two-sample-t-test-1"><i class="fas fa-link"></i></a>
</h3>
<div id="task-1-5" class="section level4" number="6.6.1.1">
<h4>
<span class="header-section-number">6.6.1.1</span> Task 1<a class="anchor" aria-label="anchor" href="#task-1-5"><i class="fas fa-link"></i></a>
</h4>
<div class="sourceCode" id="cb266"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="st"><a href="https://tidyverse.tidyverse.org">"tidyverse"</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="st"><a href="https://broom.tidymodels.org/">"broom"</a></span><span class="op">)</span> <span class="co"># you'll need broom::tidy() later</span></span>
<span></span>
<span><span class="va">evaluators</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://readr.tidyverse.org/reference/read_delim.html">read_csv</a></span><span class="op">(</span><span class="st">"evaluators.csv"</span><span class="op">)</span></span>
<span></span>
<span><span class="va">evaluators</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarize</a></span><span class="op">(</span>mean_age <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">age</span>, na.rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="va">evaluators</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/count.html">count</a></span><span class="op">(</span><span class="va">sex</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># If using `recode()`:</span></span>
<span><span class="va">evaluators</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/count.html">count</a></span><span class="op">(</span><span class="va">sex</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>sex_names <span class="op">=</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/recode.html">recode</a></span><span class="op">(</span><span class="va">sex</span>, <span class="st">"1"</span> <span class="op">=</span> <span class="st">"male"</span>, <span class="st">"2"</span> <span class="op">=</span> <span class="st">"female"</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<ul>
<li>The mean age of the evaluators was 30.9</li>
<li>The standard deviatoin of the age of the evaluators was 6.24</li>
<li>There were 4 males and <code>e_count %&gt;% filter(sex_names == "female") %&gt;% pull(n)</code> females, with 5 people not stating a sex.</li>
</ul>
<p><a href="nhst-two-sample-t-test.html#Ch6InClassQueT1">Return to Task</a></p>
</div>
<div id="task-2-6" class="section level4" number="6.6.1.2">
<h4>
<span class="header-section-number">6.6.1.2</span> Task 2<a class="anchor" aria-label="anchor" href="#task-2-6"><i class="fas fa-link"></i></a>
</h4>
<ul>
<li>load in the data</li>
</ul>
<div class="sourceCode" id="cb267"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">ratings</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://readr.tidyverse.org/reference/read_delim.html">read_csv</a></span><span class="op">(</span><span class="st">"ratings.csv"</span><span class="op">)</span></span></code></pre></div>
<ol style="list-style-type: decimal">
<li>First pull out the ratings associated with intellect</li>
</ol>
<div class="sourceCode" id="cb268"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">iratings</span> <span class="op">&lt;-</span> <span class="va">ratings</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">Category</span> <span class="op"><a href="https://rdrr.io/r/base/match.html">%in%</a></span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"competent"</span>, <span class="st">"thoughtful"</span>, <span class="st">"intelligent"</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<ol start="2" style="list-style-type: decimal">
<li>Next calculate means for each evaluator</li>
</ol>
<div class="sourceCode" id="cb269"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">imeans</span> <span class="op">&lt;-</span> <span class="va">iratings</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/group_by.html">group_by</a></span><span class="op">(</span><span class="va">eval_id</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarise</a></span><span class="op">(</span>Rating <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">Rating</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<ol start="3" style="list-style-type: decimal">
<li>Mutate on the Category variable. This way we can combine with 'impression' and 'hire' into a single table which will be very useful!</li>
</ol>
<div class="sourceCode" id="cb270"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">imeans2</span> <span class="op">&lt;-</span> <span class="va">imeans</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>Category <span class="op">=</span> <span class="st">"intellect"</span><span class="op">)</span></span></code></pre></div>
<p>And then combine all the information in to one single tibble.</p>
<div class="sourceCode" id="cb271"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">ratings2</span> <span class="op">&lt;-</span> <span class="va">ratings</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">Category</span> <span class="op"><a href="https://rdrr.io/r/base/match.html">%in%</a></span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"impression"</span>, <span class="st">"hire"</span><span class="op">)</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/bind_rows.html">bind_rows</a></span><span class="op">(</span><span class="va">imeans2</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate-joins.html">inner_join</a></span><span class="op">(</span><span class="va">evaluators</span>, <span class="st">"eval_id"</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="op">-</span><span class="va">age</span>, <span class="op">-</span><span class="va">sex</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/arrange.html">arrange</a></span><span class="op">(</span><span class="va">eval_id</span>, <span class="va">Category</span><span class="op">)</span></span></code></pre></div>
<p><a href="nhst-two-sample-t-test.html#Ch6InClassQueT3">Return to Task</a></p>
</div>
<div id="task-4-5" class="section level4" number="6.6.1.3">
<h4>
<span class="header-section-number">6.6.1.3</span> Task 4<a class="anchor" aria-label="anchor" href="#task-4-5"><i class="fas fa-link"></i></a>
</h4>
<ol style="list-style-type: decimal">
<li>First we calculate the group means:</li>
</ol>
<div class="sourceCode" id="cb272"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">group_means</span> <span class="op">&lt;-</span> <span class="va">ratings2</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/group_by.html">group_by</a></span><span class="op">(</span><span class="va">condition</span>, <span class="va">Category</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarise</a></span><span class="op">(</span>m <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">Rating</span><span class="op">)</span>, sd <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/sd.html">sd</a></span><span class="op">(</span><span class="va">Rating</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<pre><code>## `summarise()` has grouped output by 'condition'. You can override using the
## `.groups` argument.</code></pre>
<ol start="2" style="list-style-type: decimal">
<li>And we can call them and look at them by typing:</li>
</ol>
<div class="sourceCode" id="cb274"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">group_means</span></span></code></pre></div>
<ol start="3" style="list-style-type: decimal">
<li>Now to just look at intellect ratings we need to filter them into a new tibble:</li>
</ol>
<div class="sourceCode" id="cb275"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">intellect</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">ratings2</span>, <span class="va">Category</span> <span class="op">==</span> <span class="st">"intellect"</span><span class="op">)</span></span></code></pre></div>
<ol start="4" style="list-style-type: decimal">
<li>And then we run the actual t-test and tidy it into a table.
<ul>
<li>
<code><a href="https://rdrr.io/r/stats/t.test.html">t.test()</a></code> requires two vectors as input</li>
<li>
<code><a href="https://dplyr.tidyverse.org/reference/pull.html">pull()</a></code> will pull out a single column from a tibble, e.g. Rating from intellect</li>
<li>
<code><a href="https://generics.r-lib.org/reference/tidy.html">tidy()</a></code> takes information from a test and turns it into a table. Try running the t.test with and without piping into <code><a href="https://generics.r-lib.org/reference/tidy.html">tidy()</a></code> to see what it does differently.</li>
</ul>
</li>
</ol>
<div class="sourceCode" id="cb276"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">intellect_t</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/t.test.html">t.test</a></span><span class="op">(</span><span class="va">intellect</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">condition</span> <span class="op">==</span> <span class="st">"listened"</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/pull.html">pull</a></span><span class="op">(</span><span class="va">Rating</span><span class="op">)</span>,</span>
<span>                      <span class="va">intellect</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">condition</span> <span class="op">==</span> <span class="st">"read"</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/pull.html">pull</a></span><span class="op">(</span><span class="va">Rating</span><span class="op">)</span>,</span>
<span>                      var.equal <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://generics.r-lib.org/reference/tidy.html">tidy</a></span><span class="op">(</span><span class="op">)</span></span></code></pre></div>
<ol start="5" style="list-style-type: decimal">
<li>Now we repeat for HIRE and IMPRESSION</li>
</ol>
<div class="sourceCode" id="cb277"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">hire</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">ratings2</span>, <span class="va">Category</span> <span class="op">==</span> <span class="st">"hire"</span><span class="op">)</span></span>
<span><span class="va">hire_t</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/t.test.html">t.test</a></span><span class="op">(</span><span class="va">hire</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">condition</span> <span class="op">==</span> <span class="st">"listened"</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/pull.html">pull</a></span><span class="op">(</span><span class="va">Rating</span><span class="op">)</span>,</span>
<span>                      <span class="va">hire</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">condition</span> <span class="op">==</span> <span class="st">"read"</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/pull.html">pull</a></span><span class="op">(</span><span class="va">Rating</span><span class="op">)</span>,</span>
<span>                 var.equal <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://generics.r-lib.org/reference/tidy.html">tidy</a></span><span class="op">(</span><span class="op">)</span></span></code></pre></div>
<ol start="6" style="list-style-type: decimal">
<li>And for Impression</li>
</ol>
<div class="sourceCode" id="cb278"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">impress</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">ratings2</span>, <span class="va">Category</span> <span class="op">==</span> <span class="st">"impression"</span><span class="op">)</span></span>
<span><span class="va">impress_t</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/t.test.html">t.test</a></span><span class="op">(</span><span class="va">impress</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">condition</span> <span class="op">==</span> <span class="st">"listened"</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/pull.html">pull</a></span><span class="op">(</span><span class="va">Rating</span><span class="op">)</span>,</span>
<span>                    <span class="va">impress</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">condition</span> <span class="op">==</span> <span class="st">"read"</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/pull.html">pull</a></span><span class="op">(</span><span class="va">Rating</span><span class="op">)</span>,</span>
<span>                    var.equal <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://generics.r-lib.org/reference/tidy.html">tidy</a></span><span class="op">(</span><span class="op">)</span></span></code></pre></div>
<ol start="7" style="list-style-type: decimal">
<li>Before combining all into one table showing all three t-tests</li>
</ol>
<div class="sourceCode" id="cb279"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">results</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/bind_rows.html">bind_rows</a></span><span class="op">(</span><span class="st">"hire"</span> <span class="op">=</span> <span class="va">hire_t</span>, </span>
<span>                     <span class="st">"impression"</span> <span class="op">=</span> <span class="va">impress_t</span>,</span>
<span>                     <span class="st">"intellect"</span> <span class="op">=</span> <span class="va">intellect_t</span>, .id <span class="op">=</span> <span class="st">"id"</span><span class="op">)</span></span>
<span></span>
<span><span class="va">results</span></span></code></pre></div>
<p><a href="nhst-two-sample-t-test.html#Ch6InClassQueT4">Return to Task</a></p>
</div>
</div>
<div id="practice-your-skills-9" class="section level3" number="6.6.2">
<h3>
<span class="header-section-number">6.6.2</span> Practice Your Skills<a class="anchor" aria-label="anchor" href="#practice-your-skills-9"><i class="fas fa-link"></i></a>
</h3>
<div id="task-1a-libraries" class="section level4" number="6.6.2.1">
<h4>
<span class="header-section-number">6.6.2.1</span> Task 1A: Libraries<a class="anchor" aria-label="anchor" href="#task-1a-libraries"><i class="fas fa-link"></i></a>
</h4>
<div class="sourceCode" id="cb280"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://broom.tidymodels.org/">broom</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://tidyverse.tidyverse.org">tidyverse</a></span><span class="op">)</span></span></code></pre></div>
<p><a href="#Ch6AssignQueT1">Return to Task</a></p>
</div>
<div id="task-1b-loading-in-the-data" class="section level4" number="6.6.2.2">
<h4>
<span class="header-section-number">6.6.2.2</span> Task 1B: Loading in the data<a class="anchor" aria-label="anchor" href="#task-1b-loading-in-the-data"><i class="fas fa-link"></i></a>
</h4>
<ul>
<li>Use <code><a href="https://readr.tidyverse.org/reference/read_delim.html">read_csv()</a></code> to read in data!</li>
</ul>
<div class="sourceCode" id="cb281"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">crt</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://readr.tidyverse.org/reference/read_delim.html">read_csv</a></span><span class="op">(</span><span class="st">"data/06-s01/homework/CRT_Data.csv"</span><span class="op">)</span></span></code></pre></div>
<div class="sourceCode" id="cb282"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">crt</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://readr.tidyverse.org/reference/read_delim.html">read_csv</a></span><span class="op">(</span><span class="st">"CRT_Data.csv"</span><span class="op">)</span></span></code></pre></div>
<p><a href="#Ch6AssignQueT1">Return to Task</a></p>
</div>
<div id="task-2-selecting-only-relevant-columns" class="section level4" number="6.6.2.3">
<h4>
<span class="header-section-number">6.6.2.3</span> Task 2: Selecting only relevant columns<a class="anchor" aria-label="anchor" href="#task-2-selecting-only-relevant-columns"><i class="fas fa-link"></i></a>
</h4>
<p>The key columns are:</p>
<ul>
<li>ID</li>
<li>Treatment</li>
<li>CorrectAnswers</li>
</ul>
<p>Creating <code>crt2</code> which is a tibble with 3 columns and 243 rows.</p>
<div class="sourceCode" id="cb283"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">crt2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="va">crt</span>, <span class="va">ID</span>, <span class="va">Treatment</span>, <span class="va">CorrectAnswers</span><span class="op">)</span></span></code></pre></div>
<p><a href="nhst-two-sample-t-test.html#Ch6AssignQueT2">Return to Task</a></p>
</div>
<div id="task-3-verify-the-number-of-subjects-in-each-group" class="section level4" number="6.6.2.4">
<h4>
<span class="header-section-number">6.6.2.4</span> Task 3: Verify the number of subjects in each group<a class="anchor" aria-label="anchor" href="#task-3-verify-the-number-of-subjects-in-each-group"><i class="fas fa-link"></i></a>
</h4>
<p>The Participants section of the article contains the following statement:</p>
<p><strong>243 men (mostly college students; for demographic details, see Table S1 in the Supplemental Material available online) were randomly administered a topical gel containing either testosterone (n = 125) or placebo (n = 118).</strong></p>
<p>In the t3 code block below, replace the <code>NULLs</code> with lines of code to calculate:</p>
<ol style="list-style-type: decimal">
<li><p>The number of men in each Treatment. This should be a tibble/table called <code>cond_counts</code> containing a column called <code>Treatment</code> showing the two groups and a column called <code>n</code> which shows the number of men in each group.</p></li>
<li><p>The total number of men in the sample. This should be a single value, not a tibble/table, and should be stored in <code>n_men</code>.</p></li>
</ol>
<p>You know the answer to both of these tasks already. Make sure that your code gives the correct answer!</p>
<p>For <code>cond_counts</code>, you could do:</p>
<div class="sourceCode" id="cb284"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">cond_counts</span> <span class="op">&lt;-</span> <span class="va">crt2</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/group_by.html">group_by</a></span><span class="op">(</span><span class="va">Treatment</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarise</a></span><span class="op">(</span>n <span class="op">=</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/context.html">n</a></span><span class="op">(</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<p>Or alternatively</p>
<div class="sourceCode" id="cb285"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">cond_counts</span> <span class="op">&lt;-</span> <span class="va">crt2</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/count.html">count</a></span><span class="op">(</span><span class="va">Treatment</span><span class="op">)</span></span></code></pre></div>
<p>For <code>n_men</code>, you could do:</p>
<div class="sourceCode" id="cb286"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">n_men</span> <span class="op">&lt;-</span> <span class="va">crt2</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarise</a></span><span class="op">(</span>n <span class="op">=</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/context.html">n</a></span><span class="op">(</span><span class="op">)</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/pull.html">pull</a></span><span class="op">(</span><span class="va">n</span><span class="op">)</span></span></code></pre></div>
<p>Or alternatively</p>
<div class="sourceCode" id="cb287"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">n_men</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/nrow.html">nrow</a></span><span class="op">(</span><span class="va">crt2</span><span class="op">)</span></span></code></pre></div>
<p><strong>Solution:</strong></p>
<p>When formatted with inline R code as below:</p>
<p><strong><code>`r n_men`</code> men (mostly college students; for demographic details, see Table S1 in the Supplemental Material available online) were randomly administered a topical gel containing either testosterone (n = <code>`r cond_counts %&gt;% filter(Treatment == 1) %&gt;% pull(n)`</code>) or placebo (n = <code>`r cond_counts %&gt;% filter(Treatment == 0) %&gt;% pull(n)`</code>).</strong></p>
<p>should give:</p>
<p><strong>243 men (mostly college students; for demographic details, see Table S1 in the Supplemental Material available online) were randomly administered a topical gel containing either testosterone (n = 125) or placebo (n = 118).</strong></p>
<p><a href="nhst-two-sample-t-test.html#Ch6AssignQueT3">Return to Task</a></p>
</div>
<div id="task-4-reproduce-figure-2a" class="section level4" number="6.6.2.5">
<h4>
<span class="header-section-number">6.6.2.5</span> Task 4: Reproduce Figure 2A<a class="anchor" aria-label="anchor" href="#task-4-reproduce-figure-2a"><i class="fas fa-link"></i></a>
</h4>
<p>You could produce a good representation of Figure 2A with the following approach:</p>
<div class="sourceCode" id="cb288"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">crt_means</span> <span class="op">&lt;-</span> <span class="va">crt2</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/group_by.html">group_by</a></span><span class="op">(</span><span class="va">Treatment</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarise</a></span><span class="op">(</span>m <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">CorrectAnswers</span><span class="op">)</span>, sd <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/sd.html">sd</a></span><span class="op">(</span><span class="va">CorrectAnswers</span><span class="op">)</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>Treatment <span class="op">=</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/recode.html">recode</a></span><span class="op">(</span><span class="va">Treatment</span>, <span class="st">"0"</span> <span class="op">=</span> <span class="st">"Placebo"</span>, <span class="st">"1"</span> <span class="op">=</span> <span class="st">"Testosterone Group"</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">crt_means</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span><span class="va">Treatment</span>, <span class="va">m</span>, fill <span class="op">=</span> <span class="va">Treatment</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_bar.html">geom_col</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_classic</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>x <span class="op">=</span> <span class="st">"CRT"</span>, y <span class="op">=</span> <span class="st">"Number of Correct Answers"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/guides.html">guides</a></span><span class="op">(</span>fill <span class="op">=</span> <span class="st">"none"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_manual.html">scale_fill_manual</a></span><span class="op">(</span>values <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"#EEEEEE"</span>,<span class="st">"#AAAAAA"</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/coord_cartesian.html">coord_cartesian</a></span><span class="op">(</span>ylim <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1.4</span>,<span class="fl">2.4</span><span class="op">)</span>, expand <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span></code></pre></div>
<div class="figure" style="text-align: center">
<span style="display:block;" id="fig:t4"></span>
<img src="06-s01-lab06d_files/figure-html/t4-1.png" alt="A representation of Figure 2A" width="100%"><p class="caption">
Figure 6.5: A representation of Figure 2A
</p>
</div>
<p><a href="nhst-two-sample-t-test.html#Ch6AssignQueT4">Return to Task</a></p>
</div>
<div id="task-5-interpreting-your-figure" class="section level4" number="6.6.2.6">
<h4>
<span class="header-section-number">6.6.2.6</span> Task 5: Interpreting your Figure<a class="anchor" aria-label="anchor" href="#task-5-interpreting-your-figure"><i class="fas fa-link"></i></a>
</h4>
<p>Option 3 is the correct answer given that:</p>
<p>The Testosterone group (M = 1.66, SD = 1.18) would appear to have fewer correct answers on average than the Placebo group (M = 2.10, SD = 1.02) on the Cognitive Reflection Test suggesting that testosterone does in fact inhibit the ability to override incorrect intuitive judgements with the correct response.</p>
<div class="sourceCode" id="cb289"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">answer_t5</span> <span class="op">&lt;-</span> <span class="fl">3</span></span></code></pre></div>
<p><a href="nhst-two-sample-t-test.html#Ch6AssignQueT5">Return to Task</a></p>
</div>
<div id="task-6-t-test" class="section level4" number="6.6.2.7">
<h4>
<span class="header-section-number">6.6.2.7</span> Task 6: t-test<a class="anchor" aria-label="anchor" href="#task-6-t-test"><i class="fas fa-link"></i></a>
</h4>
<p>You need to pay attention to the order when using this first approach, making sure that the <strong>0</strong> group are entered first. This will put the Placebo groups as Estimate1 in the output. In reality it does not change the values, but the key thing is that if you were to pass this code on to someone, and they expect Placebo to be Estimate1, then you need to make sure you coded it that way.</p>
<div class="sourceCode" id="cb290"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">t_table</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/t.test.html">t.test</a></span><span class="op">(</span><span class="va">crt2</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">Treatment</span> <span class="op">==</span> <span class="fl">0</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/pull.html">pull</a></span><span class="op">(</span><span class="va">CorrectAnswers</span><span class="op">)</span>,</span>
<span>                  <span class="va">crt2</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">Treatment</span> <span class="op">==</span> <span class="fl">1</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/pull.html">pull</a></span><span class="op">(</span><span class="va">CorrectAnswers</span><span class="op">)</span>,</span>
<span>                  var.equal <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://generics.r-lib.org/reference/tidy.html">tidy</a></span><span class="op">(</span><span class="op">)</span></span></code></pre></div>
<ul>
<li>Alternatively, you could use what is known as the formula approach as shown below. Here you state the <code>DV ~ IV</code> and you say the name of the tibble in <code>data = ...</code>. You just need to make sure that the columns you state as the DV and the IV are actually in the tibble!</li>
</ul>
<div class="sourceCode" id="cb291"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">t_table</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/t.test.html">t.test</a></span><span class="op">(</span><span class="va">CorrectAnswers</span> <span class="op">~</span> <span class="va">Treatment</span>, data <span class="op">=</span> <span class="va">crt2</span>, var.equal <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="fu"><a href="https://generics.r-lib.org/reference/tidy.html">tidy</a></span><span class="op">(</span><span class="op">)</span></span></code></pre></div>
<p><a href="nhst-two-sample-t-test.html#Ch6AssignQueT6">Return to Task</a></p>
</div>
<div id="task-7-reporting-results" class="section level4" number="6.6.2.8">
<h4>
<span class="header-section-number">6.6.2.8</span> Task 7: Reporting results<a class="anchor" aria-label="anchor" href="#task-7-reporting-results"><i class="fas fa-link"></i></a>
</h4>
<ul>
<li>The degrees of freedom (df) is found under <code>parameter</code>
</li>
</ul>
<div class="sourceCode" id="cb292"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">t_df</span> <span class="op">&lt;-</span> <span class="va">t_table</span><span class="op">$</span><span class="va">parameter</span></span></code></pre></div>
<ul>
<li>An alternative option for this would be as follows, using the <code><a href="https://dplyr.tidyverse.org/reference/pull.html">pull()</a></code> method. This would work for B to D as well</li>
</ul>
<div class="sourceCode" id="cb293"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">t_df</span> <span class="op">&lt;-</span> <span class="va">t_table</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/pull.html">pull</a></span><span class="op">(</span><span class="va">parameter</span><span class="op">)</span></span></code></pre></div>
<ul>
<li>The t-value is found under <code>statistic</code>
</li>
</ul>
<div class="sourceCode" id="cb294"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">t_value</span> <span class="op">&lt;-</span> <span class="va">t_table</span><span class="op">$</span><span class="va">statistic</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="fl">3</span><span class="op">)</span></span></code></pre></div>
<ul>
<li>The p-value is found under <code>p.value</code>
</li>
</ul>
<div class="sourceCode" id="cb295"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">p_value</span> <span class="op">&lt;-</span> <span class="va">t_table</span><span class="op">$</span><span class="va">p.value</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="fl">3</span><span class="op">)</span></span></code></pre></div>
<ul>
<li>The absolute difference between the two means can be calculated as follows:</li>
</ul>
<div class="sourceCode" id="cb296"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">t_diff</span> <span class="op">&lt;-</span> <span class="op">(</span><span class="va">t_table</span><span class="op">$</span><span class="va">estimate1</span> <span class="op">-</span> <span class="va">t_table</span><span class="op">$</span><span class="va">estimate2</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="fl">3</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">abs</a></span><span class="op">(</span><span class="op">)</span></span></code></pre></div>
<p>If you have completed t7A to t7D accurately, then when knitted, Option 4 would be stated as such</p>
<p><strong>The testosterone group performed significantly worse (0.438 fewer correct answers) than the placebo group, t(241) = 3.074, p = 0.002</strong></p>
<p>and would therefore be the correct answer!</p>
<div class="sourceCode" id="cb297"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">answer_t7e</span> <span class="op">&lt;-</span> <span class="fl">4</span></span></code></pre></div>
<p><a href="nhst-two-sample-t-test.html#Ch6AssignQueT7">Return to Task</a></p>
<p><span style="font-size: 22px; font-weight: bold; color: var(--purple);">Chapter Complete!</span></p>

</div>
</div>
</div>
</div>
<script>

/* update total correct if #webex-total_correct exists */
update_total_correct = function() {
  console.log("webex: update total_correct");

  if (t = document.getElementById("webex-total_correct")) {
    var correct = document.getElementsByClassName("webex-correct").length;
    var solvemes = document.getElementsByClassName("webex-solveme").length;
    var radiogroups = document.getElementsByClassName("webex-radiogroup").length;
    var selects = document.getElementsByClassName("webex-select").length;
    
    t.innerHTML = correct + " of " + (solvemes + radiogroups + selects) + " correct";
  }
}

/* webex-solution button toggling function */
b_func = function() {
  console.log("webex: toggle hide");
  
  var cl = this.parentElement.classList;
  if (cl.contains('open')) {
    cl.remove("open");
  } else {
    cl.add("open");
  }
}

/* function for checking solveme answers */
solveme_func = function(e) {
  console.log("webex: check solveme");

  var real_answers = JSON.parse(this.dataset.answer);
  var my_answer = this.value;
  var cl = this.classList;
  if (cl.contains("ignorecase")) {
    my_answer = my_answer.toLowerCase();
  }
  if (cl.contains("nospaces")) {
    my_answer = my_answer.replace(/ /g, "")
  }

  if (my_answer == "") {
    cl.remove("webex-correct");
    cl.remove("webex-incorrect");
  } else if (real_answers.includes(my_answer)) {
    cl.add("webex-correct");
    cl.remove("webex-incorrect");
  } else {
    cl.add("webex-incorrect");
    cl.remove("webex-correct");
  }

  // match numeric answers within a specified tolerance
  if(this.dataset.tol > 0){
    var tol = JSON.parse(this.dataset.tol);
    var matches = real_answers.map(x => Math.abs(x - my_answer) < tol)
    if (matches.reduce((a, b) => a + b, 0) > 0) {
      cl.add("webex-correct");
    } else {
      cl.remove("webex-correct");
    }
  }

  // added regex bit
  if (cl.contains("regex")){
    answer_regex = RegExp(real_answers.join("|"))
    if (answer_regex.test(my_answer)) {
      cl.add("webex-correct");
    }
  }

  update_total_correct();
}

/* function for checking select answers */
select_func = function(e) {
  console.log("webex: check select");
  
  var cl = this.classList
  
  /* add style */
  cl.remove("webex-incorrect");
  cl.remove("webex-correct");
  if (this.value == "answer") {
    cl.add("webex-correct");
  } else if (this.value != "blank") {
    cl.add("webex-incorrect");
  }
  
  update_total_correct();
}

/* function for checking radiogroups answers */
radiogroups_func = function(e) {
  console.log("webex: check radiogroups");

  var checked_button = document.querySelector('input[name=' + this.id + ']:checked');
  var cl = checked_button.parentElement.classList;
  var labels = checked_button.parentElement.parentElement.children;
  
  /* get rid of styles */
  for (i = 0; i < labels.length; i++) {
    labels[i].classList.remove("webex-incorrect");
    labels[i].classList.remove("webex-correct");
  }
  
  /* add style */
  if (checked_button.value == "answer") {
    cl.add("webex-correct");
  } else {
    cl.add("webex-incorrect");
  }
  
  update_total_correct();
}

window.onload = function() {
  console.log("onload");
  /* set up solution buttons */
  var buttons = document.getElementsByTagName("button");

  for (var i = 0; i < buttons.length; i++) {
    if (buttons[i].parentElement.classList.contains('webex-solution')) {
      buttons[i].onclick = b_func;
    }
  }

  /* set up webex-solveme inputs */
  var solveme = document.getElementsByClassName("webex-solveme");

  for (var i = 0; i < solveme.length; i++) {
    /* make sure input boxes don't auto-anything */
    solveme[i].setAttribute("autocomplete","off");
    solveme[i].setAttribute("autocorrect", "off");
    solveme[i].setAttribute("autocapitalize", "off");
    solveme[i].setAttribute("spellcheck", "false");
    solveme[i].value = "";

    /* adjust answer for ignorecase or nospaces */
    var cl = solveme[i].classList;
    var real_answer = solveme[i].dataset.answer;
    if (cl.contains("ignorecase")) {
      real_answer = real_answer.toLowerCase();
    }
    if (cl.contains("nospaces")) {
      real_answer = real_answer.replace(/ /g, "");
    }
    solveme[i].dataset.answer = real_answer;

    /* attach checking function */
    solveme[i].onkeyup = solveme_func;
    solveme[i].onchange = solveme_func;
  }
  
  /* set up radiogroups */
  var radiogroups = document.getElementsByClassName("webex-radiogroup");
  for (var i = 0; i < radiogroups.length; i++) {
    radiogroups[i].onchange = radiogroups_func;
  }
  
  /* set up selects */
  var selects = document.getElementsByClassName("webex-select");
  for (var i = 0; i < selects.length; i++) {
    selects[i].onchange = select_func;
  }

  update_total_correct();
}

</script><script>
$( document ).ready(function() {
  var cite = ' ';
  var psyteachr = ' <a href="https://psyteachr.github.io/"><img src="images/logos/psyteachr_logo.png" style="height: 31px; color: white;" alt="psyTeachR: Reproducible Research" /></a>';
  var license = ' <a rel="license" href="https://creativecommons.org/licenses/by-sa/4.0/" target="blank"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-sa/4.0/88x31.png"></a>';

  $("footer div.row div:eq(1) p").html(
    psyteachr + license + cite
  );
  
  // open rdrr links externally
  $("a[href^='https://rdrr.io']").click(function(){
    window.open(this.href);
    return false;
  });
  
  // visible second sidebar in mobile
  function move_sidebar() {
    var w = window.innerWidth;
    if (w < 992) {
      $("#toc").appendTo($("#main-nav"));
    } else {
      $("#toc").appendTo($("div.sidebar-chapter"));
    }
  }
  move_sidebar();
  window.onresize = move_sidebar;
});
</script><div class="chapter-nav">
<div class="prev"><a href="nhst-binomial-test-and-one-sample-t-test.html"><span class="header-section-number">5</span> NHST: Binomial test and One-Sample t-test</a></div>
<div class="next"><a href="nhst-paired-sample-t-test-and-nonparametric-tests.html"><span class="header-section-number">7</span> NHST: Paired-Sample t-test and Nonparametric tests</a></div>
</div></main><div class="col-md-3 col-lg-2 d-none d-md-block sidebar sidebar-chapter">
    <nav id="toc" data-toggle="toc" aria-label="On this page"><h2>On this page</h2>
      <ul class="nav navbar-nav">
<li><a class="nav-link" href="#nhst-two-sample-t-test"><span class="header-section-number">6</span> NHST: Two-Sample t-test</a></li>
<li><a class="nav-link" href="#overview-6"><span class="header-section-number">6.1</span> Overview</a></li>
<li><a class="nav-link" href="#background-of-data-speech-as-indicator-of-intellect"><span class="header-section-number">6.2</span> Background of data: Speech as indicator of intellect</a></li>
<li>
<a class="nav-link" href="#the-two-sample-t-test"><span class="header-section-number">6.3</span> The Two-Sample t-test</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#Ch6InClassQueT1"><span class="header-section-number">6.3.1</span> Task 1: Evaluators</a></li>
<li><a class="nav-link" href="#Ch6InClassQueT2"><span class="header-section-number">6.3.2</span> Task 2: Ratings</a></li>
<li><a class="nav-link" href="#Ch6InClassQueT3"><span class="header-section-number">6.3.3</span> Task 3: Creating a Figure</a></li>
<li><a class="nav-link" href="#Ch6InClassQueT4"><span class="header-section-number">6.3.4</span> Task 4: t-tests</a></li>
</ul>
</li>
<li><a class="nav-link" href="#students-versus-welchs-t-tests"><span class="header-section-number">6.4</span> Student's versus Welch's t-tests</a></li>
<li>
<a class="nav-link" href="#practice-your-skills-8"><span class="header-section-number">6.5</span> Practice Your Skills</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#single-dose-testosterone-administration-impairs-cognitive-reflection-in-men."><span class="header-section-number">6.5.1</span> Single-dose testosterone administration impairs cognitive reflection in men.</a></li>
<li><a class="nav-link" href="#Ch6AssignQueT1A"><span class="header-section-number">6.5.2</span> Task 1A: Libraries</a></li>
<li><a class="nav-link" href="#Ch6AssignQueT1B"><span class="header-section-number">6.5.3</span> Task 1B: Loading in the data</a></li>
<li><a class="nav-link" href="#Ch6AssignQueT2"><span class="header-section-number">6.5.4</span> Task 2: Selecting only relevant columns</a></li>
<li><a class="nav-link" href="#Ch6AssignQueT3"><span class="header-section-number">6.5.5</span> Task 3: Verify the number of subjects in each group</a></li>
<li><a class="nav-link" href="#Ch6AssignQueT4"><span class="header-section-number">6.5.6</span> Task 4: Reproduce Figure 2a</a></li>
<li><a class="nav-link" href="#Ch6AssignQueT5"><span class="header-section-number">6.5.7</span> Task 5: Interpreting your Figure</a></li>
<li><a class="nav-link" href="#Ch6AssignQueT6"><span class="header-section-number">6.5.8</span> Task 6: t-test</a></li>
<li><a class="nav-link" href="#Ch6AssignQueT7"><span class="header-section-number">6.5.9</span> Task 7: Reporting results</a></li>
</ul>
</li>
<li>
<a class="nav-link" href="#solutions-to-questions-5"><span class="header-section-number">6.6</span> Solutions to Questions</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#the-two-sample-t-test-1"><span class="header-section-number">6.6.1</span> The Two-Sample t-test</a></li>
<li><a class="nav-link" href="#practice-your-skills-9"><span class="header-section-number">6.6.2</span> Practice Your Skills</a></li>
</ul>
</li>
</ul>

      <div class="book-extra">
        <ul class="list-unstyled">
<li><a id="book-source" href="https://github.com/psyteachr/analysis-v2/blob/master/book/06-s01-lab06a.Rmd">View source <i class="fab fa-github"></i></a></li>
          <li><a id="book-edit" href="https://github.com/psyteachr/analysis-v2/edit/master/book/06-s01-lab06a.Rmd">Edit this page <i class="fab fa-github"></i></a></li>
        </ul>
</div>
    </nav>
</div>

</div>
</div> <!-- .container -->

<footer class="bg-primary text-light mt-5"><div class="container"><div class="row">

  <div class="col-12 col-md-6 mt-3">
    <p>"<strong>Analysis</strong>" was written by Phil McAleer, Carolina E. Kuepper-Tetzel, Helena Paterson. It was last built on 2023-09-21.</p>
  </div>

  <div class="col-12 col-md-6 mt-3">
    <p>This book was built by the <a class="text-light" href="https://bookdown.org">bookdown</a> R package.</p>
  </div>

</div></div>
</footer><!-- dynamically load mathjax for compatibility with self-contained --><script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script><script type="text/x-mathjax-config">const popovers = document.querySelectorAll('a.footnote-ref[data-toggle="popover"]');
for (let popover of popovers) {
  const div = document.createElement('div');
  div.setAttribute('style', 'position: absolute; top: 0, left:0; width:0, height:0, overflow: hidden; visibility: hidden;');
  div.innerHTML = popover.getAttribute('data-content');

  var has_math = div.querySelector("span.math");
  if (has_math) {
    document.body.appendChild(div);
    MathJax.Hub.Queue(["Typeset", MathJax.Hub, div]);
    MathJax.Hub.Queue(function() {
      popover.setAttribute('data-content', div.innerHTML);
      document.body.removeChild(div);
    })
  }
}
</script>
</body>
</html>
