<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>Chapter 4 Revisiting Probability Distributions | Analysis</title>
<meta name="author" content="Phil McAleer, Carolina E. Kuepper-Tetzel, Helena Paterson">
<meta name="description" content="4.1 Overview Probability is to some degree the cornerstone of any Psychological theory that is based on quantitative analysis. We establish an outcome (e.g., a difference between two events), then...">
<meta name="generator" content="bookdown 0.35 with bs4_book()">
<meta property="og:title" content="Chapter 4 Revisiting Probability Distributions | Analysis">
<meta property="og:type" content="book">
<meta property="og:url" content="https://psyteachr.github.io/analysis-v2/revisiting-probability-distributions.html">
<meta property="og:image" content="https://psyteachr.github.io/analysis-v2/images/logos/logo.png">
<meta property="og:description" content="4.1 Overview Probability is to some degree the cornerstone of any Psychological theory that is based on quantitative analysis. We establish an outcome (e.g., a difference between two events), then...">
<meta name="twitter:card" content="summary">
<meta name="twitter:title" content="Chapter 4 Revisiting Probability Distributions | Analysis">
<meta name="twitter:description" content="4.1 Overview Probability is to some degree the cornerstone of any Psychological theory that is based on quantitative analysis. We establish an outcome (e.g., a difference between two events), then...">
<meta name="twitter:image" content="https://psyteachr.github.io/analysis-v2/images/logos/logo.png">
<!-- JS --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/fuse.js/6.4.6/fuse.js" integrity="sha512-zv6Ywkjyktsohkbp9bb45V6tEMoWhzFzXis+LrMehmJZZSys19Yxf1dopHx7WzIKxr5tK2dVcYmaCk2uqdjF4A==" crossorigin="anonymous"></script><script src="https://kit.fontawesome.com/6ecbd6c532.js" crossorigin="anonymous"></script><script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link href="libs/bootstrap-4.6.0/bootstrap.min.css" rel="stylesheet">
<script src="libs/bootstrap-4.6.0/bootstrap.bundle.min.js"></script><script src="libs/bs3compat-0.5.0/transition.js"></script><script src="libs/bs3compat-0.5.0/tabs.js"></script><script src="libs/bs3compat-0.5.0/bs3compat.js"></script><link href="libs/bs4_book-1.0.0/bs4_book.css" rel="stylesheet">
<script src="libs/bs4_book-1.0.0/bs4_book.js"></script><script src="libs/kePrint-0.0.1/kePrint.js"></script><link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet">
<!-- Global site tag (gtag.js) - Google Analytics --><script async src="https://www.googletagmanager.com/gtag/js?id=G-6NP3MF25W3"></script><script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'G-6NP3MF25W3');
    </script><script src="https://cdnjs.cloudflare.com/ajax/libs/autocomplete.js/0.38.0/autocomplete.jquery.min.js" integrity="sha512-GU9ayf+66Xx2TmpxqJpliWbT5PiGYxpaG8rfnBEk1LL8l1KGkRShhngwdXK1UgqhAzWpZHSiYPc09/NwDQIGyg==" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/mark.min.js" integrity="sha512-5CYOlHXGh6QpOFA/TeTylKLWfB3ftPsde7AnmhuitiTX4K5SqCLBeKro6sPS8ilsz1Q4NRx3v8Ko2IBiszzdww==" crossorigin="anonymous"></script><!-- CSS --><style type="text/css">
    
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  </style>
<style type="text/css">
    /* Used with Pandoc 2.11+ new --citeproc when CSL is used */
    div.csl-bib-body { }
    div.csl-entry {
      clear: both;
        }
    .hanging div.csl-entry {
      margin-left:2em;
      text-indent:-2em;
    }
    div.csl-left-margin {
      min-width:2em;
      float:left;
    }
    div.csl-right-inline {
      margin-left:2em;
      padding-left:1em;
    }
    div.csl-indent {
      margin-left: 2em;
    }
  </style>
<link rel="stylesheet" href="include/psyteachr.css">
<link rel="stylesheet" href="include/webex.css">
<link rel="stylesheet" href="include/style.css">
</head>
<body data-spy="scroll" data-target="#toc">

<div class="container-fluid">
<div class="row">
  <header class="col-sm-12 col-lg-3 sidebar sidebar-book"><a class="sr-only sr-only-focusable" href="#content">Skip to main content</a>

    <div class="d-flex align-items-start justify-content-between">
      <h1>
        <a href="index.html" title="">Analysis</a>
      </h1>
      <button class="btn btn-outline-primary d-lg-none ml-2 mt-1" type="button" data-toggle="collapse" data-target="#main-nav" aria-expanded="true" aria-controls="main-nav"><i class="fas fa-bars"></i><span class="sr-only">Show table of contents</span></button>
    </div>

    <div id="main-nav" class="collapse-lg">
      <form role="search">
        <input id="search" class="form-control" type="search" placeholder="Search" aria-label="Search">
</form>

      <nav aria-label="Table of contents"><h2>Table of contents</h2>
        <ul class="book-toc list-unstyled">
<li><a class="" href="index.html">Overview</a></li>
<li><a class="" href="starting-with-r-markdown.html"><span class="header-section-number">1</span> Starting with R Markdown</a></li>
<li><a class="" href="data-wrangling-a-key-skill.html"><span class="header-section-number">2</span> Data-Wrangling: A Key Skill</a></li>
<li><a class="" href="data-visualisation-through-ggplot2.html"><span class="header-section-number">3</span> Data Visualisation Through ggplot2</a></li>
<li><a class="active" href="revisiting-probability-distributions.html"><span class="header-section-number">4</span> Revisiting Probability Distributions</a></li>
<li><a class="" href="nhst-binomial-test-and-one-sample-t-test.html"><span class="header-section-number">5</span> NHST: Binomial test and One-Sample t-test</a></li>
<li><a class="" href="nhst-two-sample-t-test.html"><span class="header-section-number">6</span> NHST: Two-Sample t-test</a></li>
<li><a class="" href="nhst-paired-sample-t-test-and-nonparametric-tests.html"><span class="header-section-number">7</span> NHST: Paired-Sample t-test and Nonparametric tests</a></li>
<li><a class="" href="apes---alpha-power-effect-sizes-sample-size.html"><span class="header-section-number">8</span> APES - Alpha, Power, Effect Sizes, Sample Size</a></li>
<li><a class="" href="correlations.html"><span class="header-section-number">9</span> Correlations</a></li>
<li><a class="" href="simple-regression.html"><span class="header-section-number">10</span> Simple Regression</a></li>
<li><a class="" href="multiple-regression.html"><span class="header-section-number">11</span> Multiple Regression</a></li>
<li><a class="" href="one-way-anova.html"><span class="header-section-number">12</span> One-way ANOVA</a></li>
<li><a class="" href="factorial-anova.html"><span class="header-section-number">13</span> Factorial ANOVA</a></li>
<li class="book-part">Appendices</li>
<li><a class="" href="acknowledgements.html">Acknowledgements</a></li>
<li><a class="" href="installing-r.html"><span class="header-section-number">A</span> Installing R</a></li>
<li><a class="" href="updating-r-rstudio-and-packages.html"><span class="header-section-number">B</span> Updating R, RStudio, and packages</a></li>
<li><a class="" href="exporting-files-from-the-server.html"><span class="header-section-number">C</span> Exporting files from the server</a></li>
<li><a class="" href="symbols.html"><span class="header-section-number">D</span> Symbols</a></li>
<li><a class="" href="license.html">License</a></li>
<li><a class="" href="references.html">References</a></li>
</ul>

        <div class="book-extra">
          <p><a id="book-repo" href="https://github.com/psyteachr/analysis-v2">View book source <i class="fab fa-github"></i></a></p>
        </div>
      </nav>
</div>
  </header><main class="col-sm-12 col-md-9 col-lg-7" id="content"><div id="revisiting-probability-distributions" class="section level1" number="4">
<h1>
<span class="header-section-number">4</span> Revisiting Probability Distributions<a class="anchor" aria-label="anchor" href="#revisiting-probability-distributions"><i class="fas fa-link"></i></a>
</h1>
<div id="overview-4" class="section level2" number="4.1">
<h2>
<span class="header-section-number">4.1</span> Overview<a class="anchor" aria-label="anchor" href="#overview-4"><i class="fas fa-link"></i></a>
</h2>
<p>Probability is to some degree the cornerstone of any Psychological theory that is based on quantitative analysis. We establish an outcome (e.g., a difference between two events), then establish the probability of that outcome against some model or standard. Probability is important for quantifying the uncertainty in our conclusions. You will have already heard about probability in lectures/journal articles/etc., but we will try to help you gain a deeper understanding of probability through the course of the next few chapters and in how we use it to make an inference about a <a class="glossary">population<span class="def"></span></a>.</p>
<p>We will start by looking at some of the general ideas behind probability. We won't be using a lot of Psychology data or concepts here as it can be easier to understand probability first in everyday concrete examples. That said, whilst reading the examples, and trying them out, think about how they might relate to Psychology examples and be sure to ask questions.</p>
<p>This preclass is a bit of a read so take your time and try to understand it fully. Much of it will be familiar though from the PsyTeachR <a href="https://psyteachr.github.io/" target="_blank">Data Skills book</a> as it recaps some of the ideas. Also, there are no cheatsheets for this chapter as we will not be using a specific package. However you can make full use of the R help function (e.g. <code><a href="https://rdrr.io/r/base/sample.html">?sample</a></code>) when you are not clear on what a function does. Also, remember what we have said previously; do not be shy to do what we do and run a Google Search for finding out more about some of the stats concepts covered here. There are loads of videos and help pages out there with clear examples to explain difficult concepts.</p>
<p>In this chapter you will:</p>
<ol style="list-style-type: decimal">
<li>Revise probability concepts that we discussed in the PsyTeachR <a href="https://psyteachr.github.io/" target="_blank">Data Skills book</a>
</li>
<li>Calculate probabilities</li>
<li>Create probability distributions</li>
<li>Make estimations from probability distributions.</li>
</ol>
<div class="webex-solution">
<button>
Portfolio Point - Samples, Populations and Inference
</button>
<div class="info">
<p>
The population is the whole group that you want to know something
about - everyone or everything in that group. The sample is the part of
the population that you are testing. The sample is always smaller than
the population as it is unlikely that you would ever be able to test
everyone in a population, but the sample should be representative of the
population based on random sampling. This means that even though you are
not using the whole population, the sample you are using represents the
whole population because you randomly sampled people into it. If this is
true, that the sample is representative of the population, then testing
on the sample allows you to make some inference about the population;
you infer a characteristic of the population from testing on the
sample.
</p>
</div>
</div>
<p><br><span style="font-size: 22px; font-weight: bold; color: var(--black);">Discrete versus Continuous Data</span></p>
<p>Let's recap questions on how the <strong>level of measurement</strong> can alter the way you tackle probability - i.e., whether the data is <a class="glossary">discrete<span class="def"></span></a> or <a class="glossary">continuous<span class="def"></span></a>.</p>
<p><span style="font-size: 22px; font-weight: bold; color: var(--green);">Quickfire Questions</span></p>
<p><strong>Discrete</strong> data can only take specific/certain/exact values (e.g., groups, integers). For example, the number of participants in an experiment would be discrete - we can't have half a participant! Discrete variables can also be further broken down into <strong>nominal/categorical</strong> and <strong>ordinal</strong> variables.
<br>
Fill in the blanks in the below sentences using the words: ordinal, nominal/categorical.</p>
<ul>
<li><p><select class="webex-select"><option value="blank"></option>
<option value="answer">Nominal</option>
<option value="">Ordinal</option></select> data is based on a set of categories that have no natural ordering (e.g., left or right handed). For example, you could separate participants according to left or right handedness or by course of study (e.g., psychology, biology, history, etc.).</p></li>
<li><p><select class="webex-select"><option value="blank"></option>
<option value="">Nominal</option>
<option value="answer">Ordinal</option></select> data is a set of categories that have a natural ordering; you know which is the top/best and which is the worst/lowest, but the difference between categories may not be constant. For example, you could ask participants to rate the attractiveness of different faces based on a 5-item Likert scale (very unattractive, unattractive, neutral, attractive, very attractive).</p></li>
</ul>
<p><strong>Continuous</strong> data on the other hand can take any value in the scale being measured. For example, we can measure age on a continuous scale (e.g., we can have an age of 26.55 years), also reaction time or the distance you travel to university.</p>
<p>Fill in the blanks in the below sentences using the two remaining levels of measurement not offered above:</p>
<ul>
<li>Continuous data can be broken into <input class="webex-solveme nospaces ignorecase" size="10" data-answer='["interval","ratio"]'> or <input class="webex-solveme nospaces ignorecase" size="10" data-answer='["interval","ratio"]'> data.</li>
</ul>
<p>When you read journal articles or when you are working with data, it is really good practice to take a minute or two to figure out the type of variables you are reading about and/or working with.</p>
<div class="webex-solution">
<button>
Explain This - I don't get these answers
</button>
<div class="info">
<p>
The four level of measurements are nominal (also called categorical),
ordinal, interval, and ratio. Discrete data only uses categories or
whole numbers and is therefore either nominal or ordinal data.
Continuous data can take any value, e.g., 9.00 or 9.999999999, and so is
either interval or ratio data.
</p>
</div>
</div>

</div>
<div id="discrete-data-and-binomial-distributions" class="section level2" number="4.2">
<h2>
<span class="header-section-number">4.2</span> Discrete Data and Binomial Distributions<a class="anchor" aria-label="anchor" href="#discrete-data-and-binomial-distributions"><i class="fas fa-link"></i></a>
</h2>
<div id="general-probability-calculations" class="section level3" number="4.2.1">
<h3>
<span class="header-section-number">4.2.1</span> General Probability Calculations<a class="anchor" aria-label="anchor" href="#general-probability-calculations"><i class="fas fa-link"></i></a>
</h3>
<p>Today we will begin by recapping the concepts of probability calculations from lectures and the PsyTeachR <a href="https://psyteachr.github.io/" target="_blank">Data Skills book</a>, looking at discrete distributions - where values are categories (e.g., house, face, car) or whole numbers (e.g., 1,2, 3 and not 1.1, 1.2 etc).</p>
<p>When we talk about probability we mean we are interested in the likelihood of an event occurring. The probability of any discrete event occurring can be formulated as:</p>
<p><span class="math display">\[p = \frac{number \  of  \ ways \ the \ event \ could \  arise}{number \ of \ possible \ outcomes}\]</span></p>
<p>The probability of an event is represented by a number between 0 and 1, and the letter <strong>p</strong>. For example, the probability of flipping a coin and it landing on 'tails', most people would say, is estimated at <strong>p = .5</strong>, i.e. the likelihood of getting tails is <span class="math inline">\(p = \frac {1}{2}\)</span> as there is one desired outcome (tails) and two possibilities (heads or tails).<br><br></p>
<p><strong>For example:</strong></p>
<p><strong>1.</strong> The probability of drawing the ten of clubs from a standard pack of cards would be 1 in 52: <span class="math inline">\(p = \frac {1}{52} \ = .019\)</span>. One outcome (ten of clubs) with 52 possible outcomes (all the cards)</p>
<p><strong>2.</strong> Likewise, the probability of drawing <strong>either</strong> a ten of clubs or a seven of diamonds as the the first card that you draw from a full deck would be 2 in 52: <span class="math inline">\(p = \frac {2}{52} \ = .038\)</span>. In this case you are adding to the chance of an event occurring by giving two possible outcomes so it becomes <strong>more likely</strong> to happen than when you only had one outcome.</p>
<p><strong>3.</strong> Now say you have two standard packs of cards <strong>mixed</strong> together. The probability of drawing the 10 of clubs from this mixed pack would be 2 in 104: <span class="math inline">\(p = \frac{2}{104}= .019\)</span>. Two possible outcomes <strong>but more alternatives</strong> than above, 104 this time, meaning it is <strong>less probable</strong> than Example 2 but the same probability as Example 1. The key thing to remember is that probability is a ratio between the number of ways a specified outcome can happen and the number of all possible outcomes.</p>
<p><strong>4.</strong> Let's instead say you have two <strong>separate</strong> packs of cards. The probability of drawing the 10 of clubs from <strong>both</strong> packs would be: <span class="math inline">\(p = \frac{1}{52} \times \frac{1}{52}= .0004\)</span>. The probability has gone down again because you have created an event that is <strong>even more unlikely</strong> to happen. This is called the <strong>joint probability</strong> of events.</p>
<pre><code>* To find the joint probability of two separate events occuring you multiply together the probabilities of the two individual separate events (often stated as independent, mutually exclusive events). </code></pre>
<p><strong>5.</strong> What about the probability of drawing the 10 of clubs from a pack of 52, putting it back (which we call <strong>replacement</strong>), and subsequently drawing the 7 of diamonds? Again, this would be represented by multiplying together the probability of each of these events happening: <span class="math inline">\(p = \frac{1}{52} \times \frac{1}{52}= .0004\)</span>.</p>
<pre><code>* The second event (drawing the 7 of diamonds) has the same probability as the first event (drawing the 10 of clubs) because we put the original card back in the pack, keeping the number of all possible outcomes at 52. This is **replacement**.</code></pre>
<p><strong>6.</strong> Finally, say you draw the 10 of clubs from a pack of 52 but this time <strong>don't replace it</strong>. What is the probability that you will draw the 7 of diamonds in your next draw (again without replacing it) and the 3 of hearts in a third draw? This time the number of cards in the pack is <strong>fewer</strong> for the second (51 cards) and third draws (50 cards) so you take that into account in your multiplication: <span class="math inline">\(p = \frac{1}{52} \times \frac{1}{51}\times \frac{1}{50}= .000008\)</span>.</p>
<div class="webex-solution">
<button>
Portfolio Point - Presenting probabilities
</button>
<div class="info">
<p>
So, the probability of an event is the number of all the possible
ways an event could happen, divided by the number of all the possible
outcomes. When you combine probabilities of two separate events you
multiple them together to obtain the joint probability.
</p>
<p>
You may have noticed that we tend to write p = .008, for example, as
opposed to p = 0.008 (with a 0 before the decimal place). Why is that?
Convention really. As probability can never go above 1, then the 0
before the decimal place is pointless. Meaning that most people will
write p = .008 instead of p = 0.008, indicating that the max value is
1.
</p>
<p>
We allow either version in the answers to this chapter as we are
still learning, but try to get in the habit of writing probability
without the 0 before the decimal place.
</p>
</div>
</div>
<p><br><span style="font-size: 22px; font-weight: bold; color: var(--green);">Quickfire Questions</span></p>
<ul>
<li><p>What is the probability of randomly drawing your name out of a hat of 12 names where one name is definitely your name? Enter your answer to 3 decimal places: <input class="webex-solveme nospaces" size="5" data-answer='["0.083",".083"]'></p></li>
<li><p>What is the probability of randomly drawing your name out of a hat of 12 names, putting it back, and drawing your name again? Enter your answer to 3 decimal places: <input class="webex-solveme nospaces" size="5" data-answer='["0.007",".007"]'></p></li>
<li><p><strong>Tricky</strong>: In a stimuli set of 120 faces, where 10 are inverted and 110 are the right way up, what is the probability of randomly removing one inverted face on your first trial, not replacing it, and then removing another inverted face on the second trial? Enter your answer to three decimal places:<input class="webex-solveme nospaces" size="5" data-answer='["0.006",".006"]'></p></li>
</ul>
<div class="webex-solution">
<button>
Helpful Hint
</button>
<div class="info">
<ol style="list-style-type: decimal">
<li>
<p>
Out of 12 possible outcomes you are looking for one possible
event.
</p>
</li>
<li>
<p>
There are two separate scenarios here. In both scenarios there
are 12 possible outcomes in which you are looking for one possible
event. Since there are two separate scenarios, does this make it more or
less likely that you will draw your name twice?
</p>
</li>
<li>
<p>
In the first trial here are 120 possible outcomes (faces) in
which you are looking for 10 possible events (inverted faces). In the
second trial you have removed the first inverted face from the stimuli
set so there are now only 119 trials in total and 9 inverted faces.
Remember you need to multiply the probabilities of the first trial and
second trial results together!
</p>
</li>
</ol>
</div>
</div>
<div class="webex-solution">
<button>
Explain This - I don't get these answers
</button>
<div class="info">
<ol style="list-style-type: decimal">
<li>
<p>
p = .083. One outcome (your name) out of 12 possibilities,
i.e. <span class="math inline"><span class="math inline">\(p = \frac{1}{12}\)</span></span>
</p>
</li>
<li>
<p>
p = .007. Because you replace the name on both draws it is <span class="math inline"><span class="math inline">\(p = \frac{1}{12}\)</span></span> in each draw. So <span class="math inline"><span class="math inline">\(p = \frac{1}{12} * \frac{1}{12}\)</span></span> and then
rounded to three decimal places
</p>
</li>
<li>
<p>
p = .006. In the first trial you have 10 out of 120, but as you
remove one inverted face the second trial is 9 out of 119. So the
formula is <span class="math inline"><span class="math inline">\(p = \frac{10}{120} * \frac{9}{119}\)</span></span>
</p>
</li>
</ol>
</div>
</div>
</div>
<div id="creating-a-simple-probability-distribution" class="section level3" number="4.2.2">
<h3>
<span class="header-section-number">4.2.2</span> Creating a Simple Probability Distribution<a class="anchor" aria-label="anchor" href="#creating-a-simple-probability-distribution"><i class="fas fa-link"></i></a>
</h3>
<p>We will now recap plotting probability distributions by looking at a simulated coin toss. You may remember some of this from the the PsyTeachR <a href="https://psyteachr.github.io/" target="_blank">Data SKills book</a> but don't worry if not as we are going to work through it again. Work or read through this example and then apply the logic to the quickfire questions at the end of the section.</p>
<p><strong>Scenario:</strong> Imagine we want to know the probability of X number of heads in 10 coin flips - for example, what is the probability of flipping a coin 10 times and it coming up heads two times.</p>
<p>To simulate 10 coin flips we will use the <code><a href="https://rdrr.io/r/base/sample.html">sample()</a></code> function where we randomly sample (with replacement) from all possible events: i.e. either <strong>heads</strong> or <strong>tails</strong>.</p>
<p><strong>Let's begin:</strong></p>
<ul>
<li>Open a new script and copy in the code lines below.
<ul>
<li>The first line of code loads in the library as normal.</li>
<li>The second line of code provides the instruction to sample our options "Heads" or "Tails", ten times, with replacement set to <code>TRUE</code>.</li>
</ul>
</li>
<li>
<strong>Note:</strong> Because our event labels are strings (text), we enter them into the function as a vector; i.e. in "quotes"</li>
<li>
<strong>Note:</strong> Below the lines of code, you will see the output that we got when we ran our code. Don't worry if your sequence of heads and tails is different from this output; this is to be expected as we are generating a random sample.</li>
</ul>
<div class="sourceCode" id="cb142"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="st"><a href="https://tidyverse.tidyverse.org">"tidyverse"</a></span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/sample.html">sample</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"HEADS"</span>, <span class="st">"TAILS"</span><span class="op">)</span>, <span class="fl">10</span>, <span class="cn">TRUE</span><span class="op">)</span> </span></code></pre></div>
<pre><code>##  [1] "TAILS" "HEADS" "TAILS" "HEADS" "TAILS" "TAILS" "TAILS" "HEADS" "HEADS"
## [10] "TAILS"</code></pre>
<ul>
<li>
<strong>Note:</strong> If you want to get the same output as we did, add this line of code to your script prior to loading in the library. This is the <code><a href="https://rdrr.io/r/base/Random.html">set.seed()</a></code> function which you can put a number in so that each time you run a randomisation you get the same number.</li>
</ul>
<div class="sourceCode" id="cb144"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span><span class="op">(</span><span class="fl">1409</span><span class="op">)</span></span></code></pre></div>
<div class="webex-solution">
<button>
Portfolio Point - Sampling and Replacement
</button>
<div class="info">
<p>
Sampling is simply choosing or selecting something - here we are
randomly choosing one of the possible options; heads or tails. Other
examples of ‘sampling’ include randomly selecting participants, randomly
choosing which stimuli to present on a given trial, or randomly
assigning participants to a condition e.g.drug or placebo…etc.
</p>
<p>
Replacement is putting the sampled option back into the ‘pot’ of
possible options. For example, on the first turn you randomly sample
HEADS from the options of HEADS and TAILS <strong>with
replacement</strong>, meaning that on the next turn you have the same
two options again; HEADS or TAILS. Sampling <strong>without
replacement</strong> means that you remove the option from subsequent
turns. So say on the first turn you randomly sample HEADS from the
options HEADS and TAILS but without replacement. Now on the second turn
you only have the option of TAILS to ‘randomly’ sample from. On the
third turn without replacement you would have no options.
</p>
<p>
So replacement means putting the option back for the next turn so
that on each turn you have all possible outcome options.
</p>
</div>
</div>
<p><br>
Why would you or why wouldn't you want to use sampling with replacement in our coin toss scenario? If you aren't sure then set replacement as <code>FALSE</code> (change the last argument from <code>TRUE</code> to <code>FALSE</code>) and run the code again. The code will stop working after 2 coin flips. We want to sample with replacement here because we want both options available at each sampling - and if we didn't then we would run out of options very quickly since we're doing 10 flips.</p>
<p>So far our code returns the outcomes from the 10 flips; either heads or tails. If we want to count how many 'heads' we have we can simply sum up the heads. However, heads isn't a number, so to make life easier we can re-label our events (i.e. our flips) as <strong>0 for tails</strong> and <strong>1 for heads</strong>. Now if we run the code again we can pipe the sample into a <code><a href="https://rdrr.io/r/base/sum.html">sum()</a></code> function to total up all the 1s (heads) from the 10 flips.</p>
<ul>
<li>Run this line of code a number of times, what do you notice about the output?</li>
<li>
<strong>Note:</strong> As our event labels are now numeric, we don't need the vector.</li>
<li>
<strong>Note:</strong> <code>0:1</code> means all numbers from 0 to 1 in increments of 1. So basically, 0 and 1.</li>
</ul>
<div class="sourceCode" id="cb145"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/sample.html">sample</a></span><span class="op">(</span><span class="fl">0</span><span class="op">:</span><span class="fl">1</span>, <span class="fl">10</span>, <span class="cn">TRUE</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="op">)</span> </span></code></pre></div>
<pre><code>## [1] 5</code></pre>
<p>The ouptut of this line changes every time we run the code as we are randomly sampling 10 coin flips each time. And to be clear, if you get an answer of 6 for example, this means 6 heads, and in turn, 4 tails. By running this code over and over again we are basically demonstrating how a <strong>sampling distribution</strong> is created.</p>
<div class="webex-solution">
<button>
Portfolio Point - What's a sampling distribution?
</button>
<div class="info">
<p>
A sampling distribution shows you the probability of drawing a sample
with certain characteristics from the population; e.g. the probability
of 5 heads in 10 flips, or the probability of 4 heads in 10 flips, or
the probability of X heads in 10 flips of the coin.
</p>
</div>
</div>
<p><br>
Now in order to create a full and accurate sampling distribution for our scenario we need to replicate these 10 flips a large number of times - i.e. replications. The more replications we do the more reliable the estimates. Let's do 10000 replications of our 10 coin flips. This means we flip the coin 10 times, count how many heads, save that number, and then repeat it 10000 times. We could do it the slow way we demonstrated above, just running the same line over and over and over again and noting the outcome each time. Or we could use the <code><a href="https://rdrr.io/r/base/lapply.html">replicate()</a></code> function.</p>
<ul>
<li>Copy the line of code below into your script and run it.</li>
<li>Here we are doing exactly as we said and saving the 10000 outputs (counts of heads) in the dataframe called <code>heads10k</code> (k is shorthand for thousand).</li>
</ul>
<div class="sourceCode" id="cb147"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">heads10k</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/lapply.html">replicate</a></span><span class="op">(</span><span class="fl">10000</span>, <span class="fu"><a href="https://rdrr.io/r/base/sample.html">sample</a></span><span class="op">(</span><span class="fl">0</span><span class="op">:</span><span class="fl">1</span>, <span class="fl">10</span>, <span class="cn">TRUE</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="op">)</span><span class="op">)</span>   </span></code></pre></div>
<p>To reiterate, the sum of heads (i.e., the number of times we got heads) from each of these 10000 replications are now stored as a <a class="glossary">vector<span class="def"></span></a> in <code>heads10k</code>. If you have a look at <code>heads10k</code>, as shown in the box below, it is a series of 10000 numbers between 0 and 10 each indicating the number of heads, or more specifically 1s, that you got in a set of 10 flips.</p>
<pre><code>##  int [1:10000] 7 4 5 6 2 6 2 6 8 5 ...</code></pre>
<p>Now, in order to complete our distribution we need to:</p>
<ol style="list-style-type: decimal">
<li>Convert the <a class="glossary">vector<span class="def"></span></a> (list of numbers for the heads counts) into a data frame (a tibble) so we can work on it. The numbers will be stored in a column called <code>heads</code>.</li>
<li>Then group the results by the number of possible <code>heads</code>; i.e. group all the times we got 5 heads together, all the times we got 4 heads together, etc.</li>
<li>Finally, we work out the probability of a <code>heads</code> result, (e.g., probability of 5 heads), by totaling the number of observations for each possible result (e.g., 5 heads) and submitting it to our probability formula above (number of outcomes of event divided by all possible outcomes)
<ul>
<li>so the number of times we got a specific number of heads (e.g., 5 heads) divided by the total number of outcomes (i.e., the number of replications - 10000).</li>
</ul>
</li>
</ol>
<p>We can carry out these steps using the following code:</p>
<ul>
<li>Copy the below code into your script and run it.</li>
</ul>
<div class="sourceCode" id="cb149"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">data10k</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://tibble.tidyverse.org/reference/tibble.html">tibble</a></span><span class="op">(</span>heads <span class="op">=</span> <span class="va">heads10k</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span>       <span class="co"># creating a tibble/data frame</span></span>
<span>                <span class="fu"><a href="https://dplyr.tidyverse.org/reference/group_by.html">group_by</a></span><span class="op">(</span><span class="va">heads</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span>           <span class="co"># group by number of possibilities</span></span>
<span>                <span class="fu"><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarise</a></span><span class="op">(</span>n <span class="op">=</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/context.html">n</a></span><span class="op">(</span><span class="op">)</span>, p<span class="op">=</span><span class="va">n</span><span class="op">/</span><span class="fl">10000</span><span class="op">)</span> <span class="co"># count occurences of possibility,</span></span>
<span>                                              <span class="co"># &amp; calculate probability (p) of</span></span>
<span>                                              <span class="co"># each</span></span></code></pre></div>
<p>We now have a discrete probability distribution of the number of heads in 10 coin flips. Use the <code><a href="https://rdrr.io/r/utils/View.html">View()</a></code> function to have look at your <code>data10k</code> variable. You should now see for each heads outcome, the total number of occurrences in 10000 replications (<code>n</code>) plus the probability of that outcome (<code>p</code>).</p>
<div class="inline-table"><table class="table table-sm">
<caption>
<span id="tab:coin-distribution-show">Table 4.1: </span>A sampling distribution for the number of heads in 10 flips of a coin. p = probability of obtaining that number of heads in 10000 replications of 10 flips of a coin
</caption>
<thead><tr>
<th style="text-align:center;">
heads
</th>
<th style="text-align:center;">
n
</th>
<th style="text-align:center;">
p
</th>
</tr></thead>
<tbody>
<tr>
<td style="text-align:center;">
0
</td>
<td style="text-align:center;">
7
</td>
<td style="text-align:center;">
0.0007
</td>
</tr>
<tr>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
82
</td>
<td style="text-align:center;">
0.0082
</td>
</tr>
<tr>
<td style="text-align:center;">
2
</td>
<td style="text-align:center;">
465
</td>
<td style="text-align:center;">
0.0465
</td>
</tr>
<tr>
<td style="text-align:center;">
3
</td>
<td style="text-align:center;">
1186
</td>
<td style="text-align:center;">
0.1186
</td>
</tr>
<tr>
<td style="text-align:center;">
4
</td>
<td style="text-align:center;">
2070
</td>
<td style="text-align:center;">
0.2070
</td>
</tr>
<tr>
<td style="text-align:center;">
5
</td>
<td style="text-align:center;">
2401
</td>
<td style="text-align:center;">
0.2401
</td>
</tr>
<tr>
<td style="text-align:center;">
6
</td>
<td style="text-align:center;">
2113
</td>
<td style="text-align:center;">
0.2113
</td>
</tr>
<tr>
<td style="text-align:center;">
7
</td>
<td style="text-align:center;">
1166
</td>
<td style="text-align:center;">
0.1166
</td>
</tr>
<tr>
<td style="text-align:center;">
8
</td>
<td style="text-align:center;">
422
</td>
<td style="text-align:center;">
0.0422
</td>
</tr>
<tr>
<td style="text-align:center;">
9
</td>
<td style="text-align:center;">
79
</td>
<td style="text-align:center;">
0.0079
</td>
</tr>
<tr>
<td style="text-align:center;">
10
</td>
<td style="text-align:center;">
9
</td>
<td style="text-align:center;">
0.0009
</td>
</tr>
</tbody>
</table></div>
<p>It will be useful to visualize the above distribution:</p>
<div class="sourceCode" id="cb150"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">data10k</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span><span class="va">heads</span>,<span class="va">p</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_bar.html">geom_col</a></span><span class="op">(</span>fill <span class="op">=</span> <span class="st">"skyblue"</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>x <span class="op">=</span> <span class="st">"Number of Heads"</span>, y <span class="op">=</span> <span class="st">"Probability of Heads in 10 flips (p)"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_bw</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_discrete.html">scale_x_discrete</a></span><span class="op">(</span>limits<span class="op">=</span><span class="fl">0</span><span class="op">:</span><span class="fl">10</span><span class="op">)</span></span></code></pre></div>
<pre><code>## Warning: Continuous limits supplied to discrete scale.
## i Did you mean `limits = factor(...)` or `scale_*_continuous()`?</code></pre>
<div class="figure" style="text-align: center">
<span style="display:block;" id="fig:10khist"></span>
<img src="04-s01-lab04b1_files/figure-html/10khist-1.png" alt="Probability Distribution of Number of Heads in 10 Flips" width="100%"><p class="caption">
Figure 4.1: Probability Distribution of Number of Heads in 10 Flips
</p>
</div>
<p>So in our analysis, the probability of getting 5 heads in 10 flips is <strong>0.2401</strong>. But remember, do not be surprised if you get a slightly different value. Ten thousand replications is a lot but not a huge amount compared to infinity. If you run the analysis with more replications your numbers would become more stable, e.g. <code>100K</code>.</p>
<p>Note that as the possible number of heads in 10 flips are <strong>all related to one another</strong>, then summing up all the probabilities of the different number of heads will give you a total of 1. This is different to what we looked at earlier in cards where the events were unrelated to each other. As such, you can use this information to start asking questions such as what would be the probability of obtaining 2 or less Heads in 10 flips? Well, if the probability of getting no heads (in 10 flips) in this distribution is <strong>0.0007</strong>, and the probability of getting 1 head is <strong>0.0082</strong>, and the probability of getting 2 heads is <strong>0.0465</strong>, then the probability of 2 or less Heads in this distribution is simply the sum of these values: <strong>0.0554</strong>. Pretty unlikely then!</p>
<p><span style="font-size: 22px; font-weight: bold; color: var(--green);">Quickfire Questions</span></p>
<p>Look at the probability values corresponding to the number of coin flips you created in the <code>data10k</code> sample distribution (use <code><a href="https://rdrr.io/r/utils/View.html">View()</a></code> to see this):</p>
<ul>
<li><p>Choose from the following options, if you wanted to calculate the probability of getting 4, 5 or 6 heads in 10 coin flips you would: <select class="webex-select"><option value="blank"></option>
<option value="">multiply individual probabilities together</option>
<option value="answer">sum individual probabilities together</option></select></p></li>
<li><p>Choose from the following options, if you wanted to calculate the probability of getting 6 or more heads in 10 coin flips you would: <select class="webex-select"><option value="blank"></option>
<option value="">multiply individual probabilities together</option>
<option value="answer">sum individual probabilities together</option></select></p></li>
<li><p>Choose from the following options, the distribution we have created is: <select class="webex-select"><option value="blank"></option>
<option value="">continuous</option>
<option value="answer">discrete</option></select></p></li>
</ul>
<div class="webex-solution">
<button>
Explain This - I don't understand the answers!
</button>
<div class="info">
<p>
If you think about it, we can’t get 5.5 heads or 2.3 heads, we can
only get whole numbers, 2 heads or 5 heads. This means that the data and
the distribution is discrete. (Don’t be confused by one of the functions
saying continuous)
</p>
<p>
To find the probability of getting say 4, 5, or 6 heads in 10 coin
flips, you are combining related scenarios together, therefore you need
to find the individual probabilities of getting 4, 5 or 6 heads in 10
coin flips, then sum the probabilities together to get the appropriate
probability of obtaining 4, 5 or 6 heads. It is the same with 6 or more
heads, just sum the probabilities of 6, 7, 8, 9 and 10 heads to get the
probability of 6 or more heads.
</p>
<p>
Not sure if you should be summing or multiplying probabilities? A
good way to remember, from both the coin flip examples and from the pack
of cards examples earlier, is that if the scenarios are
<strong>related</strong> you are summing probabilities, if scenarios are
<strong>separate</strong> you are multiplying probabilities.
<strong>Related</strong> scenarios are usually asking you about the
probability of <strong>‘either / or’</strong> scenarios occuring,
whereas <strong>separate</strong> scenarios usually ask about the
probability of one scenario <strong>‘and’</strong> another scenario both
occuring.
</p>
<p>
Your sample distribution <code>data10k</code> has already completed
the first part of this calculation for you (finding individual
probabilities of n heads in 10 coin flips), so all you need to to is sum
the required probabilities together!
</p>
</div>
</div>
</div>
<div id="the-binomial-distribution---creating-a-discrete-distribution" class="section level3" number="4.2.3">
<h3>
<span class="header-section-number">4.2.3</span> The Binomial Distribution - Creating a Discrete Distribution<a class="anchor" aria-label="anchor" href="#the-binomial-distribution---creating-a-discrete-distribution"><i class="fas fa-link"></i></a>
</h3>
<p>Great, so we are now learning how probabilities and distributions work. However, if we had wanted to calculate the probability of 8 heads from 10 coin flips, we don't have to go through this entire procedure each time. Instead, because we have a dichotomous outcome, "heads or tails", we can establish probabilities using the <strong>binomial distribution</strong> - effectively what you just created. You can look up the R help page on the binomial distribution (type <code><a href="https://rdrr.io/r/stats/Binomial.html">?dbinom</a></code> directly into the console) to understand how to use it but we will walk through some essentials here.</p>
<p>We'll use 3 functions to work with the binomial distribution and to ask some of the questions we have asked above:</p>
<ul>
<li><p><code><a href="https://rdrr.io/r/stats/Binomial.html">dbinom()</a></code> - <strong>the density function</strong>. This function gives you the probability of <code>x</code> successes (e.g., heads) given the <code>size</code> (e.g., number of trials) and probability of success <code>prob</code> on a single trial (here it's 0.5, because we assume we're flipping a fair coin - Heads or Tails)</p></li>
<li><p><code><a href="https://rdrr.io/r/stats/Binomial.html">pbinom()</a></code> - <strong>the cumulative probability function</strong>. This function gives you the probability of getting a number of successes below a certain cut-off point given the <code>size</code> and the <code>prob</code>. This would be for questions such as the probability of 5 heads or less for example. It sums the probability of 0, 1, 2, 3, 4, and 5 heads.</p></li>
<li><p><code><a href="https://rdrr.io/r/stats/Binomial.html">qbinom()</a></code> - <strong>the quantile function</strong>. This function is the inverse of <code>pbinom</code> in that it gives you the x-axis value below (and including the value) which the summation of probabilities is greater than or equal to a given probability <code>p</code>, given the <code>size</code> and <code>prob</code>. In other words, how many heads would you need to have a probability of <strong>p = 0.0554</strong></p></li>
</ul>
<p>Let's look at each of these functions in turn a little. The thing to keep in mind about probability is that every event has a likelihood of occurring on their distribution. We are trying to look at how those numbers come about and what they mean for us.</p>
</div>
<div id="dbinom---the-density-function" class="section level3" number="4.2.4">
<h3>
<span class="header-section-number">4.2.4</span> <strong><code>dbinom()</code></strong> - The Density Function<a class="anchor" aria-label="anchor" href="#dbinom---the-density-function"><i class="fas fa-link"></i></a>
</h3>
<p>Using the <code><a href="https://rdrr.io/r/stats/Binomial.html">dbinom()</a></code> function we can create probabilities for any possible outcomes where there are two possibilities of outcome on each trial - e.g., heads or tails, cats or dogs, black or red. We are going to stick with the coin flip idea. Here we are showing the code for obtaining 3 heads in 10 flips:</p>
<div class="sourceCode" id="cb152"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/Binomial.html">dbinom</a></span><span class="op">(</span><span class="fl">3</span>, <span class="fl">10</span>, <span class="fl">0.5</span><span class="op">)</span></span></code></pre></div>
<p>or all possible outcomes of heads (0:10) in 10 flips:</p>
<div class="sourceCode" id="cb153"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/Binomial.html">dbinom</a></span><span class="op">(</span><span class="fl">0</span><span class="op">:</span><span class="fl">10</span>, <span class="fl">10</span>, <span class="fl">0.5</span><span class="op">)</span></span></code></pre></div>
<p>And if we plot the probability of all possible outcomes in 10 flips it would look like this:</p>
<div class="figure" style="text-align: center">
<span style="display:block;" id="fig:binom-distrib1"></span>
<img src="04-s01-lab04b1_files/figure-html/binom-distrib1-1.png" alt="Probability Distribution of Number of Heads in 10 Flips" width="100%"><p class="caption">
Figure 4.2: Probability Distribution of Number of Heads in 10 Flips
</p>
</div>
<p>The dbinom (<strong>d</strong>ensity <strong>binom</strong>) function takes the format of <code>dbinom(x, size, prob)</code>, where the arguments we give are:</p>
<ul>
<li>
<code>x</code> the number of 'heads' we want to know the probability of. Either a single one, <code>3</code> or a series <code>0:10</code>.</li>
<li>
<code>size</code> the number of trials (flips) we are doing; in this case, 10 flips.</li>
<li>
<code>prob</code> the probability of 'heads' on one trial. Here chance is 50-50 which as a probability we state as 0.5 or .5</li>
</ul>
<p>Now say if we wanted to know the probability of 6 heads out of 10 flips. We would only have to change the first argument to the code we used above for 3 heads, as such:</p>
<div class="sourceCode" id="cb154"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/Binomial.html">dbinom</a></span><span class="op">(</span><span class="fl">6</span>, <span class="fl">10</span>, <span class="fl">0.5</span><span class="op">)</span></span></code></pre></div>
<pre><code>## [1] 0.2050781</code></pre>
<p>So the probability of 6 heads, using <code><a href="https://rdrr.io/r/stats/Binomial.html">dbinom()</a></code> is p = 0.2050781. If you compare this value to the <code>data10k</code> value for 6 you will see they are similar but not quite the same. This is because <code><a href="https://rdrr.io/r/stats/Binomial.html">dbinom()</a></code> uses a lot more replications than the 10000 we used in our simulation.</p>
<p>In terms of visualising what we have just calculated, p = 0.2050781 is the height of the green bar in the plot below.</p>
<div class="figure" style="text-align: center">
<span style="display:block;" id="fig:binom-plot1"></span>
<img src="04-s01-lab04b1_files/figure-html/binom-plot1-1.png" alt="Probability Distribution of Number of Heads in 10 Flips with the probability of 6 out of 10 Heads highlighted in green" width="100%"><p class="caption">
Figure 4.3: Probability Distribution of Number of Heads in 10 Flips with the probability of 6 out of 10 Heads highlighted in green
</p>
</div>
<p><span style="font-size: 22px; font-weight: bold; color: var(--green);">Quickfire Questions</span></p>
<ul>
<li>To three decimal places, what is the probability of 2 heads out of 10 flips? <input class="webex-solveme nospaces" size="10" data-answer='["0.044",".044"]'>
</li>
</ul>
<div class="webex-solution">
<button>
Explain This - I can't get the right answer
</button>
<div class="info">
<p>
You want to know the probability of 2 heads in 10 flips.
</p>
<ul>
<li>
X is therefore 2;
</li>
<li>
Size is therefore 10;
</li>
<li>
and the probability of outcomes on each trial stays the same at
.5.
</li>
</ul>
<p>
As such the would be <code>dbinom(2, 10, 0.5)</code> = .04394531 or
rounded = .044
</p>
</div>
</div>
</div>
<div id="pbinom---the-cumulative-probability-function" class="section level3" number="4.2.5">
<h3>
<span class="header-section-number">4.2.5</span> <strong><code>pbinom()</code></strong> - The Cumulative Probability Function<a class="anchor" aria-label="anchor" href="#pbinom---the-cumulative-probability-function"><i class="fas fa-link"></i></a>
</h3>
<p>What if we wanted to know the probability of <strong>up to and including</strong> 3 heads out of 10 flips? We have asked similar questions above. We can either use <code>dbinom</code> for each outcome up to 3 heads and sum the results:</p>
<div class="sourceCode" id="cb156"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/Binomial.html">dbinom</a></span><span class="op">(</span><span class="fl">0</span><span class="op">:</span><span class="fl">3</span>, <span class="fl">10</span>, <span class="fl">0.5</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="op">)</span></span></code></pre></div>
<pre><code>## [1] 0.171875</code></pre>
<p>Or we can use the <code><a href="https://rdrr.io/r/stats/Binomial.html">pbinom()</a></code> function; known as the <strong>cumulative probability distribution function</strong> or the <strong>cumulative density function</strong>. The first argument we give is the <strong>cut-off value up to and including</strong> the value which we want to know the probability of (here it's up to 3 <code>heads</code>). Then, as before, we tell it how many flips we want to do and the probability of <code>heads</code> on a single trial.</p>
<ul>
<li>Copy this line into your script and run it:</li>
</ul>
<div class="sourceCode" id="cb158"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/Binomial.html">pbinom</a></span><span class="op">(</span><span class="fl">3</span>, <span class="fl">10</span>, <span class="fl">0.5</span>, lower.tail <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>  </span></code></pre></div>
<pre><code>## [1] 0.171875</code></pre>
<p>So the probability of <strong>up to and including 3 heads</strong> out of 10 flips is <strong>0.172</strong>. For visualization, what we have done is calculated the cumulative probability of the lower tail of the distribution (<code>lower.tail = TRUE</code>; shown in green below) up to our cut-off of 3:</p>
<div class="figure" style="text-align: center">
<span style="display:block;" id="fig:binom-plot2"></span>
<img src="04-s01-lab04b1_files/figure-html/binom-plot2-1.png" alt="Probability Distribution of Number of Heads in 10 Flips with the probability of 0 to 3 Heads highlighted in green - `lower.tail = TRUE` " width="100%"><p class="caption">
Figure 4.4: Probability Distribution of Number of Heads in 10 Flips with the probability of 0 to 3 Heads highlighted in green - <code>lower.tail = TRUE</code>
</p>
</div>
<p>The <code>pbinom</code> function gives us the <strong>cumulative probability</strong> of outcomes <strong>up to and including the cut-off</strong>. But what if we wanted to know the probability of outcomes <strong>including and above</strong> a certain value? Say we want to know the probability of 7 heads or more out of 10 coin flips. The code would be this:</p>
<div class="sourceCode" id="cb160"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/Binomial.html">pbinom</a></span><span class="op">(</span><span class="fl">6</span>, <span class="fl">10</span>, <span class="fl">0.5</span>, lower.tail <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span> </span></code></pre></div>
<pre><code>## [1] 0.171875</code></pre>
<p>Let's explain this code a little.</p>
<ul>
<li>First, we switch the <code>lower.tail</code> call from <code>TRUE</code> to <code>FALSE</code> to tell <code><a href="https://rdrr.io/r/stats/Binomial.html">pbinom()</a></code> we don't want the lower tail of the distribution this time (to the left of and including the cut-off), we want the <strong>upper tail, to the right of the cut-off</strong>. This results in the cumulative probability for the upper tail of the distribution down to our cut-off value (shown in green below).</li>
<li>Next we have to specify a cut-off but instead of stating 7 as you might expect, even though we want 7 and above, we specify our cut-off as 6 heads. But why? We set the cut-off as '6' because when working with the discrete distribution, only <code>lower.tail = TRUE</code> includes the cut-off (6 and below) whereas <code>lower.tail = FALSE</code> would be everything above the cut-off <strong>but not including</strong> the cut-off (7 and above).</li>
<li>So in short, if we want the upper tail when using the discrete distribution we set our cut-off value (<code>x</code>) as one lower than the number we were interested in. We wanted to know about 7 heads so we set our cut-off as 6.</li>
</ul>
<div class="figure" style="text-align: center">
<span style="display:block;" id="fig:binom-plot3"></span>
<img src="04-s01-lab04b1_files/figure-html/binom-plot3-1.png" alt="Probability Distribution of Number of Heads in 10 Flips with the probability of 7 or more Heads highlighted in green - `lower.tail = FALSE`" width="100%"><p class="caption">
Figure 4.5: Probability Distribution of Number of Heads in 10 Flips with the probability of 7 or more Heads highlighted in green - <code>lower.tail = FALSE</code>
</p>
</div>
<div class="webex-solution">
<button>
Portfolio Point - All in a tail spin! Lower TRUE or FALSE
</button>
<div class="info">
<p>
The most confusing part for people we find is the concept of
<code>lower.tail</code>. If you look at a distribution, say the
binomial, you find a lot of the high bars are in the middle of the
distribution and the smaller bars are at the far left and right of the
distribution. Well the far left and right of the distribution is called
the <strong>tail</strong> of the distribution - they tend to be an
extremity of the distribution that taper off like a…..well like a tail.
A lot of the time we will talk of left and right tails but the
<code><a href="https://rdrr.io/r/stats/Binomial.html">pbinom()</a></code> function only ever considers data in relation to
the left side of the distribution - this is what it calls the
<code>lower.tail</code>.
</p>
<p>
Let’s consider <code>lower.tail = TRUE</code>. This is the default,
so if you don’t state <code>lower.tail = ...</code> then this is what is
considered to be what you want. <code>lower.tail = TRUE</code> means all
the values to the left of your value <strong>including</strong> the
value you state. So on the binomial distribution if you say give me the
probability of 5 heads or less, then you would set
<code>lower.tail = TRUE</code> and you would be counting and summing the
probability of 0, 1, 2, 3, 4 and 5 heads. You can check this with
<code>dbinom(0:5, 10, .5) %&gt;% sum()</code>.
</p>
<p>
However, if you say give me the probability of 7 or more heads, then
you need to do <code>lower.tail = FALSE</code>, to consider the
right-hand side tail, but also, you need to set the code as
<code>pbinom(6, 10, .5, lower.tail = FALSE)</code>. Why 6 and not 7?
Because the <code><a href="https://rdrr.io/r/stats/Binomial.html">pbinom()</a></code> function, when
<code>lower.tail = FALSE</code>, starts at the value <strong>plus one to
the value you state</strong>; it always considers the value you state as
being part of the <code>lower.tail</code> so if you say 6, it includes 6
in the <code>lower.tail</code> and then gives you 7, 8, 9 and 10 as the
upper tail. If you said 7 with <code>lower.tail = FALSE</code>, then it
would only give you 8, 9 and 10. This is tricky but worth keeping in
mind when you are using the <code><a href="https://rdrr.io/r/stats/Binomial.html">pbinom()</a></code> function. And
remember, you can always check it by using
<code>dbinom(7:10, 10, .5) %&gt;% sum()</code> and seeing whether it
matches <code>pbinom(6, 10, 0.5, lower.tail=FALSE)</code> or
<code>pbinom(7, 10, 0.5, lower.tail=FALSE)</code>
</p>
</div>
</div>
<p><br><span style="font-size: 22px; font-weight: bold; color: var(--green);">Quickfire Questions</span></p>
<ul>
<li><p>Using the format shown above for the <code><a href="https://rdrr.io/r/stats/Binomial.html">pbinom()</a></code> function, enter the code that would determine the probability of <strong>up to and including</strong> 5 heads out of 20 flips, assuming a probability of 0.5: <input class="webex-solveme nospaces" size="45" data-answer='["pbinom(5, 20, 0.5)","pbinom(5, 20, .5)","pbinom(5, 20, 0.5, lower.tail=TRUE)","pbinom(5, 20, .5, lower.tail=TRUE)"]'></p></li>
<li><p>To two decimal places, what is the probability of obtaining <strong>more than but not including</strong> 50 heads in 100 flips? <input class="webex-solveme nospaces" size="15" data-answer='[".46","0.46"]'></p></li>
</ul>
<div class="webex-solution">
<button>
Helpful Hint
</button>
<div class="info">
<ol style="list-style-type: decimal">
<li>
<p>
You are looking to calcuate the probability of 5 or less heads
(<code>x</code>) out of 20 flips (<code>size</code>), with the
probability of ‘heads’ in one trial (<code>prob</code>) remaining the
same. Do you need the <code>lower.tail</code> call here if you are
calculating the cumulative probability of the lower tail of the
distribution?
</p>
</li>
<li>
<p>
You are looking to calculate the probability of 51 or more heads
(<code>x</code>), out of 100 flips (<code>size</code>), with the
probability of ‘heads’ in one trial (<code>prob</code>) remaining the
same (<code>0.5</code>). Do you need the <code>lower.tail</code> call
here if you are calculating the cumulative probability of the upper tail
of the distribution? Remember, because you are not looking at the
<code>lower.tail</code>, the value of heads that you enter in
<code><a href="https://rdrr.io/r/stats/Binomial.html">pbinom()</a></code> will <strong>not</strong> be included in the final
calculation, e.g. entering
<code>pbinom(3, 100, lower.tail = FALSE)</code> will give you the
probability for 4 and above heads. If you were instead looking at the
<code>lower.tail</code>, entering
<code>pbinom(3, 100, lower.tail = TRUE)</code> would give you the
probability of 3 and below heads.
</p>
</li>
</ol>
</div>
</div>
<div class="webex-solution">
<button>
Explain This - I can't get these answers
</button>
<div class="info">
<ol style="list-style-type: decimal">
<li>
<p>
The code for the first one would be:
<code>pbinom(5, 20, 0.5)</code> or
<code>pbinom(5, 20, 0.5, lower.tail = TRUE)</code>
</p>
</li>
<li>
<p>
The code for the second one would be:
<code>pbinom(50, 100, 0.5, lower.tail = FALSE)</code>, giving an answer
of .46. Remember you can confirm this with:
<code>dbinom(51:100, 100, 0.5) %&gt;% sum()</code>
</p>
</li>
</ol>
</div>
</div>
<p><br></p>
</div>
<div id="qbinom---the-quantile-function" class="section level3" number="4.2.6">
<h3>
<span class="header-section-number">4.2.6</span> <strong><code>qbinom()</code></strong> - The Quantile Function<a class="anchor" aria-label="anchor" href="#qbinom---the-quantile-function"><i class="fas fa-link"></i></a>
</h3>
<p>The <code><a href="https://rdrr.io/r/stats/Binomial.html">qbinom()</a></code> function is the <strong>inverse</strong> of the <code><a href="https://rdrr.io/r/stats/Binomial.html">pbinom()</a></code> function. Whereas with <code><a href="https://rdrr.io/r/stats/Binomial.html">pbinom()</a></code> you supply an outcome value <code>x</code> and get a tail probability, with <code><a href="https://rdrr.io/r/stats/Binomial.html">qbinom()</a></code> you supply a tail probability and get the outcome value that (approximately) cuts off that tail probability. Think how you would rephrase the questions above in the <code><a href="https://rdrr.io/r/stats/Binomial.html">pbinom()</a></code> to ask a <code><a href="https://rdrr.io/r/stats/Binomial.html">qbinom()</a></code> question. Worth noting though that <code><a href="https://rdrr.io/r/stats/Binomial.html">qbinom()</a></code> is approximate with a discrete distribution because of the "jumps" in probability between the discrete outcomes (i.e. you can have probability of 2 heads or 3 heads but not 2.5 heads).</p>
<p>Let's see how these two functions are inverses of one another. Below is code for the probability of 49 heads or less in 100 coin flips</p>
<div class="sourceCode" id="cb162"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">p1</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Binomial.html">pbinom</a></span><span class="op">(</span><span class="fl">49</span>, <span class="fl">100</span>, <span class="fl">.5</span>, lower.tail <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span>
<span><span class="va">p1</span></span></code></pre></div>
<pre><code>## [1] 0.4602054</code></pre>
<p>This tells us that the probability is p = 0.4602054. If we now put that probability (stored in p1) into qbinom we get back to where we started. E.g.</p>
<div class="sourceCode" id="cb164"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/Binomial.html">qbinom</a></span><span class="op">(</span><span class="va">p1</span>, <span class="fl">100</span>, <span class="fl">.5</span>, lower.tail <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span></code></pre></div>
<pre><code>## [1] 49</code></pre>
<p>This can be stated as the number of heads required to obtain a probability of 0.4602054 is 49. So the <code><a href="https://rdrr.io/r/stats/Binomial.html">qbinom()</a></code> function is useful if you want to know the minimum number of successes (‘heads’) that would be needed to achieve a particular probability. This time the cut-off we specify is not the number of ‘heads’ we want but the <strong>probability</strong> we want.</p>
<p>For example say we want to know the minimum number of ‘heads’ out of 10 flips that would result in a 5% heads success rate (a probability of .05), we would use the following code.</p>
<div class="sourceCode" id="cb166"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/Binomial.html">qbinom</a></span><span class="op">(</span><span class="fl">.05</span>, <span class="fl">10</span>, <span class="fl">0.5</span>, lower.tail <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span> </span></code></pre></div>
<pre><code>## [1] 2</code></pre>
<p>Because we are dealing with the lower tail, this is telling us for a lower tail probability of .05, we would expect at most 2 heads in 10 flips. However, it is important to note that for a discrete distribution, this value is not exact. We can see this by:</p>
<div class="sourceCode" id="cb168"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/Binomial.html">pbinom</a></span><span class="op">(</span><span class="fl">2</span>, <span class="fl">10</span>, <span class="fl">.5</span>, lower.tail <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span> </span></code></pre></div>
<pre><code>## [1] 0.0546875</code></pre>
<p>This is not exactly p = .05 but very close. This is because the data we are working with is a discrete distribution and so <code><a href="https://rdrr.io/r/stats/Binomial.html">qbinom()</a></code> gives us the closest category to the boundary.</p>
<div class="webex-solution">
<button>
Portfolio Point - I don't understand qbinom arguments
</button>
<div class="info">
<p>
We found a lot of students asking about <code><a href="https://rdrr.io/r/stats/Binomial.html">qbinom()</a></code> and how
it works when you are inputting two different probabilities as the
arguments for <code><a href="https://rdrr.io/r/stats/Binomial.html">qbinom()</a></code>. Let us try and make things
clearer.
</p>
<p>
First, it is useful to remember that it is the inverse of
<code><a href="https://rdrr.io/r/stats/Binomial.html">pbinom()</a></code>: <code><a href="https://rdrr.io/r/stats/Binomial.html">pbinom()</a></code> gives you a tail
probability associated with <code>x</code>, and <code><a href="https://rdrr.io/r/stats/Binomial.html">qbinom()</a></code>
gives you the closest <code>x</code> that cuts off the specified tail
probability. If you understand <code><a href="https://rdrr.io/r/stats/Binomial.html">pbinom()</a></code> then try reversing
the question and see if that helps you understand
<code><a href="https://rdrr.io/r/stats/Binomial.html">qbinom()</a></code>.
</p>
<p>
The <code><a href="https://rdrr.io/r/stats/Binomial.html">qbinom()</a></code> function is set up as
<code>qbinom(p, size, prob)</code>. First of all, you have used
<code>prob</code> in the previous two functions, <code><a href="https://rdrr.io/r/stats/Binomial.html">dbinom()</a></code>
and <code><a href="https://rdrr.io/r/stats/Binomial.html">pbinom()</a></code>, and it represents the probability of success
on a single trial (here it is the probability of ‘heads’ in one coin
flip, <code>prob</code> = .5). Now, <code>prob</code> represents the
probability of success in <strong>one</strong> trial, whereas
<code>p</code> represents the tail probability you want to know about.
The function gives you the value of <code>x</code> that would yield that
probability you asked for. So you give <code><a href="https://rdrr.io/r/stats/Binomial.html">qbinom()</a></code> a tail
probability of p = .05, in 10 flips, when the probability of a success
on any one flip is prob = .5. And it tells you the answer is 2, meaning
that getting up to 2 flips on 10 trials has a probability of roughly
.05.
</p>
<p>
<code><a href="https://rdrr.io/r/stats/Binomial.html">qbinom()</a></code> also uses the <code>lower.tail</code> argument
and it works in a similar fashion to <code><a href="https://rdrr.io/r/stats/Binomial.html">pbinom()</a></code>.
</p>
</div>
</div>
<p><br><span style="font-size: 22px; font-weight: bold; color: var(--green);">Quickfire Questions</span></p>
<ul>
<li>Type in the box, the maximum number of heads associated with a tail probability of 10% (.1) in 17 flips: <input class="webex-solveme nospaces" size="1" data-answer='["6"]'>
</li>
</ul>
<div class="webex-solution">
<button>
Explain This - I can't get the answer
</button>
<div class="info">
<p>
The answer would be 6 because the code would be:
</p>
<p>
<code>qbinom(0.1, 17, 0.5, lower.tail = TRUE)</code>
</p>
<p>
Remember that you want an overall probability of 10% (<code>p</code>
= .1), you have 17 flips in each go (<code>size</code> = 17), and the
probability of heads on any one flip is .5 (<code>prob</code> = .5). And
you want the maximum number for the lower tail, so the
<code>lower.tail</code> is TRUE.
</p>
</div>
</div>
<p><br></p>
<p>Keep in mind: You are trying to get an understanding that every value in a distribution has a probability of existing in that distribution. That probability may be very large, meaning that, for bell-shaped distributions we have looked at, the value is from the middle of the distribution, or that probability might be rather low, meaning it is from the tail, but ultimately every value of a distribution has a probability.</p>

</div>
</div>
<div id="continuous-data-and-normal-distribution" class="section level2" number="4.3">
<h2>
<span class="header-section-number">4.3</span> Continuous Data and Normal Distribution<a class="anchor" aria-label="anchor" href="#continuous-data-and-normal-distribution"><i class="fas fa-link"></i></a>
</h2>
<div id="continuous-data-properties" class="section level3" number="4.3.1">
<h3>
<span class="header-section-number">4.3.1</span> Continuous Data Properties<a class="anchor" aria-label="anchor" href="#continuous-data-properties"><i class="fas fa-link"></i></a>
</h3>
<p>In the previous section, we have seen how we can use a distribution to estimate probabilities and determine cut-off values (these will play an important part in hypothesis testing in later chapters), but we have looked only at the <strong>discrete binomial distribution</strong>. Many of the variables we will encounter will be <strong>continuous</strong> and tend to show a <strong>normal distribution</strong> (e.g., height, weight, IQ).</p>
<p>Let's say we're interested in the height of the <a class="glossary">population<span class="def"></span></a> of psychology students, which we estimate to be between 146cm and 194cm. If we plotted this as a continuous, normal distribution, it will look like:</p>
<div class="figure" style="text-align: center">
<span style="display:block;" id="fig:normplot1"></span>
<img src="04-s01-lab04b2_files/figure-html/normplot1-1.png" alt="The Normal Distribution of height in Psychology students (black line). Green line represents the mean. Blue line represent 1 Standard Deviation from the mean. Yellow line represents 2 Standard Deviation from the mean. Red line represents 3 Standard Deviation from the mean." width="100%"><p class="caption">
Figure 4.6: The Normal Distribution of height in Psychology students (black line). Green line represents the mean. Blue line represent 1 Standard Deviation from the mean. Yellow line represents 2 Standard Deviation from the mean. Red line represents 3 Standard Deviation from the mean.
</p>
</div>
<p>The figure shows the hypothetical probability density of heights ranging from 146cm to 194cm in the population of Psychology students (black curve). This data is <strong>normally distributed</strong> and has the following properties:</p>
<p><span style="font-size: 22px; font-weight: bold; color: var(--black);">Properties of the Normal distribution</span></p>
<p><strong>1. The distribution is defined by its mean and standard deviation:</strong> The mean (<span class="math inline">\(\mu\)</span>) describes the center, and therefore peak density, of the distribution. This is where the largest number of the people in the population will be in terms of height. The standard deviation (<span class="math inline">\(\sigma\)</span>) describes how much variation there is from the mean of the distribution - on the figure, the standard deviation is the distance from the mean to the inflection point of the curve (the part where the curve changes from a upside-down bowl shape to a right-side-up bowl shape).</p>
<p><strong>2. Distribution is symmetrical around the mean:</strong> The mean lies in the middle of the distribution and divides the area under the curve into two equal sections - so we get the typical bell-shaped curve.</p>
<p><strong>3. Total area under the curve is equal to 1:</strong> If we were to add up the probabilities (densities) for every possible height, we would end up with a value of 1.</p>
<p><strong>4. The mean, median and mode are all equal:</strong> A good way to check if a given dataset is normally distributed is to calculate each measure of central tendency and see if they are approximately the same (normal distribution) or not (skewed distribution).</p>
<p><strong>5. The curve approaches, but never touches, the x axis:</strong> You will never have a probability of 0 for a given x axis value.</p>
<p><strong>6. The normal distribution follows the Empirical Rule:</strong> The Empirical Rule states that 99.7% of the data within the normal distribution falls within three standard deviations (<span class="math inline">\(\pm3\sigma\)</span>) from the mean, 95% falls within two standard deviations (<span class="math inline">\(\pm2\sigma\)</span>), and 68% falls within one standard deviation (<span class="math inline">\(\pm\sigma\)</span>).</p>
<p>Continuous data can take any precise and specific value on a scale, e.g. 1.1, 1.2, 1.11, 1.111, 1.11111. Many of the variables we will encounter in Psychology will:</p>
<ul>
<li>be <strong>continuous</strong> as opposed to discrete.</li>
<li>tend to show a <strong>normal distribution</strong>.</li>
<li>look similar to below - the bell-shaped curve - when plotted.</li>
</ul>
</div>
<div id="estimating-from-the-normal-distribution" class="section level3" number="4.3.2">
<h3>
<span class="header-section-number">4.3.2</span> Estimating from the Normal Distribution<a class="anchor" aria-label="anchor" href="#estimating-from-the-normal-distribution"><i class="fas fa-link"></i></a>
</h3>
<p>Unlike coin flips, the outcome in the normal distribution is not just 50/50 and as such we won't ask you to create a normal distribution as it is more complicated than the binomial distribution you estimated in the previous section. Instead, just as with the binomial distribution (and other distributions) there are functions that allow us to estimate the normal distribution and to ask questions about the distribution. These are:</p>
<ul>
<li>
<code><a href="https://rdrr.io/r/stats/Normal.html">dnorm()</a></code> - the Density function for the normal distribution</li>
<li>
<code><a href="https://rdrr.io/r/stats/Normal.html">pnorm()</a></code> - the Cumulative Probability function for the normal distribution</li>
<li>
<code><a href="https://rdrr.io/r/stats/Normal.html">qnorm()</a></code> - the Quantile function for the normal distribution</li>
</ul>
<p>You might be thinking those look familiar. They do in fact work in a similar way to their binomial counterparts. If you are unsure about how a function works remember you can call the help on it by typing in the console, for example, <code><a href="https://rdrr.io/r/stats/Normal.html">?dnorm</a></code> or <code>?dnorm()</code>.
<br></p>
<p><span style="font-size: 22px; font-weight: bold; color: var(--green);">Quickfire Questions</span></p>
<ul>
<li><p>Type in the box the binomial counterpart to <code><a href="https://rdrr.io/r/stats/Normal.html">dnorm()</a></code>? <input class="webex-solveme nospaces" size="10" data-answer='["dbinom()"]'></p></li>
<li><p>Type in the box the binomial counterpart to <code><a href="https://rdrr.io/r/stats/Normal.html">pnorm()</a></code>? <input class="webex-solveme nospaces" size="10" data-answer='["pbinom()"]'></p></li>
<li><p>Type in the box the binomial counterpart to <code><a href="https://rdrr.io/r/stats/Normal.html">qnorm()</a></code>? <input class="webex-solveme nospaces" size="10" data-answer='["qbinom()"]'></p></li>
</ul>
<div class="webex-solution">
<button>
Explain This - I don't get the answers
</button>
<div class="info">
<p>
The counterpart functions all start with the same letter, d, p, q, it
is just the distribution name that changes, <code>binom</code>,
<code>norm</code>, <code>t</code> - though we haven’t quite come across
the t-distribution yet.
</p>
<ol style="list-style-type: decimal">
<li>
<p>
<code><a href="https://rdrr.io/r/stats/Binomial.html">dbinom()</a></code> is the binomial equivalent to
<code><a href="https://rdrr.io/r/stats/Normal.html">dnorm()</a></code>
</p>
</li>
<li>
<p>
<code><a href="https://rdrr.io/r/stats/Binomial.html">pbinom()</a></code> is the binomial equivalent to
<code><a href="https://rdrr.io/r/stats/Normal.html">pnorm()</a></code>
</p>
</li>
<li>
<p>
<code><a href="https://rdrr.io/r/stats/Binomial.html">qbinom()</a></code> is the binomial equivalent to
<code><a href="https://rdrr.io/r/stats/Normal.html">qnorm()</a></code>
</p>
</li>
</ol>
<p>
There is also <code><a href="https://rdrr.io/r/stats/Normal.html">rnorm()</a></code> and <code><a href="https://rdrr.io/r/stats/Binomial.html">rbinom()</a></code> but we
will look at them another time.
</p>
</div>
</div>
</div>
<div id="dnorm---the-density-function" class="section level3" number="4.3.3">
<h3>
<span class="header-section-number">4.3.3</span> <strong><code>dnorm()</code></strong> - The Density Function<a class="anchor" aria-label="anchor" href="#dnorm---the-density-function"><i class="fas fa-link"></i></a>
</h3>
<p>Using <code><a href="https://rdrr.io/r/stats/Normal.html">dnorm()</a></code>, like we did with <code>dbinom</code>, we can plot a normal distribution. This time however we need:</p>
<ul>
<li>
<code>x</code>, a vector of quantiles (in other words, a series of values for the x-axis - think of this as the max and min of the distribution we want to plot)</li>
<li>the <code>mean</code> of our data</li>
<li>and standard deviation <code>sd</code> of our data.</li>
</ul>
<p>We will use IQ as an example. There is actually some disagreement of whether or not IQ is continuous data and to some degree it will depend on the measurement you use. IQ however is definitely normally distributed and we will assume it is continuous for the purposes of this demonstration. Many Psychologists are interested in studying IQ, perhaps in terms of heritability, or interested in controlling for IQ in their own studies to rule out any effect (e.g., clinical and autism studies).</p>
<div id="Ch4InClassQueT1" class="section level4" number="4.3.3.1">
<h4>
<span class="header-section-number">4.3.3.1</span> Task 1: Standard Deviations and IQ Score Distribution<a class="anchor" aria-label="anchor" href="#Ch4InClassQueT1"><i class="fas fa-link"></i></a>
</h4>
<ol style="list-style-type: decimal">
<li>Copy the below code into a new script and run it. Remember that you will need to call <code>tidyverse</code> to your library first.</li>
</ol>
<p>This code creates the below plot showing a normal distribution of IQ scores (M = 100, SD = 15) ranging from 40 to 160. These are values considered typical for the general population.</p>
<ul>
<li>First we set up our range of IQ values from 40 to 160</li>
<li>Then we plot the distribution of IQ_data, where we have M = 100 and SD = 15</li>
</ul>
<div class="sourceCode" id="cb170"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">IQ_data</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://tibble.tidyverse.org/reference/tibble.html">tibble</a></span><span class="op">(</span>IQ_range <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">40</span>, <span class="fl">160</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">IQ_data</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span><span class="va">IQ_range</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_function.html">stat_function</a></span><span class="op">(</span>fun <span class="op">=</span> <span class="va">dnorm</span>, args <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span>mean <span class="op">=</span> <span class="fl">100</span>, sd <span class="op">=</span> <span class="fl">15</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>x <span class="op">=</span> <span class="st">"IQ Score"</span>, y <span class="op">=</span> <span class="st">"probability"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_classic</a></span><span class="op">(</span><span class="op">)</span></span></code></pre></div>
<div class="figure" style="text-align: center">
<span style="display:block;" id="fig:normplot"></span>
<img src="04-s01-lab04b2_files/figure-html/normplot-1.png" alt="Distribution of IQ scores with mean = 100, sd = 15" width="100%"><p class="caption">
Figure 4.7: Distribution of IQ scores with mean = 100, sd = 15
</p>
</div>
<ul>
<li>Which part of the code do you need to change to alter the SD of your plot? <select class="webex-select"><option value="blank"></option>
<option value="">mean = 100</option>
<option value="answer">sd = 15</option>
<option value="">(40, 160)</option></select>
</li>
</ul>
<ol start="2" style="list-style-type: decimal">
<li>Now copy and edit the above code to plot a distribution with <code>mean = 100</code> and <code>sd = 10</code>, and visually compare the two plots.
<br>
</li>
</ol>
<p><span style="font-size: 22px; font-weight: bold; color: var(--pink);">Thinking Cap Point</span></p>
<p>What does changing the standard deviation (<code>sd</code>) do to the shape of the distribution? Spend a few minutes changing the code to various values and running it, and discussing with your group to answer the following questions:</p>
<ul>
<li><p>What happens to the shape of the distribution if you change the <code>sd</code> from 10 to 20? <select class="webex-select"><option value="blank"></option>
<option value="">the distribution gets narrower</option>
<option value="answer">the distribution gets wider</option></select></p></li>
<li><p>What happens to the shape of the distribution if you change the <code>sd</code> from 10 to 5? <select class="webex-select"><option value="blank"></option>
<option value="answer">the distribution gets narrower</option>
<option value="">the distribution gets wider</option></select></p></li>
<li><p>What does a small or large standard deviation in your sample tell you about the data you have collected?</p></li>
</ul>
<div class="webex-solution">
<button>
Explain This - I don't get Standard Deviations!
</button>
<div class="info">
<ol style="list-style-type: decimal">
<li>
Changing the SD from 10 to 20 means a larger standard deviation so
you will have a wider distribution.
</li>
<li>
Changing the SD from 10 to 5 means a smaller standard deviation so
you will have a narrower distribution.
</li>
<li>
Smaller SD results in a narrower distribution meaning that the data
is less spread out; larger SD results in a wider distribution meaning
the data is more spread out.
</li>
</ol>
<p>
<strong>A note on the Standard Deviation</strong>:
</p>
<p>
You will know from your lectures that you can estimate data in two
ways: point-estimates and spread estimates. The mean is a point-estimate
and condenses all your data down into one data point - it tells you the
average value of all your data but tells you nothing about how spread
out the data is. The standard deviation however is a spread estimate and
gives you an estimate of how spread out your data is from the mean - it
is a measure of the standard deviation from the mean.
</p>
<p>
So imagine we are looking at IQ scores and you test 100 people and
get a mean of 100 and an SD of 5. This means that the vast majority of
your sample will have an IQ around 100 - probably most will fall within
1 SD of the mean, meaning that most of your participants will have an IQ
of between 95 and 105.
</p>
<p>
Now if you test again and find a mean of 100 and an SD of 20, this
means your data is much more spread out. If you take the 1 SD approach
again then most of your participants will have an IQ of between 80 and
120.
</p>
<p>
So one sample has a very tight range of IQs and the other sample has
a very wide range of IQs. All in, from the point-estimate and spread
estimate of your data you can tell the shape of your sample
distribution.
</p>
</div>
</div>
<p><br>
So far so good! But in the above example we told <code><a href="https://rdrr.io/r/stats/Normal.html">dnorm()</a></code> the values at the limit of our range and it did the rest; we said give us a range of 40 to 160 IQ scores. However, we could plot it another way by telling <code><a href="https://rdrr.io/r/stats/Normal.html">dnorm()</a></code> the sequence, or range, of values we want and how much precision we want between them.</p>
</div>
<div id="Ch4InClassQueT2" class="section level4" number="4.3.3.2">
<h4>
<span class="header-section-number">4.3.3.2</span> Task 2: Changing Range and Step Size of The Normal Distribution<a class="anchor" aria-label="anchor" href="#Ch4InClassQueT2"><i class="fas fa-link"></i></a>
</h4>
<ol style="list-style-type: decimal">
<li>Copy the code below in to your script and run it.
Here we plot the standard Normal Distribution from -4 to 4 in steps of 0.01. We have also stated a mean of 0 and an sd of 1.</li>
</ol>
<div class="sourceCode" id="cb171"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">ND_data</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://tibble.tidyverse.org/reference/tibble.html">tibble</a></span><span class="op">(</span>ND_range <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/seq.html">seq</a></span><span class="op">(</span><span class="op">-</span><span class="fl">4</span>, <span class="fl">4</span>, <span class="fl">0.01</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">ND_data</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span><span class="va">ND_range</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_function.html">stat_function</a></span><span class="op">(</span>fun <span class="op">=</span> <span class="va">dnorm</span>, args <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span>mean <span class="op">=</span> <span class="fl">0</span>, sd <span class="op">=</span> <span class="fl">1</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>x <span class="op">=</span> <span class="st">"SD units"</span>, y <span class="op">=</span> <span class="st">"probability"</span>, title <span class="op">=</span> <span class="st">"The Normal Distribution"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_classic</a></span><span class="op">(</span><span class="op">)</span></span></code></pre></div>
<div class="figure" style="text-align: center">
<span style="display:block;" id="fig:ND-example"></span>
<img src="04-s01-lab04b2_files/figure-html/ND-example-1.png" alt="The Normal Distribution with Mean = 0 and SD = 1" width="100%"><p class="caption">
Figure 4.8: The Normal Distribution with Mean = 0 and SD = 1
</p>
</div>
<p><br><span style="font-size: 22px; font-weight: bold; color: var(--green);">Quickfire Questions</span></p>
<ul>
<li>Fill in the box to show what you would type to create a tibble containing a column called <code>ND_range</code> that has values ranging from <code>-10</code> to <code>10</code> in steps of <code>.05</code>:</li>
</ul>
<p><strong>ND_data</strong> &lt;- <input class="webex-solveme nospaces" size="40" data-answer='["tibble(ND_range = seq(-10, 10, 0.05))","tibble(ND_range = seq(-10, 10, .05))"]'></p>
<p>Now that you know what to change, try plotting a normal distribution with the following attributes:</p>
<ul>
<li><p>range of -10 to 10 in steps of 0.05,</p></li>
<li><p>a mean of 0,</p></li>
<li><p>and a standard deviation of 1.</p></li>
<li><p>Compare your new plot the the original one we created. What change is there in the distribution? <select class="webex-select"><option value="blank"></option>
<option value="">Distribution widens</option>
<option value="answer">No change in distribution</option>
<option value="">Distribution narrows</option></select></p></li>
</ul>
<div class="webex-solution">
<button>
Explain This - I don't understand the answer!
</button>
<div class="info">
<p>
To change the distribution you would write:
<code>ND_data &lt;- tibble(ND_range = seq(-10, 10, 0.05))</code>
</p>
<p>
However, when comparing the plots, whilst the plot itself may look
thinner, the distribution has not changed. The change in appearance is
due to the range of <code>sd</code> values which have been extended from
-4 and 4 to -10 and 10. The density of values within those values has
not changed however and you will see, more clearly in the second plot,
that values beyond -3 and 3 are very unlikely.
</p>
</div>
</div>
<p>Remember, every value has a probability on a distribution and we have been able to use the <code><a href="https://rdrr.io/r/stats/Normal.html">dnorm()</a></code> function to get a visual representation of how the probability of values change in the normal distribution. Some values are very probable. Some values are less probable. This is a key concept when it comes to thinking about significant differences later.</p>
<p>However, as you know, there is one important difference between continuous and discrete probability distributions - the number of possible outcomes. With discrete probability distributions there are usually a finite number of outcomes over which you take a probability. For instance, with 5 coin flips, there are 5 possible outcomes for the number of heads: 0, 1, 2, 3, 4, 5. And because the binomial distribution has exact and finite outcomes, we can use <code><a href="https://rdrr.io/r/stats/Binomial.html">dbinom()</a></code> to get the exact probability for each outcome.</p>
<p>In contrast, with a truly continuous variable, the number of possible outcomes are infinite, because you not only have 0.01 but also .0000001 and .00000000001 to arbitrary levels of precision. So rather than asking for the probability of a single value, we ask the probability for a <strong>range of values</strong>, which is equal to the area under the curve (the black line in the plots above) for that range of values.</p>
<p>As such, we will leave <code><a href="https://rdrr.io/r/stats/Normal.html">dnorm()</a></code> for now and move onto looking at establishing the probability of a range of values using the Cumulative Probability function</p>
</div>
</div>
<div id="pnorm---the-cumulative-probability-function" class="section level3" number="4.3.4">
<h3>
<span class="header-section-number">4.3.4</span> <strong><code>pnorm()</code></strong> - The Cumulative Probability Function<a class="anchor" aria-label="anchor" href="#pnorm---the-cumulative-probability-function"><i class="fas fa-link"></i></a>
</h3>
<p>Just as <code><a href="https://rdrr.io/r/stats/Normal.html">dnorm()</a></code> works like <code><a href="https://rdrr.io/r/stats/Binomial.html">dbinom()</a></code>, <code><a href="https://rdrr.io/r/stats/Normal.html">pnorm()</a></code> works just like <code><a href="https://rdrr.io/r/stats/Binomial.html">pbinom()</a></code>. So, <code><a href="https://rdrr.io/r/stats/Normal.html">pnorm()</a></code>, given the <code>mean</code> and <code>sd</code> of our data, returns the <strong>cumulative density function (cumulative probability)</strong> that a given probability (<code>p</code>) lies at a specified <strong>cut-off point and below</strong>, unless of course <code>lower.tail = FALSE</code> is specified in which case it is from the <strong>cut-off point and above</strong>.</p>
<p>OK, in English that people can understand, that means the <code><a href="https://rdrr.io/r/stats/Normal.html">pnorm()</a></code> function tells you the probability of obtaining a given value or lower if you set <code>lower.tail = TRUE</code>. Contrastingly, <code><a href="https://rdrr.io/r/stats/Normal.html">pnorm()</a></code> function tells you the probability of obtaining a given value or higher if you set <code>lower.tail = FALSE</code>.</p>
<p>We will use height to give a concrete example. Say that we test a sample of students (M = 170cm, SD = 7) and we we want to calculate the probability that a given student is 150cm or shorter we would do the following:</p>
<ul>
<li>Remember, <code>lower.tail = TRUE</code> means lower than and including the value of X</li>
<li>
<code>TRUE</code> is the default so we don't actually need to declare it</li>
</ul>
<div class="sourceCode" id="cb172"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">pnorm</a></span><span class="op">(</span><span class="fl">150</span>, <span class="fl">170</span>, <span class="fl">7</span>, lower.tail <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span></code></pre></div>
<p>This tells us that finding the probability of someone 150cm or shorter in our class is about <strong>p = 0.0021374</strong>. Stated differently, we would expect the proportion of students to be 150cm or shorter to be <strong>0.21%</strong> (You can convert probability to proportion by multiplying the probability by 100). This is a very small probability and suggests that it is pretty unlikely to find someone shorter than 150cm in our class. This is mainly because of how small the standard deviation of our distribution is. Think back to what we said earlier about narrow standard deviations round the mean!</p>
<p>Another example might be, what would be the probability of a given student being 195 cm or taller? To do that, you would set the following code:</p>
<div class="sourceCode" id="cb173"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">pnorm</a></span><span class="op">(</span><span class="fl">195</span>, <span class="fl">170</span>, <span class="fl">7</span>, lower.tail <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></span></code></pre></div>
<p>This tells us that finding the probability of someone 195cm or taller in our class is <strong>0.02%</strong>. So again, really unlikely.</p>
<p>Did you notice something different about the cut-off for this example and from when using the <code><a href="https://rdrr.io/r/stats/Binomial.html">dbinom()</a></code> function and looking above a cut-off? Why might that be? We will discuss in a second but first a quick task.</p>
<div id="Ch4InClassQueT3" class="section level4" number="4.3.4.1">
<h4>
<span class="header-section-number">4.3.4.1</span> Task 3: Calculating Cumulative Probability of Height<a class="anchor" aria-label="anchor" href="#Ch4InClassQueT3"><i class="fas fa-link"></i></a>
</h4>
<ol style="list-style-type: decimal">
<li>Edit the <code><a href="https://rdrr.io/r/stats/Normal.html">pnorm()</a></code> code above to calculate the probability that a given student is 190cm <strong>or taller</strong>.</li>
</ol>
<p>To three decimal places, as in Task 3, what is the probability of a student being 190cm or taller in this class? <input class="webex-solveme nospaces" size="5" data-answer='["0.002",".002"]'></p>
<div class="webex-solution">
<button>
Explain This - I don't understand the answer or the tail!
</button>
<div class="info">
<p>
The answer is .002. See the solution code at the end of the
chapter.
</p>
<p>
The key thing is that there is a difference in where you need to
specify the cut-off point in the <code><a href="https://rdrr.io/r/stats/Binomial.html">pbinom()</a></code> (discussed in the
preclass activity) and <code><a href="https://rdrr.io/r/stats/Normal.html">pnorm()</a></code> functions for values
<strong>above</strong> <code>x</code>, i.e. when
<strong><code>lower.tail = FALSE</code></strong>.
</p>
<p>
If you had discrete data, say the number of coin flips that result in
<code>heads</code>, and wanted to calculate the probability above
<code>x</code>, you would apply <code><a href="https://rdrr.io/r/stats/Binomial.html">pbinom()</a></code> and have to
specify your cut-off point as <strong><code>x-1</code></strong> to
include <code>x</code> in your calculation. For example, to calculate
the probability of 4 or more ‘heads’ occuring in 10 coin flips, you
would specify <code>pbinom(3, 10, 0.5, lower.tail = FALSE)</code> as
<code>lower.tail</code> includes the value you state.
</p>
<p>
For continuous data, however, such as height, you would be applying
<code><a href="https://rdrr.io/r/stats/Normal.html">pnorm()</a></code> and therefore can specify your cut-off point simply
as <strong><code>x</code></strong>. In the above example, for the
cut-off point of 190, a mean of 170 and standard deviation of 7, you can
write <code>pnorm(190, 170, 7, lower.tail = FALSE)</code>. The way to
think about this is that setting <code>x</code> as 189 on a continuous
scale, when you only want all values greater than 190, would also
include all the possible values between 189 and 190. Setting
<code>x</code> at 190 starts it at 190.0000000…001.
</p>
<p>
This is a tricky difference between <code><a href="https://rdrr.io/r/stats/Binomial.html">pbinom()</a></code> and
<code><a href="https://rdrr.io/r/stats/Normal.html">pnorm()</a></code> to recall easily, so best include this explanation
point in your portfolio to help you carry out the correct analyses in
the future!
</p>
</div>
</div>
</div>
<div id="Ch4InClassQueT4" class="section level4" number="4.3.4.2">
<h4>
<span class="header-section-number">4.3.4.2</span> Task 4: Using Figures to Calculate Cumulative Probability<a class="anchor" aria-label="anchor" href="#Ch4InClassQueT4"><i class="fas fa-link"></i></a>
</h4>
<p>Have a look at the distribution below:</p>
<div class="figure" style="text-align: center">
<span style="display:block;" id="fig:pnormplot1"></span>
<img src="04-s01-lab04b2_files/figure-html/pnormplot1-1.png" alt="The Normal Distribution of Height with the probability of people of 185cm highlighted in purple, with a mean = 170cm and SD = 7" width="100%"><p class="caption">
Figure 4.9: The Normal Distribution of Height with the probability of people of 185cm highlighted in purple, with a mean = 170cm and SD = 7
</p>
</div>
<ol style="list-style-type: decimal">
<li>Using the information in the figure, and the mean and SD as above, calculate the probability associated with the shaded area.</li>
</ol>
<div class="webex-solution">
<button>
Helpful Hint
</button>
<div class="info">
<p>
You already have your mean and standard deviations to input in
<code><a href="https://rdrr.io/r/stats/Normal.html">pnorm()</a></code>, look at the shaded area to obtain your cut-off
point. What should the <code>lower.tail</code> call be set to according
to the shaded area?
</p>
</div>
</div>
<p><br><span style="font-size: 22px; font-weight: bold; color: var(--green);">Quickfire Question</span></p>
<p>To three decimal places, what is the cumulative probability of the shaded area in Task 4? <input class="webex-solveme nospaces" size="5" data-answer='["0.016",".016"]'></p>
<div class="webex-solution">
<button>
Explain This - I don't get this answer
</button>
<div class="info">
<p>
The answer should be p = .016. See the solution code at the end of
the chapter for the correct code.
</p>
<p>
Remember, <code>lower.tail</code> is set to FALSE as you want the
area to the right.
</p>
</div>
</div>
<p>So <code><a href="https://rdrr.io/r/stats/Normal.html">pnorm()</a></code> is great for telling us the probability of obtaining a specific value or greater on a distribution, given the mean and standard deviation of the distribution. The significance of this will come clearer in the coming chapters but this is a key point to have in mind as we progress through our understanding of analyses. We will leave it there for now and look at the last function of the normal distribution.</p>
</div>
</div>
<div id="qnorm---the-quantile-function" class="section level3" number="4.3.5">
<h3>
<span class="header-section-number">4.3.5</span> <strong><code>qnorm()</code></strong> - The Quantile Function<a class="anchor" aria-label="anchor" href="#qnorm---the-quantile-function"><i class="fas fa-link"></i></a>
</h3>
<p>Using <code><a href="https://rdrr.io/r/stats/Normal.html">qnorm()</a></code> we can do the inverse of <code><a href="https://rdrr.io/r/stats/Normal.html">pnorm()</a></code>, and instead of finding out the cumulative probability from a given set of values (or to a cut-off value), we can find a cut-off value given a desired probability. For example, we can use the <code><a href="https://rdrr.io/r/stats/Normal.html">qnorm()</a></code> function to ask what is the maximum IQ a person would have if they were in the bottom 10% of the above IQ distribution (<code>M = 100</code> &amp; <code>SD = 15</code>)?</p>
<ul>
<li>
<strong>Note:</strong> We first need to convert 10% to a probability by dividing by 100</li>
<li>10% = 10 / 100 = 0.1.</li>
</ul>
<div class="sourceCode" id="cb174"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">qnorm</a></span><span class="op">(</span><span class="fl">0.1</span>, <span class="fl">100</span>, <span class="fl">15</span><span class="op">)</span> </span></code></pre></div>
<p>So anyone with an IQ of <strong>80.8</strong> or lower would be in the bottom 10% of the distribution. Or to rephrase that, a person in the bottom 10% of the distribution would have a max IQ value of <strong>80.8</strong>.</p>
<p>To recap, we have calculated the <strong>inverse cumulative density function (or inverse of the cumulative probability)</strong> of the <strong>lower tail</strong> of the distribution, with a cut-off of a probability of 0.1 (10%), illustrated in purple below:</p>
<div class="figure" style="text-align: center">
<span style="display:block;" id="fig:pnormplot2"></span>
<img src="04-s01-lab04b2_files/figure-html/pnormplot2-1.png" alt="The Normal Distribution of Height with the bottom 10% of heights highlighted in purple" width="100%"><p class="caption">
Figure 4.10: The Normal Distribution of Height with the bottom 10% of heights highlighted in purple
</p>
</div>
<p>Again, in English that people can understand, that means the <code><a href="https://rdrr.io/r/stats/Normal.html">qnorm()</a></code> function tells you the maximum value a person can have to maintain a given probability if you set <code>lower.tail = TRUE</code>. Contrastingly, <code><a href="https://rdrr.io/r/stats/Normal.html">pnorm()</a></code> function tells you the the minimum value a person can have to maintain a given probability if you set <code>lower.tail = FALSE</code>.</p>
<div id="Ch4InClassQueT5" class="section level4" number="4.3.5.1">
<h4>
<span class="header-section-number">4.3.5.1</span> Task 5: Using <strong><code>pnorm()</code></strong> and <strong><code>qnorm()</code></strong> to find probability and cut-off values<a class="anchor" aria-label="anchor" href="#Ch4InClassQueT5"><i class="fas fa-link"></i></a>
</h4>
<ol style="list-style-type: decimal">
<li><p>Calculate the lowest IQ score a student must have to be in the top 5% of the above distribution.</p></li>
<li><p>More challenging: Using the appropriate normal distribution function, calculate the probability that a given student will have an IQ between 105 and 110, on a normal distribution of mean = 100, sd = 15.</p></li>
</ol>
<div class="webex-solution">
<button>
Helpful Hint
</button>
<div class="info">
<p>
Part 1: Remember to include the <code>lower.tail</code> call if
required! If you are unsure, visualise what you are trying to find
(i.e. the lowest IQ score you can have to be in top 5%) by sketching it
out on a normal distribution curve. It may help to reverse the question
to sound more like the previous example.
</p>
<p>
Part 2: For the second part, each function, not necessarily
<code><a href="https://rdrr.io/r/stats/Normal.html">qnorm()</a></code>, gives one value, so you are looking to do a
separate calculation for each IQ. Then you have to combine these two
values, but are you summing or subtracting them? Is it more or less
likely for students to have an IQ that falls between this range than
above or below a cut-off? Again try sketching out what you are trying to
achieve.
</p>
</div>
</div>
<p><br><span style="font-size: 22px; font-weight: bold; color: var(--green);">Quickfire Questions</span></p>
<ul>
<li><p>To one decimal place, enter your answer for Task 5 part 1: What is the lowest IQ score a student must have to be in the top 5% of the distribution? <input class="webex-solveme nospaces" size="5" data-answer='["124.7"]'></p></li>
<li><p>To two decimal places, enter your answer for Task 5 part 2: What is the probability that a student will have an IQ between 105 and 110, on a normal distribution of mean = 100, sd = 15? <input class="webex-solveme nospaces" size="4" data-answer='["0.12",".12"]'><br></p></li>
</ul>
<div class="webex-solution">
<button>
Explain This - I dont get this answer
</button>
<div class="info">
<ol style="list-style-type: decimal">
<li>
<p>
The question can be rephrased as what value would give you 95% of
the distribution - and the answer would be 124.7. See the solution code
for Task 5 Question 1 at the end of the chapter.
</p>
</li>
<li>
<p>
You could use <code><a href="https://rdrr.io/r/stats/Normal.html">pnorm()</a></code> to establish the probability
of an IQ of 110. And you could use <code><a href="https://rdrr.io/r/stats/Normal.html">pnorm()</a></code> again to
establish the probability of an IQ of 105. The answer is the difference
between these two probabilities and should be p = .12. See the solution
code for Task 5 Question 2 at the end of the chapter.
</p>
</li>
</ol>
</div>
</div>

</div>
</div>
</div>
<div id="practice-your-skills-4" class="section level2" number="4.4">
<h2>
<span class="header-section-number">4.4</span> Practice Your Skills<a class="anchor" aria-label="anchor" href="#practice-your-skills-4"><i class="fas fa-link"></i></a>
</h2>
<p>In order to complete this exercise, you first have to download the assignment .Rmd file which you need to edit - titled <code>GUID_Ch4_PracticeSkills_Probabilities.Rmd</code>. This can be downloaded within a zip file from the link below. Once downloaded and unzipped you should create a new folder that you will use as your working directory; put the .Rmd file in that folder and set your working directory to that folder through the drop-down menus at the top. <a href="data/04-s01/homework/ch4_practiceyourskills.zip">Download the Assignment .zip file from here</a>.</p>
<p>Now open the assignment .Rmd file within RStudio. You will see there is a code chunk for each of the 10 tasks. Follow the instructions on what to edit in each code chunk. This will often be entering code or a single value and will be based on the skills learnt in the current chapter as well as all previous chapters.</p>
<div id="topic-probabilities" class="section level3" number="4.4.1">
<h3>
<span class="header-section-number">4.4.1</span> Topic: Probabilities<a class="anchor" aria-label="anchor" href="#topic-probabilities"><i class="fas fa-link"></i></a>
</h3>
<p>You recapped and expanded on your understanding of probability, including a number of <code>binom</code> and <code>norm</code> functions as well as some more basic ideas on probability. You will need these skills to complete the following exercises.</p>
<p><strong>Before starting, let's check</strong></p>
<ol style="list-style-type: decimal">
<li>The .Rmd file is saved into a folder on your computer that you have access to and you have manually set this folder as your working directory. For assessments we ask that you save it with the format GUID_Ch4_PracticeSkills_Probabilities.Rmd where GUID is replaced with your GUID. Though this is a practice exercise it may be good practice to do the same here.</li>
</ol>
<p><strong>Note:</strong> You should complete the code chunks below by replacing the <code>NULL</code> (except the library chunk where the appropriate code should just be entered). Not all answers require coding. On those that do not require code, you can enter the answer as either code, mathematical notation, or an actual single value. Pay attention to the number of decimal places required.</p>
</div>
<div id="Ch4AssignQueLib" class="section level3" number="4.4.2">
<h3>
<span class="header-section-number">4.4.2</span> Load in the Library<a class="anchor" aria-label="anchor" href="#Ch4AssignQueLib"><i class="fas fa-link"></i></a>
</h3>
<p>There is a good chance that you will need the tidyverse library at some point in this exercise so load it in the code chunk below:</p>
<div class="sourceCode" id="cb175"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># hint: something to do with library() and tidyverse</span></span></code></pre></div>
<p><strong>Basic probability and the binomial distribution questions</strong></p>
<p><strong>Background Information:</strong> You are conducting an auditory discrimination experiment in which participants have to listen to a series of sounds and determine whether the sound was human or not. On each trial participants hear one brief sound (100 ms) and must report whether the sound was from a human (coded as 1) or not (coded as 0). The sounds were either: a person, an animal, a vehicle, or a tone, with each type of sound equally likely to appear.</p>
</div>
<div id="Ch4AssignQueT1" class="section level3" number="4.4.3">
<h3>
<span class="header-section-number">4.4.3</span> Task 1<a class="anchor" aria-label="anchor" href="#Ch4AssignQueT1"><i class="fas fa-link"></i></a>
</h3>
<p>On a single trial, what is the probability that the sound will not be a person? Replace the <code>NULL</code> in the t1 code chunk with either mathematical notation or a single value. If entering a single value, give your answer to two decimal places.</p>
<div class="sourceCode" id="cb176"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">t1</span> <span class="op">&lt;-</span> <span class="cn">NULL</span></span></code></pre></div>
</div>
<div id="Ch4AssignQueT2" class="section level3" number="4.4.4">
<h3>
<span class="header-section-number">4.4.4</span> Task 2<a class="anchor" aria-label="anchor" href="#Ch4AssignQueT2"><i class="fas fa-link"></i></a>
</h3>
<p>Over a sequence of 4 trials, with one trial for each sound, and sampled with replacement, what is the probability of the following sequence of sounds: animal, animal, vehicle, tone? Replace the <code>NULL</code> in the t2 code chunk with either mathematical notation or a single value. If entering a single value, give your answer to three decimal places.</p>
<div class="sourceCode" id="cb177"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">t2</span> <span class="op">&lt;-</span> <span class="cn">NULL</span></span></code></pre></div>
</div>
<div id="Ch4AssignQueT3" class="section level3" number="4.4.5">
<h3>
<span class="header-section-number">4.4.5</span> Task 3<a class="anchor" aria-label="anchor" href="#Ch4AssignQueT3"><i class="fas fa-link"></i></a>
</h3>
<p>Over a sequence of four trials, with one trial for each sound, without replacement, what is the probability of the following sequence of sounds: person, tone, animal, person? Replace the NULL in the t3 code chunk with either mathematical notation or a single value.</p>
<div class="sourceCode" id="cb178"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">t3</span> <span class="op">&lt;-</span> <span class="cn">NULL</span></span></code></pre></div>
</div>
<div id="Ch4AssignQueT4" class="section level3" number="4.4.6">
<h3>
<span class="header-section-number">4.4.6</span> Task 4<a class="anchor" aria-label="anchor" href="#Ch4AssignQueT4"><i class="fas fa-link"></i></a>
</h3>
<p>Replace the <code>NULL</code> below with code, using the appropriate binomial distribution function, to determine the probability of hearing exactly 17 'tone' trials in a sequence of 100 trials. Assume the probability of a tone on any single trial is 1 in 4. Store the output in <code>t4</code>.</p>
<div class="sourceCode" id="cb179"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">t4</span> <span class="op">&lt;-</span> <span class="cn">NULL</span></span></code></pre></div>
</div>
<div id="Ch4AssignQueT5" class="section level3" number="4.4.7">
<h3>
<span class="header-section-number">4.4.7</span> Task 5<a class="anchor" aria-label="anchor" href="#Ch4AssignQueT5"><i class="fas fa-link"></i></a>
</h3>
<p>Replace the <code>NULL</code> below with code using the appropriate binomial distribution function to determine what is the probability of hearing 30 'vehicle' trials or more in a sequence of 100 trials. Assume the probability of a vehicle trial on any one trial is 1 in 4. Store the output in <code>t5</code>.
<strong>Hint: do we want the upper or lower tails of the distribution?</strong></p>
<div class="sourceCode" id="cb180"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">t5</span> <span class="op">&lt;-</span> <span class="cn">NULL</span></span></code></pre></div>
</div>
<div id="Ch4AssignQueT6" class="section level3" number="4.4.8">
<h3>
<span class="header-section-number">4.4.8</span> Task 6<a class="anchor" aria-label="anchor" href="#Ch4AssignQueT6"><i class="fas fa-link"></i></a>
</h3>
<p>If a block of our experiment contained 100 trials, enter a line of code to run 10000 replications of one block, summing how many living sounds were heard in each replication. Code 1 for living sounds (person/animal) and 0 for non living sounds (vehicle/tone) and assume the probability of a living sound on any given trial is <span class="math inline">\(p = .5\)</span>.</p>
<div class="sourceCode" id="cb181"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">t6</span> <span class="op">&lt;-</span> <span class="cn">NULL</span></span></code></pre></div>
<p><strong>Normal Distribution Questions</strong></p>
<p>Previously, in Chapter 2, we looked at an ageing research project investigating differences in visual processing speed between younger (M = 22 years) and older adults (M = 71 years). One check in this experiment, prior to further analysis, is to make sure that older participants do not show signs of mild cognitive impairment (early symptoms of Alzheimer's disease). To do this, we carry out a battery of cognitive tests to screen for such symptoms. One of the tests is the D2 test of attention which is a target cancellation task (i.e., participants cross out all letter d's with two dashes from a line of letters). It is designed to test peoples' selective and sustained attention and visual scanning speed. The results of the test give a single score of Concentration Performance for each participant. The key piece of information for this analysis is that the distributions of D2 test scores are typically normally distributed (<code>M = 100</code>, <code>SD = 10</code>).</p>
</div>
<div id="Ch4AssignQueT7" class="section level3" number="4.4.9">
<h3>
<span class="header-section-number">4.4.9</span> Task 7<a class="anchor" aria-label="anchor" href="#Ch4AssignQueT7"><i class="fas fa-link"></i></a>
</h3>
<p>Replace the <code>NULL</code> below with code using the appropriate function to determine the probability that a given participant will have a D2 score of 90 or lower? Store the output in <code>t7</code></p>
<div class="sourceCode" id="cb182"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">t7</span> <span class="op">&lt;-</span> <span class="cn">NULL</span></span></code></pre></div>
</div>
<div id="Ch4AssignQueT8" class="section level3" number="4.4.10">
<h3>
<span class="header-section-number">4.4.10</span> Task 8<a class="anchor" aria-label="anchor" href="#Ch4AssignQueT8"><i class="fas fa-link"></i></a>
</h3>
<p>Replace the <code>NULL</code> below with code using the appropriate function to determine the probability that a given participant will have a D2 score of 120 or more? Store the output in <code>t8</code></p>
<div class="sourceCode" id="cb183"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">t8</span> <span class="op">&lt;-</span> <span class="cn">NULL</span></span></code></pre></div>
</div>
<div id="Ch4AssignQueT9" class="section level3" number="4.4.11">
<h3>
<span class="header-section-number">4.4.11</span> Task 9<a class="anchor" aria-label="anchor" href="#Ch4AssignQueT9"><i class="fas fa-link"></i></a>
</h3>
<p>Replace the <code>NULL</code> below with code using the appropriate function(s) to determine what is the difference in scores that cut off the top 5% and bottom 5% of the distribution? Store the output in <code>t9</code>.</p>
<div class="sourceCode" id="cb184"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">t9</span> <span class="op">&lt;-</span> <span class="cn">NULL</span></span></code></pre></div>
</div>
<div id="Ch4AssignQueT10" class="section level3" number="4.4.12">
<h3>
<span class="header-section-number">4.4.12</span> Task 10<a class="anchor" aria-label="anchor" href="#Ch4AssignQueT10"><i class="fas fa-link"></i></a>
</h3>
<p>Finally, if a participant says to you that they are worried because they have heard that their Concentration Performance was in the bottom 2% of scores on the distribution, what is the maximum D2 score that they can have? Replace the <code>NULL</code> below with a single value to two decimal places. Do not enter code. Store this in <code>t10</code></p>
<div class="sourceCode" id="cb185"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">t10</span> <span class="op">&lt;-</span> <span class="cn">NULL</span></span></code></pre></div>
<p><br><span style="font-size: 22px; font-weight: bold; color: var(--blue);">Job Done - Activity Complete!</span></p>
<p>Well done, you are finished! Now you should go check your answers against the solutions at the end of the chapter. You are looking to check that questions looking for a single value have the same answer as you, and that questions asking for code have the same code as you or give the same answer where alternative variations in the code are allowed (e.g., including <code>lower.tail = TRUE</code> or not including it as it is default). Remember that a single value is not the same as a coded answer and that spelling matters, <code><a href="https://rdrr.io/r/base/lapply.html">replicate()</a></code> is not the same as <code>replicat()</code>. Where there are alternative answers, it means that you could have submitted any one of the options as they should all return the same answer.</p>
<p>Lastly, keep in mind the main point about probability, that we are interested in determining the probability of a given value on a distribution! That is what it is all about.</p>

</div>
</div>
<div id="solutions-to-questions-3" class="section level2" number="4.5">
<h2>
<span class="header-section-number">4.5</span> Solutions to Questions<a class="anchor" aria-label="anchor" href="#solutions-to-questions-3"><i class="fas fa-link"></i></a>
</h2>
<p>Below you will find the solutions to the questions for the Activities for this chapter. Only look at them after giving the questions a good try and speaking to the tutor about any issues.</p>
<div id="continuous-data-and-normal-distribution-tasks" class="section level3" number="4.5.1">
<h3>
<span class="header-section-number">4.5.1</span> Continuous Data and Normal Distribution Tasks<a class="anchor" aria-label="anchor" href="#continuous-data-and-normal-distribution-tasks"><i class="fas fa-link"></i></a>
</h3>
<div id="task-1-2" class="section level4" number="4.5.1.1">
<h4>
<span class="header-section-number">4.5.1.1</span> Task 1<a class="anchor" aria-label="anchor" href="#task-1-2"><i class="fas fa-link"></i></a>
</h4>
<ul>
<li>First we set up our range of IQ values from 40 to 160</li>
<li>Then we plot the distribution of IQ_data, where we have M = 100 and SD = 10</li>
</ul>
<div class="sourceCode" id="cb186"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://tidyverse.tidyverse.org">tidyverse</a></span><span class="op">)</span></span>
<span></span>
<span><span class="va">IQ_data</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://tibble.tidyverse.org/reference/tibble.html">tibble</a></span><span class="op">(</span>IQ_range <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">40</span>, <span class="fl">160</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">IQ_data</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span><span class="va">IQ_range</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_function.html">stat_function</a></span><span class="op">(</span>fun <span class="op">=</span> <span class="va">dnorm</span>, args <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span>mean <span class="op">=</span> <span class="fl">100</span>, sd <span class="op">=</span> <span class="fl">15</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>x <span class="op">=</span> <span class="st">"IQ Score"</span>, y <span class="op">=</span> <span class="st">"probability"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_classic</a></span><span class="op">(</span><span class="op">)</span></span></code></pre></div>
<div class="figure" style="text-align: center">
<span style="display:block;" id="fig:unnamed-chunk-1"></span>
<img src="04-s01-lab04e_files/figure-html/unnamed-chunk-1-1.png" alt="Distribution of IQ scores with mean = 100, sd = 10" width="100%"><p class="caption">
Figure 4.11: Distribution of IQ scores with mean = 100, sd = 10
</p>
</div>
<p><a href="revisiting-probability-distributions.html#Ch4InClassQueT1">Return to Task</a></p>
</div>
<div id="task-2-3" class="section level4" number="4.5.1.2">
<h4>
<span class="header-section-number">4.5.1.2</span> Task 2<a class="anchor" aria-label="anchor" href="#task-2-3"><i class="fas fa-link"></i></a>
</h4>
<div class="sourceCode" id="cb187"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">ND_data</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://tibble.tidyverse.org/reference/tibble.html">tibble</a></span><span class="op">(</span>ND_range <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/seq.html">seq</a></span><span class="op">(</span><span class="op">-</span><span class="fl">10</span>,<span class="fl">10</span>,<span class="fl">0.05</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">ND_data</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span><span class="va">ND_range</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_function.html">stat_function</a></span><span class="op">(</span>fun <span class="op">=</span> <span class="va">dnorm</span>, args <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span>mean <span class="op">=</span> <span class="fl">0</span>, sd <span class="op">=</span> <span class="fl">1</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>x <span class="op">=</span> <span class="st">"SD units"</span>, y <span class="op">=</span> <span class="st">"probability"</span>, title <span class="op">=</span> <span class="st">"The Normal Distribution"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_classic</a></span><span class="op">(</span><span class="op">)</span></span></code></pre></div>
<div class="figure" style="text-align: center">
<span style="display:block;" id="fig:unnamed-chunk-2"></span>
<img src="04-s01-lab04e_files/figure-html/unnamed-chunk-2-1.png" alt="Normal Distribution shown on a scale of -10 to 10, with a mean = 0, sd = 1" width="100%"><p class="caption">
Figure 4.12: Normal Distribution shown on a scale of -10 to 10, with a mean = 0, sd = 1
</p>
</div>
<p><a href="revisiting-probability-distributions.html#Ch4InClassQueT2">Return to Task</a></p>
</div>
<div id="task-3-3" class="section level4" number="4.5.1.3">
<h4>
<span class="header-section-number">4.5.1.3</span> Task 3<a class="anchor" aria-label="anchor" href="#task-3-3"><i class="fas fa-link"></i></a>
</h4>
<ul>
<li>Key thing is to set lower.tail to FALSE to calculate the above area. When using <code><a href="https://rdrr.io/r/stats/Normal.html">pnorm()</a></code> you state the actual cut-off even if using <code>lower.tail = FALSE</code>. If using <code><a href="https://rdrr.io/r/stats/Binomial.html">pbinom()</a></code> you state the cut-off minus one if using <code>lower.tail = FALSE</code>
</li>
</ul>
<div class="sourceCode" id="cb188"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">pnorm</a></span><span class="op">(</span><span class="fl">190</span>, <span class="fl">170</span>, <span class="fl">7</span>, lower.tail <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></span></code></pre></div>
<pre><code>## [1] 0.002137367</code></pre>
<p><a href="revisiting-probability-distributions.html#Ch4InClassQueT3">Return to Task</a></p>
</div>
<div id="task-4-2" class="section level4" number="4.5.1.4">
<h4>
<span class="header-section-number">4.5.1.4</span> Task 4<a class="anchor" aria-label="anchor" href="#task-4-2"><i class="fas fa-link"></i></a>
</h4>
<ul>
<li>The highlighted area is 185cm and above.</li>
<li>Key thing is to set lower.tail to FALSE to calculate the area from the cut-off and above.</li>
</ul>
<div class="sourceCode" id="cb190"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">pnorm</a></span><span class="op">(</span><span class="fl">185</span>, <span class="fl">170</span>, <span class="fl">7</span>, lower.tail <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></span></code></pre></div>
<pre><code>## [1] 0.01606229</code></pre>
<p><a href="revisiting-probability-distributions.html#Ch4InClassQueT4">Return to Task</a></p>
</div>
<div id="task-5-2" class="section level4" number="4.5.1.5">
<h4>
<span class="header-section-number">4.5.1.5</span> Task 5<a class="anchor" aria-label="anchor" href="#task-5-2"><i class="fas fa-link"></i></a>
</h4>
<ul>
<li>Question 1 - the lowest IQ score a student must have to be in the top 5% of the above distribution.</li>
</ul>
<div class="sourceCode" id="cb192"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">qnorm</a></span><span class="op">(</span><span class="fl">0.95</span>, <span class="fl">100</span>, <span class="fl">15</span>, lower.tail <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span></code></pre></div>
<pre><code>## [1] 124.6728</code></pre>
<ul>
<li>Question 2 - calculate the probability that a given student will have an IQ between 105 and 110, on a normal distribution of mean = 100, sd = 15.</li>
</ul>
<div class="sourceCode" id="cb194"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">pnorm</a></span><span class="op">(</span><span class="fl">105</span>, <span class="fl">100</span>, <span class="fl">15</span>, lower.tail <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span> <span class="op">-</span> </span>
<span>  <span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">pnorm</a></span><span class="op">(</span><span class="fl">110</span>, <span class="fl">100</span>, <span class="fl">15</span>, lower.tail <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></span></code></pre></div>
<pre><code>## [1] 0.1169488</code></pre>
<p><a href="revisiting-probability-distributions.html#Ch4InClassQueT5">Return to Task</a></p>
<!-- ### Return of the Binomial -->
<!-- #### Task 1 -->
<!-- ```{r, eval = FALSE} -->
<!-- blocks_5k <- replicate(n = 5000,  -->
<!--                        sample(0:1, -->
<!--                               size = 60,  -->
<!--                               replace = TRUE,  -->
<!--                               c(2/3,1/3)) %>% sum()) -->
<!-- ``` -->
<!-- [Return to Task](#Ch4InClassQueBinomial) -->
</div>
</div>
<div id="practice-your-skills-5" class="section level3" number="4.5.2">
<h3>
<span class="header-section-number">4.5.2</span> Practice Your Skills<a class="anchor" aria-label="anchor" href="#practice-your-skills-5"><i class="fas fa-link"></i></a>
</h3>
<div id="load-in-the-library" class="section level4" number="4.5.2.1">
<h4>
<span class="header-section-number">4.5.2.1</span> Load in the Library<a class="anchor" aria-label="anchor" href="#load-in-the-library"><i class="fas fa-link"></i></a>
</h4>
<div class="sourceCode" id="cb196"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://tidyverse.tidyverse.org">tidyverse</a></span><span class="op">)</span></span></code></pre></div>
<p><a href="revisiting-probability-distributions.html#Ch4AssignQueLib">Return to Task</a></p>
</div>
<div id="task-1-3" class="section level4" number="4.5.2.2">
<h4>
<span class="header-section-number">4.5.2.2</span> Task 1<a class="anchor" aria-label="anchor" href="#task-1-3"><i class="fas fa-link"></i></a>
</h4>
<div class="sourceCode" id="cb197"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">t1</span> <span class="op">&lt;-</span> <span class="fl">3</span><span class="op">/</span><span class="fl">4</span></span>
<span><span class="va">t1</span> <span class="op">&lt;-</span> <span class="fl">.75</span></span></code></pre></div>
<ul>
<li>The probability that the sound will not be a person is 0.75</li>
</ul>
<p><a href="revisiting-probability-distributions.html#Ch4AssignQueT1">Return to Task</a></p>
</div>
<div id="task-2-4" class="section level4" number="4.5.2.3">
<h4>
<span class="header-section-number">4.5.2.3</span> Task 2<a class="anchor" aria-label="anchor" href="#task-2-4"><i class="fas fa-link"></i></a>
</h4>
<div class="sourceCode" id="cb198"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">t2</span> <span class="op">&lt;-</span> <span class="op">(</span><span class="fl">1</span><span class="op">/</span><span class="fl">4</span><span class="op">)</span> <span class="op">*</span> <span class="op">(</span><span class="fl">1</span><span class="op">/</span><span class="fl">4</span><span class="op">)</span> <span class="op">*</span> <span class="op">(</span><span class="fl">1</span><span class="op">/</span><span class="fl">4</span><span class="op">)</span> <span class="op">*</span> <span class="op">(</span><span class="fl">1</span><span class="op">/</span><span class="fl">4</span><span class="op">)</span></span>
<span><span class="va">t2</span> <span class="op">&lt;-</span> <span class="fl">.004</span></span></code></pre></div>
<ul>
<li>The probability of that sequence of sounds is 0.004</li>
</ul>
<p><a href="revisiting-probability-distributions.html#Ch4AssignQueT2">Return to Task</a></p>
</div>
<div id="task-3-4" class="section level4" number="4.5.2.4">
<h4>
<span class="header-section-number">4.5.2.4</span> Task 3<a class="anchor" aria-label="anchor" href="#task-3-4"><i class="fas fa-link"></i></a>
</h4>
<div class="sourceCode" id="cb199"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">t3</span> <span class="op">&lt;-</span> <span class="op">(</span><span class="fl">1</span><span class="op">/</span><span class="fl">4</span><span class="op">)</span> <span class="op">*</span> <span class="op">(</span><span class="fl">1</span><span class="op">/</span><span class="fl">3</span><span class="op">)</span> <span class="op">*</span> <span class="op">(</span><span class="fl">1</span><span class="op">/</span><span class="fl">2</span><span class="op">)</span> <span class="op">*</span> <span class="op">(</span><span class="fl">0</span><span class="op">/</span><span class="fl">1</span><span class="op">)</span></span>
<span><span class="va">t3</span> <span class="op">&lt;-</span> <span class="fl">0</span></span></code></pre></div>
<ul>
<li>The probability of that sequence of sounds is 0</li>
<li>The reason is that there is no replacement and as such the repeat of the <code>person</code> trial can't happen.</li>
</ul>
<p><a href="revisiting-probability-distributions.html#Ch4AssignQueT3">Return to Task</a></p>
</div>
<div id="task-4-3" class="section level4" number="4.5.2.5">
<h4>
<span class="header-section-number">4.5.2.5</span> Task 4<a class="anchor" aria-label="anchor" href="#task-4-3"><i class="fas fa-link"></i></a>
</h4>
<div class="sourceCode" id="cb200"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">t4</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Binomial.html">dbinom</a></span><span class="op">(</span><span class="fl">17</span>, <span class="fl">100</span>, <span class="fl">1</span><span class="op">/</span><span class="fl">4</span><span class="op">)</span></span></code></pre></div>
<ul>
<li>Assuming a probability of a tone on a given trial is 1 in 4, the probability of hearing 17 'tone' trials in a sequence of 100 trials is 0.0165156</li>
</ul>
<p><a href="revisiting-probability-distributions.html#Ch4AssignQueT4">Return to Task</a></p>
</div>
<div id="task-5-3" class="section level4" number="4.5.2.6">
<h4>
<span class="header-section-number">4.5.2.6</span> Task 5<a class="anchor" aria-label="anchor" href="#task-5-3"><i class="fas fa-link"></i></a>
</h4>
<ul>
<li>This could have been answered using either <code><a href="https://rdrr.io/r/stats/Binomial.html">pbinom()</a></code> or <code><a href="https://rdrr.io/r/stats/Binomial.html">dbinom()</a></code>. The trick is to remember where to set the cut-off depending on the function used.</li>
</ul>
<div class="sourceCode" id="cb201"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">t5</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Binomial.html">pbinom</a></span><span class="op">(</span><span class="fl">29</span>, <span class="fl">100</span>, <span class="fl">1</span><span class="op">/</span><span class="fl">4</span>, lower.tail <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></span>
<span><span class="va">t5</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Binomial.html">dbinom</a></span><span class="op">(</span><span class="fl">30</span><span class="op">:</span><span class="fl">100</span>, <span class="fl">100</span>, <span class="fl">1</span><span class="op">/</span><span class="fl">4</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="op">)</span></span></code></pre></div>
<ul>
<li>In this scenario, the probability of hearing 30 'vehicle' trials or more in a sequence of 100 trials is 0.149541</li>
</ul>
<p><a href="revisiting-probability-distributions.html#Ch4AssignQueT5">Return to Task</a></p>
</div>
<div id="task-6-2" class="section level4" number="4.5.2.7">
<h4>
<span class="header-section-number">4.5.2.7</span> Task 6<a class="anchor" aria-label="anchor" href="#task-6-2"><i class="fas fa-link"></i></a>
</h4>
<ul>
<li>The appropriate code would be:</li>
</ul>
<div class="sourceCode" id="cb202"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">t6</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/lapply.html">replicate</a></span><span class="op">(</span><span class="fl">10000</span>, <span class="fu"><a href="https://rdrr.io/r/base/sample.html">sample</a></span><span class="op">(</span><span class="fl">0</span><span class="op">:</span><span class="fl">1</span>, <span class="fl">100</span>, <span class="cn">TRUE</span>, <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">.5</span>,<span class="fl">.5</span><span class="op">)</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<p>If you were to look at your output you would see something like the following. Remember your numbers will vary from ours due to random sampling. Here we are only showing the first 10 values of 10000</p>
<pre><code>##  int [1:10000] 44 54 47 52 54 45 54 48 48 55 ...</code></pre>
<p><a href="revisiting-probability-distributions.html#Ch4AssignQueT6">Return to Task</a></p>
</div>
<div id="task-7-2" class="section level4" number="4.5.2.8">
<h4>
<span class="header-section-number">4.5.2.8</span> Task 7<a class="anchor" aria-label="anchor" href="#task-7-2"><i class="fas fa-link"></i></a>
</h4>
<div class="sourceCode" id="cb204"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">t7</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">pnorm</a></span><span class="op">(</span><span class="fl">90</span>, <span class="fl">100</span>, <span class="fl">10</span>, lower.tail <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span></code></pre></div>
<ul>
<li>The probability of a given participant having a D2 score of 90 or lower is 0.1586553</li>
</ul>
<p><a href="revisiting-probability-distributions.html#Ch4AssignQueT7">Return to Task</a></p>
</div>
<div id="task-8-2" class="section level4" number="4.5.2.9">
<h4>
<span class="header-section-number">4.5.2.9</span> Task 8<a class="anchor" aria-label="anchor" href="#task-8-2"><i class="fas fa-link"></i></a>
</h4>
<div class="sourceCode" id="cb205"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">t8</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">pnorm</a></span><span class="op">(</span><span class="fl">120</span>, <span class="fl">100</span>, <span class="fl">10</span>, lower.tail <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></span></code></pre></div>
<ul>
<li>The probability that a given participant will have a D2 score of 120 or more is 0.0227501</li>
</ul>
<p><a href="revisiting-probability-distributions.html#Ch4AssignQueT8">Return to Task</a></p>
</div>
<div id="task-9" class="section level4" number="4.5.2.10">
<h4>
<span class="header-section-number">4.5.2.10</span> Task 9<a class="anchor" aria-label="anchor" href="#task-9"><i class="fas fa-link"></i></a>
</h4>
<div class="sourceCode" id="cb206"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">t9</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">qnorm</a></span><span class="op">(</span><span class="fl">.95</span>, <span class="fl">100</span>, <span class="fl">10</span><span class="op">)</span> <span class="op">-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">qnorm</a></span><span class="op">(</span><span class="fl">.05</span>, <span class="fl">100</span>, <span class="fl">10</span><span class="op">)</span></span></code></pre></div>
<ul>
<li>The difference in scores that cut off the top and bottom 5% of the distribution is 32.8970725</li>
</ul>
<p><a href="revisiting-probability-distributions.html#Ch4AssignQueT9">Return to Task</a></p>
</div>
<div id="task-10" class="section level4" number="4.5.2.11">
<h4>
<span class="header-section-number">4.5.2.11</span> Task 10<a class="anchor" aria-label="anchor" href="#task-10"><i class="fas fa-link"></i></a>
</h4>
<div class="sourceCode" id="cb207"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">t10</span> <span class="op">&lt;-</span> <span class="fl">79.46</span></span></code></pre></div>
<ul>
<li>The maximum D2 score that they can have in this situation is 79.46</li>
</ul>
<p><a href="revisiting-probability-distributions.html#Ch4AssignQueT10">Return to Task</a></p>
<p><span style="font-size: 22px; font-weight: bold; color: var(--purple);">Chapter Complete!</span></p>

</div>
</div>
</div>
</div>
<script>

/* update total correct if #webex-total_correct exists */
update_total_correct = function() {
  console.log("webex: update total_correct");

  if (t = document.getElementById("webex-total_correct")) {
    var correct = document.getElementsByClassName("webex-correct").length;
    var solvemes = document.getElementsByClassName("webex-solveme").length;
    var radiogroups = document.getElementsByClassName("webex-radiogroup").length;
    var selects = document.getElementsByClassName("webex-select").length;
    
    t.innerHTML = correct + " of " + (solvemes + radiogroups + selects) + " correct";
  }
}

/* webex-solution button toggling function */
b_func = function() {
  console.log("webex: toggle hide");
  
  var cl = this.parentElement.classList;
  if (cl.contains('open')) {
    cl.remove("open");
  } else {
    cl.add("open");
  }
}

/* function for checking solveme answers */
solveme_func = function(e) {
  console.log("webex: check solveme");

  var real_answers = JSON.parse(this.dataset.answer);
  var my_answer = this.value;
  var cl = this.classList;
  if (cl.contains("ignorecase")) {
    my_answer = my_answer.toLowerCase();
  }
  if (cl.contains("nospaces")) {
    my_answer = my_answer.replace(/ /g, "")
  }

  if (my_answer == "") {
    cl.remove("webex-correct");
    cl.remove("webex-incorrect");
  } else if (real_answers.includes(my_answer)) {
    cl.add("webex-correct");
    cl.remove("webex-incorrect");
  } else {
    cl.add("webex-incorrect");
    cl.remove("webex-correct");
  }

  // match numeric answers within a specified tolerance
  if(this.dataset.tol > 0){
    var tol = JSON.parse(this.dataset.tol);
    var matches = real_answers.map(x => Math.abs(x - my_answer) < tol)
    if (matches.reduce((a, b) => a + b, 0) > 0) {
      cl.add("webex-correct");
    } else {
      cl.remove("webex-correct");
    }
  }

  // added regex bit
  if (cl.contains("regex")){
    answer_regex = RegExp(real_answers.join("|"))
    if (answer_regex.test(my_answer)) {
      cl.add("webex-correct");
    }
  }

  update_total_correct();
}

/* function for checking select answers */
select_func = function(e) {
  console.log("webex: check select");
  
  var cl = this.classList
  
  /* add style */
  cl.remove("webex-incorrect");
  cl.remove("webex-correct");
  if (this.value == "answer") {
    cl.add("webex-correct");
  } else if (this.value != "blank") {
    cl.add("webex-incorrect");
  }
  
  update_total_correct();
}

/* function for checking radiogroups answers */
radiogroups_func = function(e) {
  console.log("webex: check radiogroups");

  var checked_button = document.querySelector('input[name=' + this.id + ']:checked');
  var cl = checked_button.parentElement.classList;
  var labels = checked_button.parentElement.parentElement.children;
  
  /* get rid of styles */
  for (i = 0; i < labels.length; i++) {
    labels[i].classList.remove("webex-incorrect");
    labels[i].classList.remove("webex-correct");
  }
  
  /* add style */
  if (checked_button.value == "answer") {
    cl.add("webex-correct");
  } else {
    cl.add("webex-incorrect");
  }
  
  update_total_correct();
}

window.onload = function() {
  console.log("onload");
  /* set up solution buttons */
  var buttons = document.getElementsByTagName("button");

  for (var i = 0; i < buttons.length; i++) {
    if (buttons[i].parentElement.classList.contains('webex-solution')) {
      buttons[i].onclick = b_func;
    }
  }

  /* set up webex-solveme inputs */
  var solveme = document.getElementsByClassName("webex-solveme");

  for (var i = 0; i < solveme.length; i++) {
    /* make sure input boxes don't auto-anything */
    solveme[i].setAttribute("autocomplete","off");
    solveme[i].setAttribute("autocorrect", "off");
    solveme[i].setAttribute("autocapitalize", "off");
    solveme[i].setAttribute("spellcheck", "false");
    solveme[i].value = "";

    /* adjust answer for ignorecase or nospaces */
    var cl = solveme[i].classList;
    var real_answer = solveme[i].dataset.answer;
    if (cl.contains("ignorecase")) {
      real_answer = real_answer.toLowerCase();
    }
    if (cl.contains("nospaces")) {
      real_answer = real_answer.replace(/ /g, "");
    }
    solveme[i].dataset.answer = real_answer;

    /* attach checking function */
    solveme[i].onkeyup = solveme_func;
    solveme[i].onchange = solveme_func;
  }
  
  /* set up radiogroups */
  var radiogroups = document.getElementsByClassName("webex-radiogroup");
  for (var i = 0; i < radiogroups.length; i++) {
    radiogroups[i].onchange = radiogroups_func;
  }
  
  /* set up selects */
  var selects = document.getElementsByClassName("webex-select");
  for (var i = 0; i < selects.length; i++) {
    selects[i].onchange = select_func;
  }

  update_total_correct();
}

</script><script>
$( document ).ready(function() {
  var cite = ' ';
  var psyteachr = ' <a href="https://psyteachr.github.io/"><img src="images/logos/psyteachr_logo.png" style="height: 31px; color: white;" alt="psyTeachR: Reproducible Research" /></a>';
  var license = ' <a rel="license" href="https://creativecommons.org/licenses/by-sa/4.0/" target="blank"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-sa/4.0/88x31.png"></a>';

  $("footer div.row div:eq(1) p").html(
    psyteachr + license + cite
  );
  
  // open rdrr links externally
  $("a[href^='https://rdrr.io']").click(function(){
    window.open(this.href);
    return false;
  });
  
  // visible second sidebar in mobile
  function move_sidebar() {
    var w = window.innerWidth;
    if (w < 992) {
      $("#toc").appendTo($("#main-nav"));
    } else {
      $("#toc").appendTo($("div.sidebar-chapter"));
    }
  }
  move_sidebar();
  window.onresize = move_sidebar;
});
</script><div class="chapter-nav">
<div class="prev"><a href="data-visualisation-through-ggplot2.html"><span class="header-section-number">3</span> Data Visualisation Through ggplot2</a></div>
<div class="next"><a href="nhst-binomial-test-and-one-sample-t-test.html"><span class="header-section-number">5</span> NHST: Binomial test and One-Sample t-test</a></div>
</div></main><div class="col-md-3 col-lg-2 d-none d-md-block sidebar sidebar-chapter">
    <nav id="toc" data-toggle="toc" aria-label="On this page"><h2>On this page</h2>
      <ul class="nav navbar-nav">
<li><a class="nav-link" href="#revisiting-probability-distributions"><span class="header-section-number">4</span> Revisiting Probability Distributions</a></li>
<li><a class="nav-link" href="#overview-4"><span class="header-section-number">4.1</span> Overview</a></li>
<li>
<a class="nav-link" href="#discrete-data-and-binomial-distributions"><span class="header-section-number">4.2</span> Discrete Data and Binomial Distributions</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#general-probability-calculations"><span class="header-section-number">4.2.1</span> General Probability Calculations</a></li>
<li><a class="nav-link" href="#creating-a-simple-probability-distribution"><span class="header-section-number">4.2.2</span> Creating a Simple Probability Distribution</a></li>
<li><a class="nav-link" href="#the-binomial-distribution---creating-a-discrete-distribution"><span class="header-section-number">4.2.3</span> The Binomial Distribution - Creating a Discrete Distribution</a></li>
<li><a class="nav-link" href="#dbinom---the-density-function"><span class="header-section-number">4.2.4</span> dbinom() - The Density Function</a></li>
<li><a class="nav-link" href="#pbinom---the-cumulative-probability-function"><span class="header-section-number">4.2.5</span> pbinom() - The Cumulative Probability Function</a></li>
<li><a class="nav-link" href="#qbinom---the-quantile-function"><span class="header-section-number">4.2.6</span> qbinom() - The Quantile Function</a></li>
</ul>
</li>
<li>
<a class="nav-link" href="#continuous-data-and-normal-distribution"><span class="header-section-number">4.3</span> Continuous Data and Normal Distribution</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#continuous-data-properties"><span class="header-section-number">4.3.1</span> Continuous Data Properties</a></li>
<li><a class="nav-link" href="#estimating-from-the-normal-distribution"><span class="header-section-number">4.3.2</span> Estimating from the Normal Distribution</a></li>
<li><a class="nav-link" href="#dnorm---the-density-function"><span class="header-section-number">4.3.3</span> dnorm() - The Density Function</a></li>
<li><a class="nav-link" href="#pnorm---the-cumulative-probability-function"><span class="header-section-number">4.3.4</span> pnorm() - The Cumulative Probability Function</a></li>
<li><a class="nav-link" href="#qnorm---the-quantile-function"><span class="header-section-number">4.3.5</span> qnorm() - The Quantile Function</a></li>
</ul>
</li>
<li>
<a class="nav-link" href="#practice-your-skills-4"><span class="header-section-number">4.4</span> Practice Your Skills</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#topic-probabilities"><span class="header-section-number">4.4.1</span> Topic: Probabilities</a></li>
<li><a class="nav-link" href="#Ch4AssignQueLib"><span class="header-section-number">4.4.2</span> Load in the Library</a></li>
<li><a class="nav-link" href="#Ch4AssignQueT1"><span class="header-section-number">4.4.3</span> Task 1</a></li>
<li><a class="nav-link" href="#Ch4AssignQueT2"><span class="header-section-number">4.4.4</span> Task 2</a></li>
<li><a class="nav-link" href="#Ch4AssignQueT3"><span class="header-section-number">4.4.5</span> Task 3</a></li>
<li><a class="nav-link" href="#Ch4AssignQueT4"><span class="header-section-number">4.4.6</span> Task 4</a></li>
<li><a class="nav-link" href="#Ch4AssignQueT5"><span class="header-section-number">4.4.7</span> Task 5</a></li>
<li><a class="nav-link" href="#Ch4AssignQueT6"><span class="header-section-number">4.4.8</span> Task 6</a></li>
<li><a class="nav-link" href="#Ch4AssignQueT7"><span class="header-section-number">4.4.9</span> Task 7</a></li>
<li><a class="nav-link" href="#Ch4AssignQueT8"><span class="header-section-number">4.4.10</span> Task 8</a></li>
<li><a class="nav-link" href="#Ch4AssignQueT9"><span class="header-section-number">4.4.11</span> Task 9</a></li>
<li><a class="nav-link" href="#Ch4AssignQueT10"><span class="header-section-number">4.4.12</span> Task 10</a></li>
</ul>
</li>
<li>
<a class="nav-link" href="#solutions-to-questions-3"><span class="header-section-number">4.5</span> Solutions to Questions</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#continuous-data-and-normal-distribution-tasks"><span class="header-section-number">4.5.1</span> Continuous Data and Normal Distribution Tasks</a></li>
<li><a class="nav-link" href="#practice-your-skills-5"><span class="header-section-number">4.5.2</span> Practice Your Skills</a></li>
</ul>
</li>
</ul>

      <div class="book-extra">
        <ul class="list-unstyled">
<li><a id="book-source" href="https://github.com/psyteachr/analysis-v2/blob/master/book/04-s01-lab04a.Rmd">View source <i class="fab fa-github"></i></a></li>
          <li><a id="book-edit" href="https://github.com/psyteachr/analysis-v2/edit/master/book/04-s01-lab04a.Rmd">Edit this page <i class="fab fa-github"></i></a></li>
        </ul>
</div>
    </nav>
</div>

</div>
</div> <!-- .container -->

<footer class="bg-primary text-light mt-5"><div class="container"><div class="row">

  <div class="col-12 col-md-6 mt-3">
    <p>"<strong>Analysis</strong>" was written by Phil McAleer, Carolina E. Kuepper-Tetzel, Helena Paterson. It was last built on 2023-11-11.</p>
  </div>

  <div class="col-12 col-md-6 mt-3">
    <p>This book was built by the <a class="text-light" href="https://bookdown.org">bookdown</a> R package.</p>
  </div>

</div></div>
</footer><!-- dynamically load mathjax for compatibility with self-contained --><script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script><script type="text/x-mathjax-config">const popovers = document.querySelectorAll('a.footnote-ref[data-toggle="popover"]');
for (let popover of popovers) {
  const div = document.createElement('div');
  div.setAttribute('style', 'position: absolute; top: 0, left:0; width:0, height:0, overflow: hidden; visibility: hidden;');
  div.innerHTML = popover.getAttribute('data-content');

  var has_math = div.querySelector("span.math");
  if (has_math) {
    document.body.appendChild(div);
    MathJax.Hub.Queue(["Typeset", MathJax.Hub, div]);
    MathJax.Hub.Queue(function() {
      popover.setAttribute('data-content', div.innerHTML);
      document.body.removeChild(div);
    })
  }
}
</script>
</body>
</html>
