# Foreword {-}

<span style="font-size: 22px; font-weight: bold; color: var(--purple);">Welcome to the Level 2 Practical Lab Series</span>

Over the course of this year's practical lab sessions, and this book, we will help you learn a whole host of skills and methods based around being a psychologist. If you have completed Book 1 in the **PsyTeachR** series (<a href="https://psyteachr.github.io/" target = "_blank">https://psyteachr.github.io/</a>) the first few labs will be familiar to you, with some additions. This is deliberate in order to refresh your knowledge and skills before moving on to more advanced topics later in this book. First, we will remind you how to work with R Markdown, before recapping the main functions we use for visualisation and data wrangling. From there we will build your understanding of probability before going on to using all these refreshed skills to analyse a variety of different experiments; all with the idea of being reproducible in our approach throughout. By the end of the book we would hope that you are both competent and confident in all the knowledge and skills we want you to have going forward, and we will be here to support you along the way. 

As you will see, this book requires more self-directed learning than the first book; part of learning is trying things out yourself and recognising where you need help. That said, that does not mean we are not here to help and any time you are unsure, please, ask in class, on the Teams channels, in our student office hours, or during our GTA drop-in sessions. 

When working through this book remember that this is not about learning a software. We do not teach R independent of statistical knowledge and content. Rather, we teach data and analytical skills and knowledge within R, mainly within the tidyverse framework. You are learning data and analytical skills and knowledge within R. The goal is to learn different skills, step-by-step, and integrating them together as you progress! 

You can do this!
