# Starting with R Markdown

## Overview

A key goal of any researcher is to carry out an experiment and to tell others about it. One of the main ways we as Psychologists do this is through publication of journal articles. There are numerous ways that people combine different software to create a journal article, but a more recent innovation in the field that we want you to know about is creating reports and articles through R Markdown. If you like, you can see an example from a research team in our school in this <a href ="http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0185093" target = "_blank">recent PLOS article</a>. A link within the article methods section (this one - <a href="https://osf.io/eb9dq/" target = "_blank">https://osf.io/eb9dq/</a>) allows you to see the one file that creates the whole manuscript. Obviously you won't be writing full journal articles just yet, but you will use R Markdown throughout this lab series to do assignments. You could also use it in other subjects to write reports, or to make yourself a portfolio of hints, tips, and study aids as we suggest throughout the labs. 

Today, we will start by showing you some of skills in using R Markdown efficiently.

**In this chapter you will learn\:**

1. What is R Markdown?
2. How to create an R Markdown file and knit it.
3. How to add code and edit rules in your R Markdown file.
4. How to format your text.

### What is R Markdown?

R Markdown (abbreviated as Rmd) is a great way to create dynamic documents through embedded chunks of code. These documents are self-contained and fully reproducible which makes it very easy to share. For more information about R Markdown, feel free to have a look at their main webpage sometime: <a href="http://rmarkdown.rstudio.com" target = "_blank">The R Markdown Webpage</a>. The key advantage of R Markdown is that it allows you to write code into a document, along with regular text, and then **knit** it using the package `knitr()` to create your document as either a webpage (HTML), a PDF, or Word document (.docx). 

`r hide("Explain This - We Knit what?")`
```{block, type = "info"}
Throughout the labs you will see little tabs that give more information, answers to quick questions, helpful hints, solutions to tasks, or suggestions for information you want to note down somewhere. You do not have to read them all and you will find they get less as the course progresses, but they might help you if you are stuck on something.    

Knit is what we say when we want to turn our R Markdown file into either a webpage, PDF, or a Word document. Often in the labs you will hear someone say, "Have you tried knitting it?" or "What happens when you knit it?". This simply means what happens when you try turning your file into a pdf or webpage. 

For any of the practical data assignments, one check to run before submitting is to knit your code to an html (webpage) file and then see if you can open that file in your browser. This doesn't check that your code is correct. It does however confirm that your code runs and has no critical issues in it that would stop your code from running. A very valuable check.
```
`r unhide()`  

### Advantages of using R Markdown

1. The output is one file that includes figures, text, and citations. No additional files are needed so it's easy to keep all your work in one place. 

2. R code can be put directly into an R Markdown report, so it is not necessary to keep your writing (e.g., a Word document) and your analysis (e.g., your R script) separate.  

3. Including the R code directly lets others see how you did your analysis - this is a good thing for science! It is both reproducible and transparent, key components of Open Science!  

4. You write your report in plain text, a non software-specific format that is easy to share, so it's not necessary to learn any new coding language such as HTML, but can create various outputs depending on what you need. 

### Creating an R Markdown (.Rmd) File

In this chapter you're going to create your own R Markdown document. Knowing how to do this will:

a. help you navigate R Markdown.
b. show you how to create homework assignment documents.
c. help you to create your own reports using it.

If at any point you are unsure about how to do something remember to think about where you can get help, do what we do, google it (there are R markdown cheat sheets on the internet). For example, if you forget how to put words in bold, you could simply go to Google and type "**rmarkdown bold**" and no doubt get a lot of useful hints. There is nothing wrong with this. Nobody is expecting you to keep every function in your head; we all need reminders. You will find some elements stick in your head better than others. So remember, Google is your friend!

<span style="font-size: 22px; font-weight: bold; color: var(--green);">Quickfire Questions</span>

We have put questions throughout to help you test your knowledge. When you type in or choose the correct answer, the dashed box will change color and become solid.

- From the following options, why are we creating an R Markdown document instead of simply using an R script? `r mcq(c(answer = "R Markdown can combine report writing and analysis", "R Scripts can't run code", answer = "Reproducible Science!"))`  

`r hide("Explain This Answer!")`
```{block, type = "info"}
So there's more than one answer to this question! R Markdown can combine report writing and analysis, providing open access for others to examine data, and create more Reproducible Science. But what about the incorrect answer? R Scripts do in fact run R code as you may remember from Level 1 labs. The key difference is that R Scripts cannot really be used for documentation and creating reports as easily - this is where R Markdown is used to ensure your code can be added to all the other information of your research and can be reproduced by others.
```
`r unhide()`  

### One last thing before beginning!

Remember: You can always go back to the <a href = "https://psyteachr.github.io/data-skills-v1/" target = "_blank">Data Skills Book</a> from Level 1 to remind you about the skills we want you have already learned through using R and RStudio. The first few chapters in this book will partly overlap with what you have learned previously, but will further extend on your skills and knowledge.
